### PR TITLE
Fix failed unit test for AddProductCoordinator on iPad

### LINKED ISSUE #6408: Crash in our unit tests when they runs on iPad
When I try to run our unit tests on iPad, I encountered a crash:

```
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<UIPopoverPresentationController: 0x10c82f8b0>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'
terminating with uncaught exception of type NSException
CoreSimulator 783.5 - Device: iPad Pro (12.9-inch) (5th generation) (846A6B9E-52C6-4D77-B1B0-FA2858F849D3) - Runtime: iOS 15.2 (19C51) - DeviceType: iPad Pro (12.9-inch) (5th generation)
(lldb) 
```

It seems that the reason is on `AddProductCoordinatorTests` -> `test_it_presents_bottom_sheet_on_start()` because of the missing `sourceView`.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #6408 

### Description

This PR fixes the failed unit test for AddProductCoordinator on iPad. Previously the coordinator was set up with a bar button item - my take is that this item needs to be associated with a navigation bar/navigation controller to make it possible to present the popover from.

The solution is to set up the test with a source view instead of source bar button item.

### Testing instructions

Please make sure that the test succeeds.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by pmusolino — COMMENTED** [review]
I launched the unit tests on an iPad Pro 12.9 inch with iOS 15.2, and I still see a unit test failing. 

Did you see the same failing test?
Schermata 2022-03-23 alle 11 58 48

**Comment by itsmeichigo** [comment]
The test succeeds locally for me - are you sure you've checked out the change yet? 😅

**Comment by pmusolino** [comment]
> The test succeeds locally for me - are you sure you've checked out the change yet? 

As you can see, the branch is correct 🤷 

Schermata 2022-03-24 alle 11 55 49

**Comment by itsmeichigo** [comment]
Okay so that's another similar test that failed 😂 I was fixing the failed test in AddProductCoordinator and didn't know the test for AddOrderCoordinator failed too. Just added a fix in e3d63d52b1af818a9d71867a118e0131b70b47df.

**Review by pmusolino — APPROVED** [review]
> Okay so that's another similar test that failed 😂 I was fixing the failed test in AddProductCoordinator and didn't know the test for AddOrderCoordinator failed too. Just added a fix in https://github.com/woocommerce/woocommerce-ios/commit/e3d63d52b1af818a9d71867a118e0131b70b47df.

🚀 🚀 🚀 🚀 🚀 🚀 🚀

**Pull request merged**
