### PR TITLE
[TTPUK] Update UK card configuration for Tap to Pay

### LINKED ISSUE #10872: [TTPUK] UK configuration including amount for PIN

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #10872

Merge after: #10886 

## Description

We'll add Tap to Pay on iPhone support for UK WooPayments merchants. This PR enables TTP in the UK, behind a feature flag.

### Changes:
1. Updates the StripeTerminal dependency to the latest in the v2 series, which adds support for Tap to Pay in the UK. 
2. Updates the configuration for the United Kingdom to enable Tap to Pay for UK stores when the feature flag is on.
3. Adds `contactlessLimitAmount` to the configuration, for future messaging around what transactions are eligible for contactless payments, especially relevant to Tap to Pay where that's the only option.

## Testing instructions

Using a build from Xcode, and a UK-based WooPayments store, on an iPhone XS or newer running iOS 16+:
1. Navigate to `Menu > Payments`
2. Observe that `Set up Tap to Pay on iPhone` is visible
3. Run through the flow and check that you can take a test payment using Tap to Pay.

Set the feature flag named `tapToPayOnIPhoneInUK` to false, then repeat the above test – observe that you don't see the Set up Tap to Pay on iPhone option.

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/2472348/b0c63a23-bef7-44fc-9939-fb8be91779c4

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by iamgabrielma** [comment]
I can't seem to be able to process a transaction, the flow stops after the "Preparing Tap to Pay on iPhone" step with the Setup failed view:

```
The payment can not be processed by the payment processor.
```

For reference I'm using the site thebritwootester.wpcomstaging.com (GB) , on iPhone 14 and iOS 16.3.1. Not sure if related, but something I see in your recording that I'm not seeing in the build is the  "Share Tap to pay on iPhone feedback" row, in case there's something I'm missing.

This is the whole log ( note the `com.apple.merchantd.transaction` bit):

```
2023-10-09 18:05:31.456731+0900 WooCommerce[3612:1384958] [MKTerm] User cancelled
2023-10-09 18:05:31.456871+0900 WooCommerce[3612:1385086] [xpc] <NSXPCConnection: 0x280a6e080> connection to service with pid 1636 named com.apple.merchantd.transaction: received an undecodable message for proxy 1 (no exported object to receive message). Dropping message.
2023-10-09 18:05:34.835953+0900 WooCommerce[3612:1384543] [MKTerm] User cancelled
2023-10-09 18:05:34.853728+0900 WooCommerce[3612:1384985] 🔵 Tracked card_reader_connection_failed, properties: [AnyHashable("country"): "GB", AnyHashable("plan"): "business-bundle", AnyHashable("is_wpcom_store"): true, AnyHashable("error_description"): "The payment can not be processed by the payment processor.", AnyHashable("plugin_slug"): "woocommerce-payments", AnyHashable("site_id"): 217705087, AnyHashable("was_ecommerce_trial"): false, AnyHashable("blog_id"): 217705087, AnyHashable("site_url"): "https://thebritwootester.wpcomstaging.com", AnyHashable("connection_type"): "user_initiated", AnyHashable("card_reader_model"): "COTS_DEVICE"]
```

Update: I see 2 `Switch must be exhaustive` warnings (which I'm unsure if are related as well, as generally those should be build errors), in `ReaderDisplayMessage.localizedMessage` for `.cardRemovedTooEarly` and `StripeCardReaderService.retryActivePaymentIntent.activePaymentIntent.status` for `.requiresAction`

**Comment by joshheald** [comment]
> I can't seem to be able to process a transaction, the flow stops after the "Preparing Tap to Pay on iPhone" step with the Setup failed view:
> 
> ```
> The payment can not be processed by the payment processor.
> ```
> 
> For reference I'm using the site thebritwootester.wpcomstaging.com (GB) , on iPhone 14 and iOS 16.3.1. 

Thanks for testing. I've not got an account on that store, so I can't check it, but I've invited you to my test store, which worked for me if you want to have a go with that one?


> Not sure if related, but something I see in your recording that I'm not seeing in the build is the "Share Tap to pay on iPhone feedback" row, in case there's something I'm missing.

The share feedback row shows up after you've taken your first TTP transaction on this device for the current store – if you've deleted the app, and not done a payment, it won't be there, but it's nothing to worry about.

> 
> This is the whole log ( note the `com.apple.merchantd.transaction` bit):
> 
> ```
> 2023-10-09 18:05:31.456731+0900 WooCommerce[3612:1384958] [MKTerm] User cancelled
> 2023-10-09 18:05:31.456871+0900 WooCommerce[3612:1385086] [xpc] <NSXPCConnection: 0x280a6e080> connection to service with pid 1636 named com.apple.merchantd.transaction: received an undecodable message for proxy 1 (no exported object to receive message). Dropping message.
> 2023-10-09 18:05:34.835953+0900 WooCommerce[3612:1384543] [MKTerm] User cancelled
> 2023-10-09 18:05:34.853728+0900 WooCommerce[3612:1384985] 🔵 Tracked card_reader_connection_failed, properties: [AnyHashable("country"): "GB", AnyHashable("plan"): "business-bundle", AnyHashable("is_wpcom_store"): true, AnyHashable("error_description"): "The payment can not be processed by the payment processor.", AnyHashable("plugin_slug"): "woocommerce-payments", AnyHashable("site_id"): 217705087, AnyHashable("was_ecommerce_trial"): false, AnyHashable("blog_id"): 217705087, AnyHashable("site_url"): "https://thebritwootester.wpcomstaging.com", AnyHashable("connection_type"): "user_initiated", AnyHashable("card_reader_model"): "COTS_DEVICE"]
> ```



> Update: I see 2 `Switch must be exhaustive` warnings (which I'm unsure if are related as well, as generally those should be build errors), in `ReaderDisplayMessage.localizedMessage` for `.cardRemovedTooEarly` and `StripeCardReaderService.retryActivePaymentIntent.activePaymentIntent.status` for `.requiresAction`

That's weird that I didn't see them but they're probably from the update of the StripeTerminal SDK. I'll take a look... thanks.

**Comment by joshheald** [comment]
> I can't seem to be able to process a transaction, the flow stops after the "Preparing Tap to Pay on iPhone" step with the Setup failed view:
> 
> 
> 
> ```
> 
> The payment can not be processed by the payment processor.
> 
> ```

@iamgabrielma I've not had a chance to look at the enum yet, but one other thought: does this store work for you with a card reader payment on trunk?

I had no problems again today. I've sent you an invite to my UK store in case that helps.

**Comment by iamgabrielma** [comment]
> Thanks for testing. I've not got an account on that store, so I can't check it, but I've invited you to my test store, which worked for me if you want to have a go with that one?
> I've not had a chance to look at the enum yet, but one other thought: does this store work for you with a card reader payment on trunk?

Thanks for the invite, I seem to have the same problem in your store than in the one I previously tested. This doesn't happen in trunk for TTP and card reader transactions as long as is an  US store, or using the WisePad3 with a UK store, so it seems the problem is only for TTP on a UK store. I also attempted a clean install with your site only and this PR and the same happened. To clarify:

| - | 2.19.1 US Store (trunk) | 2.23.2 US Store | 2.19.1 UK Store (trunk) | 2.23.2 UK Store | 
|--------|--------|--------|--------|--------|
| TTP |  ✅ | ✅ | - | ❌ |
| Wisepad3 | - | - | ✅ | ✅ |

For reference, here are the logs for both transactions:

<details>
<summary> GB-store failed transaction </summary>

```

2023-10-10 10:24:30.166314+0900 WooCommerce[3881:1464586] 🔵 Tracked hub_menu_option_tapped, properties: [AnyHashable("site_url"): "https://jhukpayments.mystagingwebsite.com", AnyHashable("blog_id"): 218017331, AnyHashable("was_ecommerce_trial"): false, AnyHashable("plan"): "jetpack_security_daily", AnyHashable("is_wpcom_store"): false, AnyHashable("option"): "payments"]
2023-10-10 10:24:32.344043+0900 WooCommerce[3881:1464589] <> Mapping Error: Dotcom Invalid REST Route
2023-10-10 10:24:32.345323+0900 WooCommerce[3881:1464587] ⛔️ Error synchronizing Stripe Account: Dotcom Invalid REST Route
2023-10-10 10:24:34.286269+0900 WooCommerce[3881:1464589] 🔵 Tracked payments_hub_tap_to_pay_tapped, properties: [AnyHashable("plan"): "jetpack_security_daily", AnyHashable("was_ecommerce_trial"): false, AnyHashable("blog_id"): 218017331, AnyHashable("is_wpcom_store"): false, AnyHashable("site_url"): "https://jhukpayments.mystagingwebsite.com"]
2023-10-10 10:24:34.394287+0900 WooCommerce[3881:1464590] 🔵 Tracked card_present_onboarding_completed, properties: [AnyHashable("site_url"): "https://jhukpayments.mystagingwebsite.com", AnyHashable("was_ecommerce_trial"): false, AnyHashable("blog_id"): 218017331, AnyHashable("plan"): "jetpack_security_daily", AnyHashable("is_wpcom_store"): false]
2023-10-10 10:24:35.492981+0900 WooCommerce[3881:1464589] 🔵 Tracked tap_to_pay_set_up_information_set_up_tapped, properties: [AnyHashable("site_url"): "https://jhukpayments.mystagingwebsite.com", AnyHashable("was_ecommerce_trial"): false, AnyHashable("blog_id"): 218017331, AnyHashable("plan"): "jetpack_security_daily", AnyHashable("is_wpcom_store"): false]
2023-10-10 10:24:35.509155+0900 WooCommerce[3881:1464545] Failed to set (isPrimary) user defined inspected property on (UIButton): [<UIButton 0x12f90df10> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key isPrimary.
2023-10-10 10:24:35.509257+0900 WooCommerce[3881:1464545] Failed to set (isPrimary) user defined inspected property on (UIButton): [<UIButton 0x12f90eeb0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key isPrimary.
2023-10-10 10:24:35.563372+0900 WooCommerce[3881:1464589] [MKTerm] User cancelled
2023-10-10 10:24:35.563612+0900 WooCommerce[3881:1464590] [xpc] <NSXPCConnection: 0x280e217c0> connection to service with pid 1636 named com.apple.merchantd.transaction: received an undecodable message for proxy 1 (no exported object to receive message). Dropping message.
*** A Tracks logging delegate has not been configured, so Tracks will log to the console. If you would like to redirect logging to an existing logging system, assign a logging delegate to TracksLogging.delegate. (You may need to import AutomatticTracksModel, depending on what else you have imported.)
Tracks <V>: TracksService sendQueuedEvents completed. Sent 28 events.
2023-10-10 10:24:38.975900+0900 WooCommerce[3881:1464545] [MKTerm] User cancelled
2023-10-10 10:24:38.993892+0900 WooCommerce[3881:1464583] 🔵 Tracked card_reader_connection_failed, properties: [AnyHashable("site_id"): 218017331, AnyHashable("was_ecommerce_trial"): false, AnyHashable("error_description"): "The payment can not be processed by the payment processor.", AnyHashable("plugin_slug"): "woocommerce-payments", AnyHashable("country"): "GB", AnyHashable("plan"): "jetpack_security_daily", AnyHashable("card_reader_model"): "COTS_DEVICE", AnyHashable("is_wpcom_store"): false, AnyHashable("connection_type"): "user_initiated", AnyHashable("site_url"): "https://jhukpayments.mystagingwebsite.com", AnyHashable("blog_id"): 218017331]
2023-10-10 10:24:40.338940+0900 WooCommerce[3881:1464587] [MKTerm] User cancelled
Tracks <V>: TracksService sendQueuedEvents completed. Sent 1 events.

``` 
</details>

<details>
<summary> US-store success transaction </summary>

```

2023-10-10 10:27:39.658560+0900 WooCommerce[3890:1467470] 🔵 Tracked card_present_onboarding_completed, properties: [AnyHashable("was_ecommerce_trial"): false, AnyHashable("site_url"): "https://indiemelon.mystagingwebsite.com", AnyHashable("blog_id"): 215063064, AnyHashable("is_wpcom_store"): false, AnyHashable("plan"): "jetpack_security_daily"]
2023-10-10 10:27:40.414335+0900 WooCommerce[3890:1467552] <> Mapping Error: Dotcom Invalid REST Route
2023-10-10 10:27:40.415510+0900 WooCommerce[3890:1467470] ⛔️ Error synchronizing Stripe Account: Dotcom Invalid REST Route
2023-10-10 10:27:40.819959+0900 WooCommerce[3890:1467372] 🔵 Tracked tap_to_pay_set_up_information_set_up_tapped, properties: [AnyHashable("was_ecommerce_trial"): false, AnyHashable("site_url"): "https://indiemelon.mystagingwebsite.com", AnyHashable("plan"): "jetpack_security_daily", AnyHashable("blog_id"): 215063064, AnyHashable("is_wpcom_store"): false]
2023-10-10 10:27:40.833943+0900 WooCommerce[3890:1467022] Failed to set (isPrimary) user defined inspected property on (UIButton): [<UIButton 0x11467e800> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key isPrimary.
2023-10-10 10:27:40.834044+0900 WooCommerce[3890:1467022] Failed to set (isPrimary) user defined inspected property on (UIButton): [<UIButton 0x1346c0ad0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key isPrimary.
2023-10-10 10:27:42.367460+0900 WooCommerce[3890:1467469] [MKTerm] User cancelled
2023-10-10 10:27:42.367902+0900 WooCommerce[3890:1467552] [xpc] <NSXPCConnection: 0x28085d860> connection to service with pid 1636 named com.apple.merchantd.transaction: received an undecodable message for proxy 1 (no exported object to receive message). Dropping message.
Tracks <V>: TracksService sendQueuedEvents completed. Sent 22 events.
2023-10-10 10:27:55.319423+0900 WooCommerce[3890:1467343] 🔵 Tracked card_reader_connection_success, properties: [AnyHashable("plan"): "jetpack_security_daily", AnyHashable("country"): "US", AnyHashable("site_url"): "https://indiemelon.mystagingwebsite.com", AnyHashable("card_reader_model"): "COTS_DEVICE", AnyHashable("connection_type"): "user_initiated", AnyHashable("blog_id"): 215063064, AnyHashable("is_wpcom_store"): false, AnyHashable("plugin_slug"): "woocommerce-payments", AnyHashable("was_ecommerce_trial"): false]
2023-10-10 10:27:57.326976+0900 WooCommerce[3890:1467343] 🔵 Tracked tap_to_pay_set_up_success_done_tapped, properties: [AnyHashable("plan"): "jetpack_security_daily", AnyHashable("site_url"): "https://indiemelon.mystagingwebsite.com", AnyHashable("is_wpcom_store"): false, AnyHashable("blog_id"): 215063064, AnyHashable("was_ecommerce_trial"): false]
2023-10-10 10:27:57.364201+0900 WooCommerce[3890:1467343] 🔵 Tracked tap_to_pay_summary_shown, properties: [AnyHashable("site_url"): "https://indiemelon.mystagingwebsite.com", AnyHashable("was_ecommerce_trial"): false, AnyHashable("blog_id"): 215063064, AnyHashable("plan"): "jetpack_security_daily", AnyHashable("is_wpcom_store"): false]
2023-10-10 10:27:58.759719+0900 WooCommerce[3890:1467552] 🔵 Tracked tap_to_pay_summary_try_payment_tapped, properties: [AnyHashable("site_url"): "https://indiemelon.mystagingwebsite.com", AnyHashable("is_wpcom_store"): false, AnyHashable("blog_id"): 215063064, AnyHashable("plan"): "jetpack_security_daily", AnyHashable("was_ecommerce_trial"): false]
2023-10-10 10:28:00.426913+0900 WooCommerce[3890:1467846] 🔵 Tracked simple_payments_flow_taxes_toggled, properties: [AnyHashable("was_ecommerce_trial"): false, AnyHashable("site_url"): "https://indiemelon.mystagingwebsite.com", AnyHashable("blog_id"): 215063064, AnyHashable("state"): "off", AnyHashable("is_wpcom_store"): false, AnyHashable("plan"): "jetpack_security_daily"]
Tracks <V>: TracksService sendQueuedEvents completed. Sent 5 events.
CoreData: debug: PostSaveMaintenance: incremental_vacuum with freelist_count - 12 and pages_to_free 5
2023-10-10 10:28:04.475957+0900 WooCommerce[3890:1467870] 🔵 Tracked card_present_onboarding_completed, properties: [AnyHashable("plan"): "jetpack_security_daily", AnyHashable("is_wpcom_store"): false, AnyHashable("was_ecommerce_trial"): false, AnyHashable("site_url"): "https://indiemelon.mystagingwebsite.com", AnyHashable("blog_id"): 215063064]
2023-10-10 10:28:06.129404+0900 WooCommerce[3890:1467870] 🔵 Tracked payments_flow_collect, properties: [AnyHashable("payment_method"): "card", AnyHashable("is_wpcom_store"): false, AnyHashable("blog_id"): 215063064, AnyHashable("flow"): "tap_to_pay_try_a_payment", AnyHashable("site_url"): "https://indiemelon.mystagingwebsite.com", AnyHashable("card_reader_type"): "built_in", AnyHashable("order_id"): 1519, AnyHashable("was_ecommerce_trial"): false, AnyHashable("plan"): "jetpack_security_daily"]
2023-10-10 10:28:06.142878+0900 WooCommerce[3890:1467022] Failed to set (isPrimary) user defined inspected property on (UIButton): [<UIButton 0x10d8a9b60> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key isPrimary.
2023-10-10 10:28:06.143000+0900 WooCommerce[3890:1467022] Failed to set (isPrimary) user defined inspected property on (UIButton): [<UIButton 0x11b419f30> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key isPrimary.
2023-10-10 10:28:14.165878+0900 WooCommerce[3890:1467552] checkAppleIDCredentialState: No Apple ID found.
2023-10-10 10:28:14.189202+0900 WooCommerce[3890:1467552] 🔵 Tracked application_opened, properties: [AnyHashable("widgets"): ""]
2023-10-10 10:28:22.377269+0900 WooCommerce[3890:1467870] 🔵 Tracked card_present_collect_payment_success, properties: [AnyHashable("is_wpcom_store"): false, AnyHashable("plugin_slug"): "woocommerce-payments", AnyHashable("country"): "US", AnyHashable("site_id"): 215063064, AnyHashable("payment_method_type"): "card", AnyHashable("was_ecommerce_trial"): false, AnyHashable("milliseconds_since_card_collect_payment_flow"): 16235, AnyHashable("site_url"): "https://indiemelon.mystagingwebsite.com", AnyHashable("card_reader_model"): "COTS_DEVICE", AnyHashable("blog_id"): 215063064, AnyHashable("plan"): "jetpack_security_daily"]
2023-10-10 10:28:25.775639+0900 WooCommerce[3890:1467552] 🔵 Tracked payments_flow_completed, properties: [AnyHashable("amount_normalized"): 50, AnyHashable("card_reader_type"): "built_in", AnyHashable("order_id"): 1519, AnyHashable("payment_method"): "card", AnyHashable("blog_id"): 215063064, AnyHashable("plan"): "jetpack_security_daily", AnyHashable("flow"): "tap_to_pay_try_a_payment", AnyHashable("is_wpcom_store"): false, AnyHashable("currency"): "USD", AnyHashable("was_ecommerce_trial"): false, AnyHashable("site_url"): "https://indiemelon.mystagingwebsite.com", AnyHashable("amount"): "$0.50"]

``` 
</details>

**Review by iamgabrielma — APPROVED** [review]
LGTM! 🚢

**Pull request merged**
