### PR TITLE
Google Ads: Update dashboard card layout

### LINKED ISSUE #13302: Update dashboard card layout following Google feedback
Internal discussion: p1720671751199109-slack-C03L1NF1EA3

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #13302 

## Description

This PR updates the Google Ads dashboard card layout following the feedback from Google. Changes include:
- Update the stats to display the total stats for paid campaigns instead of just the last active campaign.
- Display "Paid campaign performance" in the header instead of the last campaign's name and status.
- Update the title on the empty state to be the subtitle used in Hub Menu item for consistency.

## Testing steps

- Pre-requisite: Install, activate, and set up the Google Ads plugin to a test site following pe5sF9-2Qo-p2. Ensure that you're using the plugin version 2.7.5 or above. Remove any existing campaigns on your store.
- Build the app and log in to your store.
- Enable Google Ads card on the dashboard if you haven't already.
- Confirm that the title on the empty state of the card matches the subtitle on the Hub Menu entry point.
- Create a new campaign from the dashboard card.
- After successfully creating a campaign, confirm that the dashboard card displays the new title and the total stats for all campaigns. Since test campaigns don't have any impressions or clicks, feel free to stub the response of `GET wc/gla/ads/reports/programs` to confirm the correct stats being displayed.

## Screenshots

State | Before | After
--- | --- | ---
Empty |  | 
Data |  | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/213">19.5</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by selanthiraiyan — COMMENTED** [review]
👋 Huong,

I have a question about the no campaigns view behaviour. 

- I deleted campaigns from my test store.

image

- I still see the following view on dashboard card after pull to refreshing the dashboard.


This isn't the empty campaign mode view. Is this expected?

**Comment by itsmeichigo** [comment]
@selanthiraiyan Good catch! I added a fix in 9c4e5d9b0b29b2d56d6498b37ca8352491a7fe8b to reset the stats. Please try again when you can.

**Review by selanthiraiyan — APPROVED** [review]
Thanks for the updates, Huong! LGTM 🚀

**Pull request merged**
