### PR TITLE
Remove triage docs

### PR DESCRIPTION
**Pull request by toupper**
### Description
Remove issue triage docs as they're moved to p2.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by rachelmcr** [comment]
Just a heads up that there's a link to this doc in the [project readme](https://github.com/woocommerce/woocommerce-ios/blob/0a6568b2c04ae98a834f75c7b5429fdf5df2b755/README.md#-documentation) that should be removed, too.

**Comment by shiki** [comment]
We should remove the link in README as well. :) 

Edit: I left this comment before seeing @rachelmcr's comment above. 🤣

**Comment by toupper** [comment]
Thanks for the comments @rachelmcr and @shiki! I removed the link

**Pull request merged**
