### PR TITLE
Bump Zendesk. Build on Xcode 11.2.1.GM

### PR DESCRIPTION
**Pull request by ctarda**
Bump Zendesk to 3.0.3, their latest and greatest, that supports Xcode 11.2.1.

# Changes
- Bump dependency in Podfile
- Update CI to run on Xcode 11.2.1

# Testing
- Start a conversation on Zendesk in the app. Reply on web, check the reply is received on the device

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mindgraffiti** [comment]
(Circle CI is failing as expected. This is because it is not configured to build for Xcode 11.2.1)

**Comment by jkmassel** [comment]
This has been updated for CircleCI + Xcode 11.2.1 All tests pass, and installable builds are working.

It'd be nice to have someone smoke test the ZenDesk integration in order to ensure nothing is broken – from there I think this is ready to merge!

**Comment by ctarda** [comment]
Pulling in @mindgraffiti @jaclync and @pmusolino I tested the Zendesk integration nd it seems to be working, but it might be nice to have a second pair of eyes.

# Testing
- Start a conversation on Zendesk in the app. Reply on web, check the reply is received on the device

**Comment by pmusolino** [comment]
I'm downloading the latest version of Xcode to test it. 👍 
It's curious that a module compiled with Swift 5.1.2 cannot be imported by the Swift 5.1 compiler (so it doesn't work on Xcode 11.1).

**Comment by mindgraffiti** [comment]
@jkmassel @loremattei **not ready for merge**. Supporting Xcode 11.2.1 for devs requires upgrading Zendesk to v4.0.0. v4.0.0 requires migrating from v3.

See also p77Llu-cYo-p2#comment-15539

**Pull request merged**
