### PR TITLE
Podfile: Link all non shared pods as static frameworks to reduce pre-main launch time

### PR DESCRIPTION
**Pull request by jtreanor**
Sorry about the delay getting this ready. It's now ready to be reviewed 😄 

Currently, all of our CocoaPods dependencies are loaded as dynamic frameworks. Consequently, the app currently loads 28 non-system dynamic frameworks on launch. It is well documented that loading a large number of dynamic frameworks can slow down the time it takes to launch an app (see https://github.com/artsy/eigen/issues/586).

This moves most of the pods we use to be loaded as static frameworks (supported since [CocoaPods 1.5](http://blog.cocoapods.org/CocoaPods-1.5.0/)). It does not make all pods static as that would cause duplicate symbols with `Yosemite`, `Storage` and `Networking`. It reduces the number of non-system dynamic frameworks loaded on launch to 6. We could quite easily turn `Yosemite`, `Storage` and `Networking` into static frameworks and get this number to 1 if we wanted. There is also an explicit exclusion for Sentry due to an issue @jkmassel encountered.

This has been implemented and in production for WordPress-iOS since May: https://github.com/wordpress-mobile/WordPress-iOS/pull/11559.

### Testing

A smoke test of the app should confirm that this change is working correctly. Since pods are loaded statically the most likely thing to go wrong would be incorrect loading of resources (e.g. images missing from UI).

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by mindgraffiti** [comment]
Hey @jtreanor 👋 Need anything from us for this PR? I see it's still in Draft mode.

**Comment by jtreanor** [comment]
Hi @mindgraffiti. Sorry I haven't gotten back to this sooner 😞 

Nope, I'm not waiting on anything. The final step here is to update the dependencies and test thoroughly. I'll try to do that this week.

**Comment by mindgraffiti** [comment]
There's no rush. After Jeremy said his PR was ready to go, I was hoping we weren't accidentally blocking you too 😀

**Comment by mindgraffiti** [comment]
Also added @ctarda as a reviewer, since he's our Architect and may also catch something with Pods that I overlooked.

**Comment by jtreanor** [comment]
> Is that what you'd expect to see? I know Sentry is considered a dynamic framework, but it's not obvious to me what the other 2 are, from reading the podfile.

Yes, that's expected. The other two are `Alamofire` and `CocoaLumberjack` as these are shared with the `Storage`, `Networking` and `Yosemite` frameworks. If we converted those targets to be static libraries, their dependencies could be static too.

**Comment by ctarda** [comment]
Thanks @jtreanor for doing this, and thanks @mindgraffiti being on top of it.

To be honest this is completely beyond my area of expertise (I prefer saying that over just saying that I have no idea about the potential implications of the change). I cleaned the pods folder, run `bundle exec pod install` and navigated around (orders list, details, and fulfillment, notifications, settings) and logged out and back in and everything seems to work fine. 

So, it's a :shipit: from me!

**Comment by jtreanor** [comment]
Thanks @ctarda.

It's worth pointing out that these changes have been in production in WPiOS since May (https://github.com/wordpress-mobile/WordPress-iOS/pull/11559) with no issues so there is minimal risk here.

**Pull request merged**
