### PR TITLE
Show Jetpack banner and benefit modal for non-Jetpack sites

### LINKED ISSUE #9216: [REST API] Display Jetpack banner and modal without CTA while JP activation is being worked on.
Currently we're seeing user reviews where there's a confusion why some features are missing.

While the Jetpack activation feature is still in the works, let's display the Jetpack benefits banner and modal as a way to inform the limitations of REST API logins.

This modal should not include any CTA. The banner behavior should be the same for dismissal: can be dismissed but appear again in 5 days.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #9216 

## Description

This PR updates the logic of Jetpack benefit banner to show it when the user logs in to a non-Jetpack site. This helps users know what to expect when using the app without Jetpack.

Since Jetpack setup is still being implemented, the Jetpack banner has been updated to display a CTA to open wp-admin instead.

## Testing instructions

Prerequisite: Make sure that you have access to a self-hosted site with Woo but not Jetpack.
- Disable the feature flag `jetpackSetupWithApplicationPassword` and build the app.
- Log in to your test store with the correct credentials.
- After the login succeeds, notice on the dashboard screen that the Jetpack banner is present.
- Tap the Jetpack banner, the Jetpack benefit modal should be presented. Notice the CTAs should be "Open wp-admin" and "Dismiss".
- Tap "Open wp-admin", a Safari web view should be presented pointing to the Jetpack install page.

## Screenshots

https://user-images.githubusercontent.com/5533851/226545563-a15568b8-0d6d-46cb-9ed5-8570952fbbe7.mp4

| JCP | Jetpack setup enabled for non-JP site | Jetpack setup disabled | 
| ----- | ----- | ----- |
|  |  |  |

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by pmusolino — COMMENTED** [review]
It would be great if we are able to track how people are attempting to install Jetpack from here 👍 could we add some tracks events?

**Comment by itsmeichigo** [comment]
Good point @pmusolino - I added a new event for tapping the WPAdmin button in the benefits modal. This PR is ready for another look thanks!

**Review by pmusolino — COMMENTED** [review]
Hey Huong.
I just noticed the issue shown in this video 🤔 not sure why is this happening. Plus, the site is not resized but this could be a web issue and not on our side.


https://user-images.githubusercontent.com/495617/226628593-2da9f4b0-7f22-4b9e-aea6-4524c6a7bb12.mp4

**Comment by itsmeichigo** [comment]
Yes, @pmusolino that's a known issue of the Jetpack install page. Which team would you suggest talking to about this issue?

**Comment by itsmeichigo** [comment]
@pmusolino It seems from my testing that https://wordpress.com/jetpack/connect only has the scaling issue when opened in the simulator web view - I cannot reproduce it on any browsers on physical devices. Could you test again and see if this PR is good to go?

**Comment by pmusolino** [comment]
It looks good to me, but I still see this extra bar on the bottom, which seems like a webview that overlaps.
Wdyt?

**Comment by itsmeichigo** [comment]
@pmusolino That is not an issue - it's the toolbar on top of the keyboard if you enable keyboard in the simulator. It shows up because the web page has a text field there.



This only looks weird on the simulator as per my testing.

Could you please approve this PR so that it can be merged for 12.9 code freeze?

**Review by pmusolino — APPROVED** [review]
Ohh yes I see, my bad!
LGTM!

**Pull request merged**
