### PR TITLE
Dynamic Dashboard: Remove the feature flag

### LINKED ISSUE #12562: Remove feature flags
We should remove the `dynamicDashboard` feature flag to release this feature.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #12562 

## Description

This PR removes the feature flag `dynamicDashboard` to enable the feature. This also comes with a bit of cleaning up for the UserDefaults keys used for showing/hiding store onboarding and Blaze cards, as well as the configure in Settings screen for store onboarding.

There are a few more to-dos after this (which I added to the main task list of the project):
- Handle the restoring of the Blaze card after creating a new campaign.
- Removing stale feature flags for the store onboarding card.
- Clean up files of the legacy store stats flow.

Pardon the large number of changes, most of them are from removing tests 🙏 

## Testing instructions

- Build the app and log in to a store.
- Do a smoke test following the testing plan to confirm that everything looks good. Double-check the visibility of store onboarding and Blaze cards.

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/5533851/aa0413f2-9622-49e0-a59a-e37cd83d0542

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/200">18.4</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by hafizrahman — COMMENTED** [review]
This builds and works fine locally for me.

Retrying the CI job to see if it makes the error go away.

**Comment by itsmeichigo** [comment]
There seemed to be some build failures for the unit test target. I removed more tests and mocks, it should build successfully now.

**Comment by itsmeichigo** [comment]
@hafizrahman bringing the discussion from this thread [p1714109939944439-slack-C03L1NF1EA3] here for context:

> it seems like it no longer checks store onboarding eligibility on first load (but it does on pull-to-refresh)

Good catch! This was due to my check to load card details only when they are available. This causes an issue with the onboarding card since it's [originally](https://github.com/woocommerce/woocommerce-ios/blob/a8dea04dc4dfd8c71276705838fe7d2c53f85d85/WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift#L31-L34) not in the dashboard  card list.

I removed the `if` checks to avoid potential similar issues - we can look for another way to optimize the network requests later as an enhancement.

I also removed the outdated logic for hiding cards.

**Review by hafizrahman — APPROVED** [review]
Thanks for quickly checking the report and fixing it. Store onboarding loads consistently now. I believe this is ready to go 👍🏼

**Pull request merged**
