### PR TITLE
[Woo POS] Fix incorrect merge

### PR DESCRIPTION
**Pull request by joshheald**
## Description

A merge error was made when going to trunk – this fixes it.

## Steps to reproduce

Main test – does it build!

I have also checked the behaviour of the payment cancellation on view disappearance, don't feel that needs done for the review.

1. Launch the app
2. Enter POS mode 
3. Connect a reader
4. Put something in the basket
5. Tap Checkout, wait for it to say you can tap your card
6. Tap `add more`
7. Add something else
8. Tap `Checkout`
9. Tap your card this time
10. The payment should succeed.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by joshheald** [comment]
@woocommerce/ios-developers Anyone can review and merge this – no need to do the POS test, I've checked it and it's still feature flagged anyway.

Until it's merged, trunk won't build.

**Review by toupper — APPROVED** [review]
LGTM! 👍 🚢

**Comment by toupper** [comment]
@joshheald Reviewed and approved! Thanks for the quick fix

**Pull request merged**
