### PR TITLE
Fix two flaky test cases in local runs

### LINKED ISSUE #6792: Flaky unit tests when running them altogether locally
- [ ] `AddEditCouponViewModelTests.test_populatedCoupon_return_expected_coupon_during_editing`: Found difference for 
dateExpires:
```
|	timeIntervalSinceReferenceDate:
|	|	Received: 673747200.0
|	|	Expected: 673660800.0
  File: AddEditCouponViewModelTests.swift:54
```

This one is from 2019 https://github.com/woocommerce/woocommerce-ios/issues/1687, that starts failing when I run a subset of tests:
- [ ] `AddManualCustomTrackingViewModelTests.testCanCommitReturnsFalseWithoutName`: only when running all the tests altogether, passes when running the test case/class

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #6792 

### Description

While running WooCommerceTests locally as a whole, I noticed two test cases failing consistently:

#### Case 1 `AddManualCustomTrackingViewModelTests.testCanCommitReturnsFalseWithoutName`

This one is from 2019 https://github.com/woocommerce/woocommerce-ios/issues/1687 that we never got to reproduce consistently. I'm not so sure why it only starts failing consistently when I run a subset of tests locally, perhaps it's the order of the tests. The reason of failing is because in `AddCustomTrackingViewModel.init`, [if `providerName` is `nil` or empty it loads tracking providers in app settings](https://github.com/woocommerce/woocommerce-ios/blob/a848bb14f1c2c1aedbf860aef989778e7b78b297/WooCommerce/Classes/ViewModels/ManualTrackingViewModel.swift#L254-L259). In this case, because a previous test case set a tracking provider in app settings and it stays in the storage the `providerName` is no longer `nil` as expected in `testCanCommitReturnsFalseWithoutName`.

To fix this behavior, I added a line to manually unset `providerName` in the test case to ensure that a name is not set.

#### Case 2 `AddEditCouponViewModelTests.test_populatedCoupon_return_expected_coupon_during_editing`

First, I used the `assertEqual` helper in our TestKit to visualize the diffs more easily. The failure showed the difference: 
```
Found difference for 
dateExpires:
|	timeIntervalSinceReferenceDate:
|	|	Received: 673747200.0
|	|	Expected: 673660800.0
  File: AddEditCouponViewModelTests.swift:54
```

The cause is because `AddEditCouponViewModel` uses a time zone (sometimes `TimeZone.siteTimezone` and sometimes the injected one) for the expiry date of a coupon, but [the value in the existing coupon is using `TimeZone.current`](https://github.com/woocommerce/woocommerce-ios/blob/a848bb14f1c2c1aedbf860aef989778e7b78b297/WooCommerce/Classes/Model/Coupon%2BWoo.swift#L263) which might be different from the site time zone. In my simulator, `TimeZone.siteTimezone` and `TimeZone.current` are different from previous app runs. CI probably has the same time zone for both so this test always passes on CI.

This PR fixes this by setting the existing coupon's expiry date manually. Also, a time zone is now DI'ed to the view model in the test and the view model only uses the DI'ed time zone throughout the class. I think generally it's better to avoid using `Date()` but I didn't want to make too many changes that aren't directly related.

### Testing instructions

You can run WooCommerceTests altogether, or disable test cases after the 5th one, and make sure all tests pass.

Screen Shot 2022-05-09 at 10 33 01 AM

If you've run the app in the simulator with a site that has a different time zone from the simulator, `AddEditCouponViewModelTests.test_populatedCoupon_return_expected_coupon_during_editing` should not be passing before this PR. For `AddManualCustomTrackingViewModelTests.testCanCommitReturnsFalseWithoutName`, I only saw the failure when I disabled test cases after the 5th one.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by itsmeichigo** [comment]
Thank you @jaclync for taking care of the tests! The fix for the first case looks good to me - however, I'm not sure about the timezone fix since we're intending to use the site timezone for coupon expiry dates. I'm wondering if we can find some other way to fix this without having to change the tested timezone 🤔 

Unassigning myself from this PR to wait for @pmusolino's opinion 👀

**Comment by jaclync** [comment]
> The fix for the first case looks good to me - however, I'm not sure about the timezone fix since we're intending to use the site timezone for coupon expiry dates. I'm wondering if we can find some other way to fix this without having to change the tested timezone 🤔

The view model is initialized with a time zone with the site time zone as the default, though it's not currently used. Is this injected time zone for a different purpose?

https://github.com/woocommerce/woocommerce-ios/blob/3b420d5ea040c5a181aec696637f7367d4568dbb/WooCommerce/Classes/ViewRelated/Coupons/Add%20and%20Edit%20Coupons/AddEditCouponViewModel.swift#L145-L151

We could also rename this time zone property to `siteTimeZone` if we end up using it 🙂 

The fix should work without any changes in `AddEditCouponViewModel`, just the change in the existing coupon in the test case should be sufficient. I just thought it's generally easier for unit testing to use the injected property.

**Review by itsmeichigo — APPROVED** [review]
> The fix should work without any changes in AddEditCouponViewModel, just the change in the existing coupon in the test case should be sufficient. I just thought it's generally easier for unit testing to use the injected property.

This is true! So sorry for misunderstanding earlier 😅 It makes sense to use the injected value instead - this tests well for the expiry date update of coupon so I'm approving this 👍

**Review by pmusolino — APPROVED** [review]
As said by @jaclync, we are injecting the timezone just for testing purposes 👍 so the changes LGTM. 💯 

Thanks, @jaclync, for fixing them!

Tests are ✅

**Comment by jaclync** [comment]
CI failed at Installable build - AppCenter upload after a few retries, which is most likley unrelated to the PR changes. Merging this PR now to avoid merge conflicts!

```
  +------+---------------------------------------+-------------+
  --
  | \|                      fastlane summary                      \|
  | +------+---------------------------------------+-------------+
  | \| Step \| Action                                \| Time (in s) \|
  | +------+---------------------------------------+-------------+
  | \| 1    \| default_platform                      \| 0           \|
  | \| 2    \| is_ci                                 \| 0           \|
  | \| 3    \| is_ci                                 \| 0           \|
  | \| 4    \| setup_ci                              \| 0           \|
  | \| 5    \| sentry_check_cli_installed            \| 0           \|
  | \| 6    \| Switch to ios alpha_code_signing lane \| 0           \|
  | \| 7    \| match                                 \| 8           \|
  | \| 8    \| gym                                   \| 467         \|
  | \| 💥    \| appcenter_upload                      \| 0           \|
  | +------+---------------------------------------+-------------+
  |  
```

**Pull request merged**
