### PR TITLE
[Analytics Hub] Display error messages after an error retrieving order stats

### LINKED ISSUE #8213: [Analytics Hub] Handle empty and error states
We should aim to handle network errors and empty data just like the My Store stats do, with an empty state message:

Each stats card should display its own empty state message, so if just one stats request fails, the other ones can still display data:

- [x] Error state for failed order stats requests (Revenue, Orders, Products cards)
- [x] Error state for failed top performers stats request (Products card)
- [ ] Error state for failed visitor stats request (Visitors & Views card)

For the scenario where the Date range acquisition fails, then we won't be able to trigger not a single stats request. For this scenario:

- [x] We should pop out of the Analytics Hub back to the My Store view and display a notice about a critical error.

### PR DESCRIPTION
**Pull request by rachelmcr**
Part of #8213

## Description

This PR adds support for displaying an error message on each card in the Analytics Hub when there is an error retrieving order stats. Before, we were just showing an empty state with no clear error message.

**Note:** The error message is displayed below the placeholder data on each card. Right now, the delta tag placeholders stick out with a red background, but that will be updated to gray in #8243.

## Changes

* Each analytics card now has a `showSyncError` property to determine if the error should be shown, and a unique error message for that card.
* In `AnalyticsHubViewModel`, if either the current or previous order stats are `nil` when a card's view model is being created, that card's `showSyncError` property will be set to `true`.
* Updates tests to confirm that each card state works as expected (showing data when it's available, redacted while the network request is made, and showing an error when the network returns an error).

## Testing

1. Disable your network connection (to cause a sync error).
2. Launch the app.
3. Tap the "See more" button on the My Store dashboard.
4. Notice the analytics cards display placeholder data and a clear error message.

## Screenshots

Before|After
-|-
Empty state|Sync errors

https://user-images.githubusercontent.com/8658164/205099239-29968626-946c-4d73-8c5f-2a28daa12559.mp4

## Submitter Checklist

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by rachelmcr** [comment]
Sorry, no need to review this PR yet! As discussed in Slack I'm going to work on a version that retains some of the placeholders (internal ref: p1669894452036299/1669742778.905919-slack-C02KUCFCSFP) and I'll update here when that's done.

**Comment by rachelmcr** [comment]
Ok, this is now ready for review!

**Comment by rachelmcr** [comment]
I've also merged the latest from trunk and just want to point out that on the Products card, the error message will appear above the Top Performers section:



Since Top Performers come from a separate API request, they can be displayed if that request works (even if the order stats requests fail) and so they should have separate error state handling.

**Review by ThomazFB — APPROVED** [review]
Thanks for sorting out the way we should display the error and implementing it!  LGTM! :shipit:

**Pull request merged**
