### PR TITLE
[Payments Menu] Prepare Payments Menu for release

### LINKED ISSUE #11111: [Payments Menu] Remove Experimental Feature toggle and storage

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #11111

## Description

This PR removes the toggle, feature flag, and code for the old payments menu, preparing for release of the rewritten SwiftUI payments menu.

Unit tests still need to be updated for the new menu, however, and have been temporarily commented out.

## Testing instructions

1. Delete the app from your test device
2. Launch the app from Xcode
3. Navigate to Menu > Payments
4. Observe that the new payments menu is shown

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by iamgabrielma** [comment]
We need to comment out or bypass temporarily some of the UI tests as well, we have 3 failing tests in both iPad and iPhone:
```
test_complete_cash_simple_payment() in PaymentsTests (2 times)
test_load_chipper_card_reader_manual() in PaymentsTests (2 times)
test_load_learn_more_link() in PaymentsTests (2 times)
```

I just took a quick look and some of the tests rely on the component being a UIKit `cell`, so it fails to find the UI element with the SwiftUI rewrite:
```
    private let collectPaymentButtonGetter: (XCUIApplication) -> XCUIElement = {
        $0.cells["collect-payment"]
    }

    private let cardReaderManualsButtonGetter: (XCUIApplication) -> XCUIElement = {
        $0.cells["card-reader-manuals"]
    }
```

It seems a good case to revisit these tests too, since perhaps relying on an identifier rather than the concrete framework implementation would make them less flaky. Would it be preferable to keep the feature flag and set it to `!isUITesting` for the moment?

**Comment by joshheald** [comment]
@iamgabrielma Thanks for the review

> It seems a good case to revisit these tests too, since perhaps relying on an identifier rather than the concrete framework implementation would make them less flaky. Would it be preferable to keep the feature flag and set it to `!isUITesting` for the moment?

I'll flag them with QE... I've commented them out for now, reinstating the feature flag for this means leaving the legacy code in... and I don't think there's a good reason to leave in code we don't use any more, it's just confusing.

Could you approve this please?

**Comment by joshheald** [comment]
I'm AFK tomorrow so I've fixed the conflicts and enabled auto-merge pending your review.

**Review by iamgabrielma — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
