### PR TITLE
Merge/release 5.8 to develop after beta (fix conflict)

### PR DESCRIPTION
**Pull request by AliSoftware**
Replaces #3490 to fix pbxproj merge conflict. It contains:

 - The release-toolkit update from #3432
 - The fix #3483 + its patch #3489
 - The update of all the Localized strings pulled from GlotPress
 - [UPDATE] Also includes the fixes #3496 + #3497 to fix the metadata oddities which were present in this PR before (see below for details).

```
                                          #3496  #3497
                     #3483   #3489          ▼      ▼
                        ▼       ▼         ○──○   ○──○
╔═════════════╗          ╲       ╲       ╱    ╲ ╱    ╲
║ release/5.8 ║─ ─○─ ─ ─ ─●───────●─────○──────○──────○─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ▶
╚═════════════╝        5.8.0.1  5.8.0.2  ╲             ╲
                ╱                   ╲     ╲             ╲
                                     ╲     ╲             ╲  ┌────────────────────────────┐
              ╱                     ○━◎━━━○━○━━━━━━━━━━━━━○ │merge/release-5.8-to-develop│
                                   ╱  fix                   └────────────────────────────┘
            ╱                     ╱ conflict                ╲
╔═══════╗                        ╱
║develop║─○───────────────○──○──○─────────────────────────────◌─────────────▶
╚═══════╝
```

----
### Note about metadata changes

<details><summary>Old notes about metadata oddity in this PR – fixed since</summary>

⚠️ Note: that PR seems to have also removed a lot of `fastlane/metadata/*` files in [during `new_beta_release` when updating metadata translation](https://github.com/woocommerce/woocommerce-ios/pull/3495/commits/d59a50a2bb595c412f2a2d4a52c5296919c73ecb) which seems odd 🤔  _(Tried to [re-run `download_metadata.swift` separately](https://github.com/woocommerce/woocommerce-ios/pull/3495/commits/24c075711bfbc3644ca10e4dee35dafdb5a95bab) to no avail)_

@jkmassel I think that might be due to your recent PR updating the scripts and metadata? Is that expected?
For the `fastlane/metadata/*/release_notes.txt` files I can guess that it's probably because the Release Notes are not yet translated in GlotPress. But for the other metadata files, I'm a bit more confused.

I think what's happening is that since we don't have a 5.8 entry in ASC yet, fastlane was not able to find the metadata (copyright, etc) in ASC for those and deleted the metadata ? And they _should_ hopefully be pulled back when we will `finalize_release` after we will have created 5.8 in ASC? Though `copyright.txt` is not attached to versions in ASC…

I'd love to have your thoughts on this.

_[EDIT: PR moved back to Draft state as we fix this metadata issue in a separate PR and update that one once the fix has landed]_
</details>

After the fix from #3496, there should not be any more unexpected metadata deletion left (e.g. about name/copyright and similar metadata). This PR **still contains updates to metadata files**, but those should now only be restricted to:
* updates in localized content of those metadata pulled from GlotPress after translation.
* deletion of the release-notes.txt files that are not yet translated in GP for 5.8 as of today.

Still given the past comments and found issue about them in previous state of this PR, it's worth taking a bit of extra care when reviewing this PR that those metadata changes are correct.

### CODE REVIEW

**Comment by AliSoftware** [comment]
Converted the PR back to Draft as @jkmassel will soon take a stab at fixing the metadata issue in a separate PR targeting `release/5.8` to fix the erroneously deleted metadata files seen in that diff.

Once that fix on metadata has landed on `release/5.8`, we will merge `release/5.8` back into the `merge/release-5.8-to-develop` branch to update this PR and undraft it again.

**Comment by AliSoftware** [comment]
Undrafting again now that #3496 have fixed the metadata issues – thx @jkmassel 

Still worth taking some extra care during this PR's review that the remaining changes in the metadata in this PR are the expected ones.

**Comment by AliSoftware** [comment]
Just to note that we might still want to merge the other metadata fix #3497 first before merging this one

**Comment by AliSoftware** [comment]
Included #3497 so ready for review again (especially about diff on metadata \cc @jkmassel)

**Review by jkmassel — APPROVED** [review]
This looks good to me – lots of code changes, but now the metadata changes look like what I'd expect to see.

Merging.

**Pull request merged**
