### PR TITLE
Set the right timezone when setting the expire date of a Coupon

### LINKED ISSUE #6687: Edit Coupon: set the right timezone when setting the expire date
During the implementation of this PR https://github.com/woocommerce/woocommerce-ios/pull/6686, @itsmeichigo pointed me that we should take care also of the timezone probably, and I believe she is right. Right now we are sending back and fort the GMT timezone, instead we should do this:

- After parsing the expiry date, display it in the Edit screen and in the date picker considering the timezone of the current store (like we do in product prices) and not the timezone of the device.
- When we send back the info to the API, we shouldn't use the `dateTimeFormatter` under the `DateFormatter` extension, used by the method `toDictionary()` but we should implement a version where the timezone took in consideration is the one selected in the store.

### PR DESCRIPTION
**Pull request by pmusolino**
Closes #6687 

### Description
In this PR I took care of the timezone in the expiration date field for Coupon during the editing/addition phase.
- Now the `updateCoupon` and `createCoupon` methods accept the timezone parameter because we are setting the site timezone for updating the `date_expires` fields.
- The `CouponExpiryDateView` now works by default with the site timezone.

### Testing instructions
- Open a Coupon detail, and start the editing flow.
- Try to edit the date of the coupon, and save it.
- Launch Wormholy from Settings, and inspect the API request made.
- You should see in the `date_expires` field the time configured on the app at the time `00:00:00`.
- You should see in the `date_expires_gmt` field the date GMT configured on the app (you could also check the timezone configured on your website by navigating on wp-admin > Settings > General > TimeZone to see if the date is correct).

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by itsmeichigo — COMMENTED** [review]
Hi, it seems that I cannot verify these points:

> You should see in the date_expires field the time configured on the app at the time 00:00:00.
You should see in the date_expires_gmt field the date GMT configured on the app (you could also check the timezone configured on your website by navigating on wp-admin > Settings > General > TimeZone to see if the date is correct).

I'm setting UTC+7 for my site and when updating the expiry date to August 31, the `date_expires` sent in the API request is the same date with the time minus 7hrs. 

Screen Shot 2022-04-29 at 10 50 31

If I understand the thread p1651142542232179-slack-C02TD63FZA8 correctly, here are what we should do instead:
- Get the date from the date picker, strip the time off so we get a date at 00:00. Send this date when updating or creating coupons.
- When displaying the expiry date, parse the `date_expires` instead of `date_expires_gmt` like what we're doing at the moment. I'm not sure though whether we should take into account the site timezone when displaying `date_expires`.

Please correct me if I'm wrong - timezones are hard 🤯

**Comment by pmusolino** [comment]
I don't know why, but I just forgot to save the expiry date at the start of the date selected (which is like sending just the date without the time) 4339037d897cdba8f4249b228246bbaa0c5fd559
 Now everything works as expected 👍 can you do another check, please?

**Comment by pmusolino** [comment]
Are you able to review this PR @selanthiraiyan since Huong is AFK?

**Comment by selanthiraiyan** [comment]
### Device vs `wp-admin` timezone setting

Sorry, I don't understand the device vs `wp-admin` timezone configuration part.

Can you please share some points about what should happen if my device is in a different time zone? 
- Do we try to convert the selected date from the device timezone into the site's timezone?
- When we receive a date in response, do we receive the date in the `GMT` timezone or in the site timezone?

Sorry for lacking context. I believe that this will be useful for someone looking into this PR in the future.
Thanks a lot.

-------

### Inconsistent expiry date
Upon editing an expiry date in the device, I see an inconsistency in the expiry dates between the device and `wp-admin`.

https://d.pr/v/4PivY6

I had to restart the app to get rid of this issue.

After restarting the app,
- The coupon detail screen updates the date after displaying the wrong date for a split second.
- The edit coupon still shows the wrong expiry date.
- The expiry date in the edit coupon screen eventually gets updated to the correct value after navigating back and forth.

Please note that my store and device have the same time zone set. UTC+5:30

Is this work in progress?

**Comment by pmusolino** [comment]
> Can you please share some points about what should happen if my device is in a different time zone?

The timezone of the device must not affect the data sent at all, but the timezone configured on the website must be taken into account (you can see it under wp-admin > Settings > General > TimeZone).

> I had to restart the app to get rid of this issue.
> After restarting the app,
> The coupon detail screen updates the date after displaying the wrong date for a split second.
> The edit coupon still shows the wrong expiry date.
> The expiry date in the edit coupon screen eventually gets updated to the correct value after navigating back and forth.
> Please note that my store and device have the same time zone set. UTC+5:30

If I understand correctly, the timezone configured from the web is not correctly displayed on the app?

**Comment by selanthiraiyan** [comment]
> If I understand correctly, the timezone configured from the web is not correctly displayed on the app?

After editing the expiry date from device, the dates in device and `wp-admin` do not match. You can see that in 0:36 seconds from [the video](https://d.pr/v/4PivY6). And, the device nad `wp-admin` are using the same timezone. UTC+5:30

Attaching a screenshot below for clarity.
Screenshot 2022-05-03 at 7 38 59 PM

Kindly let me know if this isn't clear.

**Comment by pmusolino** [comment]
@selanthiraiyan It looks like a behavior not depending on the timezone. 🤔 
As you said, it doesn't care from where I update the date (app or wp-admin), it looks like the date displayed (after a refresh) will be always the day before. But... If I relaunch the app everything is correct.
BTW the date update from the app or the web is correct.
I'm investigating why this is happening because it doesn't make sense.

**Comment by pmusolino** [comment]
@selanthiraiyan @itsmeichigo, ready for the definitive review! 🤞  I moved to `date_expires` without considering the `GMT` version anymore. Now everything seems to work fine.

**Review by itsmeichigo — APPROVED** [review]
The new update looks good to me and tests well also! :shipit:

**Pull request merged**
