### PR TITLE
Fixed failing tests in release 4.4

### PR DESCRIPTION
**Pull request by pmusolino**
Fixed a failing test occurred after merging #2366.

This needs to be merged in release 4.4.

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by oguzkocer — APPROVED** [review]
As explained [in this comment](https://github.com/woocommerce/woocommerce-ios/pull/2378#issuecomment-638294402) I think this (merging to `release/4.4` is the right way to go, but I am just going to approve the PR and let @loremattei merge it, just in case I am mistaken.

**Review by shiki — APPROVED** [review]
Thanks for fixing this!

**Review by jaclync — APPROVED** [review]
Oh wow, thanks for noticing and fixing this @pmusolino! I was wondering how I missed this from my PR https://github.com/woocommerce/woocommerce-ios/pull/2366 🤔 maybe the test case was added after I last pulled from `develop` and this wasn't a merge conflict. I'll make sure to watch for a build after merging to release/`develop` branches more next time!

**Review by loremattei — APPROVED** [review]
Thank you all for fixing this!

**Pull request merged**
