### PR TITLE
[Settings] Show WooCommerce version and available updates in settings

### LINKED ISSUE #7778: Show the version of your WooCommerce store inside the app
It could be useful for the final user to show the current version that they are using for the selected store in the mobile app, and if a new version of WC is available.

This should encourage users to keep WooCommerce updated to the latest version available.

p1605527730186100-slack-CGPNUU63E

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #7778

### Description

Adds a `WooCommerce Version` row in Settings, showing the user whether their site has an up-to-date WooCommerce plugin or not, and if not, linking them to the wp-admin screen to update it.

### Testing instructions

On a store with an outdated copy of WooCommerce

1. Navigate to Hub Menu > ⚙️
2. Observe that the WooCommerce Version row has the correct version number.
3. Observe that `Update available` is shown, along with the version number
4. Tap the row and log in to your wp-admin
5. Update WooCommerce
6. Tap done
7. Observe that the row shows `Up to date` after the update is complete

N.B. you can simulate the above by putting a Charles/Proxyman breakpoint on the `/wc/v3/system_status` response, and editing the `woocommerce/woocommerce.php` plugin's `version` attribute to be lower than the `versionLatest`.

### Screenshots

https://user-images.githubusercontent.com/2472348/192614971-bdfa8443-c232-4353-b671-80f5106b86c2.mp4

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by joshheald** [comment]
@joe-keenan Please could you do a brief design review on this, if you have a moment? It's a HACK week project so low priority.

**Comment by jostnes** [comment]
This looks good to me from a UI test and testing perspective:
1. The UI test works well after changing the element from `log out button` to `beta feature button`. Thanks for making this change!
2. Since I was looking at the PR, I tested the new functionality as well. I tested a few "old" versions, and it works well. However, there was one time when it didn't display the "update available" message for an older WC version and showed "up to date" instead. I thought it was because of the auto-update was set but I couldn't reproduce it a second time after enabling/disabling auto-updates. Noting it here in case someone else manages to reproduce it again while reviewing this PR.

IMG_0156

**Comment by joshheald** [comment]
Thanks for the review @jostnes 

> However, there was one time when it didn't display the "update available" message for an older WC version and showed "up to date" instead. I thought it was because of the auto-update was set but I couldn't reproduce it a second time after enabling/disabling auto-updates. Noting it here in case someone else manages to reproduce it again while reviewing this PR.

That's a bit of a worry, but good that it did resolve itself. I'll see whether I can get it to do the same with auto-updates... but it would surprise me a little.

Was that the first time you opened settings with the feature on that device?

It relies on the stored values for the SystemPlugins, which are retrieved when you switch site, and at launch. It may be that you had stale data in Core Data, and it wasn't refreshed. I avoided refreshing it when the screen was shown, because it seemed like an unnecessary network request as the data would not change often, but if it's _only_ loaded at fresh launch then perhaps we need to do it a bit more often.

I'll have a bit of a play, and potentially add a call to refresh the plugins when the settings screen is shown.

**Comment by toupper** [comment]
Code looks good and tests well for me 👍

**Review by toupper — APPROVED** [review]

**Comment by jostnes** [comment]
> Was that the first time you opened settings with the feature on that device?
No it wasn't, it was after a couple of times. This was the flow that I did when the screenshot happened:
1. Remove WC via wp-admin, upload an older version of WC 
2. Go to app > saw that "update version" message displayed > update WC via webview > this went really smooth
3. Remove again and add a different older version (I was playing around with the auto updates toggle on wp-admin at this point too)
4. Saw the above "up to date" screenshot instead of the "update version" message

I tried to do the exact same flow again but wasn't able to reproduce it a second time. Let me know if you think this is worth creating a separate issue for and I can create one.

**Comment by joshheald** [comment]
> I tried to do the exact same flow again but wasn't able to reproduce it a second time. Let me know if you think this is worth creating a separate issue for and I can create one.

@jostnes Thanks, but no, I don't think we need an issue for it if we can't repro it, it's very minor and our attention is better focused elsewhere. I've added a call to sync the plugin data when the settings screen is opened, which feels like an OK balance as this is a fairly uncommonly used screen, and makes it very unlikely that we have stale data showing her.

**Comment by joshheald** [comment]
> Code looks good and tests well for me 👍

@toupper Thanks for the review!

I'm going to merge this now as it's a fairly minor change and we might as well ship it. @joe-keenan if you have any comments on the design, please let me know and I can look at addressing them, or removing it if you think there's a big issue here 😄

**Comment by joe-keenan** [comment]
Hey @joshheald, apologies for the delay!

I think this is mostly good. There are a few small visual things I think could be changed.

First up, the alignment of the text and icons looks a bit off.

image

And the icon is slightly larger than the rest of the rows.

CleanShot 2022-10-04 at 13 29 57@2x

Finally, while my brain does some mental gymnastics seeing “WooCommerce” listed under “Plugins” while using the actual WooCommerce app, and even more gymnastics when tapping WooCommerce takes me to a screen titled “Plugins”… I think the fact that it does take us to this screen means we can’t get away from showing it under the plugins heading, lest the flow make even less sense.

I do think the hierarchy of importance would suggest that the WooCommerce plugin is the most important one, though, and so deserves the top spot.

Lastly, I’d increase the font size to “Subhead”, and change the text colour to Yellow-50 so that it meets accessibility contrast guidelines.

image


I also wondered, does this whole row only show up when there’s an update, or will it be permanently visible?

If it’s permanent, I don’t think we need to show the “up to date” stamp all the time. It’s a nice confirmation when you’ve completed the update, but most of the time it will just take up space unnecessarily.

Hope that helps!

**Pull request merged**
