### PR TITLE
[HACK week] Product form - Action buttons to mark/remove as favorite

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Part of: #12274 

## Description

Show action buttons in product form to mark/remove a product as a favorite. We will show favorite products in the product list screen in a future PR.

Changes
- Feature flag to allow marking a product as favorite.
- Use case to store favorite product list into user defaults.
- Add action buttons to mark/remove a product as favorite.

## Testing instructions
- Turn on the `favoriteProducts` feature flag by returning `true` from [here](https://github.com/woocommerce/woocommerce-ios/pull/12284/files#diff-26c9afc49bb1f1a168517d43d5e36a64ff45adb046469369ef3e4d6800ccc19bR92)
- Login into the app
- Navigate to Products tab
- Open any product
- Tap "…" from the action sheet tap "Mark as favorite"
- From Xcode log ensure that `product_detail_mark_as_favorite_tapped` event is tracked
- Navigate back/Quit the app
- Open the same product again from the Products tab
- Tap "…" from the action sheet 
- You should see "Remove from favorite" option. Tap on it to remove the product from favorite list.
- From Xcode log ensure that `product_detail_remove_from_favorite_tapped` event is tracked
- Reopen the product and validate that you see "Mark as favorite"
- Switch stores and ensure that the product marked as favorite is still marked as favorite. 
- Log out and log into the same store again. Validate that the favorite products list is cleared after logout.

## Screenshots
Simulator Screen Recording - iPhone 15 Pro - 2024-03-15 at 11 13 16

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/225">20.6</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by hafizrahman — APPROVED** [review]
This works as expected, nice work. I understand everything is local data, but am curious if it's feasible to keep favorites even after logging out. Most users probably expect that to happen, not knowing the technical limitation.

I tried looking into Core to see if there is a built-in feature for this. The closest I found is the "Favorite" feature:
Screenshot 2024-03-18 at 14 26 58

This also affects how products are shown on the site itself, though, and if I understand correctly, this feature we're building is just for product management. In the future if we revisit this feature, I wonder if we can take into account this "Featured" functionality (e.g: by adding "Featured" option in the "Sort by" selector in the app).

**Comment by selanthiraiyan** [comment]
Thanks for the review, Hafiz! Marking it as draft to address feedback about using userdefaults in https://github.com/woocommerce/woocommerce-ios/pull/12287.

**Comment by selanthiraiyan** [comment]
> I tried looking into Core to see if there is a built-in feature for this. The closest I found is the "Favorite" feature:

Thanks for the input, @hafizrahman!

Yes, I took a look at this before starting work and learned that this feature in core is used to feature the product to the users (customers). 

Our "Favorite product" feature's goal is to allow merchants to favorite products for easy management. 

They are different features and our feature will be mobile only (with no backend support from core) at least for now.

**Comment by selanthiraiyan** [comment]
👋 again @hafizrahman,

I have revisited this PR and pushed changes to,
- Stop using user defaults to store favorite product information.
- Use `GeneralStoreSettings` and `AppSettingsStore` to store the favorite products information. 
- Add unit tests. 

Please take another look at the PR when you can. Thank you!

**Comment by selanthiraiyan** [comment]
Sorry, Hafiz! I am marking this PR as a draft until I find time to address the feedback from this child PR. https://github.com/woocommerce/woocommerce-ios/pull/12287#issuecomment-2175450767

**Comment by selanthiraiyan** [comment]
Thanks for the review, @hafizrahman! The PR is ready for another look.

**Review by hafizrahman — APPROVED** [review]
Thanks for the update, this looks good to me now.

I tested this in Simulator with iOS 17.5 on these cases and all good:
1. adding favorite
2. removing favorite
3. adding then logging out and back in again
4. adding then switching store and switching back in

**Pull request merged**
