### PR TITLE
[Deposit Summary] swipe between currencies

### LINKED ISSUE #11300: [Deposits Summary] Make it possible to swipe between currencies

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #11300

## Description

The new Deposit Summary displays the currency summaries in a custom TopTabView. In the Android equivalent, it's possible to swipe between the tabs, which is a nice touch.

This PR adds that swipe gesture to the TopTabView, allowing swiping between currencies, both when the view is collapsed and expanded.

Coded with the help of ChatGPT

## Testing instructions

1. Launch the app
2. Switch to a WooPayments store with multiple currencies set up
3. Navigate to `Menu > Payments`
4. Swipe between currencies
5. Observe that the swipe gesture is interruptable
6. Observe that `payments_hub_deposit_summary_currency_selected` is tracked for swipes which actually end in a change of tab only.

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/2472348/e08758ff-45c4-4e00-8c76-311a9687665e

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by toupper** [comment]
Hi @joshheald I'm trying to configure my store with multicurrency to test the PR, but I still cannot see the new currency tab. Things I've done:

- Add a second currency in `wp-admin/admin.php?page=wc-settings&tab=wcpay_multi_currency`.
- Enable _Automatically switch customers to their local currency if it has been enabled_
- Check out a product paid with the second currency

**Comment by joshheald** [comment]
> Hi @joshheald I'm trying to configure my store with multicurrency to test the PR, but I still cannot see the new currency tab. Things I've done:
> 
> * Add a second currency in `wp-admin/admin.php?page=wc-settings&tab=wcpay_multi_currency`.
> * Enable _Automatically switch customers to their local currency if it has been enabled_
> * Check out a product paid with the second currency

@toupper  I'm afraid I can't remember how I did it, but I've invited you to my store...

**Review by toupper — APPROVED** [review]
With your store works fine @joshheald, nice job. LGTM! 🎉 🚢 :shipit: 

It might be worth checking what are the conditions that make the extra currencies appear on screen, as well as reproducing the case with many currencies to make sure that it doesn' break the layout.

**Comment by joshheald** [comment]
> With your store works fine @joshheald, nice job. LGTM! 🎉 🚢 :shipit:

@toupper Thanks! ChatGPT was a great help, it's nice to feel like we can tackle these thornier but nicer UI approaches without the timescales spinning out of proportion with the benefit.

> It might be worth checking what are the conditions that make the extra currencies appear on screen, 

Agreed – AIUI, the condition for a currency to show in this view is that you have a linked bank account or debit card for the currency, not just offer a currency to customers. By default, extra currencies get converted to your default currency and added to your main balance. For any additional currencies that you have a bank account for, those get separate deposits and show up here, as they can have different deposit schedules etc.

> as well as reproducing the case with many currencies to make sure that it doesn' break the layout.

Yeah, thanks for the reminder, I'm going to fake this and check it before I merge.

**Comment by joshheald** [comment]
> > as well as reproducing the case with many currencies to make sure that it doesn' break the layout.
> 
> Yeah, thanks for the reminder, I'm going to fake this and check it before I merge.

@toupper Found some issues, fixed them in 413d3f4.

Not a _perfect_ fix, see the centring of JPY when expanding and collapsing, but pretty much there.

https://github.com/woocommerce/woocommerce-ios/assets/2472348/021aa840-03a6-47cf-be41-23a3497d9e5d

**Pull request merged**
