### PR TITLE
[Shipping Labels] Custom package weight sometimes as box_weight sometimes as boxWeight

### LINKED ISSUE #14725: Bug: custom package weight sometimes as box_weight sometimes as boxWeight
Looks like that the endpoint for creating custom package returns the weight as `boxWeight` and general endpoint for getting packages returns custom packages with weight as `box_weight` so we need to handle both cases since we use same struct for both responses

### PR DESCRIPTION
**Pull request by bozidarsevo**
Closes: #14725

## Description

- Looks like that the endpoint for creating custom package returns the weight as `boxWeight` and general endpoint for getting packages returns custom packages with weight as `box_weight` so we need to handle both cases since we use same struct for both responses.
- If in the future backend uses same naming convention for those endpoints we can remove this logic

## Testing information

1. Install and set up the Woo Shipping extension on your store.
2. Build and run the app with the revampedShippingLabelCreation feature flag enabled.
3. Create an order with the processing status and at least one physical product.
4. In your WooCommerce product settings on the web, change the weight and dimension units and save your changes.
5. On the Orders tab in the app, open the order you created.
6. In the order details, select "Create Shipping Label."
7. Tap "Select a Package."
8. Fill in all the values for the package, including weight and name and tap "Add Package"
9. Check that on the Create Shipping Labels screen the newly created package is shown, with proper name, dimensions and weight

## Screenshots

| Before      | After |
| ----------- | ----------- |
|   Simulator Screenshot - iPhone 16 Pro - 2024-12-18 at 16 11 39    |   Simulator Screenshot - iPhone 16 Pro - 2024-12-18 at 16 13 22  |

### Before

When we created new package with weight, the weight would not show in the UI because endpoint for creating the package would return the weight with a different parameter name.

https://github.com/user-attachments/assets/e2578353-3e4e-43d0-b21b-9617d2129236

### After

https://github.com/user-attachments/assets/489788da-e062-4fba-b021-1b8cd727a504

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/233">21.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by bozidarsevo** [comment]
@toupper @rachelmcr what do you think, is this ok for now or should we push for the endpoints to have one way of doing it, to have a naming convention for the parameters in the response?
To have it either `box_weight` or `boxWeight`, and not both?

**Comment by rachelmcr** [comment]
> is this ok for now or should we push for the endpoints to have one way of doing it, to have a naming convention for the parameters in the response?

I think it's worth asking for more consistent key casing in the REST API, but it seems reasonable to work around the current behavior for now to make sure everything is working. As you mentioned, we can remove the workaround if the keys are updated in the future.

**Review by rachelmcr — APPROVED** [review]
This seems like a reasonable set of workarounds. Let's ask the team if we can get consistent keys/value types for the custom packages so we can hopefully remove the workarounds at some point.

Another option for simplifying this logic could be to use a `failsafeDecodeIfPresent` method from our `KeyedDecodingContainer` extensions. We can use those to decode different value types from the same key (e.g. double or string). It looks like we'd need to add a method that decodes to a `Double`, but that way we could decode both the string and double types in a single method. Just a suggestion to reduce all the if/else checks, but not critical.

**Comment by bozidarsevo** [comment]
> Another option for simplifying this logic could be to use a `failsafeDecodeIfPresent` method from our `KeyedDecodingContainer` extensions.

Nice! Sure looks like a simpler option for this! Will use it in a separate PR, tnx!

**Comment by bozidarsevo** [comment]
> I think it's worth asking for more consistent key casing in the REST API, but it seems reasonable to work around the current behavior for now to make sure everything is working.

It will be done with https://github.com/woocommerce/woocommerce-shipping/issues/1050 so after that is merged we can remove our double logic

**Pull request merged**
