### PR TITLE
[Mobile Payments] update tap on mobile designs

### LINKED ISSUE #8355: [Mobile Payments] Use new designs for Tap on Mobile connection and payment screens
## Description

We have updated designs for the Tap on Mobile flows (see pdfdoF-1J0-p2#comment-3038)

image

This ticket covers updating the Tap on Mobile screens with the new designs.

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #8355

## Description

In sTAP Away, we're adding support for payments using the built-in card reader. With two routes through the payment screens, it's helpful to the user to be visually clear whether they are using the built in reader, or an external bluetooth reader.

This PR adds new images for the built in reader flow.

### Using an iPhone XS or newer on iOS 16.0 or newer

1. Navigate to `Menu > Settings > Experimental features`
2. Turn on `Tap to Pay on iPhone`
3. Navigate to `Menu > Payments > Collect payment`
4. Go through the payment flow, and select `Card` on the payment method screen
5. When asked for a reader type, tap `Tap to Pay on iPhone` and go through the Terms of Service Apple ID linking (if you've not done so before)
6. Tap the card to pay
7. Observe that the screens are all updated to match the new design

Disconnect the (built in) reader in `Manage card reader`

Repeat the test with the legacy bluetooth flow, tapping your card on the reader
Observe that the existing designs are still used for the bluetooth reader flow.

## Screenshots

https://user-images.githubusercontent.com/2472348/206518382-4608a724-1653-4ac2-9120-e782edd8de16.mp4

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by joshheald** [comment]
@toupper No hurry, as there's no benefit to getting this in tomorrow's freeze. 

@jostnes @lmischner Optional review again: this adds the new images for the built in screens but otherwise makes no change to functionality. It might be easier to review with the next PR if you're busy.

**Comment by toupper** [comment]
Great work @joshheald, the process looks more custom for the built-in card reader. The code looks good to me, however, I found a few issues when testing the flow design in landscape mode:

**Misplaced button**



**Preparing reader screen shows randomly different configurations. Rotate the device multiple times to achieve this:**

**Comment by joshheald** [comment]
Thanks for the review @toupper. All resolved in 6c439ee – the previous implementation (before #8115) hid the image at all times in landscape, and I've moved back to that. 

Showing the images in landscape was unintentional, and the interplay of show/hide images with the progress indicator caused the issues you found.

> [...] the process looks more custom for the built-in card reader. The code looks good to me, however, I found a few issues when testing the flow design in landscape mode:
> 
> **Misplaced button**
> 
> **Preparing reader screen shows randomly different configurations. Rotate the device multiple times to achieve this:**

Here's a video with the updates:

https://user-images.githubusercontent.com/2472348/211006134-10154136-430b-4e8d-838e-ca86fe77eaa7.mp4

**Comment by jostnes** [comment]
I was testing this PR to double check [this issue](https://github.com/woocommerce/woocommerce-ios/issues/8274) and found an odd UI issue, the size of the buttons on the "payment successful" screen when in landscape mode change as you go from portrait to landscape:

https://user-images.githubusercontent.com/17252150/211255155-8c2aca82-b5ed-45ee-bf0c-f8586343e4d7.MP4

**Comment by joshheald** [comment]
> I was testing this PR to double check [this issue](https://github.com/woocommerce/woocommerce-ios/issues/8274) and found an odd UI issue, the size of the buttons on the "payment successful" screen when in landscape mode change as you go from portrait to landscape:

Thanks @jostnes ... This is down to us changing the axis of the stack view so they can be side-by-side in landscape, then stacked in portrait. `UIStackView` is responsible for the size when it's rotated. Fortunately I was able to find a quick fix for this using the `distribution` property in 41d1e1f


https://user-images.githubusercontent.com/2472348/211289721-b0984cc9-168d-45ed-beb6-2b84daf8cddc.mp4

**Comment by toupper** [comment]
@joshheald LGTM now, thanks for the changes.
As we talked, I saw that the loading indicator of the last alert (Getting ready to collect payment) overlaps other elements when switching the orientation exactly at that point. Unfortunately, it happened very fast so I couldn't create a screenshot, and now that I want to create a video I cannot rotate fast enough :sweat_smile: If I start the process on landscape mode it does not happen, as the loading indicator is hidden.
As this is a minor issue, feel free to prioritize it as you see appropriate.

**Review by toupper — APPROVED** [review]

**Pull request merged**
