### PR TITLE
Updated Automattic-Tracks-iOS pod from 0.5.1 to 0.6.0, that includes an update of Sodium that support Xcode 12

### PR DESCRIPTION
**Pull request by pmusolino**
## Description
As part of our Xcode 12 migration, we should update our Pod libraries, because some of them show warnings about the `IPHONEOS_DEPLOYMENT_TARGET` set to iOS 8.0, that is no more supported.
In this PR I updated the Automattic-Tracks-iOS pod from v.0.5.1 to v.0.6.0 which includes an update of Sodium that now supports Xcode 12. [More info here](https://github.com/Automattic/Automattic-Tracks-iOS/pull/148).

## Testing
- CI
- Make sure that this warning disappear:
Schermata 2020-10-16 alle 12 22 19

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by loremattei** [comment]
Hey there! I'm moving this to 5.4 as 5.3 has been cut. If you still want this to make it to 5.3, please feel free to ping me.

**Comment by shiki** [comment]
Checking this now. 🙂

**Comment by shiki** [comment]
We're going to have to merge this into #3015 to avoid the Catch 22. 😁

**Comment by shiki** [comment]
As discussed, this will turn off breadcrumb tracking in Sentry. We can use the encrypted logs as a replacement.

**Comment by pmusolino** [comment]
Discussion [here](https://a8c.slack.com/archives/C6H8C3G23/p1603121364492000).

**Comment by pmusolino** [comment]
I'm going to merge this PR inside this other one https://github.com/woocommerce/woocommerce-ios/pull/3015, it will be easily testable and we can handle easily also the changes.

**Pull request merged**
