### PR TITLE
Update Ghost style beat end color to an opaque color

### LINKED ISSUE #1541: Order List "Ghost" boxes showing default text from XIB while pulsing
**Describe the bug**
When the ghost boxes are pulsing during an initial data load the text from the XIB is visible in the box rather than them being blank and with an offset background color.

**To Reproduce**
1. Log out of the app.
2. Log into the app.
3. Select a site with orders on the server to download.
4. Switch to the orders tab. Ghost with text in the fields is visible briefly.

**Screenshots**
I forced the controller to show the ghost cells every time I refreshed and I snagged a screenshot:

Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-28 at 15 00 52

**Expected behavior**
The ghost labels should be empty or at least the foreground match the background color. Not sure what broke and when so I don't know the right solution to fix it.

**Mobile Environment**
Please include:
- Device: iPhone 11 Pro Max Simulator
- iOS version: 11.2?
- WooCommerce iOS version: develop (3.2)

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #1541 

## Cause of the issue

As in the screenshot in #1541, the Ghost cells show the placeholder text from the xib after we updated the colors with Dark Mode support. Before the Dark Mode support, the ghost layer used to cover any placeholder text with a color animation between two opaque colors specified in https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Extensions/Ghost+Woo.swift#L8-L9. Since the animation end color became transparent with the Dark Mode color update (`quaternaryLabel` has 0.18 alpha in both Light and Dark modes), the placeholder text was shown through the transparent ghost layer.

## Changes

- Updated the beat animation end color to an opaque color, I picked `.neutral(.shade10)` but lemme know if there's a better color!

## Testing

- Log out of the app
- Log into the app
- Select a site with orders on the server to download
- Switch to the orders tab --> there should be no text in the ghost cells

## Example screenshots

before Dark Mode support | `develop` | PR branch - Light Mode | PR branch - Dark Mode
-- | -- | -- | --
Simulator Screen Shot - iPhone SE - 2019-12-03 at 10 25 07 | Simulator Screen Shot - iPhone SE - 2019-12-03 at 10 12 11 | Simulator Screen Shot - iPhone SE - 2019-12-04 at 16 01 25 | Simulator Screen Shot - iPhone SE - 2019-12-04 at 16 01 46

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
We're freezing `3.2` today, so I'm moving this PR forward to `3.3`. If you'd it them released as part of `3.3`, please adjust the target from `develop` to `release/3.3`, and let me know once it has been merged – I'll be happy to ship a new release candidate!

**Comment by jaclync** [comment]
@kyleaparker this is how it looks with shade5:

dark mode | light mode
-- | --
Simulator Screen Shot - iPhone SE - 2019-12-04 at 09 10 24 | Simulator Screen Shot - iPhone SE - 2019-12-04 at 09 10 47

The color in dark mode seems a bit dim. If we want to create a custom color (using shade 10 in Light mode and shade 5 in Dark mode), do you have a semantic name for it for future design usage?

**Comment by jaclync** [comment]
@kyleaparker I made a new semantic color `ghostCellAnimationEndColor` with gray-5 in Light mode and gray-10 in Dark mode, updated the screenshots in the PR description!

**Comment by jaclync** [comment]
@jkmassel it'd be great if this hot fix for the ghost cell after the Dark Mode support could be included in the next beta!

**Pull request merged**
