### PR TITLE
Store onboarding > custom domains task: navigate to custom domains

### LINKED ISSUE #8909: Task: customize your domains
We can navigate to custom domains using `DomainSettingsCoordinator` with a new `Source` enum like `customDomains`.

Entry point: `StoreOnboardingCoordinator.start(task:)`

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #8909 

## Description

This PR handled the navigation when the user taps on the custom domains onboarding task. To show custom domains, `StoreOnboardingCoordinator` creates and starts `DomainSettingsCoordinator` with a new source with analytics event property `onboarding` (ref pe5sF9-15a-p2#comment-1694). `Site` is a necessary parameter, from looking around `ServiceLocator.stores.sessionManager.defaultSite` seems like how we get the latest site.

## Testing instructions

- Login if needed
- Go to the My store tab if needed
- Tap on `Customize your domain` row --> the domain settings modal should be shown
- Dismiss the modal
- Tap on any other row to see the fullscreen onboarding view
- Tap on `Customize your domain` row --> the domain settings modal should be shown

## Screenshots

https://user-images.githubusercontent.com/1945542/221117672-8b7aa0ba-f6a5-499a-a06d-4882dc8c9393.mov

portrait | landscape
-- | --
Simulator Screen Shot - iPhone 14 - 2023-03-01 at 09 34 16 | Simulator Screen Shot - iPhone 14 - 2023-03-01 at 09 34 29
Simulator Screen Shot - iPhone 14 - 2023-03-01 at 09 37 11 | Simulator Screen Shot - iPhone 14 - 2023-03-01 at 09 37 13

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by itsmeichigo — COMMENTED** [review]
👋  I'm not sure if I missed this in the previous PRs of domains, but I noticed just now that there is no Cancel button on the modal for domains. This makes it impossible to dismiss the view in landscape mode:

Simulator Screen Shot - iPhone 14 Pro - 2023-02-27 at 11 08 03

Maybe we should add that button on the navigation bar?

**Comment by jaclync** [comment]
> 👋 I'm not sure if I missed this in the previous PRs of domains, but I noticed just now that there is no Cancel button on the modal for domains. This makes it impossible to dismiss the view in landscape mode:
> Maybe we should add that button on the navigation bar?

Great catch @itsmeichigo, I didn't know that the drag-to-dismiss gesture isn't available in landscape mode. I added a cancel CTA to the navigation bar in https://github.com/woocommerce/woocommerce-ios/pull/8967/commits/2e3ee75cc2e5b7d1110b12c09be71b0f8106b1b2 with new screenshots in the PR description. Ready for another look!

**Review by itsmeichigo — APPROVED** [review]
Thanks for the update! ✅ 

I have some suggestions for future improvement: with the onboarding tasks here, I can access the domain flow when logged in without Jetpack (site credentials + application password). The domain screen then shows an empty content with the CTA:



Should we hide the task for users authenticated without WPCom, or show a message on the domain screen when the endpoint is unreachable?

**Comment by jaclync** [comment]
> Should we hide the task for users authenticated without WPCom, or show a message on the domain screen when the endpoint is unreachable?

Yes, this is for a separate task to hide the whole onboarding under a few conditions including WPCOM sites: https://github.com/woocommerce/woocommerce-ios/issues/8893

**Pull request merged**
