### PR TITLE
Update README.md with more detailed information

### LINKED ISSUE #758: Update README.md with more detailed information about tooling, dependencies, linting, and setting up
Title has it. In short, compare the [`README.md` for WPiOS](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/README.md) to what [we currently have](https://github.com/woocommerce/woocommerce-ios/blob/develop/README.md). 😄

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #758 

## Changes

* Added more details about setup and linting
* Added Security, Getting Help, Resources, and License sections

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by jaclync** [comment]
> Do we need to add any mention to credentials?

Do we have something similar to [WPiOS](https://developer.wordpress.com/) for WCiOS? I don't think the WPiOS public mobile secrets work with WCiOS. Have we got any contribution requests before?

**Comment by loremattei** [comment]
Hey! I'm moving this to 2.4 since 2.3 has been cut. If you want it to make it to 2.3, please feel free to move it back, target the release branch and ping the me to build a new beta.

**Comment by mindgraffiti** [comment]
@jaclync you might include how to generate their `dotcom_app_id` and `dotcom_secret`. Either copy and paste the steps found under "In order to login to WordPress.com using the app:" or the section under "Setup Credentials". iirc, when the user builds the app from scratch, an empty secrets file is generated (but located in the wrong place).

**Comment by mindgraffiti** [comment]
@astralbodies should Woo mobile copy these sections from [WPiOS ReadMe](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/README.md)?
- Contributing
- Security
- Getting in Touch
- License

**Comment by astralbodies** [comment]
- Security
- License
- Need help? could point at stuff like this https://github.com/woocommerce/woocommerce-android/#need-help

For now we can leave out contributing since the model is a bit different with Woo than WP. @jaclync can you also coordinate comparable changes in the Android repo so we're somewhat consistent?

**Comment by jaclync** [comment]
Just updated the README with Security, Getting Help, Resources, and License sections. If this looks good, I'll create a ticket on Android to just add the Security and Resources sections

**Pull request merged**
