### PR TITLE
Date pickers now have the look introduced in iOS 14

### PR DESCRIPTION
**Pull request by pmusolino**
Part of #3040. 

## Description
This is an enhancement to #3042 originally started by @jaclync. I made some changes for showing correctly the new inline date picker in Product Price and in Add Tracking (under Order detail).
Now when a user is running iOS 14+ we will show the new inline date picker for choosing a date.

## How I solved the original issue
It has always been impossible to self-define the correct height of a UIDatePicker, because of a limitation on the Apple side. What we should do in this case, is to set a fixed height based on the style that we are showing.
Before, we always set the fixed height to be 216px, but the new date picker needs 345px. So I implemented a static method inside the `DatePickerTableViewCell` for getting the default cell height based on the iOS on which we are running.
I also updated the xib of the cell, since there was a little bug in the constraints that don't allow us to show the bottom border of the cell (it was hidden under the date picker).
In the end, I removed the `estimatedHeightRowAt` delegate method in `ManualTrackingViewController` because isn't needed.

#### Case 1
- Launch the app in iOS 14 simulator/device from Xcode 12
- Go to the products tab
- Tap on a product whose price is editable
- Tap on the price row
- Turn on "Schedule sale" toggle
- Tap on either "From" or "To" row --> the date picker should have the new appearance introduced in iOS 14

#### Case 2
- Launch the app in iOS 14 simulator/device from Xcode 12 and make sure to have the Shipping Tracking extension on your website
- Go to the Orders tab
- Tap an Order detail
- Press "Add tracking"
- Press "Date shipped" --> the date picker should have the new appearance introduced in iOS 14

## Screenshots
| Produce Price pickers             |  Add Tracking picker |
:-------------------------:|:-------------------------:
Simulator Screen Shot - iPhone 11 Pro - 2020-10-22 at 13 34 48 | Simulator Screen Shot - iPhone 11 Pro - 2020-10-22 at 13 35 40

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Garance91540 — APPROVED** [review]
cool stuff! 👏

**Comment by jaclync** [comment]
The code looks great! I'm not sure why, the date picker is still truncated in iOS 14.0 simulator and device 🤔 I checked in view debugger that the date picker cell height is 345px (including a 1px bottom border). I also tried adjusting the font size in accessibility but it didn't fix it. Which device type/iOS version did you test on?

iOS 14.0 iPhone 11 sim | iOS 14.0 iPhone XR device
-- | --
Simulator Screen Shot - iPhone 11 - 2020-10-23 at 10 00 55 | IMG_6345

**Comment by pmusolino** [comment]
Thank you @jaclync for testing this!

I did some tests with different devices with different languages and everything seems ok on my side. The only difference that I noticed is that you are using iOS 14.0. What happens on your side if you use iOS 14.1? 🤔 

|  iPhone XR iOS 14.1 | iPhone XR iOS 14.1 (Chinese simplified)    |  iPhone 11 Pro iOS 14.1 | iPhone 8 Pro iOS 12.2 | iPhone 5s iOS 12.2 |
:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:
iphone xr ios 14 1 | iphone xr ios 14 1 chinese | iphone 11 pro | iphone 8 | iphone 5s 12 2

**Comment by jaclync** [comment]
> The only difference that I noticed is that you are using iOS 14.0. What happens on your side if you use iOS 14.1? 🤔

Ah yea, it's iOS 14.1 / 14.0 that makes the difference! It seems like the spacing between calendar rows is slightly larger in iOS 14.0 and thus there's no space for the text on top. This is quite tricky, since most of our users are still on iOS 14.0 (based on App Store Analytics) but people are gradually upgrading to iOS 14.1 😓 I wish the date picker worked with Auto Layout in `UITableViewCell`, or they maintain the same height between iOS versions.

We can probably set different height for iOS 14.0 / 14.1 (but there's a chance we might have to do this for each iOS 14 version), or keep the wheel style for now?

iOS 14.1 | iOS 14.0
-- | --
Simulator Screen Shot - iPhone 11 - 2020-10-27 at 14 07 00 | Simulator Screen Shot - iPhone 11 - 2020-10-27 at 14 09 50

**Comment by pmusolino** [comment]
Thank you @jaclync for confirming it. 
Then, I believe that increasing the size to 380px would solve all problems on both iOS 14.0 and iOS 14.1. 

The appearance is still good on iOS 14.1, and on iOS 14.0 it would be OK, without any issue. Can you confirm that it runs properly on your device, setting the height to 380px?

**Comment by jaclync** [comment]
380px works for both iOS 14.0 and 14.1 (a bit tall but looks good), let's go for this! I also tested with the largest font size and the calendar just stays the same size 👍 Let's hope they don't increase the content size height in the later iOS versions 😅 

iOS 14.0 | iOS 14.1
-- | --
Simulator Screen Shot - iPhone 11 - 2020-10-29 at 11 57 33 | Simulator Screen Shot - iPhone 11 - 2020-10-29 at 11 57 34

**Comment by pmusolino** [comment]
Thank you for testing it @jaclync! 💯 

> Let's hope they don't increase the content size height in the later iOS versions

I really hope they didn't change, but as far I see yesterday, there are other people in GitHub that are using our same solution because it seems that the date picker is not working properly with Autolayout. 
Maybe in the future, we can try to implement this view using SwiftUI, and manage the constraints using it. Maybe in SwiftUI the issue is not existing at all. 🤷‍♂️

**Pull request merged**
