### PR TITLE
Add simple screenshots

### PR DESCRIPTION
**Pull request by jkmassel**
**To Test**
1) Download the [screenshots.zip](https://github.com/woocommerce/woocommerce-ios/files/3667580/screenshots.zip) archive, and unzip it in the `fastlane` directory. The directory structure is required to generate promo screenshots (this may be a good thing to change later).
2) Run `bundle install --with screenshots && bundle exec fastlane create_promo_screenshots`, and if prompted, confirm that you'd like to overwrite existing promo screenshots.
3) Ensure that the created screenshots look ok.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by loremattei** [comment]
@jkmassel I get this error as soon as I try to start the process:
`improper image header `./fastlane/appstoreres/assets/simple/screenshot-5-iphone-8.png' @ error/png.c/ReadPNGImage/4101`.

I verified that the file is there and double checked that `bundle install` works without errors.
Do you happen to have any flash idea before I dig into it?

**Comment by jkmassel** [comment]
This is using Git LFS for storage – I wonder if you don't have it initialized? I'll try to investigate with a CircleCI machine to see if that's related – thanks!

**Comment by loremattei** [comment]
@jkmassel you were right, I hadn't git LFS installed. 
I installed it and the screenshots generation worked perfectly.

I have two small suggestions:
1. Should add a check for Git LFS being installed in the lane? (I did a quick search and it seems that the suggested way is to run `git config --get-regexp filter.lfs` and check that the output length is > 0).

2. Could we find a stopgap solution for the directory structure?  Even something super simple like generating it when the lane is started.

**Comment by jkmassel** [comment]
> Should add a check for Git LFS being installed in the lane? (I did a quick search and it seems that the suggested way is to run git config --get-regexp filter.lfs and check that the output length is > 0).

Totally – I might add this to the release toolkit though, since it'd be a nice check to have in all the projects (using LFS for screenshot assets keeps the app repos far smaller, so I'd like to use it for all the things). 

> Could we find a stopgap solution for the directory structure? Even something super simple like generating it when the lane is started.

I was thinking about this – we could definitely create the directory structure in the lane, but to keep things nice and clean (and also have first-class support for this workflow), I could modify [this line](https://github.com/wordpress-mobile/release-toolkit/blob/c144977476155ff00a5a2c03745c0482619c8f1d/lib/fastlane/plugin/wpmreleasetoolkit/helper/promo_screenshots_helper.rb#L76) to avoid needing these directories all. I _think_ that'll be a nicer way to go, and if the screenshot configuration requires an error it should throw out a nice error message saying it can't find the file, so I think the DX is still ok there.

LMK if you disagree with any of ^^? :)

**Comment by loremattei** [comment]
Yep! Both sounds good to me!
Go for them!

**Comment by jkmassel** [comment]
Howdy @loremattei – this is ready for another review!

Updated testing steps:

1) Run `bundle install --with screenshots && bundle exec fastlane create_promo_screenshots`, and if prompted, confirm that you'd like to overwrite existing promo screenshots.
2) Ensure that the created screenshots look ok.

You no longer need to put a `screenshots` directory in. Also, if you test with `git-lfs` turned off, it'll give you a nice warning that tells you how to get that sorted out (but you could also read it in the code).

**Pull request merged**
