### PR TITLE
Updated KeychainAccess pod from 3.2.0 to 4.2.1, that includes Xcode 12 support

### PR DESCRIPTION
**Pull request by pmusolino**
## Description
As part of our Xcode 12 migration, we should update our Pod libraries, because some of them show warnings about the `IPHONEOS_DEPLOYMENT_TARGET` set to iOS 8.0, that is no more supported.
In this PR I updated the KeychainAccess pod from v.3.2.0 to v.4.2.1 that now supports Xcode 12. You can check all the improvements that happened during every bump release [here](https://github.com/kishikawakatsumi/KeychainAccess/releases).

## Testing
- Check that the login process continue to work like before.
- Make sure that this warning disappear:
Schermata 2020-10-16 alle 11 35 42

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by loremattei** [comment]
Hey there! I'm moving this to 5.4 as 5.3 has been cut. If you still want this to make it to 5.3, please feel free to ping me.

**Comment by pmusolino** [comment]
@woocommerce/ios-developers ready for review after having merged the PR for upgrading the CI to Xcode 12 😉

**Review by shiki — COMMENTED** [review]
@pmusolino Sorry for the late review. 

It looks like the warning is still happening in this case. 😞 



There is an open issue: https://github.com/kishikawakatsumi/KeychainAccess/issues/508.

**Comment by pmusolino** [comment]
@shiki I was sure that while I was testing this pod upgrade the warning disappear. I re-tested it and probably I missed it :/ I'm sorry, my bad. I'm closing this PR for the moment.

**Pull request closed without merging**
