### PR TITLE
[Product Bundles] Show product bundle stock status or quantity in product list

### LINKED ISSUE #8954: [Product Bundles] Display product bundle information in the product detail screen
Display product bundle information on the product detail screen. We can use wp-admin design as a reference

Image

### PR DESCRIPTION
**Pull request by rachelmcr**
Closes: #8954
⚠️ Depends on #9132 

## Description

This updates the stock status and stock quantity displayed for product bundles in product lists, when the feature flag is enabled:

* When the product bundle is in stock and the stock quantity is managed, it displays the product **bundle** stock quantity instead of the product stock quantity.
* When the product bundle does not manage the stock quantity, it displays the product **bundle** stock status instead of the product stock status.
* For any other product type (not product bundles), or when the feature flag is disabled, the product stock quantity or status will be displayed as before.

This is notable in two scenarios:

* If the Product > Inventory settings have e.g. an "In stock" status but one of the bundled products is out of stock, the product list will show "Insufficient stock" as the stock status.
* If the Product > Inventory settings have e.g. 5 in stock but one of the bundled products only has 1 in stock, the product list will show "1 in stock" as the stock quantity.

### Prerequisites

1. Install and activate the [Product Bundles extension](https://woocommerce.com/products/product-bundles/) on your store.
2. Create a product with the Product Bundle type.
   *  In the "Bundled products" settings, add a product that is out of stock (with its "Manage stock?" setting unchecked).
   *  In the "Inventory" settings, set the product bundle to in stock (with its "Manage stock?" setting unchecked).
3. Create another product with the Product Bundle type.
   * In the "Bundled products" settings, add a product that has a stock quantity of 1.
   *  In the "Inventory" settings, set the product bundle stock quantity to more than 1.
4. In the wp-admin product list, confirm you see "Insufficient stock" for the first product bundle and "In stock (1)" for the second product bundle.

Example:

Screenshot 2023-03-14 at 6 54 03 PM

### To test

1. Build and run the app.
2. Go to the Products tab.
3. Confirm your first product bundle shows "Insufficient stock" in the product list.
4. Confirm your second product bundle shows "1 in stock" in the product list.
5. Go to the Orders tab and create a new order.
6. Select "Add product" and confirm the correct stock status/quantity also appears there (same as above).

## Screenshots

/|Before|After
-|-|-
Products tab|Simulator Screen Shot - iPhone 14 Pro - 2023-03-14 at 19 00 07|Simulator Screen Shot - iPhone 14 Pro - 2023-03-14 at 18 30 53
Product selector (e.g. order creation)|Simulator Screen Shot - iPhone 14 Pro - 2023-03-14 at 19 00 13|Simulator Screen Shot - iPhone 14 Pro - 2023-03-14 at 18 31 02

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ThomazFB** [comment]
Hey @rachelmcr! Thanks for the detailed instructions around the Bundle configuration 😄. I tested the scenarios you described, and the `Insufficient Stock` label worked just fine, but maybe I'm doing something wrong with the Product setup here for the test.

Here's how I configured the Store products and how they're showing up in `wp-admin`.
Screenshot 2023-03-16 at 00 09 50

And this is how they get displayed in the app. The `insufficient stock` label appears as expected for the `Insufficient Stock Bundle Product`,  but the `Sufficient Stock Bundle Product` doesn't show as we see in `wp-admin` with the expected `1 in stock` label:


Here's how the `Sufficient Stock Bundle Product` is configured internally:
Screenshot 2023-03-16 at 00 12 51
Screenshot 2023-03-16 at 00 13 40

Also, when testing the Product Selector, I noticed that the Bundles are not showing up. Did I miss something here? 😓

**Comment by rachelmcr** [comment]
Thanks for the careful testing @ThomazFB!

> the `Sufficient Stock Bundle Product` doesn't show as we see in `wp-admin` with the expected `1 in stock` label

Good find! It turns out that when we're dealing with product bundles, we need to ignore the product's `manageStock` property and always display the bundle stock quantity when it's available. I've fixed that in 033688e. Let me know if that fixes it for you!

Note: We're making enough tweaks for product bundles now that it might be worth refactoring that `createStockText()` method. We could create the text with separate methods for core products and for custom product types like product bundles. But I'll leave it as-is for now, as long as it's working, and revisit that later if needed.

> Also, when testing the Product Selector, I noticed that the Bundles are not showing up. Did I miss something here?

Ah, the product selector for order creation checks if a product is `purchasable`. If you add prices for your product bundles, that should be enough for them to be `purchasable` so they show up in that list.

**Comment by rachelmcr** [comment]
Oops, sorry, I just merged #9158 into this branch (I forgot it was depending on this one). You can ignore the changes from that; they were already reviewed separately.

**Review by ThomazFB — APPROVED** [review]
No problem @rachelmcr! I was already finishing the review! Your fix adjusted the issue, and thanks for providing the details about my test scenario! Looking good! :shipit:

**Pull request merged**
