### PR TITLE
Update error logging in `OrderDetailsDataSource` for cellForRowAtIndexPath`

### PR DESCRIPTION
**Pull request by hafizrahman**
To help with https://github.com/woocommerce/woocommerce-ios/issues/14236

Internal - peaMlT-Xu-p2

### Description

we intentionally added error logging mentioned in that Sentry issue in https://github.com/woocommerce/woocommerce-ios/pull/14018 (Related CUW: peaMlT-QW-p2)

However, the logged properties did not help with debugging because in the PR where `"row": indexPath.section`, it should be `"row": indexPath.row` instead.

This PR added the fix for that.

Additionally I'm adding more properties to help with debugging as well.

### Steps to reproduce
As with before, we're pretty much unable to replicate this crash, so instead verify the new logging and ensure the code looks fine.

### Testing information
Please smoke test the Order Detail section to make sure everything works like before.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by selanthiraiyan — COMMENTED** [review]
Thanks for addressing this issue, Hafiz!

The code changes LGTM, and I don't see any issues in the Order Detail section. 🎉 

---

> we intentionally added error logging mentioned in that Sentry issue in https://github.com/woocommerce/woocommerce-ios/pull/14018 (Related CUW: peaMlT-QW-p2)

Can we close the GH issue https://github.com/woocommerce/woocommerce-ios/issues/14236 and relevant Sentry issue? If we are tracking the order details problem in a different CUW issue we can close the newly opened CUW post as well. What do you think? 

---

I don't see the `Reviewer (or Author, in the case of optional code reviews):` section with the checkboxes in the PR description. Maybe it was accidentally removed. Can you kindly fix that?

**Comment by hafizrahman** [comment]
> Can we close the GH issue https://github.com/woocommerce/woocommerce-ios/issues/14236 and relevant Sentry issue? If we are tracking the order details problem in a different CUW issue we can close the newly opened CUW post as well. What do you think?

This makes sense, let's use the original (older) CUW as it has the main issue and existing conversation.

#14236 and the Sentry issue can be closed by this PR, I suppose?

I'll write some notes to connect things together.

> I don't see the Reviewer (or Author, in the case of optional code reviews): section with the checkboxes in the PR description. Maybe it was accidentally removed. Can you kindly fix that?

Added

**Review by selanthiraiyan — APPROVED** [review]
Thanks for adding comments to the CUW post. :shipit:

**Pull request merged**
