### PR TITLE
Merge Release/4.4 back into develop

### PR DESCRIPTION
**Pull request by loremattei**
Merge Release/4.4 back into develop

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by oguzkocer** [comment]
@jaclync @shiki @pmusolino Could you take a look at the failing CI build? I assume this is related to #2366, that's why I am pinging you 3, I hope that's correct 🤞 

```
❌  /Users/distiller/project/Yosemite/YosemiteTests/Storage/StorageManagerConcurrencyTests.swift:66:61: missing argument for parameter 'crashLogger' in call
        storageManager = CoreDataManager(name: "WooCommerce")
 ```

**Comment by pmusolino** [comment]
@oguzkocer on it. Can I open a new PR on `release/4.4` branch?

**Comment by oguzkocer** [comment]
> @oguzkocer on it. Can I open a new PR on release/4.4 branch?

Thank you @pmusolino! yes please, but maybe get the PR approved but leave the merge to @loremattei just in case, since he is the release manager.

@loremattei I assume this is fine to do because it'll be fixing the tests and won't necessarily need us to publish a new beta. Also, if we don't fix it in the release branch, we'll have the issue in the later PRs as well. If you disagree, we can just change the base branch for the PR, so we should be safe regardless 🤞

**Comment by pmusolino** [comment]
Here it is: https://github.com/woocommerce/woocommerce-ios/pull/2380

**Comment by loremattei** [comment]
Thanks @oguzkocer! It makes totally sense!

**Pull request merged**
