### PR TITLE
[Auth] Remove the `.showGoogle` segue and navigate programmatically

### PR DESCRIPTION
**Pull request by mindgraffiti**
Fixes # n/a
Ref. #2003 

This PR removes the segue that sends a user to the "Continue with Google" screen. It now navigates the user programmatically.

See also: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/219

## To test:
1. Check out this branch
2. `rake dependencies`
3. Build and run
4. Navigate through each of these flows:

#### Flow 1, Login via Google
1. Select the Log in with Jetpack button
2. Select Log in with Google button text
3. Select Continue on the alert message
4. Enter a valid email address for an existing WordPress.com account
5. Follow the rest of the Google login flow (password and / or 2fa)
6. Verify you are navigated to the "Continue" screen

### Do not merge until:
1. The Authenticator PR has been merged: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/219
2. A new Authenticator release has been created 
3. The release is published on Cocoapods trunk
4. This PR points to the new release 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mindgraffiti** [comment]
Hi @pmusolino 👋 

1. Yes that is a known bug. I'm waiting for the fix to be approved, so I can merge the fix into Authenticator's master and develop branches. 
 
> After making the login with google, I can't pair the account with my existing WordPress account. 

2. I believe that's expected behavior and a limitation of Google's Authentication feature. The same problem happens if you use Google Sign in on other platforms as well.

**Comment by mindgraffiti** [comment]
Latest changes in Authenticator, added to this PR:
- Authenticator's podfile updated toWordPressKit 1.17.0-beta.1
- Restores NUX buttons (pink login / signup flow buttons) to their original dimensions
- Fixes some localized strings

**Comment by pmusolino** [comment]
Thank you so much @mindgraffiti for clarifying these points. Unfortunately, I'm not able to connect the Google account to the WordPress account, and therefore I can't test the whole process. 😞 
@shiki are you able to test it?

**Comment by mindgraffiti** [comment]
Tlhank you for the reviews @pmusolino and @shiki !

**Pull request merged**
