### PR TITLE
Update Ruby Gems for the latest release-toolkit version

### PR DESCRIPTION
**Pull request by irfano**
## Description

This only updates gems. The purpose is using the latest release-toolkit version.

## Testing information

It seems safe to me not to test anything, but let me know if I missed anything, @iangmaia.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by iangmaia — APPROVED** [review]
Thank you! 👍

**Comment by hafizrahman** [comment]
After the PR was approved, I saw a build error that says `Podfile.lock was changed by bundle exec pod install. Please run bundle exec pod install locally with a clean cache and commit the result."

I did as it said and pushed in https://github.com/woocommerce/woocommerce-ios/pull/14487/commits/3ada1876f710c2a55b54afbfb434ec83f94db848

**Comment by hafizrahman** [comment]
This is good to go but I'm setting "do not merge" for now. We want to put it into release 21.2 so we can test screenshots generation in release. I'm not sure what's the next steps are here as we're just in code freeze @selanthiraiyan

**Comment by selanthiraiyan** [comment]
Thanks, @irfano for working on this!

> This is good to go but I'm setting "do not merge" for now. We want to put it into release 21.2 so we can test screenshots generation in release. I'm not sure what's the next steps are here as we're just in code freeze @selanthiraiyan

@hafizrahman This PR and the next one here https://github.com/woocommerce/woocommerce-ios/pull/14492 look good to me to merge as beta fixes into the release branch. Will that be all, or do we need to make further changes?

**Comment by hafizrahman** [comment]
Forgot to add the context for the merge: @selanthiraiyan and I discussed in Slack about what to do with this and #14492 and the decision was to merge both this and the other PR to 21.2.

**Pull request merged**
