### PR TITLE
[Mobile Payments] Users can be reminded later for feature announcement cards

### LINKED ISSUE #7252: [Mobile Payments] Remind me later functionality on Card Reader Upsell
Dismiss button will be added to Card Reader Upsell in https://github.com/woocommerce/woocommerce-ios/issues/7251. The goal of this ticket is to show a blocking dialog, after the user taps on the dismiss button - see designs.

Designs: https://cloudup.com/cpMyfiFZvKI

Tasks
- [x] Show dialog with "Dismiss" and "Remind Later" buttons.
- [x] Move `woocommerceios_feature_card_dismissed` tracking event from the `X` to the `Dismiss` button on the dialog + start tracking `remind_later=false` property with this event.
- [x] Track taps on Remind Later  -> `woocommerceios_feature_card_dismissed` with `remind_later=true` + `source` and `campaign_name` properties (more info about the properties [here](https://github.com/woocommerce/woocommerce-ios/issues/7230))

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #7252 

⛔ Do not merge until b62353706c0cb0c8f93254e7c402ebbecd983f30 is reverted: This is just to make testing easier.

### Description

Feature Announcement Cards can be dismissed by the user. Some users may wish to temporarily get a card out of the way, but be interested in acting on it in future.

This adds a choice for the user when dismissing a card: “Don’t show again”, or “Remind me later”.

A user who chooses “Remind me later” will be shown the card again after 14 days.

### Testing instructions

To help with testing, I recommend changing [this line in AppSettingsStore](https://github.com/woocommerce/woocommerce-ios/blob/54069d4ff84ae1e590e9a4598408dbd19b2c7f79/Yosemite/Yosemite/Stores/AppSettingsStore.swift#L743) to the following, which will change the remindAfter time from 2 weeks to 20 seconds:
```
let remindAfter = remindLater ? Date().addingTimeInterval(20) : nil  // 20 seconds for testing!
```

Using a US or Canada store:

1. Navigate to Order Details for an unpaid order, then tap Collect Payment. Or: make a new Simple Payment, and go to the Payment Method screen
2. Observe that the Upsell Card Reader banner is shown, with a x button to dismiss.
3. Tap the x button and then the `Remind me later` option – observe that the card is dismissed
4. Go to another order within the remind time, and observe that the banner doesn't show there.
5. Close the order an go to any other order after the remind time elapses, observe that the card is shown.

Repeat the above test using `Don't show again`, and observe that the card is not shown even after the remind time elapses.

To reset and re-test, either delete and reinstall the app, or use the testing workaround from b62353706c0cb0c8f93254e7c402ebbecd983f30 to clear the stored dismissal. This is not part of the feature, and will be removed before it is merged.

1. Tap the `Card` option on the Payment Method screen to reset the stored preference.
2. Close the order, and open it or any other order again
3. Observe that the banner is shown

### Screenshots

https://user-images.githubusercontent.com/2472348/178279172-ce776c45-612e-4516-b4cd-152483f6cda6.mp4

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pachlava** [comment]
As I started taking a look into the PR, I noticed one thing: if the merchant taps the `[x]` button accidentally, there's no way to cancel the dismissal, except for restarting the app. Would a `Cancel` button help there, does it bring any value, wdyt? Thanks!

**Comment by pachlava** [comment]
@toupper 👋 

Since you're now working on this, just wanted to let you know about [this comment](https://github.com/woocommerce/woocommerce-ios/pull/7271#issuecomment-1183353839), which you might have not seen, because I posted it earlier than you've self-assigned the PR.

**Comment by toupper** [comment]
HI @pachlava! Thanks for your feedback here. 
I created an [issue](https://github.com/woocommerce/woocommerce-ios/issues/7305) and assign it to this project so we can enhance this feature with your suggestion in the next iteration 🚀

**Review by toupper — APPROVED** [review]

**Review by toupper — APPROVED** [review]

**Comment by pachlava** [comment]
Thanks, @toupper! It looks like @AnirudhBhat will work on a similar part for Android, so maybe it makes sense to have it aligned design-wise 👋 

UPD: sorry for not giving enough context initially. I meant adding the possibility to cancel the banner dismissal ([the issue](https://github.com/woocommerce/woocommerce-ios/issues/7305))

**Pull request merged**
