### PR TITLE
[Mobile Payments] Use reference instead of name when retrieving IPP Plugins

### PR DESCRIPTION
**Pull request by toupper**
## Description

With this PR we change the way we retrieve the Card Present Payments Plugins when performing the onboarding checks. Before we checked the plugin name, but after a problem we had when they changed the in WCPay beta, we decided that it's safer to check the plugin reference, e.g., `"woocommerce-payments/woocommerce-payments",` which is less likely to change. WIth this we also are consistent with Android, which uses the same approach.

EDIT: As the folder can also change, we only evaluate now the filename without extension: pdfdoF-3pF-p2#comment-4619

Slack Convo: p1689676894933749-slack-C025A8VV728 

## Known Caveats
This solution brings some suboptimal parts with it. Before we could directly query for the name to the database, but now, as we have to remove the file extension, we have to bring all plugins to memory and then filter them. Feel free to add your opinion about it.

## Testing instructions

Check all possible combinations for IPP plugins, it should behave as before:

- WCPay and Stripe both installed and active. The IPP Onboarding should prompt you to select one of them.

- WCPay Plugin is only installed and active. The IPP Onboarding should success and you should be able to collect a payment.
- Stripe Plugin is only installed and active. The IPP Onboarding should success and you should be able to collect a payment.
- No plugins active. The IPP Onboarding should fail and ask you to activate WCPay.

## Screenshots

See above

---
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by iamgabrielma — APPROVED** [review]
Tests well. LGTM!

```
✅ WCPay and Stripe both installed and active. The IPP Onboarding should prompt you to select one of them.
✅ WCPay Plugin is only installed and active. The IPP Onboarding should success and you should be able to collect a payment.
✅ Stripe Plugin is only installed and active. The IPP Onboarding should success and you should be able to collect a payment.
✅ No plugins active. The IPP Onboarding should fail and ask you to activate WCPay.
```

**Comment by toupper** [comment]
@iamgabrielma As the folder can also change, we only evaluate now the filename without extension: pdfdoF-3pF-p2#comment-4619. Please review again having this change into account. Thanks!

**Comment by iamgabrielma** [comment]
> @iamgabrielma As the folder can also change, we only evaluate now the filename without extension: pdfdoF-3pF-p2#comment-4619. Please review again having this change into account. Thanks!

Works as expected! 🎉 

Just a question: since we're checking the plugin slug now, isn't the same as to retrieve it via the existing `CardPresentPaymentsPlugin.gatewayID`? Since those are set to be both plugin slugs without folder and/or extension, as such:

```
woocommerce-payments
woocommerce-gateway-stripe
```

**Comment by toupper** [comment]
> Just a question: since we're checking the plugin slug now, isn't the same as to retrieve it via the existing CardPresentPaymentsPlugin.gatewayID? Since those are set to be both plugin slugs without folder and/or extension, as such:
> 
> woocommerce-payments
> woocommerce-gateway-stripe

That's a great question! As the `gatewayID` and the file name are different things with different semantics, I preferred to leave them separated in different properties. That way, if only one of the two changes, the other wouldn't be affected.

**Pull request merged**
