### PR TITLE
Blaze: Add parameter view should keep entered value after rotating device

### LINKED ISSUE #11809: Blaze: Text fields on Ad Destination > Add parameter are cleared after rotating device
**Describe the bug**
Text field states don't seem to be persisted when re-render the view.

**To Reproduce**
1. Log in to a store eligible for Blaze.
2. Go to Dashboard > Promote.
3. Select a product to promote if asked.
4. Select Ad Destination > Add parameter.
5. Type some contents in the key and value fields, then rotate the device.
6. Notice that the contents are cleared.

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/5533851/6e2d389f-8b0b-409c-9b8e-3e6d0a40b9e0

**Expected behavior**
Text field states are persisted after rotating the device.

### PR DESCRIPTION
**Pull request by hafizrahman**
Fixes #11809 

### Description:

This fixes the bug where entered user value in Ad Destination > Add Parameter setting disappears after rotation.

### The issue:

While this fix works, I must say that my understanding of `@ObservedObject` vs `@StateObject` might still be lacking. But here's my best attempt to explain the issue:

Previously, `BlazeAddParameterView` uses `@ObservedObject` to observe its view model, as the viewmodel is created by the parent  view's`BlazeAdDestinationSettingViewModel`. During rotation, the underlying parent viewmodel is recreated, which in turn also recreates the `BlazeAddParameterViewModel`.

Inside the initialization for `BlazeAddParameterViewModel`, it checks for empty `parameter` value and if it is, sets `key` and `value` as empty:

```
    init(remainingCharacters: Int,
         parameter: BlazeAdURLParameter? = nil,
         onCancel: @escaping () -> Void,
         onCompletion: @escaping BlazeAddParameterCompletionHandler) {
        self.remainingCharacters = remainingCharacters
        self.parameter = parameter
        self.cancellationHandler = onCancel
        self.completionHandler = onCompletion

        key = parameter?.key ?? ""
        value = parameter?.value ?? ""
    }
```

Thus, during rotation, the `key` and `value`  are reset to empty String again, creating the issue.

### The fix:

The fix now uses `@StateObject`, which lets the view to take over responsibility to manage the viewmodel's lifecycle. Thus, as long as the view is visible, when it is rotated, it keeps the existing viewmodel. This in turns makes sure that the entered values in the viewmodel are preserved.

### To test:

To Reproduce

1. Log in to a store eligible for Blaze.
2. Go to Dashboard > Promote.
3. Select a product to promote if asked.
4. Select Ad Destination > Add parameter.
5. Type some contents in the key and value fields, then rotate the device.
6. Ensure the entered contents are not removed.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by selanthiraiyan — COMMENTED** [review]
This looks good to me. Thanks for explaining the why. 🚢 

@itsmeichigo Please add if you have any comments.

**Review by selanthiraiyan — APPROVED** [review]

**Comment by itsmeichigo** [comment]
Looks good to me too 👍

**Comment by hafizrahman** [comment]
Thanks folks @selanthiraiyan @itsmeichigo !

**Pull request merged**
