### PR TITLE
Update Xcode version from 14.3.1 to 15.1 on CI

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #

## Screenshots

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

When merging:
- [ ] Merge and apply the corresponding Terraform PR to apply the configuration to the Buildkite pipeline: https://github.com/Automattic/buildkite-ci/pull/339

After merging:
- [ ] @spencertransier will post a P2 informing the WCiOS developers that they'll need to rebase on trunk in order for CI checks to pass on PRs

### CODE REVIEW

**Comment by jaclync** [comment]
Hello @woocommerce/mobile-ui-testing-squad 👋 I'm trying to update the CI to use Xcode 15.0.1 (the latest official version), but struggling with issues from some UI tests. When I ran the UI tests locally with iPhone 15 simulator, I only saw one test failure on `OrdersTests.test_create_new_order.addCustomAmount` because the keyboard wasn't available. Because the [text field has opacity 0](https://github.com/woocommerce/woocommerce-ios/blob/3bf78cbb1d67dc848f97e7c08aa6e9356b1ef7e7/WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI%20Components/FormattableAmountTextField.swift#L20) with the formatted amount, I couldn't trigger the text field either. When testing manually, I had to enable the software keyboard (cmd+K) but I couldn't find a way to do so programmatically in UI tests. Do you have any insights/advice on this keyboard handling?

Apparently, there are other issues with UI tests on CI that I'm going to look more into after fixing the UI tests locally.

**Comment by pachlava** [comment]
Hey @jaclync! Thank you for the ping. We'll have a look into the PR soon, but initially I'd like to say that issues with UI tests on Xcode 15 are known (see https://github.com/wordpress-mobile/WordPress-iOS/pull/21921), and "workaroundable" only to a certain extent, because apparently the issue is within Xcode 15.0.1 itself.

**Comment by pachlava** [comment]
@jaclync 👋 

0d044b2620de70835961a5d8dfbed523abbd60d4 disables the parallel execution for UI tests (cc @jostnes), and now they pass. Unit tests still fail, though. Possibly the unit tests-related commits from https://github.com/wordpress-mobile/WordPress-iOS/pull/21921 might give some ideas. It's worth mentioning the UI tests are now much slower, but I believe we have no choice if we want to upgrade to Xcode 15 on CI.

**Comment by jaclync** [comment]
> [0d044b2](https://github.com/woocommerce/woocommerce-ios/commit/0d044b2620de70835961a5d8dfbed523abbd60d4) disables the parallel execution for UI tests (cc @jostnes), and now they pass. Unit tests still fail, though. Possibly the unit tests-related commits from https://github.com/wordpress-mobile/WordPress-iOS/pull/21921 might give some ideas. It's worth mentioning the UI tests are now much slower, but I believe we have no choice if we want to upgrade to Xcode 15 on CI.

Thanks a lot @pachlava for the insights and the commit! It's really helpful to know the past discussion on this issue in JPiOS. The unit tests also took 1.5x the time (20 -> 30 min) in addition to the 4x time in UI tests. The whole CI build took 2 hours 😵 I don't think this is an acceptable time for the development workflow.

This looks like a known issue in [CircleCI with a long discussion](https://discuss.circleci.com/t/severe-performance-problems-with-xcode-15/49205/127) as well. The latest update mentioned a Xcode 15.1 RC, which probably isn't available in BK yet, that could help with this issue from the [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-15_1-release-notes#Resolved-Issues):

> [Resolved Issues](https://developer.apple.com/documentation/xcode-release-notes/xcode-15_1-release-notes#Resolved-Issues)
> Fixed: Executing Unit/UI tests from Xcode on the iOS Simulator takes an extended time to launch on first run of the suite. (115187363) (110330776) (FB12237092)

Hopefully, the upcoming Xcode 15.1 fixes the issue so that the CI time can be similar to before. According to [this CircleCI comment](https://discuss.circleci.com/t/severe-performance-problems-with-xcode-15/49205/110), Xcode 15.1 beta 2 had improvements on this issue. However, I wasn't able to try Xcode 15.1 beta versions on Buildkite and I couldn't find information about the supported Xcode versions. Let's wait for the Apps infra team to support Xcode 15.1 RC: p1701810243361429/1701810046.390629-slack-CC7L49W13

**Comment by spencertransier** [comment]
@jaclync We're in the process of migrating the apps to our Apple Silicon CI infra, which is where the Xcode 15.1 image lives. I branched off from this PR's branch to start that migration since it requires from configuration and a bit of testing before we roll all of WCiOS over to Apple Silicon CI. I'm hoping to get that done within the next day or two so that you'll be able to switch over to Xcode 15 ASAP.

**Comment by spencertransier** [comment]
@jaclync https://github.com/woocommerce/woocommerce-ios/pull/11580 is now merged into this one, so everything is good to go on my side.

**Comment by mokagio** [comment]
Took the liberty of changing the title to use 15.1 instead of 15.0.1, for consistency.

I'm also keeping an eye on the Apple Silicon infra migration on the Buildkite end, and will trigger a new build once done to check if everything works.

**Comment by mokagio** [comment]
🤔 Danger is [failing the build,](https://buildkite.com/automattic/woocommerce-ios/builds/18707) but it's not clear why...

**Comment by mokagio** [comment]
Running locally, with `bundle exec danger pr https://github.com/woocommerce/woocommerce-ios/pull/11352` returns

```
Results:

Errors:
- [ ] fastlane/Fastfile#L1231: Lint/UselessAssignment: Useless assignment to variable - `parallel_testing_value`.
```

But I don't understand why it Danger did not comment on this PR 🤔

**Comment by mokagio** [comment]
> But I don't understand why it Danger did not comment on this PR 🤔

It did comment on https://github.com/woocommerce/woocommerce-ios/pull/11642 not long ago and the step runs on Docker, so there should be no issues due to the cluster change in Buildkite.

image

**Comment by mokagio** [comment]
There's a UI test failure in both devices

```
test_load_support_screen() in SupportTests
```

Investigating...

**Comment by jaclync** [comment]
If possible, maybe the `Try Xcode 15*` attempted commits that I made can be deleted with a force push 😅 I can also do this when it's not WIP.

**Comment by mokagio** [comment]
Hi @jaclync 👋 

Yes it's possible. I expected to be myself at this time. Sorry...

The commit should still be in your local copy, though. And you can cherry-pick it.

Example, `git reflog` will show the log of changes to the local repo, each with a SHA. The commit should be in there. Once the SHA is identified, `git cherry-pick <SHA>` will add it here.

Also, I think I got the UI tests "sorted",  but I keep getting failures around the countries mapping. E.g.: I was about to look into this that I just got, but I need to hop offline for some hours.

image

**Comment by mokagio** [comment]
@jaclync according to my view on GitHub for iOS, the only problem here is a Hound violation. So I think we should easily address that then merge and finally unblock the other PRs for which the Xcode 14.3.1 CI is no longer available.

**Comment by jaclync** [comment]
@mokagio thanks for looking into the UI tests! I'll take over the PR until the next update comment since I'm going to:
- Look into the countries mapping unit test failure
- Delete the Xcode version attempt commits which requires a force push

**Comment by jaclync** [comment]
Update: Just added some commits to address the unit test failures (first `DataStoreTest` mentioned in Gio's comment https://github.com/woocommerce/woocommerce-ios/pull/11352#issuecomment-1884196540 that I can reproduce, then `FreeTrialBannerViewModelTests` that I can't reproduce probably due to the specific current time on CI). Waiting for the CI result now. Handing off the PR as I'm offline for the next few hours. If CI passes, maybe @woocommerce/apps-infrastructure can merge it to unblock other open PRs.

I also looked into the failing UI test `SupportTests`, I can repro it but couldn't figure out a fix within the time I had. The error was:

```
Failed to synthesize event: Neither element nor any descendant has keyboard focus. Event dispatch snapshot: TextField, {{21.0, 620.0}, {388.0, 22.0}}, ...
```

Tried the suggested fix in [the SO question](https://stackoverflow.com/questions/32184837/ui-testing-failure-neither-element-nor-any-descendant-has-keyboard-focus-on-se) but it didn't work. Not sure if it's something from Xcode 15.

**Review by mokagio — APPROVED** [review]
Thank you @jaclync for looking into the tests here 🙌

**Comment by jaclync** [comment]
Thanks @mokagio and Apps Infra for all the work to upgrade CI to Apple Silicon and Xcode 15.1!

**Pull request merged**
