### PR TITLE
IPP analytics: add `payment_method_type` property to `card_present_collect_payment_success` and `card_present_collect_payment_failed` events

### PR DESCRIPTION
**Pull request by jaclync**
Part of #5984 

### Description

To make it easier for reviewing and testing, this PR only implemented one change: adding `payment_method_type` property to `card_present_collect_payment_success` and `card_present_collect_payment_failed ` events, the only 2 events that contain this property. The mapping from `PaymentMethod` enum to analytics event property value is based on the [Android implementation](https://github.com/woocommerce/woocommerce-android/blob/f094beacdff4e2f79a5a9f1adc021d25c8265b22/libs/cardreader/src/main/java/com/woocommerce/android/cardreader/payments/CardPaymentStatus.kt#L145-L149).

#### Success case

- Launch the app
- Switch to a store that is eligible for IPP in Canada or the US
- Go to the Orders tab
- Tap on the "+" CTA in the navigation bar and select "Simple payment"
- Enter any number for the amount and tap "Next"
- Select the "Card" payment method to start the card reader and swipe a card if it's a physical card reader --> after the payment is collected, processed, and captured, an event should be logged in the console like: `🔵 Tracked card_present_collect_payment_success, properties: [AnyHashable("payment_method_type"): "card",  ...]`

#### Failed case

- If using a simulated card reader, you can use a test card number that is in one of the [error cases from Stripe doc](https://stripe.com/docs/terminal/references/testing#simulated-test-cards) in `StripeCardReaderService` (e.g. `4000000000009987`) 
- Launch the app
- Switch to a store that is eligible for IPP in Canada or the US
- Go to the Orders tab
- Tap on the "+" CTA in the navigation bar and select "Simple payment"
- If using a physical card reader, enter 12.01 for the amount for simulating processing error and tap "Next". Otherwise, you can enter any amount and tap "Next"
- Select the "Card" payment method to start the card reader and swipe a card if it's a physical card reader --> after the payment is collected, processed, and captured, an event should be logged in the console like: `🔵 Tracked card_present_collect_payment_failed, properties: [AnyHashable("payment_method_type"): "card",  ...]`

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by joshheald — APPROVED** [review]
Thanks, this looks good and tests well both in US and CA stores for the success events.

I think we also need to add it for the failure events though: pdfdoF-vx-p2#why-is-payment-method-type-important – an early concern we want to track is failure rate and whether there's any difference between card and interac flows for that.

I'll update the issue to make it match the discussion, but I don't mind if you want to do a new PR or add it here 😊

**Comment by jaclync** [comment]
> I think we also need to add it for the failure events though: [pdfdoF-vx-p2#why-is-payment-method-type-important](https://href.li/?pdfdoF-vx-p2#why-is-payment-method-type-important) – an early concern we want to track is failure rate and whether there's any difference between card and interac flows for that.
> 
> I'll update the issue to make it match the discussion, but I don't mind if you want to do a new PR or add it here 😊

Great question @joshheald! I forgot to mention that I didn't add it for the failure event after testing on Android with an invalid card and there is no `payment_method_type` in the failure events. Though, there are probably other error scenarios than the credit card error. In https://github.com/woocommerce/woocommerce-ios/pull/6495/commits/90433ead3216d7f9c8f9410e357b9b3407798b2a, I added an error case to encapsulate the payment method and log the property if it's available. Do you know if there is any way to test scenarios where payment is processed (so that the payment method is available) but then fails to be captured?

**Comment by joshheald** [comment]
> In https://github.com/woocommerce/woocommerce-ios/commit/90433ead3216d7f9c8f9410e357b9b3407798b2a, I added an error case to encapsulate the payment method and log the property if it's available. Do you know if there is any way to test scenarios where payment is processed (so that the payment method is available) but then fails to be captured?

Yes, absolutely! With a physical reader, [we can use specific amounts to trigger error cases](https://stripe.com/docs/terminal/references/testing#physical-test-cards). I think we can do similar with the simulated reader, using [certain card numbers](https://stripe.com/docs/terminal/references/testing#test-cards-for-specific-error-cases), though I don't think any of those are interac cards, so it's slightly limiting.

I used $12.01, which causes a `call_issuer` error, and on inspecting the Stripe API traffic, this is the response. See `error.payment_intent.charges[0].payment_method_details`, Stripe are definitely returning what we need.

```
{
  "error": {
    "charge": "ch_3KgozC2ETjwGHy9P0Fx1x8oV",
    "code": "card_declined",
    "decline_code": "call_issuer",
    "doc_url": "https://stripe.com/docs/error-codes/card-declined",
    "message": "Your card was declined. You can call your bank for details.",
    "payment_intent": {
      "id": "pi_3KgozC2ETjwGHy9P0Q9UWnuY",
      "object": "payment_intent",
      "amount": 1201,
      "amount_capturable": 0,
      "amount_received": 0,
      "amount_subtotal": 1201,
      "application": "ca_Ex84e31yMTLaNU5ozQvi5woLclpIDVpX",
      "application_fee_amount": null,
      "automatic_payment_methods": null,
      "canceled_at": null,
      "cancellation_reason": null,
      "capture_method": "manual",
      "charges": {
        "object": "list",
        "data": [
          {
            "id": "ch_3KgozC2ETjwGHy9P0Fx1x8oV",
            "object": "charge",
            "amount": 1201,
            "amount_captured": 0,
            "amount_refunded": 0,
            "application": "ca_Ex84e31yMTLaNU5ozQvi5woLclpIDVpX",
            "application_fee": null,
            "application_fee_amount": null,
            "authorization_code": "123456",
            "balance_transaction": null,
            "billing_details": {
              "address": {
                "city": null,
                "country": null,
                "line1": null,
                "line2": null,
                "postal_code": null,
                "state": null
              },
              "email": null,
              "name": null,
              "phone": null
            },
            "calculated_statement_descriptor": "JHMOOSE.MYSTAGINGWEBSI",
            "captured": false,
            "created": 1648121887,
            "currency": "cad",
            "customer": "cus_LNa9n9IlL4breR",
            "description": "In-Person Payment for Order #120 for My WordPress Site",
            "destination": null,
            "dispute": null,
            "disputed": false,
            "failure_code": "card_declined",
            "failure_message": "Your card was declined. You can call your bank for details.",
            "fraud_details": {},
            "invoice": null,
            "livemode": false,
            "metadata": {
              "order_id": "120",
              "payment_type": "single",
              "paymentintent.storename": "My WordPress Site",
              "reader_ID": "WPC323026000396",
              "reader_model": "WISEPAD_3",
              "site_url": "https://jhmoose.mystagingwebsite.com"
            },
            "on_behalf_of": null,
            "order": null,
            "outcome": {
              "network_status": "declined_by_network",
              "reason": "call_issuer",
              "risk_level": "not_assessed",
              "seller_message": "The bank returned the decline code `call_issuer`.",
              "type": "issuer_declined"
            },
            "paid": false,
            "payment_intent": "pi_3KgozC2ETjwGHy9P0Q9UWnuY",
            "payment_method": "pm_1KgozS2ETjwGHy9PIUZvgb9K",
            "payment_method_details": {
              "interac_present": {
                "brand": "visa",
                "cardholder_name": "USA INTERAC/Test Card 01",
                "country": "CA",
                "emv_auth_data": "8A023031",
                "exp_month": 12,
                "exp_year": 2022,
                "fingerprint": "rRszUUzMmNu5Onxg",
                "funding": "debit",
                "generated_card": null,
                "last4": "1933",
                "network": "interac",
                "preferred_locales": [
                  "en"
                ],
                "read_method": "contact_emv",
                "receipt": {
                  "account_type": "checking",
                  "application_cryptogram": "21A05A9F09CD9F24",
                  "application_preferred_name": "Interac",
                  "authorization_code": null,
                  "authorization_response_code": "5A31",
                  "cardholder_verification_method": "offline_pin",
                  "dedicated_file_name": "A0000002771010",
                  "terminal_verification_results": "8000008000",
                  "transaction_status_information": "6800"
                }
              },
              "type": "interac_present"
            },
            "receipt_email": null,
            "receipt_number": null,
            "receipt_url": null,
            "refunded": false,
            "refunds": {
              "object": "list",
              "data": [],
              "has_more": false,
              "total_count": 0,
              "url": "/v1/charges/ch_3KgozC2ETjwGHy9P0Fx1x8oV/refunds"
            },
            "review": null,
            "shipping": null,
            "source": null,
            "source_transfer": null,
            "statement_descriptor": "JHMOOSE.MYSTAGINGWEBSI",
            "statement_descriptor_suffix": null,
            "status": "failed",
            "transfer_data": null,
            "transfer_group": null
          }
        ],
        "has_more": false,
        "total_count": 1,
        "url": "/v1/charges?payment_intent=pi_3KgozC2ETjwGHy9P0Q9UWnuY"
      },
      "client_secret": "pi_3KgozC2ETjwGHy9P0Q9UWnuY_secret_owitiulyCbcgw3r48EB2QdLGT",
      "confirmation_method": "automatic",
      "created": 1648121870,
      "currency": "cad",
      "customer": "cus_LNa9n9IlL4breR",
      "description": "In-Person Payment for Order #120 for My WordPress Site",
      "invoice": null,
      "last_payment_error": {
        "charge": "ch_3KgozC2ETjwGHy9P0Fx1x8oV",
        "code": "card_declined",
        "decline_code": "call_issuer",
        "doc_url": "https://stripe.com/docs/error-codes/card-declined",
        "message": "Your card was declined. You can call your bank for details.",
        "payment_method": {
          "id": "pm_1KgozS2ETjwGHy9PIUZvgb9K",
          "object": "payment_method",
          "billing_details": {
            "address": {
              "city": null,
              "country": null,
              "line1": null,
              "line2": null,
              "postal_code": null,
              "state": null
            },
            "email": null,
            "name": null,
            "phone": null
          },
          "created": 1648121886,
          "customer": null,
          "interac_present": {},
          "livemode": false,
          "metadata": {},
          "type": "interac_present"
        },
        "type": "card_error"
      },
      "level3": null,
      "livemode": false,
      "metadata": {
        "order_id": "120",
        "payment_type": "single",
        "paymentintent.storename": "My WordPress Site",
        "reader_ID": "WPC323026000396",
        "reader_model": "WISEPAD_3",
        "site_url": "https://jhmoose.mystagingwebsite.com",
        "customer_email": "",
        "customer_name": ""
      },
      "next_action": null,
      "on_behalf_of": null,
      "payment_method": null,
      "payment_method_options": {
        "card_present": {},
        "interac_present": {}
      },
      "payment_method_types": [
        "card_present",
        "interac_present"
      ],
      "processing": null,
      "receipt_email": null,
      "review": null,
      "setup_future_usage": null,
      "shipping": null,
      "source": null,
      "statement_descriptor": "JHMOOSE.MYSTAGINGWEBSI",
      "statement_descriptor_suffix": null,
      "status": "requires_payment_method",
      "total_details": {
        "amount_discount": 0,
        "amount_tax": 0
      },
      "transfer_data": null,
      "transfer_group": null
    },
    "payment_method": {
      "id": "pm_1KgozS2ETjwGHy9PIUZvgb9K",
      "object": "payment_method",
      "billing_details": {
        "address": {
          "city": null,
          "country": null,
          "line1": null,
          "line2": null,
          "postal_code": null,
          "state": null
        },
        "email": null,
        "name": null,
        "phone": null
      },
      "created": 1648121886,
      "customer": null,
      "interac_present": {},
      "livemode": false,
      "metadata": {},
      "type": "interac_present"
    },
    "type": "card_error"
  }
}
```

`StripeTerminal` is giving us the following error for that:

In [`StripeCardReaderService.processPayment(intent:)`](https://github.com/woocommerce/woocommerce-ios/blob/f02dcad2921e2ccf045e3ec1ec72115c8e30df20/Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift#L450):
```
po error
<SCPProcessPaymentError: 0x28333ba80; code = 6000; message = The Stripe API declined the transaction, see the event logs in your Stripe Dashboard for detailed information.; requestId = req_rKNXnrKvTVAP4Z; requestError = 0x2829f3060; paymentIntent = pi_3KgpDS2ETjwGHy9P0L6IWhlC: 0x28023f660>

po error.paymentIntent
▿ Optional<SCPPaymentIntent>
  - some : <SCPPaymentIntent: 0x28023f660; amount = 1201; currency = cad; created = 2022-03-24 11:52:34 +0000; charges = (
    "<SCPCharge: 0x28054f890; amount = 1201; currency = cad; metadata = {\n    \"order_id\" = 120;\n    \"payment_type\" = single;\n    \"paymentintent.storename\" = \"My WordPress Site\";\n    \"reader_ID\" = WPC323026000396;\n    \"reader_model\" = \"WISEPAD_3\";\n    \"site_url\" = \"https://jhmoose.mystagingwebsite.com\";\n}; paymentMethodDetails = <SCPPaymentMethodDetails: 0x2829f0330; cardPresent = (null); interacPresent = <SCPCardPresentDetails: 0x280de3800; brand = visa; funding = debit; last4 = 1933; cardholderName = USA INTERAC/Test Card 01; expMonth = 12; expYear = 2022; fingerprint = rRszUUzMmNu5Onxg; generatedCard = (null); receipt = <SCPReceiptDetails: 0x28054ea80; accountType = checking; authorizationResponseCode = 5A31; dedicatedFileName = A0000002771010; applicationPreferredName = Interac; applicationCryptogram = E49FFF47F1C5A5D9; terminalVerificationResults = 8000008000; transactionStatusInformation = 6800>; emvAuthData = 8A023031>; type = interac_present>; status = failed; stripeDescription = In-Person Payment for Order #120 for My WordPress Site; stripeId = ch_3KgpDS2ETjwGHy9P0RX752Fd>"
); metadata = {
    "customer_email" = "";
    "customer_name" = "";
    "order_id" = 120;
    "payment_type" = single;
    "paymentintent.storename" = "My WordPress Site";
    "reader_ID" = WPC323026000396;
    "reader_model" = "WISEPAD_3";
    "site_url" = "https://jhmoose.mystagingwebsite.com";
}; offline_details = (null); status = requires_payment_method; stripeId = pi_3KgpDS2ETjwGHy9P0L6IWhlC>
```

And we are translating that to

In [`InPersonPayments.collectPaymentFailed(forGatewayID:error:countryCode:)`](https://github.com/woocommerce/woocommerce-ios/blob/f02dcad2921e2ccf045e3ec1ec72115c8e30df20/WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift#L782):
```
▿ CardReaderServiceError
  ▿ paymentCapture : 1 element
    ▿ underlyingError : UnderlyingError
      ▿ paymentDeclinedByPaymentProcessorAPI : 1 element
        - declineReason : Hardware.DeclineReason.fraud
```

So at the moment, the `paymentMethod` isn't being pulled out and logged by your change, but it's probably a fairly small change to make it do that...

Let me know if you need any tests doing for error scenarios that you can't do in the simulator, or just as a double check.

**Comment by jaclync** [comment]
> Yes, absolutely! With a physical reader, [we can use specific amounts to trigger error cases](https://stripe.com/docs/terminal/references/testing#physical-test-cards). I think we can do similar with the simulated reader, using [certain card numbers](https://stripe.com/docs/terminal/references/testing#test-cards-for-specific-error-cases), though I don't think any of those are interac cards, so it's slightly limiting.

Nice, TIL about the order amounts with a physical reader! For Interac, there is a test card number 4506445006931933 at the bottom of [the doc](https://stripe.com/docs/terminal/references/testing#simulated-test-cards) or we use `Terminal.shared.simulatorConfiguration.simulatedCard = .init(type: .interac)`. I was able to test it in a CA store, and saw the payment method type as `card_interac` in the success event from the simulator.

> I used $12.01, which causes a `call_issuer` error, and on inspecting the Stripe API traffic, this is the response. See `error.payment_intent.charges[0].payment_method_details`, Stripe are definitely returning what we need.

Wow thanks for the pointer @joshheald, I had no idea the error has a payment intent! 😮 Now I see payment method type included in the failure events. I updated the PR to include the payment method from the error, you can take another look when you get a chance!

Also would like your feedback on this: in https://github.com/woocommerce/woocommerce-ios/pull/6495/commits/9d697cb1624d3d9d9fa893d9045de7692d56abc3, I added `error` to the event wrapper so that we can log the full error including domain and code. But after testing, I'm uncertain about whether to log such detailed information for privacy reasons since the analytics logger uses `error.description`. Example:

<details>
"error_description": "Hardware.CardReaderServiceError.paymentCaptureWithPaymentMethod(underlyingError: Hardware.UnderlyingError.paymentDeclinedByPaymentProcessorAPI(declineReason: Hardware.DeclineReason.fraud), paymentMethod: Hardware.PaymentMethod.cardPresent(details: Hardware.CardPresentTransactionDetails(last4: \"9995\", expMonth: 12, expYear: 2030, cardholderName: nil, brand: Hardware.CardBrand.visa, fingerprint: \"NteeWkydkwzhsjHD\", generatedCard: Optional(\"pm_1Kh74V2Hmx1ceOwsPa3NZj6R\"), receipt: Optional(Hardware.ReceiptDetails(applicationPreferredName: \"\", dedicatedFileName: \"\", authorizationResponseCode: \"3031\", applicationCryptogram: \"\", terminalVerificationResults: \"\", transactionStatusInformation: \"\", accountType: Optional(\"credit\"))), emvAuthData: Optional(\"8A023031\"))))"
</details>

If you also feel unsure about logging this much, I will revert the changes to manually log the failure with `error.localizedDescription` 🙂

**Comment by joshheald** [comment]
> But after testing, I'm uncertain about whether to log such detailed information for privacy reasons since the analytics logger uses `error.description`. Example:
> 
> ```"error_description": "Hardware.CardReaderServiceError.paymentCaptureWithPaymentMethod(underlyingError: Hardware.UnderlyingError.paymentDeclinedByPaymentProcessorAPI(declineReason: Hardware.DeclineReason.fraud), paymentMethod: Hardware.PaymentMethod.cardPresent(details: Hardware.CardPresentTransactionDetails(last4: \"9995\", expMonth: 12, expYear: 2030, cardholderName: nil, brand: Hardware.CardBrand.visa, fingerprint: \"NteeWkydkwzhsjHD\", generatedCard: Optional(\"pm_1Kh74V2Hmx1ceOwsPa3NZj6R\"), receipt: Optional(Hardware.ReceiptDetails(applicationPreferredName: \"\", dedicatedFileName: \"\", authorizationResponseCode: \"3031\", applicationCryptogram: \"\", terminalVerificationResults: \"\", transactionStatusInformation: \"\", accountType: Optional(\"credit\"))), emvAuthData: Optional(\"8A023031\"))))"```
> If you also feel unsure about logging this much, I will revert the changes to manually log the failure with `error.localizedDescription` 🙂

I agree, that's quite a lot of detail to log to analytics. We definitely don't want to log `cardholderName` or any individual card details like expiry and last4. I think we should limit it to:

* declineReason
* paymentMethodType (the actual property you're pulling out anyway)
* cardBrand

Perhaps an `analyticsDescription` extension on `CardReaderServiceError`, and the other objects it's logging, would be a good option here? `localisedDescription` still seems to log the same sort of thing in my testing:

<details>
```
🔵 Tracked card_present_collect_payment_failed, properties: [AnyHashable("error_code"): "6", AnyHashable("payment_method_type"): "card_interac", AnyHashable("error_description"): "Hardware.CardReaderServiceError.paymentCaptureWithPaymentMethod(underlyingError: Hardware.UnderlyingError.paymentDeclinedByPaymentProcessorAPI(declineReason: Hardware.DeclineReason.fraud), paymentMethod: Hardware.PaymentMethod.interacPresent(details: Hardware.CardPresentTransactionDetails(last4: \"1933\", expMonth: 12, expYear: 2022, cardholderName: Optional(\"USA INTERAC/Test Card 01\"), brand: Hardware.CardBrand.visa, fingerprint: \"rRszUUzMmNu5Onxg\", generatedCard: nil, receipt: Optional(Hardware.ReceiptDetails(applicationPreferredName: \"Interac\", dedicatedFileName: \"A0000002771010\", authorizationResponseCode: \"5A31\", applicationCryptogram: \"D36B53378EFBC9EF\", terminalVerificationResults: \"8000008000\", transactionStatusInformation: \"6800\", accountType: Optional(\"checking\"))), emvAuthData: Optional(\"8A023031\"))))", AnyHashable("is_wpcom_store"): false, AnyHashable("plugin_slug"): "woocommerce-payments", AnyHashable("error_domain"): "Hardware.CardReaderServiceError", AnyHashable("country"): "CA", AnyHashable("blog_id"): 203184915]
```
</details>

All that said, `payment_method_type` is being logged correctly now 🥳 so it tests well 👍

**Comment by jaclync** [comment]
Sounds good @joshheald to only log the card brand and underlying error in addition to the payment method type 👍 I just updated the PR to manually generate the error description, and now the failed event looks like:

<details>
🔵 Tracked card_present_collect_payment_failed, properties: [AnyHashable("blog_id"): 204028600, AnyHashable("payment_method_type"): "card", AnyHashable("is_wpcom_store"): false, AnyHashable("plugin_slug"): "woocommerce-payments", AnyHashable("country"): "CA", AnyHashable("error_description"): "[\"underlyingError\": Hardware.UnderlyingError.paymentDeclinedByPaymentProcessorAPI(declineReason: Hardware.DeclineReason.fraud), \"cardBrand\": Hardware.CardBrand.visa]"]
</details>

**Pull request merged**
