### PR TITLE
Merge 3.9 final into develop

### PR DESCRIPTION
**Pull request by oguzkocer**
There were a couple conflicts:

```
deleted by us:   fastlane/metadata/ar-SA/subtitle.txt
deleted by us:   fastlane/metadata/he/subtitle.txt
```

I accepted both of them as I am guessing these don't really matter since we are auto updating these strings anyway.

### CODE REVIEW

**Comment by oguzkocer** [comment]
@loremattei The tests are currently failing in `develop` as well. Do we ping someone about this type of thing?

**Comment by jaclync** [comment]
hey @oguzkocer I have a PR open to fix the build error that was caused by 2 of my previous PRs: https://github.com/woocommerce/woocommerce-ios/pull/2080 - hopefully it can be merged soon!

**Comment by oguzkocer** [comment]
@jaclync Thanks a lot for the heads up!

**Comment by jaclync** [comment]
@oguzkocer I just merged the above PR to `develop`! I'll also watch the status of the merge commit on `develop` in case there are any other issues

**Pull request merged**
