### PR TITLE
Storage: Product details

### PR DESCRIPTION
**Pull request by bummytime**
This PR adds product details  support to **model v12** which is scheduled to ship with WCiOS v1.5:

Screen Shot 2019-03-20 at 1 55 36 PM

Nothing really earth shattering here, just updates the the model and all of the generated `NSManagedObject` subclasses for `Product`.

Ref: #764

## Testing

1. Review the model + code
2. Run the unit tests — verify they are ✅ 
3. Build and run the app — verify nothing strange is going on
4. Verify the lightweight migration works from v11 to v12 (it should since we are simply adding new entities in this PR).

@ctarda would you mind giving this a quick review?

/cc @astralbodies because core data 🥇

### CODE REVIEW

**Comment by bummytime** [comment]
Thanks for the review @ctarda. 

> The app crashes on startup at CoreDataIterativeMigrator.iterativeMigrate

Interesting. I had this exact same issue with Thuy's last model update. My simulator seemed to be in a bad state such that simply deleting the app didn't fix it. In that situation I had to completly reset the simulator via Hardware → Erase all content and settings and everything worked as expected.

@astralbodies not sure if you have any thoughts here since I am unable to repro @ctarda's issue on my side.

> Also, one question, just to make sure I understand the big picture. Should we add the siteID to these entities? These look like might be site dependant.

That's a fair question. I thought about doing this but realized that it would require a bunch of changes in the Networking layer to support it. Additionally, the child entities connected to `Product` are (probably) never going to be queried directly without the consumer having context to their parent. 

So maybe a good general summary here is that we should make sure all top-level (parent) entities have a `siteID` and, as long as child entities have a relationship defined to the parent, we can don't have to put `siteID` in them. 

Let me know your thoughts! 😄

**Comment by bummytime** [comment]
Thank you for double-checking this @astralbodies!

**Comment by bummytime** [comment]
@ctarda with @astralbodies :shipit: above, I am going to go ahead and merge into `develop` so the changes in this PR don't have to be redone on a model v13 next week. If you have any strong objections I am more than happy to make any updates as you see fit. Thanks again!!!

**Comment by ctarda** [comment]
@bummytime No objections here! And your explanation about `siteID` makes total sense, thanks!  😊

**Pull request merged**
