### PR TITLE
Rename "deposit" to "payout" in code and documentation URL

### LINKED ISSUE #14369: Rename Deposits to Payouts
Rename Deposits to Payouts in both user facing strings as well as on the code level.

More context paJDYF-e8c-p2.

- [x] User-facing changes: https://github.com/woocommerce/woocommerce-ios/pull/14402
- [x] Doc change: https://github.com/woocommerce/woocommerce-ios/pull/14415
- [x] Code-level changes: https://github.com/woocommerce/woocommerce-ios/pull/14415

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #14369 

## Description

- Documentation URL: from `https://woocommerce.com/document/woopayments/deposits/deposit-schedule/` to `https://woocommerce.com/document/woopayments/payouts/payout-schedule/` (the previous URL already redirects to the new one in production).
- Code-level changes: renamed every "deposit" mention to "payout" as much as possible. There are some exceptions in the Networking layer, because the API path and schema still use "deposit" (like the Codable struct `WooPaymentsPayoutsOverview` if manual naming mapping isn't implemented). I didn't rename the simulated network response JSON files because the API path is still using "deposit" (confirmation about the API path/schema renaming plan in paJDYF-e8c-p2#comment-26973)

After this PR, there should be minimal mentions of "deposit" in the app with the exceptions in the Networking layer and Tracks event names.

## Steps to reproduce

- Switch to a store eligible for payout
- Go to Menu > Payments --> the payout summary should be shown at the top
- Tap on the payout summary to expand --> all mentions should be about "payout"
- Tap on the learn more row --> the doc content still refers to "deposit" at the moment, but the URL should be using "payout" in the path

## Screenshots

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.69

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jaclync** [comment]
Note for reviewer: Danger CI step requires the PR to have a `category: tracks` label due to some diffs on the analytics code, but the diffs are only from renaming the variables/constants without affecting the values.

**Comment by staskus** [comment]
> the doc content still refers to "deposit" at the moment, but the URL should be using "payout" in the path

✅ Already updated!

image

**Review by staskus — APPROVED** [review]
Thanks for the change.

Looks good and as expected 👍 

image

**Pull request merged**
