### PR TITLE
[Woo POS] Add missing font specifiers

### LINKED ISSUE #13691: [Woo POS] Add missing POSFontStyle to Text
All our `Text` elements should have `.font` with `POSFontStyle` set. Missing usage:

- PointOfSaleCardPresentPaymentScanningForReadersView
- PointOfSaleCardPresentPaymentScanningForReadersFailedView
- PointOfSaleCardPresentPaymentBluetoothRequiredAlertView
- PointOfSaleCardPresentPaymentConnectingToReaderView
- PointOfSaleCardPresentPaymentConnectingFailedView
- PointOfSaleCardPresentPaymentConnectingFailedNonRetryableView
- PointOfSaleCardPresentPaymentConnectingFailedUpdatePostalCodeView
- PointOfSaleCardPresentPaymentConnectingFailedChargeReaderView
- PointOfSaleCardPresentPaymentFoundReaderView
- PointOfSaleCardPresentPaymentConnectingFailedUpdateAddressView
- PointOfSaleCardPresentPaymentRequiredReaderUpdateInProgressView
- PointOfSaleCardPresentPaymentOptionalReaderUpdateInProgressView
- PointOfSaleCardPresentPaymentReaderUpdateCompletionView
- PointOfSaleCardPresentPaymentReaderUpdateFailedView
- PointOfSaleCardPresentPaymentConnectionSuccessAlertView
- PointOfSaleCardPresentPaymentReaderUpdateFailedNonRetryableView
- PointOfSaleCardPresentPaymentReaderUpdateFailedLowBatteryView
- ReaderConnectedView
- PointOfSaleDashboardView Text(totalsViewModel.cardPresentPaymentEvent.temporaryEventDescription)
-

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #13691

## Description
This PR updates the existing payment views to use `POSFontStyle` in their `Text` elements, when missing. The pattern we've followed is to use `.font(POSFontStyle.posBodyRegular)` for titles, and `.font(POSFontStyle.posDetailLight)` for description and error details.

## Testing
While the changes are just adding missing .font modifiers to existing Text views, not much has changed, but since we've updated 18 screens, it would be good to smoke test the following flows:
- Card reader connection flow
- Payment collection flow
- Reader low on battery
- Reader needs optional/required updates

I've tested the above flows both in simulator and physical device, except the different _failed_ views (failed zip code, failed charge, ...) which I tested via Xcode Previews only.

I've also smoke tested card reader connection and payment flow in dark mode, as was merged with trunk on https://github.com/woocommerce/woocommerce-ios/pull/13733/commits/fa46171ae2302bc1b3d06e033beac443dc984d93

## Screenshots

| PointOfSaleCardPresentPaymentScanningForReadersView | PointOfSaleCardPresentPaymentScanningForReadersFailedView |
|--------|--------|
| 1 PointOfSaleCardPresentPaymentScanningForReadersView | 2 PointOfSaleCardPresentPaymentScanningForReadersFailedView |

| PointOfSaleCardPresentPaymentBluetoothRequiredAlertView | PointOfSaleCardPresentPaymentConnectingToReaderView |
|--------|--------|
| 3 PointOfSaleCardPresentPaymentBluetoothRequiredAlertView | 4 PointOfSaleCardPresentPaymentConnectingToReaderView |

| PointOfSaleCardPresentPaymentConnectingFailedView | PointOfSaleCardPresentPaymentConnectingFailedNonRetryableView |
|--------|--------|
| 5 PointOfSaleCardPresentPaymentConnectingFailedView | 6 PointOfSaleCardPresentPaymentConnectingFailedNonRetryableView |

| PointOfSaleCardPresentPaymentConnectingFailedUpdatePostalCodeView | PointOfSaleCardPresentPaymentConnectingFailedChargeReaderView |
|--------|--------|
| 7 PointOfSaleCardPresentPaymentConnectingFailedUpdatePostalCodeView | 8 PointOfSaleCardPresentPaymentConnectingFailedChargeReaderView |

| PointOfSaleCardPresentPaymentFoundReaderView | PointOfSaleCardPresentPaymentConnectingFailedUpdateAddressView |
|--------|--------|
| 9 PointOfSaleCardPresentPaymentFoundReaderView | 10 PointOfSaleCardPresentPaymentConnectingFailedUpdateAddressView | 

| PointOfSaleCardPresentPaymentRequiredReaderUpdateInProgressView | PointOfSaleCardPresentPaymentOptionalReaderUpdateInProgressView |
|--------|--------|
| 11 PointOfSaleCardPresentPaymentRequiredReaderUpdateInProgressView | 12 PointOfSaleCardPresentPaymentOptionalReaderUpdateInProgressView | 

| PointOfSaleCardPresentPaymentReaderUpdateCompletionView | PointOfSaleCardPresentPaymentReaderUpdateFailedView |
|--------|--------|
| 13 PointOfSaleCardPresentPaymentReaderUpdateCompletionView | 14 PointOfSaleCardPresentPaymentReaderUpdateFailedView | 

| PointOfSaleCardPresentPaymentConnectionSuccessAlertView | PointOfSaleCardPresentPaymentReaderUpdateFailedNonRetryableView |
|--------|--------|
| 15 PointOfSaleCardPresentPaymentConnectionSuccessAlertView | 16 PointOfSaleCardPresentPaymentReaderUpdateFailedNonRetryableView | 

| PointOfSaleCardPresentPaymentReaderUpdateFailedLowBatteryView | ReaderConnectedView |
|--------|--------|
| 17 PointOfSaleCardPresentPaymentReaderUpdateFailedLowBatteryView | 18 ReaderConnectedView | 

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by joshheald** [comment]
> The pattern we've followed is to use `.font(POSFontStyle.posBodyRegular)` for titles, and `.font(POSFontStyle.posDetailLight)` for description and error details.

Why not Title and Body styles? The goal isn't to make it match the existing app's styling, but the POS instead. I don't think Joe ever got it into the designs unfortunately.

**Comment by iamgabrielma** [comment]
> Why not Title and Body styles? The goal isn't to make it match the existing app's styling, but the POS instead. I don't think Joe ever got it into the designs unfortunately.

From what I tested `.posBodyRegular` and `.posDetailLight` are the ones closer to the existing  designs, by using title and body styles it seems that the font increases considerably for the titles, and the body increases in weight, which looks a bit odd compared with the rest, so I just went ahead with the ones that cause less friction with what's already being used.

That said, if we're not looking to match the app styling or keep the existing looks, happy to change those as needed.

**Comment by joshheald** [comment]
> From what I tested `.posBodyRegular` and `.posDetailLight` are the ones closer to the existing designs, by using title and body styles it seems that the font increases considerably for the titles, and the body increases in weight, which looks a bit odd compared with the rest, so I just went ahead with the ones that cause less friction with what's already being used.

The designs aren't fully up to date, and the general idea is to make all the text big, bold, and readable in POS. We have plenty of space, after all. The designs for this area haven't had much attention as they're iOS only. If you look at Figma, they're a screenshot of the existing error with a new image put over the top.

> That said, if we're not looking to match the app styling or keep the existing looks, happy to change those as needed.

Yeah, that's the plan. Sorry, I didn't get to this ticket to note it but agreed with Joe here: p1722925445037829/1722851716.972199-slack-C070SJRA8DP

**Review by joshheald — APPROVED** [review]
I've updated to use `posTitleEmphasized` and `posBodyRegular` throughout to match other modals.

Also updated the Multiple readers view – that will get more work under #13731.

The `ReaderConnectedView` was a leftover from the wireframe days so I deleted it.

Here's some of my testing – note that I merged the [disconnection work](https://github.com/woocommerce/woocommerce-ios/pull/13720) for my testing to make it easier to check a few things:

https://github.com/user-attachments/assets/3e14885f-d7fe-493b-8c0e-4191aa4bd397

Please have a run through before you merge... but also don't stress too much. I'm going to be looking at them all again in #13731 and can catch any issues there.

**Comment by iamgabrielma** [comment]
Thanks for the link to the slack thread. Those look great to me, thanks for updating them. Merging!

**Pull request merged**
