### PR TITLE
Dark Mode: update colors for Dashboard tab

### LINKED ISSUE #1566: Stats: Selected bar in stats chart shows dark text on dark background
**Describe the bug**

With the older stats feature (not improved stats), the stats bar chart shows the bars in pink. Selecting a bar makes it dark pink. The details that pop up above the bar also have a dark pink background, with black text, making it hard to read.

**To Reproduce**
1. Make sure improved stats is not enabled (under Settings > Experimental Features disable the "Improved stats" toggle).
2. On the My store tab, select a bar in the stats bar chart.
3. Notice the text is hard to read.

**Screenshots**

The text looks ok with the dark mode colors:

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.2.3
- WooCommerce iOS version: 3.2.0.1

Originally reported by a TestFlight beta tester.

### PR DESCRIPTION
**Pull request by jaclync**
Stats/Dashboard for #1555 
Fixes #1566

- [x] ⚠️update PR base to `release/3.2` after https://github.com/woocommerce/woocommerce-ios/pull/1565 is merged  ⚠️ 

## Changes

- Updated colors on the Dashboard tab: stats v3/v4, top performers, top banner view. Issues from @kyleaparker's checklist:
  - There is a strange double border under the stats. This border should actually be removed entirely (image below)
  - The border under the tab bar is too thick, I’m not sure it’s using the correct colour either (System separator)
  - Wrong loading state:
  - There should be a border under the date (image below)
  - Chart colours need updating
  - Stats on light mode: the borders all look too dark and some of them are too thick, should be using system separator
  - Try our improved stats border colours could use system separator: 
  - Change “Try it now” link to accent

## Testing

- Launch the app, logged in --> the Dashboard should look as expected

## Example screenshots

screen | Dark | Light
-- | -- | --
Stats v4 | Simulator Screen Shot - iPhone 8 - 2019-12-09 at 14 46 05 | Simulator Screen Shot - iPhone 8 - 2019-12-09 at 14 46 13
Stats v3 + v3 -> v4 banner | Simulator Screen Shot - iPhone 8 - 2019-12-09 at 14 25 48 | Simulator Screen Shot - iPhone 8 - 2019-12-09 at 14 25 59
Top performers | Simulator Screen Shot - iPhone 8 - 2019-12-09 at 14 26 36 | Simulator Screen Shot - iPhone 8 - 2019-12-09 at 14 26 28
Top banner v4 -> v3 | Simulator Screen Shot - iPhone 8 - 2019-12-09 at 14 32 35 | Simulator Screen Shot - iPhone 8 - 2019-12-09 at 14 32 28
Loading state | Simulator Screen Shot - iPhone 8 - 2019-12-06 at 14 19 07 | Simulator Screen Shot - iPhone 8 - 2019-12-06 at 14 19 17

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by mindgraffiti — COMMENTED** [review]
I can't build this with the current podfile. It appears that the branch the Authenticator is pointing to is gone?

@jaclync @kyleaparker can the label text color for a selected stat in Dark Mode be changed to black? There isn't enough contrast between the selected stat color and white text. I have low vision and am unable to read the stat details easily.

**Review by kyleaparker — CHANGES_REQUESTED** [review]
- On the Stats V2, can we remove the dark separator between the three stats and the chart?
- The banners should be separated from the chart (the background colour in between should use the grouped background colour). I sent you some design updates separately :)

**Comment by kyleaparker** [comment]
>@jaclync @kyleaparker can the label text color for a selected stat in Dark Mode be changed to black? There isn't enough contrast between the selected stat color and white text. I have low vision and am unable to read the stat details easily.

Agreed 👍

**Comment by jaclync** [comment]
@kyleaparker @mindgraffiti great catches! I updated the PR and the screenshots in the PR description with the following changes:
- Updated the borders in stats v3
- Updated the colors of the dashboard background views
- Updated the selected stats bar callout text color

**Comment by jaclync** [comment]
> I can't build this with the current podfile. It appears that the branch the Authenticator is pointing to is gone?

@mindgraffiti sorry the `Podfile` was pointing to a PR branch that was deleted earlier, could you try again?

**Review by pmusolino — APPROVED** [review]
Code LGTM ✅ 
UI Testing ✅  everything is like in screenshots

**Review by mindgraffiti — APPROVED** [review]
Love it! Thanks for fixing all the details.

✅ code
✅ UI tested

Screenshots:

| Light | Dark |
| --- | --- |
|  |  |
|  |  |

**Review by kyleaparker — COMMENTED** [review]
Looks good! My only comment is the dividers within the chart still look too dark, what colour are these using?

**Comment by jaclync** [comment]
> My only comment is the dividers within the chart still look too dark, what colour are these using?

@kyleaparker it's currently setting the chart lines to `listSmallIcon` (`systemGray`). I just checked the Figma and tried using `systemGray5`, but the lines are quite hard to see in Dark mode (screenshots below) - do you think we can use a different system gray color?

mode | before (`systemGray`) | after (`systemGray5`)
-- | -- | --
Dark | Simulator Screen Shot - iPhone 8 - 2019-12-10 at 09 31 08 | Simulator Screen Shot - iPhone 8 - 2019-12-10 at 09 35 19
Light | Simulator Screen Shot - iPhone 8 - 2019-12-10 at 09 30 15 | Simulator Screen Shot - iPhone 8 - 2019-12-10 at 09 35 27

**Comment by jaclync** [comment]
Since other PRs depend on this PR, I added the stats chart lines color update to the master issue #1555 and merging this PR now

**Comment by kyleaparker** [comment]
>@kyleaparker it's currently setting the chart lines to listSmallIcon (systemGray). I just checked the Figma and tried using systemGray5, but the lines are quite hard to see in Dark mode (screenshots below) - do you think we can use a different system gray color?

It should be using **divider** to match the other separators

**Pull request merged**
