### PR TITLE
Set `waitTimeout` to 7 for all screen objects

### PR DESCRIPTION
**Pull request by pachlava**
### Description
The default waiting timeout during `ScreenObject` instantiation is 20 seconds, which in most cases is more than enough. 

Before doing their thing, methods often check if a specific screen is really absent. For example, when opening a screen via tab bar, the method will check if said screen is not already open, which means waiting for 20 seconds for a screen (that most probably is not present anyway) to appear. 

Thankfully, `ScreenObject` is flexible and provides a possibility to set a custom waiting timeout, so this is what I did. I went for 7 seconds, thinking that 5 seconds might be on the edge for slower CI.

Local execution on iPhone 13 iOS 15 went down by 68 seconds (342 ~> 274).

### Testing instructions
- CI is green.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by jostnes — APPROVED** [review]
Thanks for making this change @pachlava ! TIL on the custom timeout. There is however a conflict in the PR (should be from my merge earlier, sorry about that 🙏 ) that you'll have to resolve first but other than that this is good so I'll give it my early approval.

I have something more controversial to suggest, as noted in this PR, some of the slowness happens during the tab nav navigation where it checks that the test is not on a specific screen before tapping to go to the screen, in theory this is done to save time (don't tap unless needed) but in reality it seems that the multiple checks are adding unnecessary time to the test. 

Definitely not for this PR but as a conversation starter, what do you think about removing that condition, e.g. to go to `ProductsScreen`, do this directly: 
```
    public func gotoProductsScreen() throws -> ProductsScreen {
        productsTabButton.tap()
        return try ProductsScreen()
    }
```

**Review by mokagio — APPROVED** [review]
Once again, thank you for researching and taking action on this. I love the speed improvement.

See also https://github.com/wordpress-mobile/WordPress-iOS/pull/17701#pullrequestreview-841415220

**Comment by pachlava** [comment]
> Definitely not for this PR but as a conversation starter, what do you think about removing that condition, e.g. to go to ProductsScreen, do this directly:

Good idea @jostnes ! At the moment, I see no reason not to do this. Added this is as a task [here](pdcxQM-fS-p2#comment-276) (not assigned so far)

**Comment by pachlava** [comment]
After some thought (and also after seeing how outdated the code became after two weeks of being stale) I decided to cancel this PR in favour of defining the default minimal timeout directly in the `ScreenObject`.

**Pull request closed without merging**
