### PR TITLE
[Tablet Products] Show product search in split view

### LINKED ISSUE #12260: [Design review] Products tab: update product search to show product list in the primary column and product form in the secondary column
Ref: Joe's comment pfoUAQ-iv-p2#comment-227 / w3JBReW1UJesCf02sj43kR-fi-1894_11886

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #12260 

## Why

As in Joe's comment pfoUAQ-iv-p2#comment-227 / w3JBReW1UJesCf02sj43kR-fi-1894_11886 for a more significant UX change:

> Searching for a product and opening it in a modal feels particularly strange on tablet. I’d like us to think about opening searched products in the same way as from the main list. Do you have any historical context for why we chose to do it like this in the first place?

I implemented the first version and showed Joe in person, and confirmed the UX.

## How

To show product search in a split view similar to the product list, `primaryNavigationController.viewControllers` is updated from the search CTAs - start and end - in `ProductsSplitViewCoordinator`.

There are a few tricky scenarios since the search view uses generics to be shared in a few screens other than product search:

- When canceling the search, the primary column should go back to the product list:
  - Opened up `cancel(from:)` in `SearchUICommand` protocol and implemented this in `ProductSearchUICommand`
- Cell doesn’t stay selected after switching all/SKU:
  - With the split view support, new parameters were added to `SearchViewController`:
    - `selectedObject: AnyPublisher<Command.ResultsControllerModel.ReadOnlyType?, Never>?` an optional observable of the selected object, so that the search results can be selected other than the tap gesture (e.g. auto-selection on the first product in expanded mode, updating selected row after data reload). This is `nil` by default for any other search screens that don't have split view support
    - `isSelectedObject` an optional function to compare two generic objects, so that the search view can compare the selected object from the observable and the currently selected object in the table view
- Cell is deselected briefly before it stays selected again in split view:
  - Added `shouldDeselectSearchResultOnSelection` in `SearchUICommand` protocol and implemented this in `ProductSearchUICommand` to return false with default implementation to return true
- Expanded —> collapsed —> expanded scenario, because the primary column can now be either `ProductsViewController` or `SearchViewController`:
  - `ProductsSplitViewCoordinator.showEmptyViewOrFirstProduct` was updated to show the first product for each case
  - `ProductsSplitViewCoordinator.willNavigateFromTheLastSecondaryViewControllerToProductListInCollapsedMode` was updated to include the search case
- Navigation bar disappears after cancelling search because `SearchViewController` sets the navigation bar to be hidden and when it's recovered in `viewWillDisappear` the navigation controller is already `nil`:
  - `primaryNavigationController.setNavigationBarHidden(false, animated: true)` is called explicitly when the search is canceled in `ProductsSplitViewCoordinator`
- The search cancel button next to the search bar shows the default title "Button" from the xib briefly before it's set to "Cancel":
  - The title configuration is in search's `viewDidLoad`, and might be too late when the view controller is replacing a navigation controller's root. I removed the default title in https://github.com/woocommerce/woocommerce-ios/pull/12261/commits/23cfad41d6d03f52417ad90fa05c4b39bd5c3b1d and it looks fine now

## Testing instructions

Prerequisite: the device/simulator allows switching between expanded and collapsed states like a tablet

- [x] @jaclync tests on iPhone
- [x] @jaclync tests on other search screens to ensure the same behavior

---

- Launch the app
- Go to the products tab in expanded mode
- Tap on the search icon in the primary column navigation bar --> the product search should be shown in the primary view while the secondary view shows the same product form. If the product in the secondary view is in the product search results, it should be selected
- Enter a query to search for products --> if the product in the secondary view is in the product search results, it should be selected
- Make some changes to the product form in the secondary view
- Select a different product from the search results --> a discard changes alert should be shown
- Tap `Discard changes` --> it should show the selected product in the secondary view
- Tap `Cancel` in the primary navigation bar to cancel search --> it should show the product list in the primary view. if the product in the secondary view is in the product list, it should be selected

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/1945542/ce00a4af-9e7d-45c9-bfc3-fe25fea8a890

https://github.com/woocommerce/woocommerce-ios/assets/1945542/de78f735-2d27-4cf3-bdd4-30316581c30e

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by bozidarsevo** [comment]
While watching the video in description I noticed a strange "glitch", for a split second the cancel button says "Button". It is not visible probably for users but it is strange:
Screenshot 2024-03-12 at 10 10 36

**Comment by jaclync** [comment]
> While watching the video in description I noticed a strange "glitch", for a split second the cancel button says "Button". It is not visible probably for users but it is strange:
> Screenshot 2024-03-12 at 10 10 36

Great catch! 🦅 👀  I noticed this after writing the PR description and fixed this in the last commit https://github.com/woocommerce/woocommerce-ios/pull/12261/commits/23cfad41d6d03f52417ad90fa05c4b39bd5c3b1d. I've updated the screencasts in the PR description to reflect this change.

**Review by bozidarsevo — APPROVED** [review]

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/190">17.8</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
