### PR TITLE
Blaze: Update budget for evergreen campaigns

### LINKED ISSUE #13603: Blaze campaign item: Update budget field for evergreen campaigns
We need to display weekly budget for evergreen campaigns. Currently these campaigns display the total budget for the year.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #13603 

## Description

This PR updates the budget field displayed on the Blaze campaign list items to support evergreen campaigns. Specifically:
- Updated the title of the field to Total budget for non-evergreen campaigns and Weekly budget for evergreen ones.
- Calculate the weekly budget to be displayed for evergreen campaigns.
- Add "$" in the budget field following Android.

## Steps to reproduce

- Log in to a store eligible for Blaze.
- Create a non evergreen campaign and an evergreen one if your store hasn't had any campaign created yet.
- Navigate to the Menu tab and select Blaze.
- Confirm that the budget field on non-evergreen campaigns display the total amount budget evergreen campaigns display weekly budget. In both cases, the amounts are displayed with a "$" sign.

## Screenshots

Before | After 
--- | ---
 | 

---
- [x]  I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [ ] This PR includes refactoring; smoke testing of the entire section is needed.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/218">20.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by selanthiraiyan — APPROVED** [review]
This works as described. 🚢 

---

Not related to this PR

I noticed a minor alignment issue. The texts are not aligned vertically when comparing an evergreen campaign cell and a normal campaign cell. 



Notice that the Clicks and Total/Weekly budget texts in the two cells are not vertically aligned. 

I am not sure whether the misalignment is worth our effort to fix it. What do you think?

**Comment by itsmeichigo** [comment]
@selanthiraiyan Great catch! I added a fix in 90939edc3d707ca72ee41926fc71ea49ab87eb58 to align the columns again. The campaign list should now look like this:



LMK if you have any other comments, I'll address them in a subsequent PR. I'll enable auto-merge for this PR now.

**Comment by itsmeichigo** [comment]
Great catch @selanthiraiyan! I attempted to add a few commits to fix the layout but it seems the layout is a bit broken in some cases. I'll target this PR to the next release to have some time to update the layout.

**Comment by itsmeichigo** [comment]
@selanthiraiyan I added a new reusable view `CollapsibleHStack` to help with the problem with using `fixedSize` of the budget views. Please give this PR another look when you can, thanks!

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by itsmeichigo** [comment]
@selanthiraiyan I updated the campaign item layout following the discussion with Joe [p1723791455674239-slack-C0354HSNUJH] The campaign list should now look like this:



Also, to avoid messing up the layout, I removed the `fixedSize` modifier on the stats labels and set 1-line limit instead. In cases of long text (e.g. translations) and small width, the labels might be cut off at the end with an ellipsis. This is a trade-off for the two-column layout.

This PR is ready for another look when you can.

**Review by selanthiraiyan — APPROVED** [review]
Thanks for initiating the design discussion and making the updates, Huong! The new design looks clean. 👏 

The PR still LGTM. :shipit:

**Pull request merged**
