### PR TITLE
Products (M3): Add a new Product Category

### LINKED ISSUE #2000: Edit Products: Manage Product Categories
This will need to be broken down to a list of tasks/features that should be built. 

## Task Breakdown

The task breakdown is in https://github.com/woocommerce/woocommerce-ios/issues/2000#issuecomment-602852371.

### PR DESCRIPTION
**Pull request by pmusolino**
Resolves #2000 

## Description
This PR implements the last part for completing the management of Product Categories (part of Products Milestone 3). In particular, in this PR it's possible to create a new product category and to select a parent category.

## Changes
- The `addCloseNavigationBarButton:` method helper now accept also a custom title.
- Implemented the `AddProductCategoryViewController`
- Implemented the `ProductParentCategoriesViewController`
- `ProductCategoryListViewController` now contains the new “Add Button” on top of the view.
- Implemented a new method `addAndSelectedNewCategory:` in `ProductCategoryListViewModel`
- `TextFieldTableViewCell` now contains a new method `resignFirstResponder:`

## Testing
1. Open a product with or without product categories
2. Open the Product Categories screen
3. Tap "Add Category" button on top
4. Try to create a new category without parent category -> When it's saved, you will see it in category list selected. Save the product and make sure that it will be updated correctly.
5. Try to create a new category with parent category -> The new parent category should be selected in "New category" screen. Save the product and make sure that it will be updated correctly.
6. Try to create a new category where the title it's just a space ` `. -> Make sure to see an error notice which appears on the screen, and where you are able to retry.

## Add Product Category in action (GIF)
add product category

## Screenshots (dark mode enabled)
| Categories             |  Add Category | Select Parent Category |
:-------------------------:|:-------------------------:|:-------------------------:
Simulator Screen Shot - iPhone 11 Pro - 2020-06-23 at 18 31 01 | Simulator Screen Shot - iPhone 11 Pro - 2020-06-23 at 18 31 12 | Simulator Screen Shot - iPhone 11 Pro - 2020-06-23 at 18 31 17

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pmusolino** [comment]
Thank you so much @jaclync for your review. I implemented all your suggestions.

I also added the disclosure indicator.

**Comment by pmusolino** [comment]
Thank you @Garance91540 for your review!

> Additionally, I think we should give more guidance to the users on the error so they can easily fix it.

I'd say this would be ideal, but our API doesn't return the specific reason why the API failed. They return a generic error, which is not really readable from a user. I added it in the description, but I'm not sure it's useful for the end-user. I'd say that in this case, we should show a generic error message until our API endpoints return better error messages for the users (but, they should also be localized).

**Comment by Garance91540** [comment]
@pmusolino can we make this request to get more information on error cases from the API somewhere? 

Until this is possible, I think what you have work!

**Comment by pmusolino** [comment]
Thanks @Garance91540. I opened a discussion here p7bje6-2c4. Going deeper, I noticed that I can handle the error, but I'd like to handle all the possible scenario 👍

**Pull request merged**
