### PR TITLE
Blaze: Fix campaign creation on devices with non-Western Arabic number formatting system

### LINKED ISSUE #13657: [Blaze] Update campaign creation request to respect the ISO date format
Android issue - https://github.com/woocommerce/woocommerce-android/issues/12370

Internal - p1724072373257359-slack-C03L1NF1EA3

Currently, when sending the campaign creation request, the app sends the date formatted using the device's locale, which might result when using some languages such as Arabic in using digits other than regular Arabic numerals (for example: `٢٠٢٤-٠٧-٠٨`), which is not a standard ISO date format.

### PR DESCRIPTION
**Pull request by hafizrahman**
Closes: #13657 

## Description

The API for campaign creation expects standard ISO format using numberal system known as [Western Arabic](https://en.wikipedia.org/wiki/Arabic_numerals) (aka these numbers: 1234567890)

However, when a device was set to use a different locale, e.g: Arabic, it sent [Eastern Arabic](https://en.wikipedia.org/wiki/Eastern_Arabic_numerals) numerals which the servers couldn't handle. This was because during the `campaign.toDictionary()` conversion, the `dateFormatter.locale` value followed the device locale, which then created Eastern Arabic numbers in the dictionary.

This PR updates the formatting to use the existing formatter `Defaults.yearMonthDateFormatter`. The formatter forces the use of `en_US_POSIX` locale, which uses Western Arabic system, so the resulting formatting in the dictionary matches the expectation.

## Steps to reproduce

The easiest way to check is probably to debug and ensure unit tests are correct.

1. Set device language to Arabic,
2. in Networking > Requests > DotcomRequest, set a breakpoint on line 58 `self.parameters = parameters`
3. Start Woo app,
4. Go to product details, pick a product, and create a Blaze Campaign,
5. Wait on the Blaze Confirm Payment view, and enable the Debugger if you haven't,
6. Create the Campaign,
7. Once the breakpoint hits, check the content of `parameters` (e.g: using `po parameters` in the Debugger Console) and ensure that `start_date` and `end_date` value.
8. Ensure campaign is created properly.

Finally also check `BlazeRemoteTests` and ensure everything passes, including the newly added test `test_createCampaign_sends_correctly_formatted_dates_regardless_of_locale()`

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by itsmeichigo** [comment]
@hafizrahman I found that there's a similar error with the forecasted impression request too. Can you add a fix for that as well?

**Comment by hafizrahman** [comment]
Good catch @itsmeichigo , I added the handling for that as well. Good for another review, thanks!

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/219">20.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by itsmeichigo — APPROVED** [review]
Thanks for the update, this looks good now :shipit:

**Pull request merged**
