### PR TITLE
[Shipping Labels] Adding a package UI - WooShippingTabView UI component

### PR DESCRIPTION
**Pull request by bozidarsevo**
Part of #13551

Created a UI component `WooShippingTabView` that will be used in "Carrier" tab of Adding a package flow. The component itself is quite generic so if needed we can make it even more generic so it can be used in other parts of the app.

## Screenshots

Preview of WooShippingTabView in various size categories:

| Light    | Dark |
| -------- | ------- |
| Screenshot 2024-10-21 at 18 23 34  | Screenshot 2024-10-21 at 18 24 09    |

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by bozidarsevo** [comment]
@rachelmcr @toupper I did not find in the current code base similar UI component so I created this one. It is more or less generic and if needed we can move it from Shipping part to general Woo UI components if needed.
If there is some similar component that we can reuse let me know before I merge this one!
Thanks

**Comment by rachelmcr** [comment]
Have you already looked at the reusable `TopTabView` component? I haven't closely compared that with the new component in this PR, but the UI looks similar.

**Comment by bozidarsevo** [comment]
> `TopTabView` component

Tnx, looks ok, but it is missing:
- option to set icon/image
- ability to specify/inject (un)selected color
- ability to specify/inject fonts for text for (un)selected state

Would it be better for me to add those adaptations to `TopTabView` so it we can reuse it for our Carrier packages or use this one I created?

**Comment by rachelmcr** [comment]
> Would it be better for me to add those adaptations to TopTabView so it we can reuse it for our Carrier packages or use this one I created?

I would add those to `TopTabView`. They're all pretty understandable tweaks to the design without affecting its primary purpose or behavior, so IMO they are reasonable changes to make to the reusable component.

**Comment by bozidarsevo** [comment]
> > Would it be better for me to add those adaptations to TopTabView so it we can reuse it for our Carrier packages or use this one I created?
> 
> I would add those to `TopTabView`. They're all pretty understandable tweaks to the design without affecting its primary purpose or behavior, so IMO they are reasonable changes to make to the reusable component.

I agree!
Thanks for feedback and I will do it in a separate PR!

**Pull request closed without merging**
