### PR TITLE
Add associated domain entitlement for wordpress.com

### PR DESCRIPTION
**Pull request by ealeksandrov**
## Description

This PR adds associated domain entitlement, so we have password autofill filter/suggestion on `wordpress.com` domain.

Docs:
- https://developer.apple.com/documentation/security/password_autofill/
- https://developer.apple.com/documentation/xcode/supporting-associated-domains
- https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_associated-domains

### Blockers
- [x] update `apple-app-site-association` by @astralbodies (p1636641097264100-slack-C6H8C3G23)
- [x] add "Associated Domains" capability on WC App IDs by @AliSoftware (pdnsEh-3L-p2)

## Test

> Apple’s Content Delivery Network requests the apple-app-site-association file for your domain within 24 hours. Devices check for updates approximately once per week after app installation.

1. Delete previous version of the app from device. App Store updates won't need this step.
2. Run local build or download installable build from comments below.
3. Make sure you see suggested profile on Log In screen.
4. Tap on "key" icon above keyboard -> choose your password manager.
5. Verify that you see filtered wp.com accounts in the list of all suggestions.
6. Complete login flow by selecting an account from suggestions.

---
Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by AliSoftware** [comment]
Just triggered Installable Build after updating the entitlement on the App Identifier in ADC's Enterprise Account, regenerating the corresponding profile, and updating `fastlane match`.

According to the logs in the Installable Build CI job, `match` installed the Provisioning Profile with UUID `e7aeb2f3-4c5e-4a88-a279-44a01c0dd2f8`, and when comparing with the profile with the same UUID installed on my machine I see that my local one (also installed via `match`) has the associated domains entitlements as expected… so hopefully all should be good.

```
$ pprof e7aeb2f3-4c5e-4a88-a279-44a01c0dd2f8
- name: match InHouse com.automattic.alpha.woocommerce
- uuid: e7aeb2f3-4c5e-4a88-a279-44a01c0dd2f8
- app_id_name: WooCommerce iOS Alpha
- app_id_prefix: ["99KV9Z6BKV"]
- creation_date: 2021-11-16T11:50:02+00:00
- expiration_date: 2022-11-16T11:50:02+00:00
- ttl: 365
- team_ids: ["99KV9Z6BKV"]
- team_name: Automattic, Inc.
- Entitlements:
   - com.apple.developer.associated-domains: *
   - application-identifier: 99KV9Z6BKV.com.automattic.alpha.woocommerce
   - keychain-access-groups: ["99KV9Z6BKV.*", "com.apple.token"]
   - get-task-allow: false
   - com.apple.developer.team-identifier: 99KV9Z6BKV
   - com.apple.developer.ubiquity-kvstore-identifier: 99KV9Z6BKV.*
   - com.apple.developer.icloud-services: *
   - com.apple.developer.icloud-container-environment: ["Production", "Development"]
   - com.apple.developer.icloud-container-identifiers: ["iCloud.com.automattic.alpha.woocommerce"]
   - com.apple.developer.icloud-container-development-container-identifiers: ["iCloud.com.automattic.alpha.woocommerce"]
   - com.apple.developer.ubiquity-container-identifiers: ["iCloud.com.automattic.alpha.woocommerce"]
   - aps-environment: production
- 1 Developer Certificates
- 0 Provisioned Devices
- Provision all devices: true
```

**Comment by rachelmcr** [comment]
I deleted the app and installed the installable build on my device, but it's not working for me. (I confirmed that I have multiple saved passwords for `wordpress.com` and I get the expected autofill behavior in the WordPress app on the same device.)

The changes look like they should do what we need, but I've checked all over and can't figure out what I'm missing. @ealeksandrov Do you know of anything more I might need to do to get this working?

**Review by rachelmcr — APPROVED** [review]
I tested this again running a local build on the same device I tested earlier, and this time it worked exactly as expected. 👍 

It might be worth re-testing/re-checking the installable build setup on the back end to make sure it's all working for those builds, but these changes look good.

**Comment by ealeksandrov** [comment]
Thanks for testing! I've checked installable build on 2 devices - password autofill works well on first try. I think it's a caching issue.

I'll merge it now and let's check installable builds again after some time.

**Pull request merged**
