### PR TITLE
Product details: Hide subscription product type options when site is ineligible for subscription products

### LINKED ISSUE #11459: [Product details] Option to change product to subscription type appears when Subscriptions extension not active
Even if my store doesn't have the Subscriptions extension installed or active, I see the option in product details to change the product to a subscription type:

If I choose a subscription type there, it changes what I see in the form to the expected subscription fields. But if I try to save my changes, I get an error in the app logs and on screen:

> ⛔️ Error updating Product: unknown(error: Yosemite.AnyError(error: Dotcom Error: [rest_invalid_param] Invalid parameter(s): type))

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #11459

## Description

Currently, the product type bottom sheet displays the options for subscription product types even when a site doesn't have the Subscription Products extension.

This PR fixes that by unifying the logic for the product type bottom sheet contents. Changes include:
- Updated `ProductTypeBottomSheetListSelectorCommand`'s initializer:
  - Injected the eligibility checker for subscription products.
  - Replaced `selected` param with a new source value to determine if the bottom sheet is for product creation or edit.
- Made `ProductTypeBottomSheetListSelectorCommand` data a computed variable instead of a globally mutable property.
- Updated the calls to `ProductTypeBottomSheetListSelectorCommand` from the `AddProductCoordinator` and `ProductFormViewController` accordingly.

## Steps to reproduce

- Install the WooCommerce Subscription extension to your test store if you haven't already.
- Build and run the app. Navigate to the Products tab and select "+" > Add manually to add a new product.
- Confirm that the product type bottom sheet contains subscription and variable subscription types.
- Create a product or open an existing product. Open the product detail form, tap the Product Type row and confirm that the product type bottom sheet contains subscription and variable subscription types.
- Switch to a different store without the WooCommerce Subscription extension or deactivate the extension on your test store.
- Repeat the above steps to confirm that subscription and variable subscription product types are not available in either the product creation bottom sheet or the product edit form.

## Screenshots

Store with WooCommerce Subscription | Store without WooCommerce Subscription 
--- | ---
 | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/209">19.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by hafizrahman — APPROVED** [review]
Thanks for the fix! The refactor also improves things nicely. 💯

**Comment by hafizrahman** [comment]
Maybe there's still time to put it back to milestone 19.1 and merge now?

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/209">19.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by itsmeichigo** [comment]
Thanks Hafiz for the review! I updated the release note and the milestone, will enable auto-merge now!

**Pull request merged**
