### PR TITLE
Make the app compatible with Xcode 14

### PR DESCRIPTION
**Pull request by crazytonyli**
### Description

Here are the fixed required for the project to run on Xcode 14:
- https://github.com/woocommerce/woocommerce-ios/issues/7393 is a SwiftUI backward compatibility issue (surprise surprise), which is resolved by adding a workaround to show/hide navigation bar using UIKit.
- Here is a very strange issue only happens in UI test on CI. I had to explicitly make [a text field](https://github.com/woocommerce/woocommerce-ios/pull/7371/files#diff-e1ee95623c8f8278d8814fed88be69d800c8ad94be3cbb963a1be585ad3fa979R35) loose keyboard focus by [changing the binding variable](https://github.com/woocommerce/woocommerce-ios/pull/7371/files#diff-e1ee95623c8f8278d8814fed88be69d800c8ad94be3cbb963a1be585ad3fa979R56), for the other "add-shipping-name-field" text field to gain keyboard focus.
- `DateFormatter`'s output for a specific date format has changed in iOS 16, the workaround is [changing the assertion based on the OS version](https://github.com/woocommerce/woocommerce-ios/pull/7371/files#diff-4842f252045323c202ab617819b20f06828e29929f47cbac2cda478c8c0f5a4dR345).

### Testing instructions
No test required, as this PR goes to the `xcode-14` branch.

### CODE REVIEW

**Comment by crazytonyli** [comment]
The test failures on this PR is a bit strange... UI tests on iPhone and iPad pass on my own mac, whereas they fail reliably on CI. Unit tests fail on my own mac too, but more than just the two cases on CI.

**Comment by crazytonyli** [comment]
Similar to https://github.com/wordpress-mobile/WordPress-iOS/pull/19119, I'll summarize the status of UI and unit tests. I'll come back once next beta is out.

- Two unit tests fail on CI:
  * one failure due to a `DataFormatter` bug in Xcode beta. "Monday, Jan 3 at 1:00 AM" is returned when using `EEEE, MMM d, h:mm a` format
  * the other is also formatter related. "lbs" isn't translated to localized "磅" in Chinese
- UI tests fail due to https://github.com/woocommerce/woocommerce-ios/issues/7393

**Comment by crazytonyli** [comment]
> the other is also formatter related. "lbs" isn't translated to localized "磅" in Chinese

This issue is fixed in beta 5.

**Comment by oguzkocer** [comment]
@crazytonyli I am updating the milestone dates for WCiOS & WCAndroid. Since this PR is currently a draft, I removed the `10.0` milestone from it. I suggest waiting to add the milestone until you're ready to merge the PR. Sorry about the extra hassle.

**Comment by crazytonyli** [comment]
@oguzkocer No problem. Thanks for the reminder. I should've removed the milestone when I turned this PR to draft.

**Comment by crazytonyli** [comment]
> the other is also formatter related. "lbs" isn't translated to localized "磅" in Chinese

This issue is fixed in Xcode 14 beta 6. Given Apple is about to release iOS 16 next week, I doubt the other two issues are going to be fixed in Xcode 14 GM. I'll start working on a fix.

**Comment by itsmeichigo** [comment]
Just commenting to note that this PR has changes that will also fix #7091, thanks @crazytonyli.

**Comment by crazytonyli** [comment]
Hi @mokagio , this PR is ready for review. Thanks!

**Comment by mokagio** [comment]
Spooky that the unit tests failed in CI. I retried them and they failed again, in the same way. Trying to replicate locally...

**Review by mokagio — APPROVED** [review]
Third time lucky: 

image

The flaky test is `test_loading_indicator_gets_disabled_after_the_network_operation_completes`. In the successful run, it took >2s to run. That it's so slow is a concern and something to investigate further.

image

**Comment by crazytonyli** [comment]
@mokagio Thanks for getting the flaky test passed. https://github.com/woocommerce/woocommerce-ios/pull/7719 should fix this flaky test. 🤞

**Pull request merged**
