### PR TITLE
Order Details → Show Item Total on the Right Instead of Quantity

### PR DESCRIPTION
**Pull request by shiki**
⚠️ Requires #2381 to be merged first.

Refs #2281. 

### Order Details

This swaps the quantity shown on the right side with the item total. The header also now just says “Products” instead of “Product” and “QTY” on the right. According to #2281, the header should be using a white background. I'll get to that in a follow-up PR. 

There are no changes in the layout. 

@Garance91540 Should the font sizes of the SKU and "Quantity x Price" be bigger? I couldn't find an existing style of that in the app so I wasn't sure. 

Before | After 
--------|-------
 image    |       image

After (Dark) | After (Large)
--------|-------
Simulator Screen Shot - iPhone 11 Dark - 2020-06-03 at 13 18 50        |     image

### Refunded Products

Since the Refunded Products view is using the same components as the Order Details, it is also affected by the changes too. 

Before | After 
--------|-------
image        |     image

@Garance91540 Please let me know if this is okay or not. 

## Testing

1. Navigate to a processing Order.
2. Confirm that the price is on the right side.
3. Tap on Begin Fulfillment. 
4. Confirm that the quantity is still on the right side. 
5. Navigate to an Order with a refund. 
6. Tap on the Refunded Products
7. Confirm that the price is shown on the right. 

## Reviewing 

Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] If it's feasible, I have added unit tests. 
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by Garance91540** [comment]
> The header also now just says “Products” instead of “Product” and “QTY” on the right

One quick note on this: actually the desired behavior is to have the header be "Product" when there's only one product in the orders and "Products" as soon as there's more than one

**Comment by shiki** [comment]
> I'm not sure why we'd want to show SKU in the product rows actually, I think it's kind of useless at this level and it overcrowds the page. What do you think?

@Garance91540 It's always been there so I didn't touch it. I personally have no idea how SKUs are used. 😬 Should it be removed?

**Comment by Garance91540** [comment]
>  😬 Should it be removed?
Yep let's remove! you can see them when you select the product row

**Comment by shiki** [comment]
Thank you, @jaclync. Excellent catch on the comments and method names. That was embarrassing. 🙈 Fixed in 5524620bd3d1a251d2536fcdf161e12fda3930b1, e973d123b46dc0114825693dd3cdbf4de904daca, and a349acec1967315fab82a79b8e640459b5b2046b.

@Garance91540 I'll remove the SKU on a separate PR.

**Comment by designsimply** [comment]
At first, I was confused because I thought that Fulfill Order screen should also show the price and not the quantity but then I re-read the instructions and found that's the expected behavior. 🙂 I wanted to drop in some screenshots from my test for reference.

IMG_3784 IMG_3785 IMG_3786

<p style="clear:both;"><sup>Tested with Woo iOS 4.5.0.2 TestFlight beta on iPhone 6S iOS 13.3.1.</sup></p>

**Pull request merged**
