### PR TITLE
Update Embassy to latest version.

### PR DESCRIPTION
**Pull request by hafizrahman**
### Description

When testing `WooCommerceScreenshots`, I consistently run into this issue:

image

```
Thread 1: Fatal error: self must be a properly aligned pointer for types Pointee and T
```

The problem seems to stem from using an older version of Embassy, and upgrading the version makes the error go away.

## Steps to reproduce

1. Use `trunk` branch,
2. Set target to `WooComerceScreenshots`,
3. Find `func testScreenshots()` in `WooComerceScreenshots`, and run that test,
4. Ensure that the same fatal error as the one in description appears,
5. Switch to this PR's branch `fix/spm-embassy-update-version`,
6. Retry step 3 again,
7. Ensure that the fatal error does not appear again.
8. You will likely see a different error now: `fatalError("Unable to handle action: \(action.identifier) \(String(describing: action))")` This is expected as there are actions that need to be mocked for `WooCommerceScreenshots` to work correctly. They will be handled in a separate PR.

## Testing information

I tested this in XCode 15.4, using an iPhone 11 Pro Max Simulator with iOS 16.0.

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by selanthiraiyan — APPROVED** [review]
Thanks for working on this. 

I am not sure whether the UI tests depend on this library as well. Good to merge once the UI tests pass in CI. 🚢

**Comment by hafizrahman** [comment]
> I am not sure whether the UI tests depend on this library as well.

- According to [the readme](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/WooCommerceUITests/README.md), `WooCommerceUITests` use `WireMock` instead
- As far as I can check, `Embassy` is only used here in `WooCommerceScreenshots`
- `Embassy` is used especially to serve test images, while the UI tests as far as I can tell do not deal with test images

So, afaik, this is only affecting `WooCommerceScreenshots` and likely a safe change.

**Comment by hafizrahman** [comment]
Added https://github.com/woocommerce/woocommerce-ios/pull/14309/commits/addd8794a567e09cf16e87ba0aef22e9fb53ebd7 to temporarily disable the flaky login UI test (issue logged in https://github.com/woocommerce/woocommerce-ios/issues/14314)

**Pull request merged**
