### PR TITLE
A quick example using the badgeValue property

### LINKED ISSUE #1576: Product List: Orders badge appears on wrong tab icon in RTL
**Describe the bug**

When using an RTL language (e.g. Arabic) the orders badge appears on the Products icon instead of the Orders icon in the bottom nav.

**To Reproduce**
1. Open the Woo app and confirm you see the orders badge on the Order icon (for orders with the Processing status).
2. Go to the Settings app > Woo > Preferred Language and select an RTL language for the Woo app (e.g. Arabic or Hebrew).
3. Open the Woo app again and note that the orders badge appears on the Products icon instead.

**Screenshots**

**Expected behavior**
The orders badge should appear on the Orders icon in the bottom nav.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.2.3
- WooCommerce iOS version: 3.2.0.1

### LINKED ISSUE #1601: Orders tab: research using `tabbaritem.badgeValue`
**Is your feature request related to a problem? Please describe.**
We use a custom solution. We've had numerous PRs trying to position the badge, adjust the font size, and modify the color. The border and border width have also been a problem.

**Describe the solution you'd like**
I would like to research and find out: Why we aren't using `tabbaritem.badgeValue` for the new order count on the Orders tab? It's marked as a [Legacy Customization](https://developer.apple.com/documentation/uikit/uitabbaritem/legacy_customizations) by Apple, but that is not the same as deprecating the API. When checking Xcode's API documentation, the `badgeValue` is marked as available since iOS 2.0, but (importantly) is not marked as deprecated.

**Describe alternatives you've considered**
We are using an alternative right now. 

**Additional context**
I have put together a draft PR that can be tested for the proposed changes. Here are some quick example screenshots using the `UITabBarItem`'s `badgeValue` property on iPhone 11 Pro Max:

cc: @ctarda and @kyleaparker, who also worked on the orders tab badge

### PR DESCRIPTION
**Pull request by mindgraffiti**
Fixes #1576
Fixes #1601 

Since this proposal has dev & design support, I have converted the draft PR to a normal PR.

~This PR is meant to demo the order badge using the `badgeValue` property found in `UITabBarItem`. It's not merge-worthy right now because it doesn't remove the manual orderBadge creation code. If this proposal is approved, I will change this to a real PR and make sure the custom code is removed.~

(Kylea let me know if you need any other screenshot types.)

### Changes
- removes any references to the `OrdersBadgeController`
- replaces them with the `badgeValue` property in `UITabBarItem`
- deletes the custom control, `OrdersBadgeController`

### To test
- run the app on any device
- transition from portrait to landscape and back again to check the orientation of the badge
- use a RTL language, activate Products, and ensure the badge remains on the Orders tab (instead of Products)
- transition from light mode to dark mode
- try to break it in general

---

Original testing instructions

- [x] Does is work for all screen sizes? Previously we had issues with the iPad's badge position and iPhone 8's badge position, when using the custom badge code.
- [x] Does it transition colors correctly between dark mode and light mode?
- [x] Does it pass design standards? Note that the `badgeValue` property does not allow a border and it does not allow us to control the positioning.

**iPhone 11 Pro Max**

Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-10 at 11 34 19

**iPhone 8**
Select an image to see a larger version.

| Light Mode | Dark Mode | 
| --- | --- |
|  |  |

<kbd>Simulator Screen Shot - iPhone 8 - 2019-12-10 at 11 52 48</kbd>

<kbd>Simulator Screen Shot - iPhone 8 - 2019-12-10 at 11 53 29</kbd>

**iPad Pro (10.5 inch)**
Select an image to see a larger version.

<kbd></kbd>

<kbd>Simulator Screen Shot - iPad Pro (10 5-inch) - 2019-12-10 at 11 59 22</kbd>

**iPad Pro (10.5 inch) with 9+ orders**
<kbd></kbd>

<kbd>Simulator Screen Shot - iPad Pro (10 5-inch) - 2019-12-10 at 12 06 18</kbd>

**iPhone Xs**
<kbd></kbd>

<kbd>Simulator Screen Shot - iPhone Xs - 2019-12-10 at 12 01 47</kbd>

**9+ Orders on iPhone Xs**
<kbd></kbd>

<kbd>Simulator Screen Shot - iPhone Xs - 2019-12-10 at 12 03 33</kbd>

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ctarda** [comment]
I think simpler is better, and simple and using a stock component/API is even better. In this case, in particular, getting the badge right has been painful, maybe letting UIKit take care of it is a good idea.

When it comes to the code, it looks good. I see one warning though:

```
/woocommerce-ios/WooCommerce/Classes/ViewRelated/OrdersBadgeController.swift:43:9: Handle unknown values using "@unknown default"
```

And the mandatory screenshots:

iPhone 11:



iPhone 11 Pro Max:




iPad Pro 11"

**Comment by mindgraffiti** [comment]
@ctarda the warning is new and happens on `develop` too. I haven't looked into it yet but I haven't forgotten about it :)

**Comment by pmusolino** [comment]
Look absolutely interesting for me. After testing, I confirm which this solve also this issue 💯 https://github.com/woocommerce/woocommerce-ios/issues/1576

**Comment by mindgraffiti** [comment]
@kyleaparker I trust your taste in design. You've got the final call on this one. I couldn't remember _why_ we originally went with custom code so that answers that question. 🙂 

You're right, the `badgeValue` handles the positioning automatically and everywhere, so the up side is no more encounters with bugs. The downside is that we can't control how it's positioned. If you prefer that we stick with our custom solution (which **does** give us some control over the positioning) I'll close this PR and make sure to add comments in the code so it's not forgotten again.

**Comment by kyleaparker** [comment]
It feels like we _should_ be using this if it's the default component that comes with iOS

**Comment by mindgraffiti** [comment]
**Update on design comments:** @kyleaparker highlighted that the native badge positioning does not look as nice on iPads. Our users rarely run the app on an iPad, so we're going to adopt the native badge after all.

**Pull request merged**
