### PR TITLE
Products & Product Variation: Allow alternative type for purchasable

### LINKED ISSUE #7510: Swift.DecodingError on purchasable products. Expected to decode Bool but found a Number.
Ref: p4a5px-2PC-p2

Some plugins seem to return `0` or  `1` rather than the expected  boolean for the [purchasable API response](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties). This leads to problems loading content within the app as data can't be decoded:

```
let purchasable = try container.decode(Bool.self, forKey: .purchasable)
```

We can attempt and offer an alternative decoding if the expected one fails. For example, we offer alternative types for `salePrice` as is known that plugins alter this field:

```
        // Even though a plain install of WooCommerce Core provides string values,
        // some plugins alter the field value from String to Int or Decimal.
        let salePrice = container.failsafeDecodeIfPresent(targetType: String.self,
                                                          forKey: .salePrice,
                                                          shouldDecodeTargetTypeFirst: false,
                                                          alternativeTypes: [
                                                            .string(transform: { (onSale && $0.isEmpty) ? "0" : $0 }),
                                                            .decimal(transform: { NSDecimalNumber(decimal: $0).stringValue })])
            ?? ""
```

### PR DESCRIPTION
**Pull request by reginabally**
Closes: #7510 

## Description

Some plugins alter the field value from a boolean to an integer. This causes issues in loading products in the app. As suggested in #7510, we can attempt to offer an alternative decoding if the expected one fails.

### Changes:

* In `Networking/Product` - update decoding of purchasable to accept both Bool and an alternative integer value.
* In `Networking/ProductVariation` - update decoding of purchasable to accept both Bool and an alternative integer value.
* In `Networking.KeyedDecodingContainer+Woo` - add integer support to `alternativeTypes`

## Testing instructions

According to p4a5px-2PC-p2, we found out the [YITH WooCommerce Gift Cards](https://wordpress.org/plugins/yith-woocommerce-gift-cards/) plugin is returning `0` or `1` values for the `purchasable` field. This plugin will be used for this test.

1. Install the [YITH WooCommerce Gift Cards](https://wordpress.org/plugins/yith-woocommerce-gift-cards/) extension on your store
2. Create a gift card at WP Admin > YITH > Gift Cards. Enter an amount (e.g., 10) and any current balance (> 0).
3. Create a new product at WP Admin > Products > Add New.
4. Set the `Product data` to `Gift card` and add any Gift card amounts.
5. Check the product fields via WC REST API using the product ID (e.g., `../wp-json/wc/v3/products/212`). The `purchasable` field should return 1. (Note: if you set the current balance to 0 in step 2, `purchasable` will be 0)
6. In the app, open the Products tab
7. All products should be shown

**Unit test results**

```
Test Suite 'Selected tests' started at 2023-01-20 19:01:00.846
Test Suite 'NetworkingTests.xctest' started at 2023-01-20 19:01:00.847
Test Suite 'ProductMapperTests' started at 2023-01-20 19:01:00.848
Test Case '-[NetworkingTests.ProductMapperTests test_that_product_alternative_types_are_properly_parsed]' started.
2023-01-20 19:01:00.911840+0800 xctest[33045:136105] Message: Tag aztec.htmltag.rootnode invalid

Test Case '-[NetworkingTests.ProductMapperTests test_that_product_alternative_types_are_properly_parsed]' passed (0.075 seconds).
Test Suite 'ProductMapperTests' passed at 2023-01-20 19:01:00.923.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.075 (0.076) seconds
Test Suite 'NetworkingTests.xctest' passed at 2023-01-20 19:01:00.924.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.075 (0.076) seconds
Test Suite 'Selected tests' passed at 2023-01-20 19:01:00.924.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.075 (0.077) seconds
Program ended with exit code: 0
```

## Screenshots

**Before**

**After**

---
- [] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by iamgabrielma — APPROVED** [review]
Thanks for fixing this @reginabally LGTM! 🚢 

Nit: there seems to be some extra spaces [here](https://github.com/woocommerce/woocommerce-ios/blob/9184b0d2421761632bddd0cc348f1551c67c3353/Networking/Networking/Extensions/KeyedDecodingContainer%2BWoo.swift#L60-L62) and [here](https://github.com/woocommerce/woocommerce-ios/blob/9184b0d2421761632bddd0cc348f1551c67c3353/Networking/Networking/Model/Product/Product.swift#L320) (but Lint doesn't complain). An easy way to align these to the rest is to select the block and use `ctrl + I` in Xcode 👍

**Comment by reginabally** [comment]
Thanks again for reviewing my changes, @iamgabrielma! I fixed the indentation issues and added this PR to the release notes. Please have a quick review again when the required checks are complete. Thank you!!

**Comment by hafizrahman** [comment]
Nice work @reginabally ! From the linked post it seems like this affects Android too, do you know if there's an equivalent issue for it?

**Comment by reginabally** [comment]
Thanks, @hafizrahman!

I didn't see any GitHub issue created for WCAndroid. I just tested WCAndroid 12.0-rc-1 with my test site that has the plugin installed, the Products tab didn't show an error, but the number of products shown in the app wasn't complete. The following error was also spotted in the app:

```
[Jan-30 07:12 WP e] API StackTrace: com.android.volley.ParseError: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 15210 path $.data[5].purchasable
at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:99)
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:144)
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 15210 path $.data[5].purchasable
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:225)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
at com.google.gson.Gson.fromJson(Gson.java:991)
at com.google.gson.Gson.fromJson(Gson.java:956)
at com.google.gson.Gson.fromJson(Gson.java:905)
at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:92)
... 3 more
Caused by: java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 15210 path $.data[5].purchasable
at com.google.gson.stream.JsonReader.nextBoolean(JsonReader.java:853)
at com.google.gson.internal.bind.TypeAdapters$3.read(TypeAdapters.java:145)
at com.google.gson.internal.bind.TypeAdapters$3.read(TypeAdapters.java:134)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
... 11 more
```

I will create a GitHub issue for Android.

**Comment by reginabally** [comment]
@hafizrahman Looks like there were two issues filed for this bug: https://github.com/woocommerce/woocommerce-android/issues?q=is%3Aissue+is%3Aopen+purchasable

I should have looked through the issues on the Android repo instead of just checking the comments in the P2 post.

**Pull request merged**
