### PR TITLE
[Mobile Payments] Apply secondary style to cancel button in modal alerts

### LINKED ISSUE #4364: [Mobile Payments] [UI] Apply secondary style to cancel button in modal alerts
Brought up during the review of #4331

120673770-c3413800-c493-11eb-86d9-2b4759e9c1d7-1

### PR DESCRIPTION
**Pull request by koke**
Fixes #4364

This switches the style of the cancel buttons to secondary on the alerts for scanning for readers, when reader is ready, and when it's waiting for a card to be tapped (which seems identical to the previous one).

For this, I introduced a new `.secondaryOnly` action mode to `CardPresentPaymentsModalViewModel`, in which there is only one secondary button and no primary. This feels a bit awkward, but it seemed like the simplest way forward without changing the modals too much.

I also added a bunch of new tests for `CardPresentPaymentsModalViewController` to make sure the visible buttons match what's expected for each action mode.

## To test

1. Without a reader connected, go to an order and tap Collect Payment
2. The alert should display the Cancel button in a secondary style.
3. Tapping Cancel should dismiss the modal
4. Connect to a reader.
5. The alert shown when the reader is ready to collect payment should show the Cancel button in a secondary style.
6. Tapping Cancel should cancel payment

Scanning for reader | Collecting payment
-|-
Screen Shot 2021-06-04 at 13 32 24|Screen Shot 2021-06-04 at 14 00 24

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ctarda — COMMENTED** [review]
It looks like the background color of the cancel button is a bit off. 

Here is how it looks in dark mode:





I will push a commit to change the background color to .backgroundTertiary

**Comment by ctarda** [comment]
Oh boy, it's not that simple. This is a NUXButton, and the background is an image filled with a color.

**Comment by ctarda** [comment]
There is another PR that changes the buttons to regular UIButtons (#4369). We can tackle this one again after #4369 is merged. That would solve all the issues with the buttons

**Review by Garance91540 — APPROVED** [review]
👏

**Comment by ctarda** [comment]
@koke I just pushed an update to integrate the rest of the changes we had already applied to the modal view:
* leading and training padding
* Button size
* Background colors
* Get rid of NUXButton

Plus a new style specific for the cancel button

**Comment by ctarda** [comment]
@koke if this looks good to you, it looks good to me too 😉

**Comment by koke** [comment]
Tested one last time, the new buttons look nice ✨

**Pull request merged**
