### PR TITLE
Merge release/6.6 final to trunk

### PR DESCRIPTION
**Pull request by AliSoftware**
Binary has just been submitted to Apple for review.

This is ready for review but should not be merged until Monday once the app goes live to the AppStore.

### CODE REVIEW

**Review by loremattei — COMMENTED** [review]
@AliSoftware I see changes in the English `Localizable.strings`, but it looks like there are no changes in the translations. Is this expected?

**Comment by loremattei** [comment]
I've just checked GlotPress and it looks like all the translations are available 🤔 
@AliSoftware do you know why we don't have them?

**Comment by AliSoftware** [comment]
Nice catch! Explanation in [the other PR](https://github.com/woocommerce/woocommerce-ios/pull/4203#issuecomment-842198346).

Fixed, withdraw the build submitted Friday and just retriggered a build to submit to Apple with the fix. PR now ready for re-review (but please don't merge this PR until Apple has approved though).

**Comment by AliSoftware** [comment]
@woocommerce/release-managers Apple has approved the new 6.6.0.2 (with the translation issue fixed), and rollout has been started, so this is ready to be reviews/approved and merged

**Review by oguzkocer — APPROVED** [review]

**Pull request merged**
