### PR TITLE
Update project for Xcode 11

### PR DESCRIPTION
**Pull request by ctarda**
This branch incorporates the Zendesk SDK built for Xcode 11 beta 6 and provides support for building the project using Xcode 11 without an conditional compilation.

This should be base branch for any iOS 13 / Xcode 11 specific development

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ctarda** [comment]
Tests fail as the CI job seems to run them with Xcode 10.2, but pass locally (aka “works in my machine”). One more thing to do next week 🤷🏻‍♂️

**Comment by jaclync** [comment]
Re CI: looks like Circle CI has `11.0.0` for Xcode 11 beta 6  https://github.com/woocommerce/woocommerce-ios/blob/develop/.circleci/config.yml#L12 according to https://circleci.com/docs/2.0/testing-ios/

**Review by jaclync — COMMENTED** [review]
I was wondering if the diffs in `ProductDetailsTableViewCell.xib` are necessary? couldn't really tell if the diffs are from opening the xib file of an older version or actual changes?

**Comment by ctarda** [comment]
@mindgraffiti @jaclync I'm upgrading this draft PR to a proper one. Also, pulling @loremattei into the discussion 😊 

Things to have in mind:
- The project does not pass CI @loremattei could you take a look at that, please, I am afraid this is beyond my expertise.
- There seem to be two warnings in our own pods. I think it is safe to expect that those warnings will disappear soon (I am looking at opening PRs in the corresponding repos)
- Zendesk points to a branch but not a proper release. I am not sure if we are completely fine with that, but it also safe to assume that they make a proper release soon(ish)

**Comment by loremattei** [comment]
@ctarda thanks for pinging me! Yeah, CI configuration needs some updates. 
Can I push the updates directly to this branch?

**Comment by ctarda** [comment]
@loremattei please do, we’d really appreciate your help! 🙇

**Review by mindgraffiti — CHANGES_REQUESTED** [review]
Hey Cesar, can you revert the changes to the ProductsDetailView table cell? It looks like it was opened in IB and Xcode made unnecessary changes.

**Review by jaclync — COMMENTED** [review]
LGTM after the diffs on `ProductDetailsTableViewCell.xib` are reset, and CI passes!

**Comment by ctarda** [comment]
Thanks @mindgraffiti @jaclync 

I've just updated the PR, removing the diff to the cell, and updating title and base branch as discussed in this comment: paaHJt-EN-p2/#comment-1423

@loremattei the branch is all yours!

**Review by jaclync — APPROVED** [review]
:shipit: after CI!

**Comment by ctarda** [comment]
Thanks for the updates to the branch @loremattei Would you let us know when it is safe to merge this PR (once approved)?

**Comment by loremattei** [comment]
@ctarda we can merge as soon as this is approved and your team is set up with XCode 11. 
I'll build and release a new beta with these changes so that they can be tested.

**Review by mindgraffiti — APPROVED** [review]

**Comment by mindgraffiti** [comment]
Thanks @ctarda!

**Comment by ctarda** [comment]
Alright folks, merging!

**Pull request merged**
