### PR TITLE
Readonly Product Variations: Variations & Product Details UI

### LINKED ISSUE #1469: Readonly Product Variations: variations UI
Depends on #1468 

Create a screen with a table view of Product Variations:

Screen Shot 2019-11-14 at 1 47 02 PM

### LINKED ISSUE #1470: Readonly Product Variations: show Product variations summary on Product Details screen
- Create a feature flag like `readonlyProductVariations`
- Show the Product attributes on the existing Product Details screen like on Android: https://github.com/woocommerce/woocommerce-android/pull/1541

TODO: confirm design

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #1469 
Fixes #1470 

Summary: Add a Product variants info row to the Product Details screen, and navigate to a new Product Variations paginated list screen on tapping the variants info row.

## Changes
- Added a new feature flag `readonlyProductVariants`
- On Product Details screen, conditionally showed the Product variants info (Product attributes with their number of options) based on the feature flag and whether the Product has non-empty variations
- Created `ProductVariationsViewController` that displays a paginated table view of Product Variations with the data from `ProductVariationAction.synchronizeProductVariations`
  - Added a `ProductsTabProductViewModel` extension to set up the view model with a `ProductVariation`
- Navigated to `ProductVariationsViewController` when the user taps on the Product variants info row on Product Details screen

## Testing
Prerequisites: have two types of Products - simple and variable Products with variations
- Launch the app
- Go to the Products tab
- Tap into a simple Product --> should see the Price & Inventory section on the Product Details screen
- Go back to the Products tab
- Tap into a variable Product --> should see the variants info below the reviews row with each attribute and the number of options, and should **not** see the Price & Inventory section on the Product Details screen
- Tap the variants info row --> should see a list of variations with the price or visibility

## Example screenshots

Product has no variations | Product has variations | Variations UI
-- | -- | --
Simulator Screen Shot - iPhone 8 - 2019-11-22 at 09 17 09 | Simulator Screen Shot - iPhone 8 - 2019-11-22 at 09 08 32 | Simulator Screen Shot - iPhone 8 - 2019-11-22 at 09 08 38

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jaclync** [comment]
> I discovered only a small "issue" in variations screen. When loader finishes spinning, under the last cell appears the line separator. 🤷‍♂

Interesting, I didn't see this on the iPhone 8 iOS 13.1 simulator:

spinner | no spinner
-- | --
Simulator Screen Shot - iPhone 8 - 2019-11-25 at 07 47 34 | Simulator Screen Shot - iPhone 8 - 2019-11-25 at 07 47 36

I created an issue to track this: https://github.com/woocommerce/woocommerce-ios/issues/1519

**Comment by kyleaparker** [comment]
The label/title should be consistent across the two screens, I would suggest "Variations" on both

**Comment by jaclync** [comment]
> The label/title should be consistent across the two screens, I would suggest "Variations" on both

@kyleaparker did you mean we update the navigation bar title of the existing Product Details screen to be "Variations" if the Product has variations?

**Comment by kyleaparker** [comment]
>@kyleaparker did you mean we update the navigation bar title of the existing Product Details screen to be "Variations" if the Product has variations?

No I mean the label for the variations section on the main product screen is "Variants" but this should also be "Variations" to match the title on the variations screen

**Comment by jaclync** [comment]
> No I mean the label for the variations section on the main product screen is "Variants" but this should also be "Variations" to match the title on the variations screen

**Pull request merged**
