### PR TITLE
Merge release/6.6 final into develop

### PR DESCRIPTION
**Pull request by AliSoftware**
Build 6.6.0.1 just got submitted for review to Apple today.

### CODE REVIEW

**Review by loremattei — COMMENTED** [review]
@AliSoftware I don't see any new translation which looks weird to me 🤔 Is this expected?

**Comment by AliSoftware** [comment]
@loremattei Nice catch, thanks!

This is due to a bug in the toolkit, which fails to glob the `.strings` files to `git add` and thus create an empty commit instead of commiting them. I spot and fixed that issue manually last 2 times, but accidentally missed it this time around. This bug has been recently fixed in the toolkit since, but WCiOS hasn't been updated to point to it yet (I'll update it as part of the upcoming Sprint). 

I've updated the translations, and discarded the build in ADC and will resubmit. Please re-review those updated PRs (develop and trunk) in the meantime 🙂

**Comment by AliSoftware** [comment]
The CI failures are because the build of UI tests was cancelled (by me triggering the release build, I assume)

**Review by loremattei — APPROVED** [review]
Looks better now :-) 
:shipit:

**Pull request merged**
