### PR TITLE
[Shipping labels] Edit selected package

### PR DESCRIPTION
**Pull request by rachelmcr**
Part of: #14522
⚠️ Depends on https://github.com/woocommerce/woocommerce-ios/pull/14711 ⚠️ 

## Description

This PR handles editing the selected package in the Woo Shipping label flow. After selecting a package, you can tap the pencil icon to select a different package.

### How

* `WooShippingSelectedPackageView` now opens `WooShippingAddPackageView` with the previously selected package data when the pencil icon is tapped. It also has an `updateSelectedPackage` closure that is used to update the selected package in `WooShippingCreateLabelsViewModel` if a new package is selected.
* `WooShippingAddCustomPackageViewModel` now accepts a preselected package:
   * It prefills the package type and dimensions with the package data.
   * It does not prefill the other fields (weight and name) since those are specific to saved templates and can be re-entered if a new template is being saved.
* `WooShippingAddPackageViewModel` now accepts a selected package:
   * It tracks the previously selected package so the view will select it unless a new package has been selected.
   * When transforming package data, if the previously selected package is still selected, it will set the corresponding tab and carrier tab so the view opens to the correct place.

## Testing information

1. Install and set up the Woo Shipping extension on your store.
2. Build and run the app with the revampedShippingLabelCreation feature flag enabled.
3. Create an order with the processing status and at least one physical product.
4. In your WooCommerce product settings on the web, change the weight and dimension units and save your changes.
5. On the Orders tab in the app, open the order you created.
6. In the order details, select "Create Shipping Label."
7. Immediately tap "Select a Package."
8. Select a package or enter custom package data and add the package.
9. Tap the pencil icon and confirm the add package view opens again with the previous selection (either the custom package data on the custom tab, or the carrier/saved tab with the correct package selected).
10. Pull to refresh the carrier/saved tab and confirm the previous selection is still selected.
11. Select a different package.
12. Pull to refresh the carrier/saved tab and confirm the new selection is still selected.

## Screenshots

https://github.com/user-attachments/assets/eb8e3b27-4699-4ef1-9992-3772ec66efcd

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by bozidarsevo — COMMENTED** [review]
Would it be possible to scroll to selected package when we edit selected package?

In this example I select a starred/saved carrier package and when I go to edit it, the saved list is showed but that selected package is not visible.

Maybe we can leave that for a separate PR?

https://github.com/user-attachments/assets/3ee13387-16c3-4a2b-8bd0-e7eedf951d21

**Comment by rachelmcr** [comment]
> Would it be possible to scroll to selected package when we edit selected package?

Good idea, tracked in https://github.com/woocommerce/woocommerce-ios/issues/14734.

**Review by bozidarsevo — APPROVED** [review]

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/233">21.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
