### PR TITLE
Blaze: Enable feature flag for evergreen campaign creation

### PR DESCRIPTION
**Pull request by itsmeichigo**
Part of #13460 

## Description

This PR enables the feature flag `blazeEvergreenCampaigns` to enable creating evergreen campaigns for Blaze in production.

## Steps to reproduce

- Log in to a store eligible for Blaze.
- Navigate to the Products tab and select an existing published product (or create a new one).
- On the product form, select Promote with Blaze.
- Confirm that the budget field displays a weekly budget without an end date by default.
- Select the budget field, confirm that the budget screen displays the weekly budget and no end date.
- Select Edit on Schedule, confirm that the Set duration screen has a switch for "Specify the duration" disabled. 
- Toggle the switch and confirm that a slider for duration appears.
- Adjust the duration and select Apply. Confirm that the budget screen now displays the total spend for the selected duration.
- Select Update and confirm that the budget label displays the total budget for the selected duration.
- Tap the Budget field again, this time disable "Specify the duration" and save the change.
- Tap Confirm Details. Confirm that the payment screen displays the weekly amount to be charged.
- Tap Submit Campaign. The creation should succeed.
- Check the campaign list to confirm that the latest campaign item displays the weekly budget.
- Select the campaign and confirm that the details for duration and budget are correct.

## Screenshots

https://github.com/user-attachments/assets/d7bf7e05-be2d-4619-930f-90272438f15f

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/221">20.2</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by itsmeichigo** [comment]
Converted the PR back to draft as tracking is still missing.

**Comment by hafizrahman** [comment]
> - Log in to a store eligible for Blaze.
> - Navigate to the Products tab and select an existing published product (or create a new one).
> - On the product form, select Promote with Blaze.
> - Confirm that the budget field displays a weekly budget without an end date by default.

When I tried this:
1. In the "Set your budget" screen, the slider is showing "Daily spend" instead of "Weekly spend" like in your video
2. The "Schedule" section has an "Edit" button that's differently designed (bold, right aligned) than the one in the "Duration" section.

I'm not sure if these are expected or not but thought to mention it first. Video below:

https://github.com/user-attachments/assets/c6a9607f-bfe4-4703-b99c-a0038a917265

**Comment by itsmeichigo** [comment]
@hafizrahman There was an UI update done in #13748 but I forgot to update the PR description here. The UI you see is expected. Sorry for the confusion.

**Review by hafizrahman — APPROVED** [review]
This LGTM.

Tested the Blaze creation and duration updating flow in:

1. Simulator iPad Pro 13 inch, iOS 17.5
2. Simulator iPhone, iOS 17.5

👍🏼 

I have some unrelated feedbacks while smoke testing this, will make separate issues for them (update: #13794, #13795)

**Pull request merged**
