### PR TITLE
Improvements in Product Creation with AI Starting View

### PR DESCRIPTION
**Pull request by pmusolino**
## Description
Following what comes out in this PR https://github.com/woocommerce/woocommerce-ios/pull/13329#issuecomment-2235933352 I made the following improvements:
- When navigating back from the preview screen, the advice block is visible but the progress bar is reset. Now the progress bar keeps its status.
- When navigating back from the preview screen, the text view collapsed instead of displaying all the content as before. Now I substituted the `TextEditor` with a `TextField` which seems to be more reliable under this aspect, and I fixed the issue.
- Previously, the UX/UI was not the best in landscape mode, given the new advice block. Now, for vertical size classes equal to `compact`, the main button for generating the preview will disappear, and it will appear on the navigation bar.

## Testing information
1. Start doing a smoke test, making sure that everything works properly as before.
2. Navigating back from the previous screen, should still display the prompt text expanded and also the advice block with the right progress.
3. Rotate the screen to landscape mode on the iPhone: you will notice that the "Generate" button is on the navigation bar (top right side). Go back to portrait mode, and the main button for generating the preview should be visible again, while the one in the navigation bar should disappear..

## Screenshots

| Portrait mode             |  Landscape mode |
:-------------------------:|:-------------------------:
Simulator Screenshot - iPhone 15 Pro Max - 2024-07-18 at 16 11 09 | Simulator Screenshot - iPhone 15 Pro Max - 2024-07-18 at 16 11 31

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/214">19.6</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by itsmeichigo — APPROVED** [review]
This looks good to me. I also added 2 commits 53f59c41efef0aa3371ccacee656e6d9db07fcf2 to reuse the generate button logic and 6aba38990ac45b249e10cebf6c92cb024f972921 to fix some typos.

Using the `TextField` fixes the collapse issue, but we have a long placeholder text, which would be clipped off when switching to a large font size. I'm unsure which problem is more serious, but I'm approving this PR for now. @selanthiraiyan please feel free to leave your opinion here - in case the placeholder and accessibility are more important, we can revert to using `TextEditor`.

**Comment by selanthiraiyan** [comment]
Thanks, folks! 🙇 I am good with using `TextField`. 

This works as expected with feature flags for M3 turned off, and M1 turned on. I am enabling auto-merge to get this into the 19.6 code freeze.

**Comment by pmusolino** [comment]
Thank you both @itsmeichigo & @selanthiraiyan!

**Pull request merged**
