### PR TITLE
[Mobile Payments] Tracks events for receipts

### PR DESCRIPTION
**Pull request by koke**
Part of #4082

This PR includes all the events related to receipts.

## Events included

- receipt_view_tapped: The user viewed a saved receipt
- receipt_email_tapped: The user tapped on the button to email a receipt.
- receipt_email_failed: Sending or saving the receipt email failed.
- receipt_email_canceled: The user canceled sending the receipt by email.
- receipt_email_success: The receipt was sent by email.
- receipt_print_tapped: The user tapped on the button to print a receipt.
- receipt_print_failed: Printing the receipt failed.
- receipt_print_canceled: The user canceled printing the receipt.
- receipt_print_success: The receipt was successfully sent to the printer. iOS won't guarantee that the receipt has actually printed

## To test

I can't figure out how to make either email or printing fail, so I haven't been able to verify those, but they would be triggered on the same code paths as the other results, so I think we can leave these and maybe not validate until we receive some events from users?

- After completing payment:
  -  [x] Tap on Email receipt: `receipt_email_tapped `
      - [x] Send email: `receipt_email_success`
      - [x] Cancel and save as draft: `receipt_email_success`
      - [x] Cancel and discard draft: `receipt_email_canceled`
      - [ ] ❓Make the email fail: `receipt_email_failed`
  -  [x] Tap on Print receipt: `receipt_print_tapped `
      - [x] Print receipt: `receipt_print_success`
      - [x] Cancel printing: `receipt_print_canceled`
      - [ ] ❓Make printing fail: `receipt_print_failed`
- From an order with a saved receipt:
  - [x] Tap See Receipt: `receipt_view_tapped`
    -  [x] Tap on Print receipt: `receipt_print_tapped `
        - [x] Print receipt: `receipt_print_success`
        - [x] Cancel printing: `receipt_print_canceled`
        - [ ] ❓Make printing fail: `receipt_print_failed`

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by koke** [comment]
> The PR must be assigned the Tracks label PR Reviewer

@AliSoftware I assumed the right new label was `category: analytics` and I don't see a `Tracks` one. Maybe peril needs to be updated?

**Review by ctarda — APPROVED** [review]
Sorry for the late review @koke  I completely missed this PR earlier today.

Thanks a lot for taking this one. 

I tested all the code paths (except for email and printing failure) and I saw the events going out. 

:shipit:

**Comment by koke** [comment]
> I completely missed this PR earlier today

I only marked it for review like an hour ago 😅 I created the draft earlier to have a checklist of things to test.

**Comment by AliSoftware** [comment]
> > The PR must be assigned the Tracks label PR Reviewer
> 
> @AliSoftware I assumed the right new label was `category: analytics` and I don't see a `Tracks` one. Maybe peril needs to be updated?

Yep, that's something that is still pending being fixed – the PR to Peril to fix that is [here](https://github.com/Automattic/peril-settings/pull/72) but not yet merged; I'll try to get that moving 👍  \cc @designsimply

**Pull request merged**
