### PR TITLE
Fixed launch screen stretched

### LINKED ISSUE #1932: Launch screen stretched on iPhone 11 Max
I don't know if this is only happening on the Max or if it's all sizes. Reporting so we don't forget.

Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-10 at 15 57 26

### PR DESCRIPTION
**Pull request by pmusolino**
Fixes #1932 

## Description
This PR fixes the launch screen which appears stretched, probably caused by this PR https://github.com/woocommerce/woocommerce-ios/pull/1855.
I adapted the `UIImageView` inside `LaunchScreen.storyboard` to match the aspect ratio of the new logo image.

## Testing 
1) Delete the app on your device/simulator (to make sure that is not cached)
2) Run the app on different simulators.
3) Make sure that the launch screen is no more stretched.

## Screenshots

| Before             |  After |
:-------------------------:|:-------------------------:
76358859-320f0000-62e8-11ea-95da-33f6ff052bfa | Simulator Screen Shot - iPhone 11 Pro - 2020-03-11 at 15 55 42

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pmusolino** [comment]
Tests are failing because we need to merge this https://github.com/woocommerce/woocommerce-ios/pull/1939 on `develop` first.

**Review by Garance91540 — APPROVED** [review]
Looks good Paolo! I can't check if we have this issue on iPad too, would you mind checking?

**Review by jaclync — APPROVED** [review]
:shipit: 

Code: ✅ 
Testing: ✅ 

It's interesting the logo doesn't look very high resolution on simulators, as shown in screenshots below 🤔 but I tested on a device, and the logo looks good (the second row of the screenshots)

@Garance91540 you can check the iPad screenshots below too!

device | before | after
-- | -- | --
iPhone 11 simulator | Simulator Screen Shot - iPhone 11 - 2020-03-12 at 08 00 18 | Simulator Screen Shot - iPhone 11 - 2020-03-12 at 08 02 30
iPhone 6s Plus device | IMG_7670 | IMG_7671
iPad Air 2 simulator | Simulator Screen Shot - iPad Air 2 - 2020-03-12 at 08 16 45 | Simulator Screen Shot - iPad Air 2 - 2020-03-12 at 08 18 09

**Comment by pmusolino** [comment]
@jaclync Good catch. I think I found the issue... because the image is 82 × 48 px at 1x, but the image view is 164x96px at 1x. I'm going to update it. If you zoom your second image (iPhone 6s Plus device) you can notice that also in that device the image is low resolution.

**Pull request merged**
