### PR TITLE
Lightweight storefront: Fix UI glitches

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #11665 

## Description

This PR add fixes for the minor UI glitches:
- Explicitly set the theme settings view to display its navigation view in stack style. The issue was due to the view being presented from UIKit, which determines the style of the navigation view as split view based on the device's size class. The safest way to work with Navigation view is to set the desired style when you are in doubt, or switch to `NavigationStack` when we drop iOS 15.
- Added a bottom padding to the "No credit card required" on the free trial summary screen.

## Testing instructions

- Build the app to an iPad and log in to a WPCom store.
- Switch to Menu tab > Settings > Themes. Notice that the theme setting view is not displayed in a split view.
- Navigate back to the Menu tab and open the store picker.
- Select Add a Store > Create a new store. Notice that the "No credit card required" has a padding at the bottom.

Please feel free to confirm that the screens still look correctly on iPhone.

## Screenshots

Free trial summary | Theme settings
--- | ---
 |  

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/179">16.8 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by selanthiraiyan — APPROVED** [review]
Thanks for adding this fix. It works as expected in iPad and iPhone simulators. :shipit: 

---

> Explicitly set the theme settings view to display its navigation view in stack style. The issue was due to the view being presented from UIKit, which determines the style of the navigation view as split view based on the device's size class. The safest way to work with Navigation view is to set the desired style when you are in doubt, or switch to NavigationStack when we drop iOS 15.

TIL. Thanks for adding this info.

**Comment by itsmeichigo** [comment]
@spencertransier I have this fix I want to merge for 16.8 but looks like CI fails due to Xcode version. Is there a way to mitigate this and include this fix in the next beta build?

**Comment by spencertransier** [comment]
@itsmeichigo I have a PR for updating to Xcode 15.1 ready to go for the `release/16.8` branch that will fix CI. I'm waiting on final approval before moving forward with that before submitting to the App Store today. See peaMlT-nT-p2

**Comment by spencertransier** [comment]
@itsmeichigo I just merged the Xcode 15 into `release/16.8` then merged `release/16.8` into this branch, so CI should be able to pass now.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/179">16.8 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
