### PR TITLE
Filter Products: navigate to screens for filtering products by stock status, product status, and product type

### PR DESCRIPTION
**Pull request by jaclync**
Handle tapping on each filter row and changing the filter value (UI only) for #2037 

- [ ] ⚠️ Update PR base to `develop` after https://github.com/woocommerce/woocommerce-ios/pull/2204 is merged ⚠️ 

This PR adds navigation from the filter list selector screen to each filter option list selector. You can see the remaining subtasks in #2037.

## Changes

- Createed `FilterProductsByProductStatusListSelectorCommand`, `FilterProductsByProductTypeListSelectorCommand`, `FilterProductsByStockStatusListSelectorCommand` for filtering products by different attributes with basic unit tests
- In `FilterProductListCommand`, navigates to each filter option list selector screen and reload UI if filters change

## Testing

- Go to the Products tab
- Tap on the "Filter" CTA in the toolbar below the WIP banner --> should see the Filter Products screen **without "Clear All" CTA in the navigation bar**
- Tap on "Stock status" row --> it should navigate to the stock status list selector screen
- Select a different stock status (e.g. "Out of stock") filter and tap "Show Products" at the bottom --> it should go back to the Products tab without any changes to the product list
- Tap on the "Filter" CTA again --> should see the Filter Products screen as in the screenshots below, **with "Clear All" CTA in the navigation bar**, the navigation bar title should say "Filters (1)", and the "Stock status" row should say the selected stock status
- Repeat the same steps for "Product status" and "Product type" rows and notice the navigation bar title should update to the number of active filters
- Tap "Clear all" CTA in the navigation bar --> all filters should be cleared to "Any"

## Example screenshots

Similar to https://github.com/woocommerce/woocommerce-ios/pull/2204 @Garance91540 the list will be updated to be plain style (no space above the cells) in a later task

mode \ screen | filter products | filter products by stock status | filter products by product status | filter products by product type
-- | -- | -- | -- | --
Light | Simulator Screen Shot - iPhone 11 - 2020-04-28 at 18 35 39 | Simulator Screen Shot - iPhone 11 - 2020-04-28 at 18 35 26 | Simulator Screen Shot - iPhone 11 - 2020-04-28 at 18 31 07 | Simulator Screen Shot - iPhone 11 - 2020-04-28 at 18 35 30
Dark | Simulator Screen Shot - iPhone 11 - 2020-04-28 at 18 35 49 | Simulator Screen Shot - iPhone 11 - 2020-04-28 at 18 35 52 | Simulator Screen Shot - iPhone 11 - 2020-04-28 at 18 35 54 | Simulator Screen Shot - iPhone 11 - 2020-04-28 at 18 35 56

iPad Air 2 (iOS 13.4)

mode \ screen | filter products | filter products by a filter
-- | -- | --
Dark (landscape) | Simulator Screen Shot - iPad Air 2 - 2020-04-29 at 16 04 19 | Simulator Screen Shot - iPad Air 2 - 2020-04-29 at 16 04 03
Dark (portrait) | Simulator Screen Shot - iPad Air 2 - 2020-04-29 at 16 04 24 | Simulator Screen Shot - iPad Air 2 - 2020-04-29 at 16 04 27
Light (landscape) | Simulator Screen Shot - iPad Air 2 - 2020-04-29 at 16 04 44 | Simulator Screen Shot - iPad Air 2 - 2020-04-29 at 16 04 47
Light (portrait) | Simulator Screen Shot - iPad Air 2 - 2020-04-29 at 16 04 42 | Simulator Screen Shot - iPad Air 2 - 2020-04-29 at 16 04 39

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by Garance91540** [comment]
@jaclync could you please send me a screenshot of what it looks like on iPad? Thank you!

**Comment by jaclync** [comment]
@Garance91540 I added some screenshots from iPad Air 2 simulator to the PR description! lemme know if there are other screenshots you'd like to check 🙂

**Comment by Garance91540** [comment]
Looking great, thanks @jaclync !

**Comment by jaclync** [comment]
closing this in favor of the updated architecture in https://github.com/woocommerce/woocommerce-ios/pull/2204 :)

**Pull request closed without merging**
