### PR TITLE
[Watch App] Adds initial WooWatchApp setup

### LINKED ISSUE #12641: Setup WCiOS with Apple Watch module
## Tasks
```[tasklist]
- [x] Create feature branch
- [x] Add watch target
- [x] Make sure it runs on testflight
```

### LINKED ISSUE #12645: Configure Watch app Theme, Icons and Colors?
## Tasks

Make sure the following is properly set

```[tasklist]
- [x] Icon
- [x] App name
```

### PR DESCRIPTION
**Pull request by Ecarrion**
closes #12641 
closes #12645 

# Why

This PR adds the ⌚  target to the main WooCommerce iOS Project.

# How

- Added watch app target as a companion with the iOS App
- Set icons 
- Set development provisioning profile
- Set `VALID_ARCHS` build setting to `$(ARCHS_STANDARD)`, otherwise it will not compile.

# Testing Steps

- [x] Make sure the watch app runs via code in the simulator
- [x] Make sure the watch app runs via code in a real device
- [x] Make sure the watch app runs via the installable build?

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Ecarrion** [comment]
Hi @iangmaia, 👋 

Following the Watch App provisioning profiles you created. Can you help us set them on our installable builds to test that everything works correctly? 

I see on [the docs](https://devblogs.microsoft.com/appcenter/announcing-ios-app-extension-and-watchos-support-in-visual-studio-app-center/) that it is supported, but I don't have the correct role to make any change.

Additionally, if possible, feel free to configure testflight too! 😇

**Comment by iangmaia** [comment]
@Ecarrion I took the freedom to commit directly to this branch, I hope it's ok 😇 . I think it should all be working now, thanks for the ping! 🚀

**Comment by Ecarrion** [comment]
Thanks a lot @iangmaia, I just had to adjust a [minor thing](https://github.com/woocommerce/woocommerce-ios/pull/12647/commits/ed182c13fbedeea1ef4ad8015367d687e05eca5b) and now everything seems to be working correctly! 🎉

**Pull request merged**
