### PR TITLE
Fix in-stock product variations with "Manage stock" disabled showing wrong stock status in variations list

### LINKED ISSUE #2934: Products: In-stock variations with "Manage stock" disabled show wrong stock status in variations list
**Describe the bug**

If a variation (of a variable product) is set to "In stock" with "Manage stock" disabled, it should show as "In stock" in the variations list. However, it shows "0 in stock" instead.

**To Reproduce**

1. Open the Products tab.
2. Select a variable product.
3. Open the Variations list.
4. Select a variation.
5. Open the variation's Inventory settings.
6. Toggle "Manage stock" off, and set "Stock status" to "In stock."
7. Tap "Done" to save the change to the Inventory settings.
8. Tap "Update" on the variation to save it.
9. Go back to the variations list and notice that the variation now shows "0 in stock" as the stock status, instead of "In stock" as expected.

**Screenshots**

Screencast: https://cloudup.com/caPsnvzZ0yT

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 14.0.1
- WooCommerce iOS version: 5.2.0.0 TestFlight beta

cc @jaclync

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #2934 

## Changes

- In `ProductFormDataModel`'s extension helper `createStockText` that generates the text for stock details, it only shows the non-nil stock quantity if manage stock is enabled (when it is disabled, the stock quantity is invalid even though it could be non-nil).
- Added/updated unit tests

## Testing

- Go to the Products tab
- Tap on a variable product
- Tap on the variations row
- Tap on a variation
- Tap on the inventory row
- Turn off "Manage stock", and set "Stock status" to "In stock"
- Tap "Done" to save the change to the Inventory settings
- Tap "Update" on the variation to save it remotely
- Go back to the variations list --> the variation row should read "In stock" without a quantity

## Example screenshots

before | after
-- | --
Simulator Screen Shot - iPhone 11 - 2020-10-08 at 15 21 24 | Simulator Screen Shot - iPhone 11 - 2020-10-08 at 15 25 02

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Ecarrion — COMMENTED** [review]
Code looks ok ✅ but I couldn't follow the testing steps. In particular, I couldn't tap on a variation. And turning off the management stock in the main product doesn't let me set the stock status.

Maybe I was doing something wrong? 🤔

**Comment by jaclync** [comment]
> but I couldn't follow the testing steps. In particular, I couldn't tap on a variation. And turning off the management stock in the main product doesn't let me set the stock status.
Maybe I was doing something wrong? 🤔

I bet it's because the Products feature switch was previously off so that all M3 features are disabled (https://github.com/woocommerce/woocommerce-ios/issues/2927 - it was merged to release 5.2 branch as a hotfix and was just merged back to `develop` yesterday). Could you try again now that I merged `develop` to the PR branch with the hotfix?

**Review by Ecarrion — APPROVED** [review]
That's weird, I could swear that I deleted the app to circumvent the m3_flag problem. 🤔 
Anyway, just tested the latest state of the branch and it works as expected 👍

**Comment by jaclync** [comment]
> That's weird, I could swear that I deleted the app to circumvent the m3_flag problem. 🤔

The products feature switch is default to be off if it hasn't been set before, that's probably why reinstalling the app didn't work:

https://github.com/woocommerce/woocommerce-ios/blob/02946dd52a6e71e68574ea562df7c17d6aa6d546/Yosemite/Yosemite/Stores/AppSettingsStore.swift#L432-L434

Thanks for testing again, merging now!

**Pull request merged**
