### PR TITLE
Fix/speculative fix for double order pushes

### PR DESCRIPTION
**Pull request by joshheald**
Part of: #12071

## Description

Some of the issues under this crash appear to be related to double-pushing Order loaders, probably from a notification.

This _really_ shouldn't be possible, because we make a new instance of the order loader every time that we use it, and we also don't push them, we set the splitview's viewcontroller's property to an array with just the one order loader in it.

So... I'm not confident that this fix will do anything, but it doesn't break anything either.

If this doesn't have any effect on the crash numbers, we should remove it

peaMlT-zn-p2 for context.

## Testing instructions

I could not repro the crash, so these are general testing instructions.

1. Launch the app, then background it
2. Make an order on the web
3. Tap the notification which comes up
4. Observe that the order is shown as expected.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/201">18.5</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by iamgabrielma — APPROVED** [review]
Thanks for working on this! 
```
Make an order on the web
Tap the notification which comes up
```

I don't seem able to see notifications when I create new orders, but the fix from https://github.com/woocommerce/woocommerce-ios/pull/12633 it's on this branch. These are enabled system-wise, and I'm running WCiOS 18.4.0.4. What am I missing here? 🤔 

If I do the tests through a deep link, this works as expected: All tests I've done confirm that at the point we follow a link to an order that is not loaded locally, the secondary view is of type `WooNavigationController`, and that we don't have a `OrderLoaderViewController` in memory, which will be created fresh at this point.

Edit: Not part of this PR but, adding to the notifications oddness above, maybe it's not us since I've only received one notification as well in my wpcom account, the other 2 orders were skipped:

Screenshot 2024-05-03 at 13 04 58

All of them through the web, the one marked as completed via "Payment to be made upon delivery", the  two marked as Processing using WooCommerce Payments:
Screenshot 2024-05-03 at 13 09 06

**Comment by joshheald** [comment]
@iamgabrielma thanks for the review.

Not sure about why you're not getting notifications, I get them even for pay-in-person orders.

**Comment by iamgabrielma** [comment]
> Not sure about why you're not getting notifications, I get them even for pay-in-person orders.

I think is a wider issue not exclusive to iOS. More instances reported here p1714738845170739-slack-C025A8VV728

**Pull request merged**
