### PR TITLE
Product sharing: Enable feature flag for AI-generated content

### LINKED ISSUE #9867: Activate: Add AI support for sharing product messages
Part of #9785.

- [x] New feature flag for AI Generated product messages https://github.com/woocommerce/woocommerce-ios/pull/9873
- [x] Update `ProductStore` and `ProductAction` to generate sharing message based on product URL #9872 
- [x] Add coordinator to switch between AI generated sharing messages and the basic sharing sheet https://github.com/woocommerce/woocommerce-ios/pull/9875 , https://github.com/woocommerce/woocommerce-ios/pull/9880
- [x] Update UI to show product sharing message AI generation for eligible sites #9885
- [x] Update prompt to include product name, description and product URL for improved generation #9921
- [x] Analytics #9912

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #9867 

## Description

This PR simply enables the local feature flag to release the AI product sharing feature for the next version.

Also: updated the sparkles icon to match the design instead of the system image.

## Testing instructions

Feel free to do a quick test by tapping share on a published product in a public WPCom site to make sure that AI-generated content is available and works appropriately.

## Screenshot

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by selanthiraiyan** [comment]
I observed that the generated content has a different language. My product's title and description are in English, though.

Title - "WN Camera"
Description - "Introducing the WN Camera - the ultimate tool for photography enthusiasts and thrill-seekers. This remarkable camera effortlessly captures life's most precious moments, empowering you to create unforgettable memories that will last a lifetime. Take your photography to the next level with the WN Camera's powerful features and intuitive design. Whether you're on an adventure or simply looking to capture a special moment, the WN Camera is the perfect choice to help you achieve your goals." (AI generated)

| Language 1 | Language 2 |
|--------|--------|
| Simulator Screen Shot - iPhone 14 - 2023-06-16 at 08 42 34 | Simulator Screen Shot - iPhone 14 - 2023-06-16 at 08 42 47 |

**Comment by selanthiraiyan** [comment]
I also noticed that the "Write with AI" button text color is not Purple. I checked and found out that the final design doesn't use the purple color. pe5sF9-1AH-p2#comment-2316


| "Write with AI" button | "Write it for me" in product detail screen (WIP) |
|--------|--------|
| Simulator Screen Shot - iPhone 14 - 2023-06-16 at 08 42 53 | Simulator Screen Shot - iPhone 14 - 2023-06-16 at 08 53 57 |

Please ignore if the color change is intentional.

**Comment by itsmeichigo** [comment]
Thanks @selanthiraiyan for raising the issue! I attempted to update the prompt about identify language to make it clearer in 3d3f18cdcbe4bbd7bc6ed3296e77a5170171d58c - please test again with your product to see if it works.

> I also noticed that the "Write with AI" button text color is not Purple. I checked and found out that the final design doesn't use the purple color. pe5sF9-1AH-p2#comment-2316

This is intended since I pushed back on the new button style, so we are using the secondary button style for now. If designers decide to unify the UI with product description AI, I'll update the button later in a future PR.

**Review by selanthiraiyan — APPROVED** [review]
Thanks for the updates, Huong! 

It works great now. ✨ 

🚢

**Pull request merged**
