### PR TITLE
Orders tab: adapt to various screens sizes for iPad split view support in iOS 15

### LINKED ISSUE #6950: Order list not fitting to screen width in iPad split view
**Describe the bug**

When using iPad split view, order list and order details still use the full device width instead of the new screen width. Other tabs seem to adjust to the screen width. I only see this issue in iOS 15 simulators.

**To Reproduce**

- Launch the app in iPad on iOS 15
- Enable split view with another app like Safari
- In the app, go to the Orders tab --> notice that after scrolling up or tapping an order to view order details, the UI looks like it's still using the full device width

**Screenshots**

order list | order details | iOS 14 (working)
-- | -- | --
Simulator Screen Shot - iPad Air (4th generation) - 2022-05-26 at 10 47 42 | Simulator Screen Shot - iPad Air (4th generation) - 2022-05-26 at 10 47 59 | Simulator Screen Shot - iPad Air (4th generation) - 2022-05-26 at 10 55 48

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad Air 4th gen
- iOS version: iOS 15
- WooCommerce iOS version: 9.3

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #6950 

### Description

While testing another PR using iPad split view, I noticed the orders tab isn't currently adjusting to different app widths when it's in split view with another app. This seems to be only an issue in iOS 15. After adding Auto Layout constraints to pin the child view controller in `OrdersSplitViewWrapperController`, the orders tab now adjusts its size to the parent/app's size. Maybe something with split view controller changed in iOS 15 🤷🏻‍♀️

### Testing instructions

- Launch the app in iPad on iOS 15
- Enable split view with another app like Safari
- In the app, go to the Orders tab --> the orders tab should adjust its width to the app width, you can check by scrolling up or tapping an order to view order details

- [x] @jaclync tested the steps in iOS 14.5 iPad simulator
- [x] @jaclync tested the steps in iOS 15.5 iPhone simulator

### Screenshots

before | after
-- | --
Simulator Screen Shot - iPad Air (4th generation) - 2022-05-26 at 12 23 19 | Simulator Screen Shot - iPad Air (4th generation) - 2022-05-26 at 12 24 04

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by itsmeichigo — APPROVED** [review]
I could not repro the issue since I'm still using an old version of Xcode at the moment 😅  (and downloading it right now). But the solution makes sense, I wonder why this issue didn't show up in the previous versions of Xcode 🤷‍♀️

**Comment by jaclync** [comment]
> I could not repro the issue since I'm still using an old version of Xcode at the moment 😅 (and downloading it right now). But the solution makes sense, I wonder why this issue didn't show up in the previous versions of Xcode 🤷‍♀️

I wonder if this behavior change is from iOS 15.4 in Xcode 13.3, I repro'ed the issue with Xcode 13.3.1 and 13.4 in iOS 15.4 and 15.5 simulators. I'm curious to see if you can reproduce this when you have Xcode 13.3.1+, or this is just some issue on my end 😅

**Comment by jaclync** [comment]
Out of curiosity, I tested this issue in Xcode 13.2.1 and wasn't able to repro this. Since we also updated CI to Xcode 13.3.1 in release 9.3 https://github.com/woocommerce/woocommerce-ios/pull/6884, this is likely not an issue in production. Still, including this change in the release notes may give us more confidence.

**Comment by itsmeichigo** [comment]
Also, I think this fixes [this issue](https://github.com/woocommerce/woocommerce-ios/pull/6424#pullrequestreview-909618466) as well! But there seem to be some constraint warnings when the empty view for the Filtered Orders list is shown.

Simulator Screen Shot - iPhone 13 Pro Max - 2022-05-26 at 17 14 09

**Comment by jaclync** [comment]
> Also, I think this fixes [this issue](https://github.com/woocommerce/woocommerce-ios/pull/6424#pullrequestreview-909618466) as well! But there seem to be some constraint warnings when the empty view for the Filtered Orders list is shown.

@itsmeichigo nice that it fixes the other issue! I just tested the PR branch and `trunk` and saw the same warning in both branches about `Clear Filters` button width being 228px when the order list panel has a compact horizontal size class. The button currently has a fixed 228px width, I think we want to change this by replacing the width constraint with leading/trailing constraints like the stack view above:

Screen Shot 2022-05-30 at 10 08 04 AM

I created a separate issue to track this: https://github.com/woocommerce/woocommerce-ios/issues/6988

Merging the PR now!

**Pull request merged**
