### PR TITLE
Screenshot: More flakiness fixes and fastlane update

### PR DESCRIPTION
**Pull request by hafizrahman**
## Various notes:

This PR depends on #14487, which contains Ruby Gem updates with fixes to promo screenshot generation.
Our initial plan is to have that and this PR to be included in 21.2 release so we can test sending updated screenshots, so it's a do not merge for now.

## Description

This PR introduces some fixes related to getting fastlane to generate screenshots properly. 

Previously there's already [a PR](https://github.com/woocommerce/woocommerce-ios/pull/14335) that made `WooCommerceScreenshot` work in the context of running the test directly inside Xcode. However, when run in fastlane to both generate raw screenshot and promo screenshot, I encountered various flakiness and issues. This PR is meant to handle those issues, more details follows.

1. https://github.com/woocommerce/woocommerce-ios/pull/14492/commits/3c503c10afe2de201d066e5569ebe25676f13197 This simply bumps the Simulator used to 16.0, matching the minimum deploy target. 
2. 31e0fae7628da69374a9e1d7b40ce7e81c56a70b As tested with @irfano in Slack p1732085614299129/1732038668.400999-slack-C03L1NF1EA3, when generating promo screenshots, I found that fastlane was unable to find the right translation files. This commit updates the right names to be used.
3. 833c0b38a29a503c9ff6f0aabadb161020026f25 During fastlane testing, I found that `app.tap()` sometimes caused a random tap in the app, which changed the screen and caused the automated test to be unable to proceed. Paired with using iOS 16, it looks like the tapping is not needed anymore, and can be removed safely.
4. 77a89990a3dc79912e4ec86f22fb2011b54c8132 The main flakiness issue I encountered was on this part of the test:

```
        .tapCollectPaymentButton()

        .tapCardPresentPayment()
        .thenTakeScreenshot(named: "order-payment")
```

For `tapCardPresentPayment()` to work, the option to pay with card must exist. However, occasionally, this option did not appear, and only "Cash" option is presented, making the test fail. From debugging in Slack p1732190657647519/1732160573.962259-slack-CGPNUU63E , it failed with `SiteAddress` was empty when checking for IPP support (it needs to check country). `SiteAddress` is injected as part of `SiteSettings` by the mock, though, so my hunch is maybe there was a race condition between the saving and the part of the code that fetches the value from DB.

With this commit I updated the saving method to use the newly introduced `performAndSave()` method. After multiple testings this seem to get rid of the flakiness. Although given my experience with CoreData so far, I would love to get a second eye on this @selanthiraiyan 

#### General test for `WooCommerceScreenshots`

1. Select WooCommerceScreenshots as target and pick an iPhone,
2. Go to Test Navigator, search for testScreenshots()
3. Run testScreenshots(), ensure that this opens the Simulator and starts going through screens automatically, and it finishes completely with the test passing.
4. Check [homedir]/Library/Caches/tools.fastlane/screenshots and ensure there are generated screenshots there. You might need to create this directory first if you don't have it.
5. Restart the same steps with an iPad.

#### Fastlane test

You can use the guide for more details P91TBi-8Pt-p2

Ideally you want to try:
1. Generating raw screenshots generating. I would recommend trying to generate just for one language: `bundle exec fastlane take_screenshotslocales:en-US`
2. Generating promo screenshots generating

Reminder that these are long processes that can be complicated. Please ping me in Slack for any questions.

## Testing information

I tested the above (both `WooCommerceScreenshots` and fastlane) on Simulators, iPad and iPhones on iO 16:
```
  'iPhone 11 Pro Max',
  'iPhone 8 Plus',
  'iPad Pro (12.9-inch) (2nd generation)',
  'iPad Pro (12.9-inch) (3rd generation)'
```

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/232">21.2 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by hafizrahman** [comment]
@selanthiraiyan Sorry, setting this back to draft as there's a new flakiness appearing in iPhone. Looking at it.

**Comment by hafizrahman** [comment]
I can't make the flakiness appear again, so reopening the PR again so we can tackle the listed issue first.

**Review by selanthiraiyan — APPROVED** [review]
Thanks for working on this, @hafizrahman!

The code changes look good to me. 

---

#### Testing

> General test for WooCommerceScreenshots

This worked great.

> Fastlane test

I face the following error while testing the `Fastlane test` step. 

```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:16.0, name:iPad Pro (12.9-inch) (2nd generation) }

	Ineligible destinations for the "WooCommerceScreenshots" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device, error:iOS 18.2 is not installed. To use with Xcode, first download and install the platform }
Exit status: 70
```

This looks like something to do with my local Xcode and simulator configuration setup.

I am approving this PR to unblock development. (As you aim to merge this into release branch as a beta fix.)

**Pull request merged**
