### PR TITLE
AddOns: Store product metadata

### LINKED ISSUE #3886: Add-Ons: Parse and store product add-on metadata
The product detail response includes add-on in its meta-data object.

We need to parse and store that add-on metadata in order to cross-reference it later with the order detail metadata

As this is a temporary solution, we shouldn't spend much time trying to parse this metadata into a very complex structure as it will be deleted later.

```json
{
  "meta_data": [
    {
      "id": 6471,
      "key": "_product_addons",
      "value": [
        {
          "name": "Topping",
          "title_format": "label",
          .
          .
          .
       }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by Ecarrion**
fix #3886 

# Why
This PR makes sure that the product add-ons parsed on #3942 are safely stored in our `Storage` layer as well as linked to a product when synchronizing/fetching products via the `ProductStore`.

# How
- Added Model-V47 with CoreData classes for `ProductAddOn` and `ProductAddOnOption`.
- Add CoreData `addOns` relationship on `Storage.Product`
- Make `ProductAddOn` and `ProductAddOnOption` conform to `ReadOnlyConvertible`
- Update `ProductStore` to persist addOns and addOns-options when `upserting` a product.
- Update `ProductStoreTests` to make sure everything is being stored correctly.
- Change the `imageID` type from `Int64` to `String`

# Testing steps

**Prerequisites:** Have your site with the add ons plugin installed, configured, and with at least one product with add-ons.

Add the following code on `ProductFormViewModel.init(...)` method

```swift
print("--------------- Add Ons ---------------")
for addOn in product.product.addOns {
  print("name: \(addOn.name)")
  print("options: \(addOn.options.map { $0.label })")
}
print("--------------- Add Ons ---------------")
```

- Launch the app 
- Navigate to the product that has addOns configured.
- See console printing addOns and options.

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pmusolino** [comment]
I was testing this PR,
but I noticed that if I put your code 
```
print("--------------- Add Ons ---------------")
for addOn in product.product.addOns {
  print("name: \(addOn.name)")
  print("options: \(addOn.options.map { $0.label })")
}
print("--------------- Add Ons ---------------")
```

as you suggested inside the `init` method of `ProductFormViewController`, I get an error `Value of type 'ViewModel.ProductModel' has no member 'product'`.

**Comment by Ecarrion** [comment]
Hey @pmusolino, thanks for testing! I copied the wrong text instructions 🤦 
That piece of code is meant to be in `ProductFormViewModel.init(...)` and not in `ProductFormViewController.init(...)` 😇

**Review by pmusolino — APPROVED** [review]
LGTM :shipit:

**Comment by Ecarrion** [comment]
Thanks for the review @pmusolino!

**Pull request merged**
