### PR TITLE
Customize table view style for list selector

### PR DESCRIPTION
**Pull request by jaclync**
Update ListSelectorViewController's table view from xib to code to enable DI'ing the table view style since it's set in initialization for #2037 

## Changes

- Replaced `ListSelectorViewController.xib` with a table view manually set up in `ListSelectorViewController`
- DI'ed `tableViewStyle: UITableView.Style` to `ListSelectorViewController` with default of grouped style
- In `FilterListViewController`, set up the list selectors for the filters and filter options to have plain table view style
- In `ListSelectorViewController`, moved `command.configureCell` to after the default cell `accessoryType` setup so that it could override the `accessoryType` (e.g. to display a disclosure indicator in the filter list selector)
- In `PaginatedListSelectorViewController`, fixed the nib name in initializer (was using `ListSelectorViewController.xib` before) and set the table view style from `plain` to `grouped` in its xib

## Testing

- Go to the Products tab
- Tap the "Filter" CTA --> the filter list selector should have **plain** table view style
- Tap on a filter type row --> the filter option selector should have **plain** table view style
- Tap "Dismiss" to dismiss the filter products UI
- Tap on a simple Product
- Tap on the price row
- Tap on the tax status row --> the list selector should have **grouped** table view style
- Leave the tax status selector back to the price settings
- Tap on the tax class row --> the paginated list selector should have **grouped** table view style

## Example screenshots

mode \ screen | filter products | filter products by product type | product tax status
-- | -- | -- | --
dark | Simulator Screen Shot - iPhone 11 - 2020-05-05 at 09 07 08 | Simulator Screen Shot - iPhone 11 - 2020-05-05 at 09 07 18 | Simulator Screen Shot - iPhone 11 - 2020-05-05 at 09 07 39
light | Simulator Screen Shot - iPhone 11 - 2020-05-05 at 09 07 59 | Simulator Screen Shot - iPhone 11 - 2020-05-05 at 09 08 22 | Simulator Screen Shot - iPhone 11 - 2020-05-05 at 09 08 30

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by Garance91540** [comment]
@jaclync what's our rationale to display plain or grouped table view on different screens? 

A quick note, can we make the screen titles ("Product type") title-cased? ("Product Type")
Same thing for the row titles ("Stock Status", "Product Status"...). To keep it consistent with the other screens on iOS

**Comment by jaclync** [comment]
> what's our rationale to display plain or grouped table view on different screens?

@Garance91540 I was following the design (screenshot below) and the filter screens seem to be using plain table view style 😄do you think grouped table view style might be more suitable for these screens?

Screen Shot 2020-05-05 at 4 50 03 PM


> A quick note, can we make the screen titles ("Product type") title-cased? ("Product Type")
Same thing for the row titles ("Stock Status", "Product Status"...). To keep it consistent with the other screens on iOS

Thanks for catching the screen titles not using the title case, will update! just double checking on the row titles, the design (like the screenshot above) doesn't use the title case right now, could we update the design so that the design has the source of truth for future reference?

**Comment by Garance91540** [comment]
Hi @jaclync ! Let's keep plain views/grouped views as you have them now. I updated the designs to reflect the title casing updates. Thank you!

**Comment by jaclync** [comment]
@pmusolino great catch on the cell background in dark mode! I checked the cell's content view background color, and it was nil in the PR branch and `develop` so I believe the table view style also sets a different default cell background color for plain vs. grouped style. I added the call to configure the default background color in https://github.com/woocommerce/woocommerce-ios/pull/2239/commits/a2fcf5f75666931dcba7cd7eead09e1ff0059ea6 with screenshots below!

@Garance91540 thanks for updating the design! here are the screenshots:


filter products | stock status | product status | product type
-- | -- | -- | --
Simulator Screen Shot - iPhone 11 - 2020-05-11 at 11 29 04 | Simulator Screen Shot - iPhone 11 - 2020-05-11 at 11 29 08 | Simulator Screen Shot - iPhone 11 - 2020-05-11 at 11 29 11 | Simulator Screen Shot - iPhone 11 - 2020-05-11 at 11 29 18

**Pull request merged**
