### PR TITLE
[ExPlat] Add A/A test to the app

### LINKED ISSUE #7407: [ExPlat] Add A/A test to the app
We need to add the following A/A test (experiment) to the app: `woocommerceios_explat_aa_test_202208`

To add an ExPlat experiment to the app, add a new case to the `ABTest` enum in the `Experiments` framework.

The goal of this experiment is to see if there is any bias in our assignment implementation of ExPlat. Because this is an A/A experiment, there will be no differences between the control and treatment variations, so there's nothing more to be added aside from the test itself (to assign users to a control or treatment group).

Experiment design (internal ref): pbxNRc-1QS-p2

### PR DESCRIPTION
**Pull request by ealeksandrov**
Closes: #7407

## Description

It's a simple change adding A/A experiment name to the app.

Experiment design (internal ref): pbxNRc-1QS-p2

### CODE REVIEW

**Comment by rachelmcr** [comment]
I just updated the status of this PR to put it on hold for now:

Let's wait for the Abacus setup to be done before adding this test. That way, we can test that the control/treatment assignment is working as expected before merging the PR. There's more about doing that testing here: PCYsg-Fq7-p2#4-testing-the-experiment-code

We need this ExPlat/Abacus setup to be done first:

1. Support for making test assignments for the `woocommerceios` platform
2. Our `woocommerceios` metrics added to Abacus
3. The test to be fully set up in Abacus (I'll do this step once the first two are done)

I'll come back to review/test this PR once that's done.

**Review by rachelmcr — APPROVED** [review]
The A/A experiment is set up in Abacus in `staging` (the test is not yet running).

I confirmed that when logged in to an a8c account (required for testing the experiment setup while in staging) the experiment works as expected in the app:

1. When the app is launched (first time or after force closing and reopening the app), the experiments `assignments` endpoint fetches an assignment for this test. (In my case it returned `null` which is what is returned for the `control` group.)
2. The exposure event for this test (`*_application_opened`) is fired as expected.

Since there is no difference between the control and treatment behavior in this A/A test, this should be sufficient for testing this experiment setup. @aaronyan should we wait to merge this PR until we receive a code review from an experiment reviewer?

(Also, I noticed the unit tests are failing on this PR but it's a known flaky test as reported in https://github.com/woocommerce/woocommerce-ios/issues/7425.)

**Comment by aaronyan** [comment]
Awesome, exciting to see this A/A test close to shipping! And thanks for testing, LGTM. I would recommend making sure users can be assigned `treatment` too. Does using the [Abacus bookmarklet](PCYsg-Fq7-p2#abacus-assignment-bookmarklet) work to manually assign yourself to the `treatment` variation?

For the exposure event, does it fire after the assignment? If not, then we can either remove the exposure event from the experiment model in Abacus or choose a different exposure event. Since this is an A/A experiment, it doesn't matter too much to have or not have an exposure event.

This will count as an experiment code review, so we can check that off after we confirm `treatment` also gets assigned.

**Comment by rachelmcr** [comment]
Thanks for reviewing this!

> I would recommend making sure users can be assigned treatment too. Does using the [Abacus bookmarklet](https://github.com/woocommerce/woocommerce-ios/pull/PCYsg-Fq7-p2#abacus-assignment-bookmarklet) work to manually assign yourself to the treatment variation?

Yep, I manually assigned myself to the `treatment` variation and received the expected assignment:

```
"variations": {
	"woocommerceios_explat_aa_test_202208": "treatment"
},
```

> For the exposure event, does it fire after the assignment?

It does. 👍  For future reference, I checked this by setting breakpoints in `ExPlatService.swift:80` (where we handle `completion(assignments)`) and in `WooAnalytics.swift:183` (where we fire the `*_application_opened` event) and confirmed I hit the assignment breakpoint first, and then the Tracks breakpoint.

**Pull request merged**
