### PR TITLE
Products: tapping on row begin editing of the text field

### LINKED ISSUE #2148: Product Details: Tapping on row should begin editing that field
**Describe the bug**
Whenever a user taps on the row of an editable field, we should begin editing that field. It's hard to tap on the UITextField directly when the content is tiny to start with.

**To Reproduce**
1. Go to a product.
2. Tap on prices.
3. Try to edit a sale price that is $0.

**Screenshots**
IMG_0008

The tap area is smaller than the square in this screenshot.

**Expected behavior**
Tapping anywhere on that row should position the cursor into the text field and begin editing.

**Mobile Environment**
Please include:
- Device: iPhone 6s Plus
- iOS version: 13.x
- WooCommerce iOS version: 4.0.1

### PR DESCRIPTION
**Pull request by pmusolino**
Fixes #2148 

## Description
Now when a user taps on the row of an editable field in Products, we begin editing that field, since it was hard to tap on the UITextField directly when the content is tiny.

## Testing
1. Go to a product
2. Tap in prices
3. Tap everywhere inside the regular price cell or inside the sale price cell. You will see the text field which becomes the first responder.
4. Do the same with the Shipping fields.
5. Do the same with the SKU field in Inventory.

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pmusolino** [comment]
Thanks @shiki for noticing it. I think that makes this improvement can be easy.
I created an issue here specifically for the price screen https://github.com/woocommerce/woocommerce-ios/issues/2160 but I'm sure that there are other sections in the app that needs an improvement under this aspect 🗡️ 

> It's also not obvious that the title can be tapped.

Do you mean always about the VoiceOver or in general?

**Comment by shiki** [comment]
> Do you mean always about the VoiceOver or in general?

That's correct. 🙂

**Comment by jaclync** [comment]
@shiki what order of VoiceOver commands do you think is a good experience for this case (Product Price Settings > edit regular/sale)?

**Comment by pmusolino** [comment]
Since I'm merging this PR, we can continue the discussion inside the issue, just for not missing anything 😃  https://github.com/woocommerce/woocommerce-ios/issues/2160

**Comment by shiki** [comment]
> what order of VoiceOver commands do you think is a good experience for this case (Product Price Settings > edit regular/sale price)?

@jaclync My idea is that all of this is just **one accessible element**:



- When the element is highlighted, VoiceOver would speak “Price, 15.01 dollars”.
- When the user activates that element using VoiceOver, the keyboard is shown and editing starts

I'm only 80% sure that this is possible to set up. 😄 But I believe this will lead to a better experience because there would be fewer accessible elements on the screen.

**Pull request merged**
