### PR TITLE
Adds ManageProductCategories feature flag #2000

### PR DESCRIPTION
**Pull request by Ecarrion**
# Why

This tiny PR aims to start the development of the [Manage Categories feature](https://github.com/woocommerce/woocommerce-ios/issues/2000) 

I've submitted only the feature flag code in case someone considers working with a feature branch is better for this case, however I think that working under a feature flag is easier to manage and maintain.

# How
- Adds `.editProductsRelease3` case
- Enable it when `BuildConfiguration.current == .localDeveloper` and `BuildConfiguration.current == .alpha`

### CODE REVIEW

**Comment by Ecarrion** [comment]
@shiki tiny PR to kick-of the manage categories feature. :-)

**Comment by pmusolino** [comment]
Just a suggestion @Ecarrion. 
I think that the flag can be called `editProductsRelease3` since behind it we will enable other features. Product Categories will be only the first functionality, and it won't be released until the rest are ready.
Furthermore, I would add in the condition `|| BuildConfiguration.current == .alpha`

**Comment by Ecarrion** [comment]
@pmusolino Thanks for the info! I have updated the PR

> BuildConfiguration.current == .alpha

I assume that is for internal releases, right?

**Comment by pmusolino** [comment]
@Ecarrion exactly. 👍 
`Production-like build but with more enabled to help people test branches, that might be behind feature flags.`

**Pull request merged**
