### PR TITLE
[Tooling] Only run UI Tests on trunk

### PR DESCRIPTION
**Pull request by AliSoftware**
## Description

As discussed in p91TBi-cBM-p2#comment-13736 

With the UI Tests currently being quite unstable and hindering the merging of PRs, the team has decided to only run them on `trunk` after PRs are merged, instead of having their flakiness block the PRs, until the flakiness is resolved.

## Testing information

 - [x] Ensure the CI doesn't run the 2 UI Tests jobs on this PR
 - [x] Ensure the "UI Tests" CI checks are not marked as required by the GitHub branch protection and thus that this PR can still be merged without those having run
 - [ ] Once this PR is merged, ensure that the 2 UI Tests jobs are still run on the resulting merge commit on `trunk`

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by malinajirka — COMMENTED** [review]
@AliSoftware Thanks for working on this 🙇!  If I understand the PR correctly, it won't be run at all for betafixes and hotfixes, is that correct? Would it be possible to enable UI tests on `trunk` and `release/...` branches?

**Comment by AliSoftware** [comment]
> If I understand the PR correctly, it won't be run at all for betafixes and hotfixes, is that correct?

Correct, the condition being `build.branch == 'trunk'` will only make them run on `trunk` not on `release/*`.

> Would it be possible to enable UI tests on `trunk` and `release/...` branches?

Sure, just pushed fb5ce66862 to adjust the condition so they also run on `release/*` now too.

This wasn't requested in the original P2 comment though, which only mentioned `trunk`; so I just want to check with @toupper that running them on `release/*` too was also what they had in mind, so that the whole team is in agreement on this.

**Comment by toupper** [comment]
> This wasn't requested in the original P2 comment though, which only mentioned trunk; so I just want to check with @toupper that running them on release/* too was also what they had in mind, so that the whole team is in agreement on this.

Thanks @AliSoftware for the quick changes, and @malinajirka for the suggestions! Indeed, it would be great to have them also when we merge on release branches 👍

**Review by malinajirka — APPROVED** [review]

**Review by toupper — APPROVED** [review]

**Comment by AliSoftware** [comment]
Confirmed via https://github.com/woocommerce/woocommerce-ios/pull/14667 / https://buildkite.com/automattic/woocommerce-ios/builds/26769 that if the branch name is `release/*` the UI Tests will run 🙂

**Pull request merged**
