### PR TITLE
Updates tracks

### PR DESCRIPTION
**Pull request by aerych**
Refs https://github.com/Automattic/Automattic-Tracks-iOS/pull/142

Updates to the latest version of tracks

To test:
Run the branch.
Visit the tracks dashboard. Look at live events for your user. Confirm that you see the updated device width and height properties.

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

cc @aforcier 

@shiki could I trouble you for a review of this one?

### CODE REVIEW

**Comment by loremattei** [comment]
Hey! I'm moving it to 4.9 since 4.8 has been cut! If you want this to make it to 4.8, please feel free to move it back, target the release branch and ping me to build another beta.

**Comment by aerych** [comment]
No worries at all!  Thanks Lore!

**Comment by aerych** [comment]
Pushed an update to resolve a Podfile.lock conflict. Apparently some unwanted Podfile.lock changes were incorporated into that merge, so I did it over and force pushed just the changes to fix the merge conflict.  Waiting on CI to go green.

**Comment by aerych** [comment]
Thanks again @shiki !

**Pull request merged**
