### PR TITLE
 Order Fulfillment: Allow the user to delete package tracking details

### PR DESCRIPTION
**Pull request by ctarda**
Implements #851 

This PR brings back the UI to delete a shipment tracking, removed during the review of PR #817 to reduce the scope.

The big issue here is that I haven't been able to make deletion work. On the bright side, running the branch as it is and trying to delete a shipment tracking will help test that the error notice is presented.

Simulator Screen Shot - iPhone 8 - 2019-04-10 at 11 59 54

## Changes:
- Minor changes to `ManualTrackingViewModel` and its two implementations (and its tests) to expose the style of the accessory view in the top cell.
- Minor changes to `FulfillViewController` to bring back the code that launches the UI
- Some changes to `ManualTrackingViewController` to remove the spinner when an action (save or delete) fails

The functionality is somehow more limited that what the original design suggested. As discussed, the backend API does not seem to support updating trackings, so we only allow users to delete them.

## Testing
- Checkout the branch, run the tests
- Navigate to an order with shipment trackings > Fullfill order
- Tap a shipment tracking
- Tap "Delete Tracking". At this moment, that should show an error notice (as mentioned, deleting does not actually work right now)

@bummytime @mindgraffiti could you please 👀 ? 

Also, could you please take a look at the code that deletes the tracking (that'd be `ShipmentsRemote.deleteShipmentTracking`) I assume there is something obvious that I am missing but I just can't see it.

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by bummytime** [comment]
@ctarda — Ok I got `DELETE` working. Check out the `JetpackRequest.swift` I updated here:

https://gist.github.com/bummytime/0060e5296cbac49c5bdf53b31ec00330

Copy + paste into XCode over the top of the existing `JetpackRequest.swift` to see what I changed.

There were two fundamental things that needed to be fixed:

1. When we hit the JP tunnel endpoint (e.g. `/rest/v1.1/jetpack-blogs/$(siteID)/rest-api/?json=true&path=XXXX`), we _must_ use a `GET` or `POST` request...even if we want to send a `DELETE` to the actual store site. `JetpackRequest` was hitting the tunnel URL with a `DELETE` verb. 

2. With that ☝️  fix out of the way, I still was having issues. So I sniffed the network traffic the app was sending to the server. Turns out the `_method` param was not getting properly url-encoded.

Before my fix:
```
/rest/v1.1/jetpack-blogs/xxxxxx/rest-api/?_method=delete&json=true&path=/wc/v2/orders/296/shipment-trackings/cabb0a506bba5d9b2077de4f53253449
```

After my fix:
```
/rest/v1.1/jetpack-blogs/xxxxxx/rest-api/?json=true&path=/wc/v2/orders/296/shipment-trackings/208ee157bf26a6871e8cf7b2a9349913%26_method%3Ddelete
```

See how `_method=delete` becomes `%26_method%3Ddelete`? That is all it took. 😄 

So, feel free to integrate these changes from my gist into your PR. There is **one giant caveat though** -->  please test across the entire app since this is a fundamental change to ALL tunneled requests. Based on my quick tests, everything still seems to work without issue. 😄 

/cc @mindgraffiti

**Comment by bummytime** [comment]
One other thing @ctarda, with my change to `JetpackRequest.swift` ☝️☝️☝️, you can still call `JetpackRequest` with `method: .delete` (in `ShipmentsRemote.deleteShipmentTracking`) — so nothing has to change there. 😄

**Comment by ctarda** [comment]
Thanks a bunch @bummytime .

I just pushed an update with deletion finally working! 🎉  So I guess this is ready for a proper review now...

**Comment by bummytime** [comment]
One other thing @ctarda we should probably add another test unit to `JetpackRequestTests` for the updated `DELETE` logic. Something like:

```swift
    /// Verifies that a DELETE JetpackRequest will actually become a GET with a `&_method=delete` query string parameter.
    ///
    func testDeleteRequestBecomesGetRequest() {
        let request = JetpackRequest(wooApiVersion: .mark3, method: .delete, siteID: sampleSiteID, path: sampleRPC, parameters: sampleParameters)

        let output = try! request.asURLRequest()
        XCTAssertEqual(output.httpMethod?.uppercased(), "GET")
        XCTAssertTrue((output.url?.absoluteString.contains("%26_method%3Ddelete"))!)
    }
```

**Comment by ctarda** [comment]
Thanks for looking at this folks, and in particular for catching those constraints breaking. I always test on iPhone 5s, iPhone 8, iPhone XR and iPad Pro 11. Turns out the constraints were breaking on an iPhone X 🤷‍♂️ 

I pushed an update that:
- adds the missing unit test to `JetpackRequestTests`
- disables the delete button while the delete operation is ongoing.
- fixes the breaking constraints.

**Comment by ctarda** [comment]
Thanks folks! Merging!

**Pull request merged**
