### PR TITLE
CircleCI: Update Xcode to 11.4

### PR DESCRIPTION
**Pull request by shiki**
In the [`issue/927-observables`](https://github.com/woocommerce/woocommerce-ios/tree/issue/927-observables) branch, I wanted to use [`XCTSkipIf`](https://developer.apple.com/documentation/xctest/3521325-xctskipif) to conditionally skip a unit test if the simulator is less than 13.0. Example:

https://github.com/woocommerce/woocommerce-ios/blob/c5d0cff51d44b957a1772bed5efc1804be0cfee1/WooCommerce/WooCommerceTests/Tools/Observables/PublishSubjectTests.swift#L234-L238

Using `XCTSkipIf()` allows better messaging when the tests are executed using an older simulator. The skipped tests are mentioned in the result:

```
Test Suite 'PublishSubjectTests' passed at 2020-04-24 09:20:55.451.
	 Executed 10 tests, with 5 tests skipped and 0 failures (0 unexpected) in 0.024 (0.068) seconds
Test Suite 'WooCommerceTests.xctest' passed at 2020-04-24 09:20:55.452.
	 Executed 10 tests, with 5 tests skipped and 0 failures (0 unexpected) in 0.024 (0.069) seconds
Test Suite 'Selected tests' passed at 2020-04-24 09:20:55.452.
	 Executed 10 tests, with 5 tests skipped and 0 failures (0 unexpected) in 0.024 (0.070) seconds
```

However, `XCTSkipIf` is only available for Xcode 11.4+. This PR updates the CircleCI config from 11.2.1 to 11.4.1 to solve this. 

## Questions

Is this okay? 😬Will this affect any of the release processes? 

## Testing

I believe checking if the build passed is good enough. 

## Reviewing 

Only 1 reviewer is needed but anyone can review. 

---

Heads up @pmusolino @jaclync. This shouldn't be a problem for us too, right?

### CODE REVIEW

**Comment by loremattei** [comment]
Hey @shiki! I've just run the Installable Builds to double check that everything works as expected. 
Also, note that from the next release, the production builds will run on the CI, so this change will impact them. 
I'm not aware of any issue related to this and if everyone on the team is on 11.4, I think we're good to go.

**Comment by jaclync** [comment]
We have a color issue that is Xcode 11.4 and certain device types only: https://github.com/woocommerce/woocommerce-ios/issues/2138 - not sure if this is worth fixing if we are updating CI to use Xcode 11.4?

**Comment by shiki** [comment]
Sorry, everyone. I looked at the issue Jaclyn shared today and it looks like that might be something we have to look closer into before we move forward with using Xcode 11.4. 

I'll close this for now until we can get #2138 resolved. 

Thank you for your time. 🙇

**Comment by mokagio** [comment]
No worries @shiki 👍 Let me know if you'll need a hand with the upgrade once that's fixed.

**Pull request closed without merging**
