### PR TITLE
Blaze: Update eligibility check to enable Blaze for JCP sites with the Blaze plugin

### LINKED ISSUE #13487: Enable Blaze for sites with Jetpack CP connection and Blaze Ads plugin
Checking if the Blaze plugin is installed requires fetching store plugins => the eligibility check need to be async again.
=> We need to revert changes to the check in all places: hub menu, dashboard, product form.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #13487

## Description

Previously, we disable Blaze for all JCP sites since Blaze DSP requires full Jetpack sync to work properly. Since the new Blaze plugin supports full JP sync, we should enable Blaze entry points to JCP stores with this plugin.

This PR updates the Blaze eligibility check by retrieving for site plugins and check if there is Blaze plugin installed and activated to enable Blaze for JCP sites. ~~To avoid repeatedly fetch from the remote, the check returns true immediately if the the Blaze plugin can be found in storage from a previous sync request.~~ We always fetch system plugins from the remote to get the most updated details about active plugins.

The above change also makes the check async again, so I reverted the changes in dashboard/hub menu/product form to support the async check.

## Steps to reproduce

- Pre-requisite: create a self-hosted site and install the [Blaze plugin](https://woocommerce.com/products/blaze-ads/).
- Build the app and log in to the test store.
- Confirm that the entry point to Blaze in dashboard/hub menu/product form are enabled for the site.
- Deactivate or uninstall the Blaze plugin on the same site - confirm that the entry points to Blaze is no longer available.

## Screenshots

N/A

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [ ] This PR includes refactoring; smoke testing of the entire section is needed.

### CODE REVIEW

**Comment by hafizrahman** [comment]
I ran into this exception when logging in, and also when restarting and just My Store is loading:

Screenshot 2024-08-05 at 18 39 12

**Review by hafizrahman — APPROVED** [review]
After the last updates, the issue I mentioned no longer appeared. Thanks for that!

This looks good to me. What I want to add is the case after deactivating the plugin:
1. My Store: The card disappears after refreshing, all good here.
2. Product details: The promotion button disappear after entering a product detail.
3. More menu: In this case the Blaze button persists and I'm not sure what will make it go away (aside from switching store/logging out and in again).

I think for point 3 it's an edge case, but perhaps we can later think about how to make deal with this situation. Maybe check eligibility when the button is tapped?  Then we can inform merchants that the plugin is deactivated and they need to enable it again to get things going. But it's clearly out of scope of this PR.

**Comment by itsmeichigo** [comment]
Thank you @hafizrahman for the reviews! 

Regarding deactivating the Blaze plugin, I assume you have the Google Ads plugin in your test store, that's why refreshing the dashboard removes the Blaze card. The reason is that the Google Ads eligibility check always fetches system plugins from the remote.

In the case where the Google Ads plugin is unavailable, I'm afraid the Blaze plugin will not removed unless switching stores since I was checking in the storage first. I removed the storage check to avoid outdated plugins in 325af433e0f1a743a8d4c54b3fd3fb2689b2b99b, even though I'm concerned we might be requesting from the remote quite often if we have both Blaze and Google Ads in a store.

To update Blaze on the hub menu, I added a change in 9c77018a8e76cf2e2bb88bf9028bc30ec15028a2 to always check Blaze eligibility again upon entering the view. This ensures that the Blaze button be hidden when the plugin is deactivated.

This PR is ready for another look when you can.

**Comment by hafizrahman** [comment]
Ran into a situation about being able to create the campaign even when the plugin is disabled. We've discussed and reached a conclusion for it in p1722941187348779-slack-C03L1NF1EA3 , so with the additional changes above I think this is good to go.

> I removed the storage check to avoid outdated plugins in https://github.com/woocommerce/woocommerce-ios/commit/325af433e0f1a743a8d4c54b3fd3fb2689b2b99b, even though I'm concerned we might be requesting from the remote quite often if we have both Blaze and Google Ads in a store.

This is a valid concern but I think the combination of both existing in the app might be a bit low right now, so we can keep it this way and monitor it.

> To update Blaze on the hub menu, I added a change in https://github.com/woocommerce/woocommerce-ios/commit/9c77018a8e76cf2e2bb88bf9028bc30ec15028a2 to always check Blaze eligibility again upon entering the view. This ensures that the Blaze button be hidden when the plugin is deactivated.

Looks good!

**Pull request merged**
