### PR TITLE
Remove the 'Excluded Architectures' setting in the Watch App target

### PR DESCRIPTION
**Pull request by crazytonyli**
> [!Note]
> This PR is built on top of https://github.com/woocommerce/woocommerce-ios/pull/12960.

This PR removes the `EXCLUDED_ARCHS` build setting on the 'Woo Watch App' target. I have tested the app can build on iOS simulator, iOS device, and "Any iOS device" destinations.

@Ecarrion Do you mind testing this PR? Maybe on a real Apple Watch? I don't have a test Apple Watch.

----

In https://github.com/woocommerce/woocommerce-ios/pull/12960, the 'NetworkingWatchOS' target's Base SDK was changed from 'Automatic' to 'watchOS'. I wonder if using 'Automatic' was the reason that we have to set `EXCLUDED_ARCHS=arm64` in order to compile the app (see pdnsEh-1DQ-p2 for context).

Xcode should build `arm64` code for iOS devices, but should not build `arm64` code for watchOS devices, because no Apple Watch is on `arm64` arch. Maybe Xcode got confused by the 'Automatic' Base SDK build setting.

### CODE REVIEW

**Review by Ecarrion — DISMISSED** [review]
~Great work @crazytonyli!~

~I'm now able to run `iOS SwiftUI Previews` fine! Unfortunately `WatchOS Previews `are still not working :-/~

~If you want to give them a look you could test with the `ConnectView.swift` file~

Hey @crazytonyli, I was able to compile in both device and watch but these changes break the `SwiftUI Previews` 😅

**Comment by crazytonyli** [comment]
Good catch! I'll close this PR and keep the 'Excluded Architectures' setting then.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/208">19.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by crazytonyli** [comment]
@Ecarrion Can you give it a another go, but removing the derived data first (`~/Library/Developer/Xcode/DerivedData/WooCommerce-*`)? That worked for me.

**Review by Ecarrion — APPROVED** [review]
>  Can you give it a another go, but removing the derived data first (~/Library/Developer/Xcode/DerivedData/WooCommerce-*)? That worked for me.

I could swear I did this before, but maybe I didn't because now it's working well 😅

**Pull request merged**
