### PR TITLE
Barcode scanner CTA behind a feature flag

### PR DESCRIPTION
**Pull request by jaclync**
CTA behind a feature flag for #2407 

## Changes

- Created a feature flag `barcodeScanner` that is enabled for debug and installable builds
- Added the scan icon (with name `icon-scan`) to the image asset catalog
- In `ProductsViewController`, added a scan CTA to the navigation bar right item if the `barcodeScanner` feature flag is enabled (no-op for now)

## Testing

- Go to the Products tab --> the scan CTA in the navigation bar should be visible only in debug & alpha builds

## Example screenshots

Light | Dark
-- | --
Simulator Screen Shot - iPhone 11 - 2020-06-09 at 10 06 02 | Simulator Screen Shot - iPhone 11 - 2020-06-09 at 10 06 11

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by Garance91540** [comment]
Hi @jaclync , cool!!!

I just have a note on the alignment of the barcode with the other elements of the screen: it looks like it's a bit too left. Can we make sure it's aligned with the other elements?

Screen Shot 2020-06-09 at 3 04 16 PM

**Comment by jaclync** [comment]
> I just have a note on the alignment of the barcode with the other elements of the screen: it looks like it's a bit too left. Can we make sure it's aligned with the other elements?

@Garance91540 the placement of the navigation bar elements is determined by iOS, and right now the image margin is already 0. we might have to set a negative value to the `imageInsets` if we want to align the navigation bar items with the 16px spacing in other UI elements. I created a separate issue https://github.com/woocommerce/woocommerce-ios/issues/2410 to update the alignment since it requires some testing to make sure the negative insets work for different device types and orientations.

Screen Shot 2020-06-10 at 1 17 09 PM


> So GridIcons does not have a scan image, eh? 😐

@shiki yea, I couldn't find the barcode in the [a8c Gridicons library](http://automattic.github.io/gridicons/) so had to add it manually 😐

**Comment by Garance91540** [comment]
>@Garance91540 the placement of the navigation bar elements is determined by iOS, and right now the image margin is already 0. we might have to set a negative value to the imageInsets if we want to align the navigation bar items with the 16px spacing in other UI elements. I created a separate issue #2410 to update the alignment since it requires some testing to make sure the negative insets work for different device types and orientations.

gotcha, in this case, I edited the barcode icon to update its internal margin so alignment should work better without needing negative padding

[Products - Inventory Scanning (9).zip](https://github.com/woocommerce/woocommerce-ios/files/4756821/Products.-.Inventory.Scanning.9.zip)

**Comment by Garance91540** [comment]
>@Garance91540 the placement of the navigation bar elements is determined by iOS, and right now the image margin is already 0. we might have to set a negative value to the imageInsets if we want to align the navigation bar items with the 16px spacing in other UI elements. I created a separate issue #2410 to update the alignment since it requires some testing to make sure the negative insets work for different device types and orientations.

Gotcha, in this case, I edited the barcode icon to update its internal margin so alignment should work better without needing negative padding

[Products - Inventory Scanning (9).zip](https://github.com/woocommerce/woocommerce-ios/files/4756821/Products.-.Inventory.Scanning.9.zip)

**Comment by Garance91540** [comment]
>@Garance91540 the placement of the navigation bar elements is determined by iOS, and right now the image margin is already 0. we might have to set a negative value to the imageInsets if we want to align the navigation bar items with the 16px spacing in other UI elements. I created a separate issue #2410 to update the alignment since it requires some testing to make sure the negative insets work for different device types and orientations.

Gotcha, in this case, I edited the barcode icon to update its internal margin so alignment should work better without needing negative padding

[Products - Inventory Scanning (9).zip](https://github.com/woocommerce/woocommerce-ios/files/4756821/Products.-.Inventory.Scanning.9.zip)

**Comment by jaclync** [comment]
> I think maybe the dropdown arrow is the issue? Can we address this in a different PR?

@Garance91540 did you mean the dropdown arrow should be more left, or the barcode icon more right? If we want to shift the barcode icon to more right, then we probably have to set a negative inset as in https://github.com/woocommerce/woocommerce-ios/issues/2410. if we're doing this, do you know if we are just shifting the icon on the Products tab, not the other tabs?

**Comment by Garance91540** [comment]
> @Garance91540 did you mean the dropdown arrow should be more left, or the barcode icon more right? If we want to shift the barcode icon to more right, then we probably have to set a negative inset as in #2410. if we're doing this, do you know if we are just shifting the icon on the Products tab, not the other tabs?

@jaclync it's a bit hard for me tell which icon is the guilty one bc what's live in prod seems a bit off from the designs (On Figma, all the icons align well with a 16px right padding). The arrow is the one that looks the most off to me:

Screen Shot 2020-06-11 at 5 41 15 PM

Are we using the gridicon-chevron-down icon?

**Comment by jaclync** [comment]
> Are we using the gridicon-chevron-down icon?

@Garance91540 yes, we use the a8c gridicons `chevron-down` and `chevron-up` for the Products tab top banner. I just checked the trailing margin for the chevron up/down button, and it's currently at 10px instead of the 16px. I added a task to https://github.com/woocommerce/woocommerce-ios/issues/2410 for updating the trailing margin to 16px, and I'll open a PR separately for that.

merging this PR for 4.5, the scan CTA is behind a feature flag that is off in release builds.

**Pull request merged**
