### PR TITLE
Xcode 16 Support

### PR DESCRIPTION
**Pull request by staskus**
Related WordPressAuthenticator PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/856
Related AutomatticAbout PR: https://github.com/Automattic/AutomatticAbout-Swift/pull/10

## Description

Updated dependencies so the project would compile for Xcode 16.

There's still some work required for proper Xcode 16 SDK, especially around new iPadOS tabs. https://github.com/woocommerce/woocommerce-ios/issues/13910

## Steps to reproduce

1. Open a project with this branch on both Xcode 15 and Xcode 16
2. Confirm that the project runs without compiler issues

## Testing information

There are no functionality changes, only 2 fixes to satisfy the compiler. These changes were already integrated in the WordPress-iOS app for several months.

## Screenshots

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.ordPre

### CODE REVIEW

**Review by itsmeichigo — APPROVED** [review]
I tested and confirmed that the changes compile for both Xcode 15.3 and Xcode 16.1 Beta 👍

**Comment by staskus** [comment]
@itsmeichigo thanks for the review! Forgot to mention that there's also a related PR on WP-Authenticator that needs to be reviewed https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/856

**Comment by itsmeichigo** [comment]
@staskus I just approved that PR as well.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/223">20.4</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
