### PR TITLE
Product Category: Support deletion

### PR DESCRIPTION
**Pull request by itsmeichigo**
Part of #10634 

## Description

This PR updates the category list to support deleting items. Changes include: 
- Added the option to delete product categories by adding a swipe action to the category list.
- Added an alert to confirm deletion when the delete  button is tapped.
- Integrated the API to delete product categories:
  - Updated `ProductCategoriesRemote` to add a missing param `force` when deleting categories since this is required by the API.
  - Handled optimistic deletion by hiding the deleted item immediately after the user confirms the deletion to avoid having to add a progress view.
  - Handled any error by showing an alert when necessary. 

## Testing instructions

- Log in to the app and navigate to the Products tab.
- Select an existing product or create a new one if needed.
- Select the category row on the product form or select Add more details > Category if the row is not already available.
- If there are no existing categories in your store, add at least one.
- On the category list, swipe left on any row. You should see a button to delete the item.
- Tap the button, notice a confirm alert is displayed.
- Disconnect the Internet and confirm the deletion. Xcode console should log the confirmation: `🔵 Tracked product_category_settings_delete_button_tapped `.
- Notice the item is removed immediately, and after a while, an error alert is displayed.
- Reconnect the Internet and try deleting the item again.
- The item should be deleted successfully.

Please feel free to check Menu > Coupon > Edit coupon > Select categories. Deleting category should not be enabled on this screen.

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/5533851/8794f37c-e4cc-4703-8079-09e10f66a38f

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by selanthiraiyan — APPROVED** [review]
The code looks good to me. 🎉 

---

> Disconnect the Internet and confirm the deletion. Xcode console should log the confirmation: 🔵 Tracked product_category_settings_done_button_tapped.

I hope you meant the `product_category_settings_delete_button_tapped` event. If yes, the delete button event gets tracked as expected.

---

https://github.com/woocommerce/woocommerce-ios/assets/524475/290b8d39-fb20-419a-8569-96827e10128e

> Notice the item is removed immediately, and after a while, an error alert is displayed.

The category is not added again after a network error. Is this expected behaviour?

**Comment by itsmeichigo** [comment]
> I hope you meant the product_category_settings_delete_button_tapped event. If yes, the delete button event gets tracked as expected.

Oh yes, I think I pasted the wrong event name in the PR description 😅 

> The category is not added again after a network error. Is this expected behaviour?

Good catch! I added a change to restore the item in local storage after deletion fails. Could you try again to see if it works? Thanks @selanthiraiyan.

**Review by selanthiraiyan — COMMENTED** [review]
I think an edge case exists in which the category is deleted, but the product isn't updated. i.e. The product detail screen shows a deleted category, and that category isn't listed in the category list screen.

The below product from the screen recording has "Shoes" as category which is already deleted.  

https://github.com/woocommerce/woocommerce-ios/assets/524475/56a9bd1b-6af3-4909-9c0a-34b07d82aadf

**Comment by itsmeichigo** [comment]
> I think an edge case exists in which the category is deleted, but the product isn't updated. i.e. The product detail screen shows a deleted category, and that category isn't listed in the category list screen.

@selanthiraiyan Could you share the steps to reproduce this issue? Could you also verify on the web whether the category still exists and the product is having that category? Thanks!

**Review by selanthiraiyan — APPROVED** [review]
> Could you share the steps to reproduce this issue? Could you also verify on the web whether the category still exists and the product is having that category?

I tested it again now and noticed this is not a consistent behaviour. Sorry about that.

The steps are,
- Add a new category and make it the only selected category for a product.
- Save the product
- Reopen the product -> Edit category -> Delete the selected category
- Save category edit progress by tapping "Done"
- The category is deleted successfully from the web.
- The deleted category is still listed in the product detail screen

I will share a screen recording in Slack.

 I am approving the PR, as the other parts of this PR work as expected. 🚀

**Comment by itsmeichigo** [comment]
Thank you Sharma! I just pushed a fix in 24e1e3d92ad0f46d2180c19a85d9e8541ff2aa9f - the cause was that the optimistic deletion didn't take into account the selected state. I had to update the state before triggering the remote update. The bug should be fixed now 🙇‍♀️

**Pull request merged**
