### PR TITLE
[Watch] Add app link complication

### LINKED ISSUE #12503: Introduce complications support
We should allow our watch app to be accessible from a watch face complication. It should be the app icon and behave as the launcher.

Image

```[tasklist]
### Tasks
- [x] Register the complication service/declaration in the Watch app
- [x] Configure the complication with the Woo logo and purple background
```

### PR DESCRIPTION
**Pull request by Ecarrion**
Closes: #12503 

# Why

This PR adds a simple icon as a complication so users can launch the app easily from their watch face.

# How

- Improve and Reuse code from our current lock screen widget
- Add the necessary provisioning profiles.

## Screenshots

Simulator Screenshot - Apple Watch Series 9 (45mm) - 2024-05-29 at 11 55 01

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by mokagio** [comment]
@Ecarrion I pushed to the branch directly for the sake of unblocking. In hindsight, opening a PR would have been little overhead but oh well...

I took the occasion to do a bit of tidy up in the project configuration by removing unnecessary target-level overrides in favor of centralized `xcconfig` settings, and upgrading from the old "iOS Developer|Distribution" to the modern "Apple Development|Distribution".

I tested the builds for both App Store and Enterprise (Prototype) locally:

image

CI will soon show if there's additional work to do, at least for the Prototype build. We'll know about the App Store version only once it'll reach TestFlight as part of a release.

**Comment by mokagio** [comment]
> CI will soon show if there's additional work to do, at least for the Prototype build

There was a minor issue due to a var name lost in extracting a lane. Now fixed [and CI is green](https://buildkite.com/automattic/woocommerce-ios/builds/21840).

**Comment by Ecarrion** [comment]
Thanks for all the help @mokagio 

> I pushed to the branch directly for the sake of unblocking. In hindsight, opening a PR would have been little overhead but oh well...

No problem with this. Feel free to push code to all my branches 😅

**Pull request merged**
