### PR TITLE
Reviews: Add workaround to reload last selected row

### LINKED ISSUE #14640: Reviews: Review still highlighted after marked as read
**Describe the bug**
When selecting an unread review and navigating back to the list, the review is still highlighted.

**To Reproduce**
1. Go to Menu tab > Reviews
2. Tap on an unread review
3. Navigate back to the list
4. Notice that the review is still highlighted. The highlight only goes away after reloading the list.

**Screenshots**
https://github.com/user-attachments/assets/0239193f-2299-4e8f-ac1e-c809b4f40cbf

**Expected behavior**
The highlight should be removed after reading reviews.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #14640 

## Description

This PR adds a quick fix for the highlighted state of the read reviews in the review list. The fix is to reload the last selected row to update its state, which should be more efficient than reloading the whole table.

No unit test was added as the fix was made on the view controller.

## Steps to reproduce

- Leave a new review on your test store.
- Build and run the app.
- Log in to your test store.
- Navigate to Menu > Reviews, notice that the new review is loaded and highlighted.
- Select the new review and then navigate back to the list.
- Confirm that the new review is no longer highlighted.

## Testing information

Tested on simulator iPhone 16 Pro iOS 18.1 and confirmed that new reviews are no longer highlighted after being opened.

## Screenshots

https://github.com/user-attachments/assets/af670fe5-913e-4a51-ac51-0c4fa7458fab

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by iamgabrielma** [comment]
> Navigate to Menu > Reviews, notice that the new review is loaded and highlighted.

I haven't checked the code yet, but the behaviour is different on my end: 

1. I've submitted reviews, then ran the app: No reviews were highlighted
2. I've submitted a review while the app was running, went back to the Settings, went back to "Reviews": The previous reviews were highlighted, but not the new one

https://github.com/user-attachments/assets/9c922bfe-2a2f-4b1a-84a3-7514e27b9dae


3. Navigated back to Settings again, then back to Reviews, now all of them were highlighted:

https://github.com/user-attachments/assets/24b05416-ac31-4c82-b57e-f3cb52dc2b1d

**Review by iamgabrielma — APPROVED** [review]
LGTM 🚢  

The PR fixes the issue described ( highlighted row is no longer highlighted when tapped and then checked again) but there seems to be other issues with product reviews as I could reproduce the behaviour in the videos in trunk, along with product names not being loaded properly the first name a review is loaded.

**Comment by itsmeichigo** [comment]
Thank you @iamgabrielma for the review! I cannot reproduce the issue you found on my end, ~~could you share the environment of your tests?~~ I've created a separate issue in #14719, and updated the environment details following your screencasts.

I'll merge this PR for now.

**Pull request merged**
