### PR TITLE
[Blaze] Check product URL

### LINKED ISSUE #13347: [Blaze] Validate product URL
#### Problem 
Currently, we don't validate that a product has a non-empty `permalink` value to be able to create a Blaze campaign.

Internal - p1721133938444799/1721099021.821499-slack-C01PKMY9T1S

The following happens when a product has an empty string as a `permalink` value. Notice that the campaign is submitted with an empty product URL.

https://github.com/user-attachments/assets/12d19763-3d02-4804-8151-30ecaef9d6b9

#### Reason

I think the product URL becomes empty when the decoding fails due to some unexpected reasons, as mentioned [here](https://github.com/woocommerce/woocommerce-ios/blob/trunk/Networking/Networking/Model/Product/Product.swift#L349-L359). 

#### Solution

Validate that `productURL` is not an empty string [here](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift#L133-L136)

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Closes: #13347 

## Description

Starts validating that the product URL is not empty before submitting a campaign.

#### Design change
As a product with an empty URL is not common, I decided to disable the "Confirm Details" button until a valid URL is selected. I also added the text "Select destination URL" when the URL is empty. 

#### Code changes
- To enable the confirm details button, add validation to check that the URL is not empty. 
- Update the "Ad destination" row content string, asking to select a destination URL when it is empty.
- Stop adding a question mark when parameters are empty.
- Check whether the product URL is empty and fallback to the site URL.
- Unit tests.

## Steps to reproduce

Prerequisites
- Change [this line](https://github.com/woocommerce/woocommerce-ios/blob/trunk/Networking/Networking/Model/Product/Product.swift#L354) and return an empty string instead of decoding the value.

Steps
- Log in to a store eligible for Blaze.
- Navigate to the products tab.
- Open a product's detail page.
- Tap on the "Promote with Blaze" button.
- Validate that you see the "Ad destination" option with text as "Select destination URL".
- Validate that the "Confirm Details" button is disabled until a valid URL is selected.
- Tap on "Ad destination" and select "The site home" option and save.
- The "Confirm Details" button should be enabled. 
- Confirm that you can successfully create the campaign without any errors. 

## Testing information

- Create a Blaze campaign with valid fields and ensure that it can submitted successfully.

## Screenshots

| Before | Now |
|--------|--------|
| image | Simulator Screenshot - iPhone 15 Pro Max - 2024-07-17 at 06 45 40 | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by itsmeichigo** [comment]
@selanthiraiyan I think disabling the Confirm details button would not make it obvious to users what is missing for the campaign. How about keeping the button enabled and displaying an alert about the empty ad destination URL?

**Comment by selanthiraiyan** [comment]
> I think disabling the Confirm details button would not make it obvious to users what is missing for the campaign. How about keeping the button enabled and displaying an alert about the empty ad destination URL?

Good suggestion. I agree, @itsmeichigo. I made the necessary changes to show an error alert if the destination URL is empty. 

Please take another look at the PR when you can. Thank you!

---
📔  GitHub file upload doesn't work for some reason. I will upload a screenshot later.

**Review by itsmeichigo — APPROVED** [review]
Thanks for the update, Sharma! This works as described. I'm approving this PR but there's another enhancement I think we could do - but it should be addressed in a separate PR.

Currently, the Save button is disabled when the URL is empty but then enabled after I add a parameter:



For a better experience, should we let the user pick the URL for the product instead of leaving it empty? A few options I have in mind:
- Display a screen with a text field where the user can paste a URL.
- Display a web view pointing to the site home. The user can navigate to the page they want and tap Done to select the URL of that page.

**Comment by selanthiraiyan** [comment]
Thanks for the review, Huong! 🙇 

>  there's another enhancement I think we could do - but it should be addressed in a separate PR.

I logged an issue [here](https://github.com/woocommerce/woocommerce-ios/issues/13355) to track your suggested enhancement.

**Pull request merged**
