### PR TITLE
Adjust TitleAndTextFieldTableViewCell to use a fixed width

### LINKED ISSUE #5084: Shipping Labels: Misalignment on text fields of Address Form
**Describe the bug**
It looks like there are some inconsistencies with the text field alignments:

| Current | Expected |
| ----- | ----- |
|  |

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix issue #5084 by setting a defined width to the Address field labels in order to keep the field content with the same vertical alignment. I'm not sure if this would be the best approach considering the variation of text sizes from different languages, but I decide to follow this inspired by how it was done in the Order Creation Address form.

Screenshots
==========
| Before  | After |
| ------------- | ------------- |
| IMG_8878 | IMG_8877 |

How to Test
==========
1. Make sure your Woo site supports the Shipping Label plugin and it's correctly configured to work with it
2. Select an Order with the status as `Processing` and select `Create Shipping Label`
3. At the `Create Shipping Label` view, select the `Continue` button under the `Ship From` Address info
4. Verify that all Address fields are correctly aligned as expected.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by itsmeichigo — COMMENTED** [review]
Thank you @ThomazFB for the fix!

However I noticed from my testing that setting a fixed width might affect readability when the font size of the device is large:

| Before | After |
| ----- | ----- |
|  |  |

I like the solution used in Order address forms - but the solution is a bit different. There are [calculations to determine the largest width](https://github.com/woocommerce/woocommerce-ios/blob/1e9cd52dbdc926b1a5cbbf2af9c024e9065591b8/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/Address%20Edit/EditOrderAddressForm.swift#L202-L207) of the titles and select it as the fixed width for all rows. The rows also use [Adaptive Stack](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI%20Components/AdaptiveStack.swift) to make sure that all contents are readable even in large font size:



The alignment for the titles are harder to achieve with UIKit, so I don't really have a good suggestion yet 😅

**Comment by ThomazFB** [comment]
Interesting! Nice scenario example and thanks for your review @itsmeichigo! 🙇 Considering that we don't quite have a straight option to adopt for the UIKit situation, do you believe it would be valid to adopt the Address view used in the Order creations in the Shipping Labels feature? I understand that this would make the fix for this issue here way bigger in terms of code changes, and we would need to adapt that view to the Shipping label needs, but the bulk stuff is already there. WDYT? Do you consider this a worthy modification?

**Comment by itsmeichigo** [comment]
@ThomazFB I think that's a great idea! It'd be nice to use the same UI for both views - but the effort to integrate the view model back in might be large. If you think it's feasible, please go ahead with the update. Thanks! ＼（＠￣∇￣＠）／

**Comment by ThomazFB** [comment]
Hey @itsmeichigo, looping back here after two days of work around migrating the Shipping Label Address form. Migrating the SwiftUI part went quite well, but as you predicted the ViewModel part was the tricky one, especially the error handling part were integrating the ViewController -> ViewModel routine to a SwiftUI -> ViewModel made everything way too complex and it will require much more development time. 

With that said, to avoid wasting too much time on this fix here, I'll halt this fix to start to focus on the Coupons project, close this PR, leave the other branch with all the migration changes I made so far and circle back here when there's more room to tackle this migration. WDYT?

**Comment by itsmeichigo** [comment]
> to avoid wasting too much time on this fix here, I'll halt this fix to start to focus on the Coupons project, close this PR, leave the other branch with all the migration changes I made so far and circle back here when there's more room to tackle this migration

Sounds good, thank you @ThomazFB for looking into this!

**Pull request closed without merging**
