### PR TITLE
Feature/beta builds on ci

### PR DESCRIPTION
**Pull request by loremattei**
This PR introduces release builds on CI.
The builds are triggered by pushing a release tag.
Tags that don't have a version-like format are not considered.
On beta tags (x.y.z.a) the system runs the app store builds.
On final tags (x.z.<z>) the system runs only the app store builds and creates a new release on GitHub.
The artifacts are uploaded to  AppStore.

[This](https://github.com/woocommerce/woocommerce-ios/tree/release/3.8.1) branch has been checked out from the source of this PR and it has been adjusted with a fake version and tags in order to test this PR.
The build log for the build triggered by a beta tag is here: https://circleci.com/gh/woocommerce/woocommerce-ios/7069
The build log for the build triggered by a final tag is here (note that upload to TestFlight has been disabled on this run to avoid uploading too much junk ;-) ): https://circleci.com/gh/woocommerce/woocommerce-ios/7073.

The release draft on GitHub has been created only on the second run: https://github.com/woocommerce/woocommerce-ios/releases 

**Note**:
As soon as this is approved and before merging it, we have to:
- remove the 3.8.1 tag from the repository.
- delete the 3.8.1 branch.
- delete the draft for release 3.8.1 on GitHub

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by oguzkocer** [comment]
@loremattei Does this mean that for the next release cycle which is in a couple days, we'll be using this automated approach? If so, could we make sure to update the documentation for these?

It'll be my first solo iOS release, so I'll be heavily relying on the instructions in the documentation.

**Comment by loremattei** [comment]
@oguzkocer I'm bumping the milestone to the next release as we're quite late in this cycle and I don't want to merge an important change like this one just before the code freeze. 
I'll be using CI builds during next WPiOS release to make sure everything works as expected and I'll then merge this and update the docs.

**Comment by oguzkocer** [comment]
@loremattei That sounds like a good plan to me!

**Comment by astralbodies** [comment]
@loremattei Do you need help moving this one forward?

**Comment by oguzkocer** [comment]
@astralbodies We talked about this with @loremattei today. We'll remove the manual tagging from our release process so as to not trigger these builds from the script. Once that's done, we'll merge this and start using it with the next release.

**Comment by loremattei** [comment]
This should be now ready to be merged @astralbodies! Thank you!
We wanted to test the feature on a single app before merging the changes to the others, but now we're ready to go. 

@oguzkocer I disabled the automatic tagging on code freeze as discussed, so that you can have more control on when the build starts. 

Conflicts are solved, so if you approve the changes, we can merge it.

**Pull request merged**
