### PR TITLE
UL&S: Remove .showLoginMethods segue from Site Address VC

### PR DESCRIPTION
**Pull request by mindgraffiti**
Ref. #2003 
Ref. https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/271

This PR removes the `.showLoginMethods` segue from `Login.storyboard` and presents the "3 button" view programmatically.

Note: although this view is not currently presented in Woo, we are keeping it up-to-date in case you'll need it when presenting SIWA as a login option. I realize the Login flows are currently being redesigned and this code may be obsolete soon.

### To Test
1. Check out this branch
2. In `AuthenticatorManager`, add a new param: `showLoginOptionsFromSiteAddress: true` to the configuration.
3. `rake dependencies`
4. Build and run (run on a device if you wish to view the "Sign in with Apple" button)
5. Log out if logged in
6. Log In > Enter the site address... > choose a WP.com hosted site with Woo installed, such as `hellotester1234.blog` > Next 
7. **Expected:** the "3 button" view is presented as a modal. On a simulator, it will look like this:

<a href="https://user-images.githubusercontent.com/1062444/81104059-94930f80-8ed7-11ea-8fc1-5811b1c84fc5.png"></a>

#### Do not merge until
1. The Authenticator PR has been merged. Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/271
2. A new Authenticator release has been created 
3. The release is published on Cocoapods trunk 
4. This PR points to the new release 

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by shiki** [comment]
@mindgraffiti Should I review this after https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/271 is fixed?

**Comment by mindgraffiti** [comment]
@shiki yes please wait. The podfiles for the host apps are refusing to pick up the latest commits in Auth, so you'll see the same bug otherwise.

**Comment by mindgraffiti** [comment]
@shiki ready for review. Peril is angry because I had to point to a commit in the podfile. (Changing the checksum in the podfile.lock isn't forcing an update for some reason.) This PR will point to the tagged release of Auth when the PRs are approved.

**Comment by shiki** [comment]
Peril is always angry about something. 🤷

**Pull request merged**
