### PR TITLE
Dynamic Dashboard: Fix layout for chart x-axis

### LINKED ISSUE #12531: Fix issue displaying values on the store stat chart's x-axis legend for custom range
We are using a fixed value 5 for store stat chart's `xAxisStrideCount` when the time range is custom range. This doesn't work when there are not enough values to display, and the chart will not show extra values:

The solution should be to calculate the number of items to be displayed based on the day difference and granularity, and if the result is larger than 5, we display 5 items.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #12531 

## Description

Previously we set a fixed value of 5 for strides of labels on the x-axis of the store stats chart. This causes an issue where the stride is too large for a custom range, causing only one label to be present on the x-axis.

This PR fixes the above issue by calculating the stride for x-axis values based on the length and granularity of each custom range. The layout of the chart has been updated to avoid any labels being clipped off.

Also: fixed the color of the navigation bar as reported in p1713856652563119-slack-C03L1NF1EA3.

## Testing instructions

- Enable the `dynamicDashboard` feature flag and build the app.
- Log in to a store with revenues and enable the Performance card on the dashboard screen.
- Add a custom range for the Performance card and confirm that the chart looks correct with x-axis labels.
- Try switching different range to confirm the x-axis looks correct for every length and granularity.

Testing navigation bar fix:
- Scroll the Dashboard screen up on both dark and light mode to confirm that the navigation bar color is correct.

## Screenshots

Before | After
--- | ---
 | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by selanthiraiyan — COMMENTED** [review]
Thanks for working on this, Huong!

I tested with a custom range and here is the screenshot. 



Is the extra year 2025 at the end of the x axis expected? 🤔

**Comment by itsmeichigo** [comment]
Thanks, @selanthiraiyan for the review. The inclusion of 2025 is due to the use of `roundLowerBound` and `roundUpperBound` of the x-axis values. This is to make sure that the labels are displayed nicely on the axis. Without that, the labels can be uneven in some cases:



I think having the labels displayed nicely would be better. WDYT?

**Review by selanthiraiyan — APPROVED** [review]
> I think having the labels displayed nicely would be better. WDYT?

Thanks for the explanation. I agree. 🚀

**Pull request merged**
