### PR TITLE
Refactor ProductAction, ProductStore and ProductsRemote to use Result

### PR DESCRIPTION
**Pull request by ealeksandrov**
## Description

This PR updates ProductAction + related Store and Remote to use Result, so the state of response is more limited with less optional parameters.

## Test

1. Check CI status for unit tests.
2. Run app and try products search, verify it works well.

---

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by koke — APPROVED** [review]
👌🏽 Result looks so much nicer

**Review by koke — CHANGES_REQUESTED** [review]
Sorry, code looked good but I missed that the tests were failing on my first pass

**Comment by ealeksandrov** [comment]
Oops, missed some unit tests!
Ready for another look @koke

**Review by koke — APPROVED** [review]
Sorry, I missed the ping. 🚢

**Comment by ealeksandrov** [comment]
No worries, thanks for review!

**Pull request merged**
