### PR TITLE
fix: deprecation warning by using string interpolation in DDLogInfo

### PR DESCRIPTION
**Pull request by pmusolino**
This is related to another PR that has been already merged. The same issue solved here: https://github.com/woocommerce/woocommerce-ios/pull/12923

For some reason, other warnings were not visible in Xcode, but this time internally to the `Hardware` target. I fixed them too.

## Changes
- Updated the `DDLogInfo` wrapper function to use string interpolation to conform to the updated CocoaLumberjackSwift 3.8.1 API.

## Testing
- Compile the project to ensure no deprecation warnings are present.
- Performed a smoke test of the application (Settings -> Help & Support -> View Application log) to confirm that logs are correctly generated and formatted.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by selanthiraiyan — COMMENTED** [review]
Thanks for the fix, Paolo!

Should we update `WooFoundation` as well?

image

**Comment by pmusolino** [comment]
> Should we update WooFoundation as well?

Absolutely. Done here: 04b94131a5034b4d1e8405aca33e91406d7a8297

However, I wonder why my version of Xcode does not display these warnings in the list -.-'

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/208">19.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by selanthiraiyan — APPROVED** [review]
🚀

**Pull request merged**
