### PR TITLE
Remove `XLPagerTabStrip` dependency from the app

### LINKED ISSUE #1911: Replace XLPagerTabStrip
Refs p99K0U-1Cj-p2 and p91TBi-2s1-p2. 

As also shown in #1851, there are problems with XLPagerTabStrip like:

- Support for safe area in landscape
- Accessibility (e.g. large font sizes)

It might be best if we create our own implementation that solves these issues.

Subtasks:

- [x] Replace `XLPagerTabStrip` with WPiOS implementation https://github.com/woocommerce/woocommerce-ios/pull/8942
- [ ] Remove `XLPagerTabStrip` library from the project https://github.com/woocommerce/woocommerce-ios/pull/9255#issuecomment-1479135074

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #1911 

## Description

The usage of `XLPagerTabStrip` was already removed in https://github.com/woocommerce/woocommerce-ios/pull/8942, now we're ready to remove the library completely.

## Testing instructions

Feel free to just do a quick confidence check in the app, some of the critical flows should be covered in the UI tests.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by selanthiraiyan — APPROVED** [review]
:shipit:

**Comment by toupper** [comment]
@jaclync I know this is quite old, but I found this through an old crash. Given that XLPagerTabStrip was removed with this PR, can we remove this [code](https://github.com/woocommerce/woocommerce-ios/blob/81d34750c255022b777a73b2e0921bfcc999e37c/WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift#L224) too?

**Comment by jaclync** [comment]
> I know this is quite old, but I found this through an old crash. Given that XLPagerTabStrip was removed with this PR, can we remove this [code](https://github.com/woocommerce/woocommerce-ios/blob/81d34750c255022b777a73b2e0921bfcc999e37c/WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift#L224) too?

I'd say so based on the comment. But it was from 5 years ago, and there could be behaviors built up over the years behind this `tableView.reloadData()` call. Some testing and merging at the beginning of the release cycle might help. Do you want me to create an issue for triage?

**Comment by toupper** [comment]
> I'd say so based on the comment. But it was from 5 years ago, and there could be behaviors built up over the years behind this tableView.reloadData() call. Some testing and merging at the beginning of the release cycle might help. Do you want me to create an issue for triage?

Ok, let's do that 👍  Thanks @jaclync

**Comment by jaclync** [comment]
Issue created: WOOMOB-670

**Pull request merged**
