### PR TITLE
[Free Trial] Redesign Hub Menu

### LINKED ISSUE #9379: [Free Trial] Redesign Hub
We should redesign the menu from big tiles to a list. In scope of this task, we should move "Upgrades/Subscriptions" link from "Settings" to "Menu" (as the part of the new list).

Image

### PR DESCRIPTION
**Pull request by Ecarrion**
Closes: #9379 

# Why

This PR updates the Hub Menu to be redesigned from a Grid to a List.

**Note: This PR is on the bigger side(Sorry 😇 ) but It is because I needed to redesign it in one go, as doing it via feature flags was getting a bit too complex**

# How

- Most of the changes are in the `HubMenu` file. Here, the main changes are:
   - Update the main structure to use a `List`
   - Create a `Row` type to be used inside the `List`. This is a simpler version of the previous `TopBar` type.
   - Remove unneeded code & move the tap handling code to its own function.

- Remove `HubMenuElement` type. No longer used. It was the previous menu button.

- Update the `HubMenuViewModel` to provide two sections(Settings & Generals) instead of one.

- Update the `HubMenuItem` to add descriptions.

# Screenshots

Light | Dark | Big Fonts
--- | --- | ---
Light | dark | big-fonts

# Testing Steps

- Launch the app and navigate to the Menu Tab
- See the new view redesigned as a list
- Tap all buttons and make sure they navigate to the correct place.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ThomazFB** [comment]
Hey @Ecarrion, just to let you know that I'll focus on review this PR tomorrow, is that OK? I'm trying to expedite all Alejandro's PRs that are focused on the main deliveries of the extensions project.

**Comment by jostnes** [comment]
👋 got a ping as part of `mobile-ui-testing-squad`, and i only reviewed the https://github.com/woocommerce/woocommerce-ios/pull/9448/commits/81b12880d2a876a414dcf88a7f361c015fec0117 commit related to the UI tests change. the changes look good and the test works as expected ✅ (i didn't approve the PR since i didn't review the rest of the code)

thanks for updating the UI test as part of your PR!

**Review by ThomazFB — APPROVED** [review]
Tested and compared with the Android counterpart. Looks good! The buttons visibility control is following the same behavior as before. I also updated the Android side to match the HubMenuItem descriptions introduced here. 

I just noticed one difference: the `Inbox` option is set above `Reviews`, but the Figma design suggests otherwise. I don't have a strong opinion about which one should be on top, but I want to align this to avoid platform differences in the menus. WDYT?

**Comment by Ecarrion** [comment]
> I just noticed one difference: the Inbox option is set above Reviews, but the Figma design suggests otherwise. I don't have a strong opinion about which one should be on top, but I want to align this to avoid platform differences in the menus. WDYT?

Good catch, I've updated it to match designs on https://github.com/woocommerce/woocommerce-ios/pull/9448/commits/61120efbf8a2888552fe410ec61f10197580f3e5

Screenshot 2023-04-16 at 4 30 24 PM

**Pull request merged**
