### PR TITLE
[Engage] Universal Links: Add the woocommerce.com app links associated domain entitlement

### PR DESCRIPTION
**Pull request by toupper**
Part of: #7535

### Description

With this PR we add the associated domains entitlement to the Woo iOS app. ~~Since we didn't upload the apple-app-site-association file to woocommerce.com, we cannot test this yet.~~ (This is already merged: [here](14416-gh-Automattic/woocommerce.com)) 

#### Order Details

1. Send yourself an email containing a link with the format https://woocommerce.com/mobile/orders/details?blog_id=your storeID&order_id=an existing orderID
2. Tap on it. You can also test the switch to a different store by adding a store id to the link other than the currently selected in Woo app.

#### Open link with an order belonging to a store already selected in the app

https://user-images.githubusercontent.com/1864060/187661029-73b218a0-f28f-44cb-9da8-5fae53eb31cf.mov

#### Open link with an order belonging to a store not selected in the app. Switch store

https://user-images.githubusercontent.com/1864060/187661149-cf24c898-a9d1-4201-bde4-f3ae3f7384a7.mov

#### Payments
1. Send yourself an email containing a link with the format https://woocommerce.com/mobile/payments
2. Tap on it. Make sure it opens the Payments Hub Menu in the Woo Mobile app

https://user-images.githubusercontent.com/1864060/187913313-b126a79e-0b71-4f39-86ec-8a49acbe6f02.MP4

### Screenshots

---
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Ecarrion — COMMENTED** [review]
Hey @toupper I ran this branch into my device, sent me an email with the links but I was not redirected to the app.

Do I need to follow any specific test steps?


https://user-images.githubusercontent.com/562080/193662580-695a5dd4-f64f-4c27-89fc-7c645ce4c2ba.MP4

**Comment by toupper** [comment]
hi @Ecarrion Thanks for checking that :) I updated the PR description with the new format for the links, as we agreed to add the `/mobile/ `segment so redirections can happen easily. So, for instance, instead of `https://woocommerce.com/payments`, it is `https://woocommerce.com/mobile/payments`. Please try again with that links URLs formats and sorry for the confusion.

**Comment by Ecarrion** [comment]
@toupper I'm still not getting re-directed. 🤔 
is there a way for me to check why the app is not being invoked?

**Comment by toupper** [comment]
Thanks for trying again @Ecarrion :) 

There are two points you can do to make sure you have the right configuration in your phone:

- Be sure you run the app from that branch (just in case ;) 
- It might be that you tapped the small button on the device status bar while using the app, which led you back to woocommerce.com. Once you do that, the system would remember that and would always launch Safari when a universal link to your app is tapped. To undo that, long-tap the link, and in the menu that pops up, choose "Open with Woo"

If none of these work, we can schedule a call to check it further :)

**Review by Ecarrion — APPROVED** [review]
Now it worked 🎉 

The problem was on my end, when I updated the links to the add `mobile` path, the string visible to me changed, but the underlying hyperlink remained the same. 🤦

**Comment by toupper** [comment]
Thanks for checking that again @Ecarrion  :) 

> The problem was on my end, when I updated the links to the add mobile path, the string visible to me changed, but the underlying hyperlink remained the same. 🤦

Yeah, that happened to me as well 😅

**Pull request merged**
