### PR TITLE
Change Circle CI image to Xcode 13

### PR DESCRIPTION
**Pull request by pmusolino**
This PR changes the Circle CI image to use Xcode 13.

## Testing
Make sure Circle CI build is green.

## Notes
Before merging this PR in `develop`, we need to fix these [issues](https://github.com/woocommerce/woocommerce-ios/issues?q=is%3Aissue+is%3Aopen+xcode+13), in particular this one https://github.com/woocommerce/woocommerce-ios/issues/5018

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jaclync** [comment]
Thanks for starting this @pmusolino! When testing in https://github.com/woocommerce/woocommerce-ios/pull/5312, I got this build error quite often:

```
error: input file '/Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/DerivedSources/ApiCredentials.swift' was modified during the build
```

Did you encounter this as well? 

After checking [this SO post](https://stackoverflow.com/a/69481200/9185596), it looks like it’s because Xcode 13 keeps running the build phase while indexing. To fix this, we can exclude the index phase when generating the credentials file:

https://github.com/woocommerce/woocommerce-ios/blob/1ae6a14f79bbc46b040220053a3e87a8fe93ef72/WooCommerce/WooCommerce.xcodeproj/project.pbxproj#7286

by 

```
			shellScript = "if [ $ACTION != \"indexbuild\" ]; then\n  $SRCROOT/../Scripts/build-phases/generate-credentials.sh \nfi\n";
```

WDYT?

**Comment by pmusolino** [comment]
Interesting @jaclync. I'm not seeing this build error in this PR, neither on #5312. Before adding the script, I'd say to ask @woocommerce/owl-team what they think of

**Comment by mokagio** [comment]
@pmusolino @jaclync great research work!

Apologies for this, I started working on something similar a few days (ecc039e98efb1f9102a3507a476c5917b35012dd) but got side-tracked and didn't close the loop, partly because that kind of error is inconsistent so I wasn't sure how to effectively verify my fix.

I opened #5329 to add that fix into this branch. I did it as a dedicated PR so we can discuss its details in there.

_Stay tuned_

**Comment by pmusolino** [comment]
Great! Thanks @mokagio 🎉

**Review by mokagio — APPROVED** [review]
Thanks again for doing this @pmusolino and @jaclync 💜 

As you can see, the infra team approved the change to the build phase. I also took the liberty of tweaking how the Ruby version is set so that there is only one source of truth in the repository: the `.ruby-version` file. This should also ensure Buildkite uses the expected version, 2.7.4.

I was tempted to enable auto-merge, but I guess we might want to coordinate an announcement regarding Xcode 13 support?

**Comment by pmusolino** [comment]
An announcement would be great @mokagio 💯 in the meantime, I'm going to merge in this PR the other PRs that are pointing to this.

**Comment by pmusolino** [comment]
@mokagio ready to be merged 🎸

**Pull request merged**
