### PR TITLE
[Shipping label] Improve selected package view for unsaved custom package

### LINKED ISSUE #14522: Selected package and shipment weight UI
We need to add the UI for the selected package and shipment weight on the main shipping label screen.

Entering a new shipment weight should trigger a new request for shipping services (label rates) after 1-2 seconds.

Design:

Image

### PR DESCRIPTION
**Pull request by rachelmcr**
Closes: #14522

## Description

This cleans up the selected package view, in particular when a custom package is selected but not saved as a template. Changes:

* If the package has no weight, the weight description is hidden (only package dimensions are shown)
* If the package has no name, the source description is shown (e.g. "Custom Package" for a custom package)
* Also adds vertical padding to the Shipping Service view

## Testing information

1. Install and set up the Woo Shipping extension on your store.
2. Build and run the app with the revampedShippingLabelCreation feature flag enabled.
3. Create an order with the processing status and at least one physical product.
4. In your WooCommerce product settings on the web, change the weight and dimension units and save your changes.
5. On the Orders tab in the app, open the order you created.
6. In the order details, select "Create Shipping Label."
7. Tap "Select a Package."
8. Select and add a package.
9. Confirm the selected package details appear as expected.

Scenarios to test:

* Custom package not saved as a template
* Custom package saved as a template (either newly saved or selected from the Saved tab)
* Carrier package

## Screenshots

/|Before|After
-|-|-
Carrier package|Carrier-Before|Carrier-After
Saved custom package|Saved-Before|Saved-After
Unsaved custom package|Custom-Before|Custom-After

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/233">21.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by bozidarsevo** [comment]
While reviewing/looking at this I was thinking maybe to change packages weight to be an optional property (`let boxWeight`) in `WooShippingCustomPackage` and `WooShippingPredefinedPackage`, what do you think?

**Comment by bozidarsevo** [comment]
> While reviewing/looking at this I was thinking maybe to change packages weight to be an optional property (`let boxWeight`) in `WooShippingCustomPackage` and `WooShippingPredefinedPackage`, what do you think?

We can do it in a separate PR, I can do it after we merge this

**Comment by rachelmcr** [comment]
> While reviewing/looking at this I was thinking maybe to change packages weight to be an optional property (let boxWeight) in `WooShippingCustomPackage` and `WooShippingPredefinedPackage`, what do you think?

At this point in the UI we're only handling `WooShippingPackageDataRepresentable`, so I think we could make the weight property optional in `WooShippingPackageDataRepresentable` to handle cases like this. 👍 

Before changing the Networking models for custom/predefined packages I'd want to check the API requirements, though. I think in some cases (e.g. when saving a custom package template) the weight is required, so making it optional in those models could have negative consequences when interacting with the API. Maybe not, but we should check that first.

**Review by bozidarsevo — APPROVED** [review]

**Pull request merged**
