### PR TITLE
Updated Charts pod from 3.3.0 to 3.6.0, that includes Xcode 12 support

### PR DESCRIPTION
**Pull request by pmusolino**
## Description
As part of our Xcode 12 migration, we should update our Pod libraries, because some of them show warnings about the `IPHONEOS_DEPLOYMENT_TARGET` set to iOS 8.0, that is no more supported.
In this PR I updated the Charts pod from v.3.3.0 to v.3.6.0 that now supports Xcode 12.

## Testing
- Check that the Stats in the dashboard are working like before.
- Make sure that this warning disappear:
Schermata 2020-10-16 alle 11 26 44

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by loremattei** [comment]
Hey there! I'm moving this to 5.4 as 5.3 has been cut. If you still want this to make it to 5.3, please feel free to ping me.

**Comment by jaclync** [comment]
I tested in Xcode 11.7, and got a crash on launch loading the dashboard 🤔 Maybe some API has changed regarding this property? Unless we're also moving fully to Xcode 12 like WPiOS, this is worth fixing? Still nice to be able to run the app in Xcode 11 though

https://github.com/woocommerce/woocommerce-ios/blob/38a588fdaeb772d2949f7de24da446b74ac3d1dc/WooCommerce/Classes/ViewRelated/Dashboard/Stats%20v4/StoreStatsV4PeriodViewController.swift#L327

```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000111458710 in swift_beginAccess ()
#1	0x000000010e7579eb in ChartViewBase._drawUnitInChart.modify ()
#2	0x000000010c852418 in StoreStatsV4PeriodViewController.configureBarChart() at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsV4PeriodViewController.swift:327
#3	0x000000010c850252 in StoreStatsV4PeriodViewController.viewDidLoad() at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsV4PeriodViewController.swift:173
#4	0x000000010c853feb in @objc StoreStatsV4PeriodViewController.viewDidLoad() ()
#5	0x00007fff48cc294e in -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] ()
#6	0x00007fff48cc786c in -[UIViewController loadViewIfRequired] ()
#7	0x00007fff48cc7c89 in -[UIViewController view] ()
#8	0x000000010cbf5c6a in closure #1 in StoreStatsAndTopPerformersPeriodViewController.configureChildViewControllers() at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewController.swift:178
#9	0x000000010cbf5d32 in thunk for @callee_guaranteed (@guaranteed UIViewController) -> (@error @owned Error) ()
#10	0x000000010cbf7154 in thunk for @callee_guaranteed (@guaranteed UIViewController) -> (@error @owned Error)partial apply ()
#11	0x000000011128490d in Sequence.forEach(_:) ()
#12	0x000000010cbf25db in StoreStatsAndTopPerformersPeriodViewController.configureChildViewControllers() at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewController.swift:176
#13	0x000000010cbf22bb in StoreStatsAndTopPerformersPeriodViewController.init(siteID:timeRange:currentDate:canDisplayInAppFeedbackCard:) at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewController.swift:110
#14	0x000000010cbf181f in StoreStatsAndTopPerformersPeriodViewController.__allocating_init(siteID:timeRange:currentDate:canDisplayInAppFeedbackCard:) ()
#15	0x000000010cb387b1 in StoreStatsAndTopPerformersViewController.configurePeriodViewControllers() at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift:265
#16	0x000000010cb38612 in StoreStatsAndTopPerformersViewController.viewDidLoad() at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift:45
#17	0x000000010cb3948b in @objc StoreStatsAndTopPerformersViewController.viewDidLoad() ()
#18	0x00007fff48cc294e in -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] ()
#19	0x00007fff48cc786c in -[UIViewController loadViewIfRequired] ()
#20	0x00007fff48cc7c89 in -[UIViewController view] ()
#21	0x000000010caadea3 in DashboardViewController.onDashboardUIUpdate(updatedDashboardUI:) at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift:141
#22	0x000000010caadaf9 in closure #1 in DashboardViewController.reloadDashboardUIStatsVersion() at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift:115
#23	0x000000010cc65ebe in DashboardUIFactory.onStatsVersionChange(previousVersion:currentVersion:onUIUpdate:) at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/Factories/DashboardUIFactory.swift:73
#24	0x000000010cc65d93 in closure #1 in DashboardUIFactory.reloadDashboardUI(onUIUpdate:) at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/Factories/DashboardUIFactory.swift:34
#25	0x000000010caffcda in StatsVersionCoordinator.version.didset at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsVersionCoordinator.swift:17
#26	0x000000010caffdd3 in StatsVersionCoordinator.version.setter ()
#27	0x000000010cb002f8 in closure #1 in StatsVersionCoordinator.loadLastShownVersionAndCheckV4Eligibility() at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsVersionCoordinator.swift:38
#28	0x000000011093cec8 in AppSettingsStore.loadInitialStatsVersionToShow(siteID:onCompletion:) at /Users/jaclynchen/Developer/testing/woocommerce-ios/Yosemite/Yosemite/Stores/AppSettingsStore.swift:373
#29	0x0000000110938fa1 in AppSettingsStore.onAction(_:) at /Users/jaclynchen/Developer/testing/woocommerce-ios/Yosemite/Yosemite/Stores/AppSettingsStore.swift:112
#30	0x00000001109087be in protocol witness for ActionsProcessor.onAction(_:) in conformance Store ()
#31	0x000000011080ab47 in WeakProcessor.onAction(_:) at /Users/jaclynchen/Developer/testing/woocommerce-ios/Yosemite/Yosemite/Base/Dispatcher.swift:100
#32	0x000000011080a49d in Dispatcher.dispatch(_:) at /Users/jaclynchen/Developer/testing/woocommerce-ios/Yosemite/Yosemite/Base/Dispatcher.swift:72
#33	0x000000010c8c17d1 in AuthenticatedState.onAction(_:) at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/Yosemite/AuthenticatedState.swift:88
#34	0x000000010c8c194a in protocol witness for StoresManagerState.onAction(_:) in conformance AuthenticatedState ()
#35	0x000000010cd183da in DefaultStoresManager.dispatch(_:) at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/Yosemite/DefaultStoresManager.swift:85
#36	0x000000010cd1a58a in protocol witness for StoresManager.dispatch(_:) in conformance DefaultStoresManager ()
#37	0x000000010cb00119 in StatsVersionCoordinator.loadLastShownVersionAndCheckV4Eligibility() at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsVersionCoordinator.swift:52
#38	0x000000010cc65baa in DashboardUIFactory.reloadDashboardUI(onUIUpdate:) at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/Factories/DashboardUIFactory.swift:38
#39	0x000000010caac74b in DashboardViewController.reloadDashboardUIStatsVersion() at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift:114
#40	0x000000010caac358 in DashboardViewController.viewWillAppear(_:) at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift:48
#41	0x000000010caac7a8 in @objc DashboardViewController.viewWillAppear(_:) ()
#42	0x00007fff48ccd71e in -[UIViewController _setViewAppearState:isAnimating:] ()
#43	0x00007fff48ccde01 in -[UIViewController __viewWillAppear:] ()
#44	0x00007fff48c2c847 in -[UINavigationController _startTransition:fromViewController:toViewController:] ()
#45	0x00007fff48c2d49b in -[UINavigationController _startDeferredTransitionIfNeeded:] ()
#46	0x00007fff48c2e7e0 in -[UINavigationController __viewWillLayoutSubviews] ()
#47	0x00007fff48c0f7b0 in -[UILayoutContainerView layoutSubviews] ()
#48	0x00007fff4987a5f0 in -[UIView(CALayerDelegate) layoutSublayersOfLayer:] ()
#49	0x00007fff2b4f9260 in -[CALayer layoutSublayers] ()
#50	0x00007fff2b4ff3eb in CA::Layer::layout_if_needed(CA::Transaction*) ()
#51	0x00007fff2b50aa8a in CA::Layer::layout_and_display_if_needed(CA::Transaction*) ()
#52	0x00007fff2b453a7c in CA::Context::commit_transaction(CA::Transaction*, double) ()
#53	0x00007fff2b487467 in CA::Transaction::commit() ()
#54	0x00007fff4938a6bf in __34-[UIApplication _firstCommitBlock]_block_invoke_2 ()
#55	0x00007fff23da1abc in __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ ()
#56	0x00007fff23da11b3 in __CFRunLoopDoBlocks ()
#57	0x00007fff23d9bfa3 in __CFRunLoopRun ()
#58	0x00007fff23d9b8a4 in CFRunLoopRunSpecific ()
#59	0x00007fff38c05bbe in GSEventRunModal ()
#60	0x00007fff49372964 in UIApplicationMain ()
#61	0x000000010cb0c7c4 in main at /Users/jaclynchen/Developer/testing/woocommerce-ios/WooCommerce/Classes/System/main.swift:7
#62	0x00007fff5211c1fd in start ()
```

**Comment by pmusolino** [comment]
This is a really strange issue @jaclync 😨 because I tried to run the app on Xcode 11.5, and everything works properly, without any crash. Are you launching just the app before the crash or are you doing other actions?

**Comment by pmusolino** [comment]
@woocommerce/ios-developers someone of you can try to run this PR on Xcode 11.7, and verify if you encounter the same crash mentioned by @jaclync?

**Comment by pmusolino** [comment]
@woocommerce/ios-developers ready for review after having merged the PR for upgrading the CI to Xcode 12 😉

**Review by jaclync — APPROVED** [review]
LGTM! Since we can't even build `develop` in Xcode 11.7 after merging the PR for Xcode 12 support on CI https://github.com/woocommerce/woocommerce-ios/pull/3015, just testing on Xcode 12 is fine.

Code: ✅ 
Testing: ✅ (Tested in iPhone 14.0 simulator & iPhone 6s Plus iOS 13.7 device and the charts worked like before! Also no warnings in Charts framework anymore 🎉 )

**Review by shiki — APPROVED** [review]
I also tested this yesterday with Xcode 12 and didn't see any issues. 

I cannot compile with Xcode 11 anymore.

**Comment by pmusolino** [comment]
Thank you all for the testing! <3

**Pull request merged**
