### PR TITLE
Order Creation: Release order creation (removes experimental toggle)

### LINKED ISSUE #6536: Order Creation: Remove order creation experimental toggle
To fully release the Order Creation feature to the general public, we need to completely remove the Order Creation option from the experimental toggle conditional and make it available by default alongside the Simple Payment options inside the Order list view.

### PR DESCRIPTION
**Pull request by rachelmcr**
Closes: #6536

## Description

This removes the Order Creation experimental toggle, releasing the feature to all users. 🎉 

Note: The top banner on the Orders tab still only mentions simple payments; the banner will be updated in a followup PR.

## Changes

* Removes the order creation section (toggle) from `BetaFeaturesViewController`.
* Removes checks for the experimental feature from `OrdersRootViewController` and `AddOrderCoordinator`, making the orders tab bottom sheet always show both order types (full order creation and simple payments).
* Updates unit and UI tests.

## Testing

Full release test plan: pdcxQM-J5-p2

1. Build and run the app.
2. Go to Menu > Settings > Experimental Features and confirm there is no Order Creation experimental toggle.
3. Go to Orders and tap the + icon. Confirm a bottom sheet appears with both order types (full order creation and simple payments).
4. Select "Create order."
5. Add details to the new order: order status, products, shipping, fee, customer details, and/or customer note.
6. Tap the "Create" button and confirm the order is created and the app navigates to the order details for the new order.

## Screenshots

https://user-images.githubusercontent.com/8658164/160665939-021e0846-84a4-4aea-9025-66bfcdaf96dc.mp4

## Submitter Checklist

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by rachelmcr** [comment]
The installable build failed on this PR, but it's unrelated to the changes here. See https://github.com/woocommerce/woocommerce-ios/pull/6531#issuecomment-1082164422.

**Review by Ecarrion — COMMENTED** [review]
Looks good! Should we also remove all the code related to loading and storing the switch state?

**Comment by rachelmcr** [comment]
> Should we also remove all the code related to loading and storing the switch state?

Ah, yep! Thanks for catching that oversight @Ecarrion; I removed that code from the Yosemite and Storage layers in [5e901f7](https://github.com/woocommerce/woocommerce-ios/pull/6537/commits/5e901f76cb3a3e4cbe4307369468332e4b571fb8) and [a14139b](https://github.com/woocommerce/woocommerce-ios/pull/6537/commits/a14139b3fac02e01256e2b38e97aad0032526678). I think I caught it all this time — let me know if you see anything I missed.

**Review by Ecarrion — APPROVED** [review]
👍

**Pull request merged**
