### PR TITLE
Added punctuations

### PR DESCRIPTION
**Pull request by 96RadhikaJadhav**
Update release notes:
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

This PR will resolve issue #3363 .

### CODE REVIEW

**Review by rachelmcr — APPROVED** [review]
Looks great! Thank you for these fixes!

**Review by rachelmcr — CHANGES_REQUESTED** [review]
Ah, I just ran our unit tests against these changes and realized there's a test that will need to be updated before we can merge this. In [JetpackErrorViewModelTests.swift](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/WooCommerceTests/Authentication/JetpackErrorViewModelTests.swift) the test `test_viewmodel_provides_expected_title_for_auxiliary_button()` checks the "What is Jetpack?" string, so the [expected string](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/WooCommerceTests/Authentication/JetpackErrorViewModelTests.swift#L67) in that test also needs to be updated to match this change.

**Comment by 96RadhikaJadhav** [comment]
> Ah, I just ran our unit tests against these changes and realized there's a test that will need to be updated before we can merge this. In [JetpackErrorViewModelTests.swift](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/WooCommerceTests/Authentication/JetpackErrorViewModelTests.swift) the test `test_viewmodel_provides_expected_title_for_auxiliary_button()` checks the "What is Jetpack?" string, so the [expected string](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/WooCommerceTests/Authentication/JetpackErrorViewModelTests.swift#L67) in that test also needs to be updated to match this change.

@rachelmcr  Done.

**Review by rachelmcr — APPROVED** [review]
Thank you @96RadhikaJadhav! I'll merge this now. 🚀

**Pull request merged**
