### PR TITLE
[Mobile Payments] UI review. Mark I

### LINKED ISSUE #4324: [Mobile Payments] Prepare UI review
Prepare a set of screenshots of the new UI associated with In-Person Payments, and open it up for a design review

### PR DESCRIPTION
**Pull request by ctarda**
Closes #4324 

We have recently reached the point where we have been able to implement our first iteration of the designs. 

This PR would help check the current status of the UI and perform a first round of review.

We are still ironing out some issues in landscape mode, so for this first review let's do only portrait and phone. We will submit separate PRs for landscape phone, and portrait and landscape tablet.

Please, @Garance91540 @adamzelinski , let's use this PR to point out inconsistencies and issues in the UI layer, so that we can log tickets for them and prioritize them for the code freeze in June 25. With that in mind, some indication of the severity would help us prioritize, in case we don't have time to fix every single thing on time (something like "to fix before beta 1" or "can wait until right after beta 1" would be very helpful).

# Videos.

1. Discover and connect to the first reader available:

https://user-images.githubusercontent.com/2722505/120219403-3125ff00-c209-11eb-97d9-7f3a3b046e9b.MP4

2. Collect a payment and print a receipt (when there is a reader connected):

https://user-images.githubusercontent.com/2722505/120219514-587ccc00-c209-11eb-93d5-10b20e340b2f.MP4

3. Connect to a reader and then collect the payment when there is no reader connected:

https://user-images.githubusercontent.com/2722505/120219661-91b53c00-c209-11eb-9a97-45edf17f351f.MP4

# Screenshots:

1. Screen 1: Instructions to connect to a reader:

| Light Appearance | Dark Appearance |
| ---- | ---- |
|  |  |

2. Screen 2: Searching for readers:

| Light Appearance | Dark Appearance |
| ---- | ---- |
|  |  |

3. Screen 3: Reader found:

| Light Appearance | Dark Appearance |
| ---- | ---- |
|  |  |

4. Screen 4: List of readers:

| Light Appearance | Dark Appearance |
| ---- | ---- |
|  |  |

5. Screen 5: Order details (collect payment button)

| Light Appearance | Dark Appearance |
| ---- | ---- |
|  |  |

6. Screen 6. Collect payment, step 1. 

| Light Appearance | Dark Appearance |
| ---- | ---- |
|  |  |

7. Screen 7. Collect payment, step 2. 

| Light Appearance | Dark Appearance |
| ---- | ---- |
|  |  |

8. Screen 8. Collect payment, step 3. 

| Light Appearance | Dark Appearance |
| ---- | ---- |
|  |  |

9. Screen 9. Success. 

| Light Appearance | Dark Appearance |
| ---- | ---- |
|  |  |

10. Screen 10. Order details after a payment has been collected (See Receipt button). 

| Light Appearance | Dark Appearance |
| ---- | ---- |
|  |  |

11. Screen 11. Receipt preview

| Light Appearance | Dark Appearance |
| ---- | ---- |
|  |  |

Update release notes:
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ctarda** [comment]
cc @koke  and @allendav .

Let's log everything that comes out of the review, and depending on what @Garance91540  and @adamzelinski mark as higher priority, let's prioritize.

**Comment by Garance91540** [comment]
Hi Cesar, thank you for kicking this off! (I see you went a bit beyond 4 screenshots :D), in my screenshot reviews, I put in red what would be nice to update before the beta release. 

- Buttons

All the buttons should be 40px height (currently I think they are 50px height, which is what we used before. I noticed that some of these new button sizes hadn't been updated properly in the designs (fixed now), and so I think we have the wrong button's height in the screenshots you sent me, they should all have a 40px height.
(can wait) 

- Modals

I noticed we have different modal sizes along the flow, which might be a bit unsettling as the modals will seem to "jump" from screen to screen. We should have a unique modal size all along the flow (382px by 280px) (can wait but should  be addressed soon if possible)

- Screen 1: Instructions to connect to a reader:

Screen Shot 2021-06-03 at 4 56 54 PM

Also, the "Learn more" text link was supposed to open up to our documentation around Woo Payments in mobile, but we haven't created this page yet. Where does this currently link to? 

- Screen 2: Searching for readers:

Screen Shot 2021-06-03 at 5 47 16 PM

Screen Shot 2021-06-03 at 5 46 29 PM

- Payment Modals,
I noticed there was no currency in the modals - I wonder if that was just an error? https://d.pr/i/bHk4yn

- Receipt preview
Is is possible to add a title "Receipt" to this screen? 

I think this was the bulk of the feedback I have. I noticed some smaller UI notes but I'll report them later as they are lower priority!

**Review by Garance91540 — CHANGES_REQUESTED** [review]
left comment in separate note

**Comment by ctarda** [comment]
Thanks a lot for the review @Garance91540  We will start logging issues, to tackle all your feedback in smaller PRs and will make sure to tag the designers group.

One question only:

> I noticed we have different modal sizes along the flow, which might be a bit unsettling as the modals will seem to "jump" from screen to screen. We should have a unique modal size all along the flow (382px by 280px) (can wait but should be addressed soon if possible)

That might be a bit tricky, specially for error messages (as some of the descriptions are pretty long). What is happening now is that the modal alert adapts its vertical size, animated, to fit the content it presents. We will try to get this into beta 1, but if it turned out to be too complicated, would it be okay if we addressed it for the first or second release after beta 1?

**Comment by ctarda** [comment]
Sorry @Garance91540  I missed this: 

> Also, the "Learn more" text link was supposed to open up to our documentation around Woo Payments in mobile, but we haven't created this page yet. Where does this currently link to?

At this moment, it is opening a web view to https://woocommerce.com/payments

**Comment by Garance91540** [comment]
> would it be okay if we addressed it for the first or second release after beta 1?

Of course!

**Comment by koke** [comment]
I was going through the cancel buttons for #4364 and noticed there's a whole modal that we missed when we are connecting to a reader:

scanning-reader

The code seems to be implemented in `CardPresentModalConnectingToReader` but it's not being displayed

**Pull request closed without merging**
