### PR TITLE
Order Notes > Icon now changes color when activate "Email note to customer"

### PR DESCRIPTION
**Pull request by leonardodamato**
This PR fixes issue #1618.

When activating the "Email note to customer" switch, the note icon in the "Write Note" text area wasn't getting changed to the right color (.primary).

Result after fixing the issue:

"Email note to   customer" not activated | "Email note to   customer" activated
:-------------------------:|:-------------------------:
image  |  image

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pmusolino** [comment]
For the future, remember that the right thing to do is: align your fork to `develop`, and open a new branch from `develop`. In this way, you are always up to date and you will commit only significative changes related to the issue where you are working on. 👍

**Comment by leonardodamato** [comment]
> For the future, remember that the right thing to do is: align your fork to `develop`, and open a new branch from `develop`. In this way, you are always up to date and you will commit only significative changes related to the issue where you are working on. 👍

Hi Paolo, so sorry for that. I forgot to do this. 
What would be the correct to way to fix it? 

Thanks :)

**Comment by mindgraffiti** [comment]
Hi @leonardodamato 👋 

It looks like you branched from your `develop` branch. Your `develop` branch has all the commits from PR #1768. We follow [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) for our work and we don't commit directly to `develop`. 

What works best is to fork the project, pull changes from `develop`, and then start a new feature branch from `develop`. Make the commits to your feature branch. When it's ready, compare your feature branch to the project's `develop` branch (like you did here :) ) and send your Pull Request.

**Comment by leonardodamato** [comment]
Thank you, @mindgraffiti for letting me know how I should do on the next time! Will not repeat it.

**Pull request closed without merging**
