### PR TITLE
Fix crash on various Settings screen

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #12656 

## Description

In #12602 I removed the `Dashboard` storyboard which contains screens related to the Settings flow. This causes crashes when open Help & Support, Application Log, Privacy, and About screens from Settings.

This PR fixes this by restoring the old `Dashboard` storyboard. To avoid misunderstanding in the future, I also renamed this storyboard to `Settings`.

## Testing instructions

- Log in to the app.
- Navigate to Menu tab > Settings.
- Select Help & Support and confirm that the app doesn't crash.
- Select View Application Log and confirm that the app doesn't crash.
- Navigate back to the Settings screen and select Privacy Settings. Confirm that the app doesn't crash.
- Navigate back and select WooCommerce in the About the app section. Confirm that the app doesn't crash.

## Screenshots

About | Privacy | Help | Application Log
--- | --- | --- | ---
 |  |  | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/201">18.5 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by hafizrahman — APPROVED** [review]
Thanks for the quick fix. This LGTM 👍🏼

**Comment by itsmeichigo** [comment]
@iamgabrielma Please help with a beta build for this fix, thank you 🙏

**Comment by iamgabrielma** [comment]
Done! 18.5.0.1 published and back merged https://github.com/woocommerce/woocommerce-ios/pull/12662

**Pull request merged**
