### PR TITLE
Blaze: Navigate to the native campaign creation flow from the campaign detail web view

### LINKED ISSUE #13867: Clicking on Promote Again button from campaign detail webview should trigger the native flow.
Currently, clicking on `Promote Again` button from campaign details webview screen triggers the Blaze webview flow to create a campaign. 

https://github.com/user-attachments/assets/4cfefbb5-ec30-400b-8670-7ff4e4fba84f

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #13867 

## Description

This PR updates the handling of URLs on the Blaze campaign detail web view by adding a custom view model for the authenticated web view. 

This new view model implements `handleRedirect` to detect the URL that triggers campaign creation and trigger a callback for the Blaze dashboard card and the campaign list where the campaign detail view is presented from.

Additionally, I also added a check to handle the tap on the Back link of the web page to dismiss it instead of redirecting to the campaign list on the web page.

## Steps to reproduce

- Log in to a store eligible for Blaze.
- Create a campaign and cancel it if your store doesn't have any canceled/rejected/completed campaigns created in the past.
- Enable the Blaze card on the dashboard screen.
- Tap the campaign displayed on the card to open the detail web page.
- Tap Back, confirm that the web page is dismissed.
- Tap the campaign again > Promote again. Confirm that the web page is dismissed and the native campaign creation flow is presented.
- Switch to the Hub menu tab > Blaze.
- Select a cancelled/rejected/completed campaign to open the detail page and tap Promote again. Confirm that the web page is dismissed and the native campaign creation flow is presented.

## Testing information

Tested on simulator iPhone 15 Pro iOS 17.4:
- Confirmed that tapping Back on the campaign detail page dismisses the page on both dashboard and hub menu.
- Confirmed that tapping Promote again dismisses the page and presents the creation flow from both dashboard and hub menu.

## Screenshots

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/223">20.4</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by hafizrahman — APPROVED** [review]
The code looks good to me, the regex looks robust enough to get product id.

Just have some non-blocking questions:

> Tested on simulator iPhone 15 Pro iOS 17.4:
> Confirmed that tapping Back on the campaign detail page dismisses the page on both dashboard and hub menu.

I don't see Back button on a webview, so I assume you meant using Back gesture? But if yes, I can't do the Back gesture by dragging left-to-right on the simulator screen 🤔 

And, what is the file used for the demo video? Is it a GIF? I can't find the progress bar like when playing videos, so it was hard finding when's the start and when's the end of the video to compare it with the testing steps.

**Comment by itsmeichigo** [comment]
Thanks @hafizrahman for the review!

> I don't see Back button on a webview, so I assume you meant using Back gesture? But if yes, I can't do the Back gesture by dragging left-to-right on the simulator screen 🤔

The Back button is on the web page as the screenshot below. I have Vietnamese enabled for my account so it might not be obvious from the screencast.




> And, what is the file used for the demo video? Is it a GIF? I can't find the progress bar like when playing videos, so it was hard finding when's the start and when's the end of the video to compare it with the testing steps.

Yes, it's a gif. Sorry if that caused any inconvenience - I was using slow Internet and uploading videos took forever so I had to convert the video to a gif.

**Comment by hafizrahman** [comment]
> The Back button is on the web page as the screenshot below. I have Vietnamese enabled for my account so it might not be obvious from the screencast.

Ohh! Somehow I thought it's a back button on the toolbar 😮‍💨  Yup, it works correctly in my test then.

> Yes, it's a gif. Sorry if that caused any inconvenience - I was using slow Internet and uploading videos took forever

Ah, thanks for explaining! I had to watch a few times until I get the gist of the flow, it's not a huge problem. I just never saw something like this somehow in GH's interface. And I can totally relate with having slow internet :/

**Pull request merged**
