### PR TITLE
[Mobile Payments] Fix try out tap to pay flow on ios 17

### LINKED ISSUE #13596: [Mobile Payments] TTP try a payment doesn't progress after payment collected
## Description

While testing other IPP issues, I've found that the TTP try a payment flow doesn't completely work.

After tapping a card, the `Preparing payment` message remains on screen, even though payment is successfully taken. The success message is not shown, and the user has to force quit the app.

This only affects the `Try a payment` $0.50 test payment flow from the Payment Menu, not normal payments, but it's a bad first impression.

## Repro
1. Go to the payments menu
2. Tap `Set up (or try out) Tap to Pay on iPhone`
3. Go through the flow and tap a card
4. Observe that the payment dialog does not show success, but wait a few seconds. You should get the new order notification.
5. Force quit and reopen the app
6. Go to the orders tab
7. Observe that the test payment had been successful

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #13596

## Description

On iOS 17, the Try out Tap to Pay on iPhone flow was broken.

After the card payment flow was presented, in the preparing state, the `SimplePaymentsSummary` was dismissed from underneath it, while the merchant tapped their card.

This meant that the `SimplePaymentsSummary` and associated `PaymentMethodsView` were no longer available to handle the ongoing payment flow, and the payment flow was never dismissed.

The `NavigationLink.init(destination:isActive:label:)` used by `LazyNavigationLink` was deprecated with iOS 16, but does still work, generally.

In this case, since the flow was only broken for iOS 17, I opted to move to the new style of navigation, which also requires a `NavigationStack`. This approach fixed the issue, and continues to work on iOS 16.

## Steps to reproduce

Launch the app on an iPhone running iOS 17

1. Go to the payments menu
2. Tap `Set up (or try out) Tap to Pay on iPhone`
3. Go through the flow and tap a card
4. Observe that the payment flow continues and shows success
5. Tap `Save receipt and continue`
6. Observe that the payments menu is shown, and the payment is automatically refunded with a notice to confirm this.

Repeat on iOS 16 to confirm it still works there.

## Testing information

No unit tests – this is UI code only.

I found #13599 at the same time, and will fix it separately.

## Screenshots

https://github.com/user-attachments/assets/4f441cf4-36e1-4dff-bb0b-2c3d08e26092

---
- [x] I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [ ] This PR includes refactoring; smoke testing of the entire section is needed.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by iamgabrielma** [comment]
I'm seeing an odd behaviour here: When using the app I couldn't make this work either for the $0.50 test transaction, nor for a normal transaction through the Order flow. In all cases I'm always stuck in the the _Tap here_ screen and the payment doesn't complete.

However, I can see that the first transaction successfully went through and was automatically refunded as expected in my site, not so any other further attempt after "cancelling" (or what I though was cancelling) the payment. I'm guessing because might be attempting to send the same transaction and doesn't allow it to go through.

Screenshot 2024-08-14 at 10 23 00

Screenshot 2024-08-14 at 10 23 21

The only thing I see in the console is:

```
2024-08-14 10:11:55.129367+0700 WooCommerce[38025:42804644] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
```

For reference, the site is https://indiemelon.mystagingwebsite.com/ if you want to take a look. Both WooCommerce and WooCommerce Payments are outdated, I kept it this way just in case we want to debug further with these versions, otherwise I can just update to latests versions and try again. Let me know!

**Comment by joshheald** [comment]
> I'm seeing an odd behaviour here: When using the app I couldn't make this work either for the $0.50 test transaction, nor for a normal transaction through the Order flow. In all cases I'm always stuck in the the _Tap here_ screen and the payment doesn't complete.

@iamgabrielma thanks for the review.

Does the Order flow work with `trunk`? I'm going to guess that it doesn't, and if not, this is an unrelated issue.

I'll dig into it anyway and see whether I can repro on your site and understand why... but if you could check with a different store so we can merge this fix, that would be helpful. I can invite you to one of mine if needed.

**Comment by iamgabrielma** [comment]
> Does the Order flow work with trunk? I'm going to guess that it doesn't, and if not, this is an unrelated issue.

It doesn't, no 😭 

>  I can invite you to one of mine if needed.

Yes please, that would be great!

**Comment by joshheald** [comment]
@iamgabrielma it works with my phone on your site – if you could send some logs and any network request details that look useful from WormHoly that might help narrow it down. Requests to our API and Stripe's are both interesting.

It's strange for it to get stuck on Apple's tap here screen – is that the one you meant?

Once you've got the logs, and tried on my site, I'd suggest deleting then reinstalling the app, if you haven't already.

Sending you an invite now.

**Review by iamgabrielma — APPROVED** [review]
LGTM :shipit: 

I'm still unsure why wasn't working before, but it does seem to work just fine now while I was trying to record the issue (I did not re-install the app or updated anything).

**Pull request merged**
