### PR TITLE
Dark Mode: update colors for Products tab

### PR DESCRIPTION
**Pull request by jaclync**
Products (minus stars UI) for #1555 

## Changes

- Added a `border` semantic color
- Added a `UILabel` extension helper to style an actionable text label
- Applied actionable text label style to `ProductDetailsViewModel`'s actionable cells
- Removed unused code `NoteTableViewCell` and its xib
- Updated colors in `ProductImageCollectionViewCell` and `ProductsTabProductTableViewCell`
- Updated colors for Product cell status
- Removed setting `contentView.backgroundColor` in `UITableViewCell`'s applyDefaultBackgroundStyle()` so that the highlighted state has a different background color

## Testing

- Launch the app
- Go to the Products tab --> the Product cell should look as expected, with the correct text color for products with "draft" and "pending reviews" status. the image border color and placeholder colors should also look as expected
- Tap a Product with an image --> the Product images on the top should have a visible border with the correct color

## Example screenshots

Screen | Dark | Light
-- | -- | --
Products tab | Simulator Screen Shot - iPhone 8 - 2019-12-09 at 18 17 55 | Simulator Screen Shot - iPhone 8 - 2019-12-09 at 18 18 03
Product Details | Simulator Screen Shot - iPhone 8 - 2019-12-11 at 10 25 54 | Simulator Screen Shot - iPhone 8 - 2019-12-11 at 10 26 02

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by pmusolino — APPROVED** [review]
Everything looks good to me! 👍 

I've discovered only one "issue", not sure if the work in progress banner needs to be like the cells color or total black. What do you think @kyleaparker?

Simulator Screen Shot - iPhone 11 Pro - 2019-12-09 at 11 30 54

**Review by mindgraffiti — APPROVED** [review]
Looks great!

Are all Product screens part of the scope for this PR? One thing I noticed is the Edit Product screen has a white bar for the safe area at the bottom:

<kbd></kbd>

**Review by kyleaparker — CHANGES_REQUESTED** [review]
- On the product details screen, the images should be on a raised background (white in light mode, and the lighter grey in dark mode. The separator below the images is slightly too dark/thick, it should match the other separators

>I've discovered only one "issue", not sure if the work in progress banner needs to be like the cells color or total black. What do you think @kyleaparker?

It should match the banners on the dashboard and use the raised bg colour

**Comment by jaclync** [comment]
> Are all Product screens part of the scope for this PR? One thing I noticed is the Edit Product screen has a white bar for the safe area at the bottom:

@mindgraffiti we aren't shipping Edit Product in release 3.2, so the Dark mode updates are saved for a later 
ticket: https://github.com/woocommerce/woocommerce-ios/issues/1524

**Comment by jaclync** [comment]
> I've discovered only one "issue", not sure if the work in progress banner needs to be like the cells color or total black

@pmusolino @kyleaparker the top banner colors were updated in another PR https://github.com/woocommerce/woocommerce-ios/pull/1571 that was just merged, it should look as expected now

also updated the PR and screenshots in the PR description based on @kyleaparker 's feedback for another look!

**Comment by pmusolino** [comment]
LGTM :shipit:

**Comment by kyleaparker** [comment]
>also updated the PR and screenshots in the PR description based on @kyleaparker 's feedback for another look!

In the product details screenshots the product images are still sitting on the main background colour, they should be part of the group (white background on light mode, dark grey in dark mode)

**Comment by jaclync** [comment]
made two color updates based on @kyleaparker's feedback in https://github.com/woocommerce/woocommerce-ios/pull/1581/commits/4442a74b597403def16b134812c0936bcfc5be56, and checked the Product Details screenshots (also updated in the PR description) with Kylea in DM - merging now!

**Pull request merged**
