### PR TITLE
Fixed issue where no dates not available for selection

### LINKED ISSUE #6089: Can not select any date in custom range selection for the orders filters
**Describe the bug**
In the custom range selection for the orders filters if you select the custom start/end dates in a particular order and then try to select again the start or end date it will have all the dates not available for selection.   

*Details*
The same datepicker is reused for the start and end date so each will set a maximum and a minimum date and then (since  they are never cleared in the prepareforReuse) no dates not available for selection.

**To Reproduce**
1. Go to `Orders`
2. Tap on 'Filters'
3. Tap on 'Date Range'
4. Tap on 'Custom Range'
5.  Tap on 'Start Range'
6. Tap on 'End Range'
7. Tap on 'Start Range' again
8. All the dates are not available for selection

**Screenshots**

https://user-images.githubusercontent.com/96764631/152687584-9c1a4ea5-8e6c-446e-8c14-a2221accfd7b.mp4

**Expected behavior**

In the custom start date of the date range picker all dates until the end date should be available for selection.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Any
- iOS version:  Any
- WooCommerce iOS version: Any

**WordPress Environment**
Not relevant

### PR DESCRIPTION
**Pull request by chrisKns**
Closes: #6089

### Description
Fixed issue where no dates not available for selection In the custom range selection for the orders filters.
If you select the custom start/end dates in a particular order and then try to select again the start or end date it will have all the dates not available for selection.
This was caused because both maximum and a minimum date is set the the datepicker of the DatePickerTableViewCell because it is reused for the start and end date.

### Testing instructions

Go to Orders
1. Tap on 'Filters'
2. Tap on 'Date Range'
3. Tap on 'Custom Range'
4. Tap on 'Start Range'
5. Tap on 'End Range'
6. Tap on 'Start Range' again
 
All the dates from the current selection until the end  should be available for selection

Before & after the fix:

https://user-images.githubusercontent.com/96764631/152693843-cff21608-a8e3-4ad9-9b50-e8086edd47a9.mp4

https://user-images.githubusercontent.com/96764631/152693852-ee25e715-2271-4bb5-b591-9ed3c9a0d7ec.mp4

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by pmusolino — APPROVED** [review]
Looks good to me! Good catch. :shipit:

**Comment by pmusolino** [comment]
This PR close also this issue (duplicated) https://github.com/woocommerce/woocommerce-ios/issues/5647.
I believe it's worth to add the fix in the release note 👍

**Comment by pmusolino** [comment]
@Ecarrion I'll left you the final merge 🙇

**Comment by Ecarrion** [comment]
Great job @chrisKns! as @pmusolino says, could you update the [RELEASE-NOTES](https://github.com/woocommerce/woocommerce-ios/blob/trunk/RELEASE-NOTES.txt) to proceed with the merge please :-)

**Comment by chrisKns** [comment]
@Ecarrion & @pmusolino I updated the release notes! (I have another PR for #6091 that updates the release notes, so whichever is merged first I will rebase the the other)

**Pull request merged**
