### PR TITLE
Dashboard: Add support for Dynamic Type to "Number of orders to fulfill" section

### LINKED ISSUE #897: Dashboard: Add support for Dynamic Type to "Number of orders to fulfill" section
The section should expand vertically to accommodate the content. At the moment, the "review, prepare and ship these orders" copy is clipped

Simulator Screen Shot - iPhone 8 - 2019-04-23 at 08 32 31

### PR DESCRIPTION
**Pull request by ctarda**
Fix #897 

The fix is not completely fixing the issue. Notice how the bottom margin is ignored for regular font sizes:

Before and after, for regular font sizes:
before-after-bottom

On the bright side, this section supports large font sizes a bit better:
before-after-large

But, there is still something off with the bottom margin.

## Changes
- Removed some constraints from the container view controller.
- Removed some constraints from the `NewOrdersViewController`
- Make the `NewOrdersViewController` calculate its own `preferredContentSize`
- The parent view controller `DashboardViewController` recalculates the height of the `NewOrdersViewController` according to its preferredContentSize.

## Testing
- Checkout the branch, run the tests.
- Navigate to Dashboard
- Open the Accessibility Inspector (Xcode > Open Developer Tool > Accessibility Inspector)
- In the Accessibility Inspector, select the simulator and the Settings button:
Screenshot 2019-04-24 at 10 26 01 AM
- Change the font size at will

@mindgraffiti @astralbodies Another case of the trees not letting me see the forest. There is something off, it has to be obvious, I can not see it. Please, send help.

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by mindgraffiti** [comment]
I took a quick look at this and I see 3 stackviews embedded inside each other. That always causes ignored autolayout constraints for me. It will take me a couple of hours to figure out what the issue is with this, so I'm going to look into it later.

**Comment by ctarda** [comment]
Thanks for the tip, @mindgraffiti I'll play with simplifying those nested stack view as well.

**Comment by ctarda** [comment]
I recreated the stack views (and removed one in the process). 

Good things:
- It seems like recalculating the preferredContentSize in the child VC and refreshing the vertical constraint in the parent VC is the way to go.
- I've learnt quite a fews things about autolayout and about myself 😛 

The not so good things:
- There is something still a bit off (the top margin seems to tall), but I've spent 4 hours on this today already. I really need to switch context a little bit.

This is how it is looking now:
order-section

**Comment by mindgraffiti** [comment]
Hey @ctarda. When you get stuck like this, it would help me out a lot if you listed
1. Where you think the problem is
2. What things you've tried

That way I don't repeat the same efforts you've made :)

**Comment by ctarda** [comment]
Thanks @mindgraffiti  Of course!. I mentioned what I tried [in this slack thread](p1556170609031200-slack-mobile-woo)

The solution I have been exploring is:
- each and everyone of the child view controllers that are inserted into the Dashboard would recalculate their `preferredContentSize` on `viewDidLayoutSubviews`
- The parent view controller (DashboardViewController) overrides `preferredContentSizeDidChange:forChildContentContainer` and re-assigns the height of the corresponding child to the value of its preferredContentSize

In this case, that seems to work reasonably well, but the top margin seems off. 

I've recreated the layout of the child view controller (`NewOrdersViewController`) using only two stack views. The external one (on the horizontal axis) is pinned to the superview's safe area, and has assigned the proper margins. The internal one (vertical) has alignment set to Fill. Now that I write it down I realise maybe problem is with the alignment of the internal stack view...

**Comment by ctarda** [comment]
@mindgraffiti @astralbodies I think this is ready for review.

The approach, that in theory should work with other sections of the Dashboard, is:

- `NewOrdersViewController` (which is inserted into `DashboardViewController` as a child) recalculates its preferredContentSize on viewDidLayoutSubviews.
- The parent view controller (DashboardViewController) overrides preferredContentSizeDidChange:forChildContentContainer and re-assigns the height of the corresponding child to the value of its preferredContentSize
- I have recreated the layout of `NewOrdersViewController`, removing a couple of spacer views.
- Added an outlet to `DashBoardViewController` to retain a reference to the constraint applied to the height of space assigned to the child. 

If you folks are okay with the approach, I'd do the same in other children of `DashboardViewController`.

This is how it looks. From left to right, with a small font size, the default system font size, and one of the accessibility font sizes:

three-sizes

**Review by mindgraffiti — APPROVED** [review]
Nice work @ctarda! I know this was a tough one. I added one tiny change to your PR. The default size of table section headers is 55.5 points, so I updated the "Top Performers" view height to be that instead of 36 points. Hope that's okay.

Screen Shot 2019-04-26 at 2 34 59 PM


:shipit:

**Comment by ctarda** [comment]
Thanks @mindgraffiti for the review, and thanks for updating the "top performers" height as well!

**Pull request merged**
