### PR TITLE
Polish footer spinner view for `plain` table view style

### LINKED ISSUE #1262: Product List: show product list with infinite scroll
- Create `ProductsViewController` with a table view
- Set up results controller for Product models
- Call `ProductAction.synchronizeProducts(siteID: Int, pageNumber: Int, pageSize: Int, onCompletion: (Error?) -> Void)` to sync products when reaching close to the next page in the table view

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #1262 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Changes
- Added `tableViewStyle: UITableView.Style` to `FooterSpinnerView` initializer
- Updated `FooterSpinnerView` usage in Orders, Oders Search, and Shipment Providers (all of these view controllers have grouped table view style)
- Updated `FooterSpinnerView` usage in `ProductsViewController`, and used `FooterSpinnerView`/empty footer view based on spinner state

## Testing
- Log out of the app and then log in to a store with products
- Go to Products tab
- Scroll down the product list and observe the spinner at the bottom of the table view --> the spinner should be horizontally centered with space at the top and bottom
- After the products are all loaded, scroll to the bottom --> there should be no spacing at the footer

## Example screenshots

- Products tab

\ | before | after
-- | -- | --
with spinner | Screen Shot 2019-09-17 at 10 46 49 AM | Screen Shot 2019-09-30 at 11 09 40 AM
without spinner | Screen Shot 2019-09-17 at 10 46 12 AM | Screen Shot 2019-09-17 at 10 56 39 AM

- Order Search

before | after
-- | --
Simulator Screen Shot - iPhone 5s - 2019-09-30 at 11 12 16 | Simulator Screen Shot - iPhone 5s - 2019-09-30 at 10 46 23

### CODE REVIEW

**Comment by ctarda** [comment]
There is something that might be a bit off. Notice how the orders list has some space at the bottom:



This is a store with 14 orders, so it might be possible that there is only one screen worth of content

**Comment by jaclync** [comment]
Regarding the extra space at the bottom on the Orders tab, I believe this is how the current UI looks like on `develop` (and production) for a while. All the view controllers with a grouped table view and footer spinner view have spacing at the top and this exact same spacing at the bottom. Our own `FooterSpinnerView` adds some height to the bottom, but I just checked on `develop` and the bottom spacing is the same on `develop` and this branch. Do you think we want to chat with Kylea about changing the bottom spacing?

For `grouped` table view, using the Orders tab for example:

setting `tableView.tableFooterView = UIView(frame: .zero)` | `develop` | this branch
-- | -- | --
Simulator Screen Shot - iPhone 5s - 2019-09-30 at 10 38 53 | Simulator Screen Shot - iPhone 5s - 2019-09-30 at 10 39 19 | Simulator Screen Shot - iPhone 5s - 2019-09-30 at 10 40 12

**Comment by jaclync** [comment]
@ctarda @mindgraffiti I responded to the feedback and updated the screenshots in the PR description for another look! If we decide to update the footer UI for view controllers with `grouped` table view style, I can create a separate issue and PR for that and keep this PR for changes only on `plain` table view style

**Comment by mindgraffiti** [comment]
@jaclync from the i3 designs it looks like a bug. So yes, would you please add a new issue?

Ref. wp.me/p99K0U-1vW-p2

**Comment by jaclync** [comment]
> @jaclync from the i3 designs it looks like a bug. So yes, would you please add a new issue?
> Ref. wp.me/p99K0U-1vW-p2

hey @mindgraffiti thanks for checking the i3 design! for the bug, you meant the spacing at the bottom right? I couldn't seem to locate the design for the footer part, I'll confirm with Kylea

**Pull request merged**
