### PR TITLE
[Design] Update buttons, CTAs, and links from pink to purple

### LINKED ISSUE #8450: [Design] Update primary button, CTA, and link colors to purple
As proposed by design, we will update the pink buttons, CTAs, and link colors from pink to purple (but with white text on the button in both light and dark mode, contrary to the image here):

image

> We’ll continue to use colours from our color studio, making a simple switch from pink to purple. For the light theme, we’ll shift down one increment, use woo-purple-60 as default, and woo-purple-80 for pressed states. For the dark theme, we will use the equivalent 30 and 50 values that we already use in pink.

Internal ref: pecCkj-fa-p2

One difference from the image above:

> The text on the button in the dark mode will remain white to match the APCA standard.

Internal ref: pe5pgL-1tt-p2#comment-1494

Some specific cases:

* In the My Store stats chart, when you tap on a specific period in the chart the indicator line and stats text should remain pink.
* Marketing CTAs (like in the card reader upsell banner) should remain pink.
* There are color contrast issues using woo-purple-30 on the dark mode iOS tertiary background color, e.g. in the order editing UI. We should adjust to use the secondary background color instead.

### PR DESCRIPTION
**Pull request by rachelmcr**
Closes: #8450

⚠️ Needs both design and code review ⚠️ 

## Description

This PR updates our accent color (used for buttons, CTAs, and links) from pink to purple:

> We’ll continue to use colours from our color studio, making a simple switch from pink to purple. For the light theme, we’ll shift down one increment, use woo-purple-60 as default, and woo-purple-80 for pressed states. For the dark theme, we will use the equivalent 30 and 50 values that we already use in pink.

There are a few specific cases handled differently:

* In the My Store stats chart, when you tap on a specific period in the chart the indicator line and stats text are still pink, for contrast.
* Marketing CTAs (like in the products onboarding banner or the card reader upsell banner) are still pink.
* There are color contrast issues with the current background in the order editing form in dark mode. To resolve that, we're using a darker background in that form in dark mode to improve contrast.

### Changes

Color updates in `UIColor+SemanticColors`:
* The main change is to update `accent` and `accentDark` to the new purple shades.
* I left the `primary` color even though it is now defined the same as `accent`. I think it's worth keeping this, to make it easy to differentiate between primary and accent colors later if we want to make them different again. (But we could always remove that and switch everything to use `accent` if we're sure we want to combine them.)
* We had an unused `chartDataBarHighlighted` color; I renamed it to `statsHighlighted` and defined it as the old pink color, to use in stats where we want to retain the pink color when a specific chart period is selected.
* I added `modalListForeground` to define a different list foreground color in dark mode for views that we present modally, where we want more contrast between that color and the purple accent color. (Otherwise, the current color is elevated in dark mode, reducing contrast.)

The other changes are to update the chart colors (to keep them the same as before) and to use `modalListForeground` in the order editing form. This PR does not include any `UIButtonConfiguration` changes (related to https://github.com/woocommerce/woocommerce-ios/issues/7881), which will be done separately but build on the color changes here.

## Testing instructions

1. Build and run the app, or use the installable build below.
2. Go through the app in light mode, logged in and logged out, and confirm all of the pinks (aside from the exceptions above) are replaced with purple.
3. Switch to dark mode and confirm the expected shade of purple is used and has sufficient contrast.

## Screenshots

Before (light)|After (light)|Before (dark)|After (dark)
-|-|-|-
Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 18 37|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 36 46|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 24 27|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 36 55
Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 18 40|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 36 58|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 24 31|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 37 00
Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 19 02|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 37 08|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 24 41|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 37 10
Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 19 09|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 37 14|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 24 51|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 37 16
Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 19 29|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 37 28|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 24 59|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 37 31
Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 19 42|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 37 38|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 25 24|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 37 40
Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 19 49|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 37 50|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 25 29|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 37 52
Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 20 29|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 38 08|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 25 53|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 38 10
Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 20 42|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 38 18|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 26 02|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 38 20
Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 27 03|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 39 32|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 27 09|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 39 35
Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 27 18|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 39 41|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 27 22|Simulator Screen Shot - iPhone 14 Pro - 2022-12-19 at 21 39 43

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Ecarrion — APPROVED** [review]
Code looks good! 

What do you think about, instead of having `.modalListForeground` and `.listForeground`  we have a static function like `listForeground(modal: Bool) -> Color`?

I worry that developers won't know or won't remember that they have different options for each scenario, and could be better if we can make them choose explicitly between one or the other.

**Comment by rachelmcr** [comment]
> What do you think about, instead of having `.modalListForeground` and `.listForeground` we have a static function like `listForeground(modal: Bool) -> Color`?

That's a really good idea. I made that change in 4d57da2 — it's a lot of lines of changes, but it was a straightforward refactor of `.listForeground` to `.listForeground(modal: false)` and `.modalListForeground` to `.listForeground(modal: true)`. Thanks!

Just noting that I'll wait to merge until this has been approved by design.

**Comment by rachelmcr** [comment]
I've added the `status: do not merge` label to the PR, to prevent accidental merge before this has been reviewed by design.

If I'm AFK and this gets design approval, please feel free to remove that label and merge. (See also internal discussion: p1671532009789359-slack-C0354HSNUJH)

**Comment by annchichi** [comment]
Heya @rachelmcr, thanks for updating for color. 👍 I tried downloading the build number pr8451-4d57da2, but I still got a pink one. I was not able to download it directly via slack. 

All the changes are nice, and I noted a few things I found odd and have concerns about the contrast. 
 
 CleanShot 2022-12-21 at 16 34 27@2x
- The announcement icon, in dark mode, I find it hard see it. We can adjust it to woo-purple 30

CleanShot 2022-12-21 at 16 28 21@2x
- The number on the badge, I find it a bit hard to read when it's in the dark text (although WCGA is higher) but in APCA is higher. So, let's try to change it to white text and see how that goes. 

CleanShot 2022-12-21 at 17 13 07@2x
- I checked the prologue, order, and the empty state's CTA. Both WCGA and APCA show higher when it's in woo-purple-50 than 30. Although numbers are for reference, I think these two give a good indication. I am curious if we can change that. 


CleanShot 2022-12-21 at 16 33 16@2x
- Last, not about color. I find the alignment here a bit odd. haha That today should be aligned with my store and the store name. :) 

I am happy to review the build in my phone again, and I gather we will tune the color as we go. Thanks so much for this! 😸

**Comment by rachelmcr** [comment]
Thanks for the review, @annchichi! I pushed some changes and the new installable build is [available here](https://install.appcenter.ms/orgs/automattic/apps/WooCommerce-Installable-Builds). You can install `pr8451-6857c1d` to get the latest changes — you might need to scroll down to find that build in the list. Let me know if it doesn't work for you!

> The announcement icon, in dark mode, I find it hard see it. We can adjust it to woo-purple 30

Good point! I checked and it's the same in the current production version, so that isn't specific to these color changes. However, I figured out it only looks like that if you switch between light and dark mode without restarting the app. Here's how it looks after a restart:

Simulator Screen Shot - iPhone 14 Pro - 2022-12-22 at 11 14 47

Is that ok for now? We could look at improving the dynamic color changes when switching between light and dark mode, but that might be better to do separately, so we can review that behavior specifically. (This happens with any images like the megaphone icon where we're using the image asset's color settings directly in the app.)

> The number on the badge, I find it a bit hard to read when it's in the dark text (although WCGA is higher) but in APCA is higher. So, let's try to change it to white text and see how that goes.

Sure thing! Here's how that looks in light mode (no change) and dark mode (now with white text):

Simulator Screen Shot - iPhone 14 Pro - 2022-12-22 at 12 09 31
Simulator Screen Shot - iPhone 14 Pro - 2022-12-22 at 12 09 23

What do you think? We can also control this badge's background color, in case you want to make it darker in dark mode for better contrast with the text.

> I checked the prologue, order, and the empty state's CTA. Both WCGA and APCA show higher when it's in woo-purple-50 than 30. Although numbers are for reference, I think these two give a good indication. I am curious if we can change that.

Sure, we can do that. I've adjusted the primary button color, so all primary buttons like those will use woo-purple-50 in dark mode. Here's an example of how that looks normally and when selected:

Normal|Selected
-|-
Simulator Screen Shot - iPhone 14 Pro - 2022-12-22 at 12 17 08|Simulator Screen Shot - iPhone 14 Pro - 2022-12-22 at 12 17 11

> Last, not about color. I find the alignment here a bit odd. haha That today should be aligned with my store and the store name. :)

Sorry for the confusion! This row is scrollable on smaller devices and with "This Year" selected it's just scrolled off to the side. It starts out aligned like you expect before scrolling. :)

**Comment by annchichi** [comment]
Thanks, @rachelmcr, for the feedback and the update! 🙌  

>  I figured out it only looks like that if you switch between light and dark mode without restarting the app.
Yeah, got it. That's super. 

>We could look at improving the dynamic color changes when switching between light and dark mode
I didn't realize we could do that. I am up for it to improve the switching between the two. I guess it's not a priority. 😆 

>What do you think? We can also control this badge's background color, in case you want to make it darker in dark mode for better contrast with the text.
The badge color feels nice in white with more clarity. 

>Sure, we can do that. I've adjusted the primary button color, so all primary buttons like those will use woo-purple-50 in dark mode. Here's an example of how that looks normally and when selected

Understood that the pressed state will go a bit darker through a fleet of a moment. With this adjustment, I gathered users can see the buttons more clearly. It's not perfect, but we can roll with this one first and adjust to it accordingly. 😸 One option we can try in the future could be to dim the text. iOS buttons also do it. (Correct me if I am wrong. )

I spot a potential bug 🐛 (not with color). 
When I tapped Payments > Collect Payment > Cancel > My app went frozen. I will need to close forcibly. 

https://user-images.githubusercontent.com/13378873/209246348-2b00b948-05e5-4937-aad8-513cab8a3233.MP4

**Pull request merged**
