### PR TITLE
Variable Products are now editable with readonly variations

### LINKED ISSUE #2084: Edit Variable Products: show variations row or edit variations action in the bottom sheet
- [ ] Whenever we show Edit Product UI, enable it for a variable product if M3 flag is on
- [ ] Hide Shipping, Inventory, and Price Settings rows for variable products
- [ ] Show the variations row if the product has any variations (we'll handle the empty state when we implement creating new variations). Tapping on the row navigates to the existing Product Variations screen (`ProductVariationsViewController`)

Screen Shot 2020-04-03 at 3 03 30 PM

- [ ] If the product has no variations yet, show a placeholder (but we can't show "Add variations" yet since we aren't supporting adding a variation until M4)

Screen Shot 2020-07-15 at 11 04 25 AM

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #2084 

- [x] ⚠️ Make sure PR base is `develop` after https://github.com/woocommerce/woocommerce-ios/pull/2508 is merged ⚠️ 

## Changes

- Added `variationsImage` with `types` icon from Gridicons for the variations row in product form + unit test
- Added `variations` case to `ProductFormEditAction` enum for the variations row. In `ProductFormActionsFactory`, it only shows the variations row for a variable product if it has non-zero variations
- Added a helper `isNotEmpty` to `ProductFormSection` enum, so that we can filter the visible sections in `DefaultProductFormTableViewModel`
- In `DefaultProductFormTableViewModel`, configured the variations row view model
- In `ProductFormViewController`, showed the readonly variations when the user taps on the variations row in product form
- In `ProductDetailsFactory`, updated to show editable product form instead of readonly product details for a variable product if M3 flag is enabled
- Updated unit tests

## Testing

Prerequisites: the site has at least 2 variable products, one has no variations and the other has non-zero variations

### M3 feature flag is on: variable products are editable

**Test case 1**

- Go to the Products tab
- Tap on a variable product without variations --> should not see a variations row
- Feel free to edit the product name, description, images, tags, categories, short description
- Tap "Update" --> the product should be updated remotely

**Test case 2**

- Go to the Products tab
- Tap on a variable product with variations --> should see a variations row
- Tap the variations row --> it should show readonly variations
- Go back to the product form, and free to edit the product name, description, images, tags, categories, short description
- Tap "Update" --> the product should be updated remotely

### M3 feature flag is on: variable products are readonly

Please turn off M3 feature flag by returning `false` for `editProductsRelease3` in `DefaultFeatureFlagService`

**Test case 1**

- Go to the Products tab
- Tap on a variable product without variations --> it should show the readonly product details

**Test case 2**

- Go to the Products tab
- Tap on a variable product with variations --> it should show the readonly product details

## Example screenshots

simulator

screen | light | dark
-- | -- | --
variable product with variations | Simulator Screen Shot - iPhone 11 - 2020-07-15 at 14 02 29 | Simulator Screen Shot - iPhone 11 - 2020-07-15 at 14 03 43
variable product with variations - bottom sheet | Simulator Screen Shot - iPhone 11 - 2020-07-15 at 14 03 18 | Simulator Screen Shot - iPhone 11 - 2020-07-15 at 14 03 46
variable product without variations | Simulator Screen Shot - iPhone 11 - 2020-07-16 at 10 49 17 | Simulator Screen Shot - iPhone 11 - 2020-07-16 at 10 48 39
variable product without variations - bottom sheet | Simulator Screen Shot - iPhone 11 - 2020-07-16 at 10 49 18 | Simulator Screen Shot - iPhone 11 - 2020-07-16 at 10 48 58

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jaclync** [comment]
> I have one comment for the variable products without variations, the variations row should read "Variations / No variations yet" for now:

@Garance91540 I first thought we're showing the row for a variable product without variations, but then I checked the Android app and it actually hides the row. In the readonly product details (the product details in production), we also currently hide the row if the variable product has no variations. do we want to be consistent across both platforms? or this is also a pending item on Android?

**Comment by Garance91540** [comment]
> @Garance91540 I first thought we're showing the row for a variable product without variations, but then I checked the Android app and it actually hides the row. In the readonly product details (the product details in production), we also currently hide the row if the variable product has no variations. do we want to be consistent across both platforms? or this is also a pending item on Android?

Hi @jaclync , I haven't reviewed it on Android yet, so I'll report it to align with iOS! I think showing the row gives more context to the users on what's going on who is opening a variable product but don't see anywhere to add variations.

**Comment by jaclync** [comment]
> Hi @jaclync , I haven't reviewed it on Android yet, so I'll report it to align with iOS! I think showing the row gives more context to the users on what's going on who is opening a variable product but don't see anywhere to add variations.

@Garance91540 sounds good! I updated the screenshots in the PR description for another pass 👀 

@pmusolino I updated with 2 commits https://github.com/woocommerce/woocommerce-ios/pull/2510/commits/425bca175cbc9235ebf75ab86a545fadea72c7ee and https://github.com/woocommerce/woocommerce-ios/pull/2510/commits/56801a49c027b5b4ebfd3eec5cdefa8b47c0b816 to show the variations row when the product has no variations. see if you'd like to take another look!

**Comment by pmusolino** [comment]
@jaclync :shipit: the changes look good to me!

**Pull request merged**
