### PR TITLE
Document Core Data Model Version Guidelines

### PR DESCRIPTION
**Pull request by shiki**
Documents the discussion about Core Data model versions (p91TBi-3pE-p2).

## Testing

Please read and review the documentation [here](https://github.com/woocommerce/woocommerce-ios/blob/24769a1c918df2656776970b972172459ec7f2b4/docs/creating-core-data-model-versions.md). 

## Submitter Checklist

- [x] If it's feasible, I have added unit tests. 
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by jaclync — APPROVED** [review]
Thanks a lot for the detailed documentation 💟 Nice link to @astralbodies's Core Data migration post!

I like the section about adding unit tests, enforcing unit tests for each model version and explaining why `NSManagedObject` is preferred. If we ever have a model version that renames an existing required attribute (pretty unlikely and it requires manual migration), we might have to version its `insert*(to:) -> NSManagedObject` helper.

**Review by Ecarrion — APPROVED** [review]
Thank you for this! 🚀

**Comment by shiki** [comment]
> If we ever have a model version that renames an existing required attribute (pretty unlikely and it requires manual migration), we might have to version its insert*(to:) -> NSManagedObject helper.

I think it can be done using a mapping model. And yeah, we'll have to version the `insert()`. I did not think that far ahead yet. 😄 

Thank you, both!

**Comment by astralbodies** [comment]
@shiki Flattery will get you nowhere!

Who am I kidding, of course, it helps hahahahaha

**Pull request merged**
