### PR TITLE
[Composite Products] Navigate from component list to settings

### PR DESCRIPTION
**Pull request by rachelmcr**
Part of #8956
⚠️ Depends on #9295

## Description

This PR adds navigation from the product details Components list to the Component Settings view for composite products.

For now, the Component Settings view will show placeholders for the Component Options and Default Option; this data will need to be loaded from storage/remote (in a separate PR).

### Changes

* Adds support for initializing the `ComponentSettingsViewModel` from a `ComponentsListViewModel.Component`.
   * Includes adding the necessary properties (`description`, `optionType`) to that `Component` struct, to pass to the settings view model.
   * For now, the `options` and `defaultOptionTitle` properties in the settings VM are set to empty/placeholders.
* Adds an extension for `CompositeComponentOptionType` to display a localized description for the option type.
* Adds the navigation from `ComponentsList` to `ComponentSettings` upon selecting a component in the list.

### Prerequisites

1. Install and activate the [Composite Products extension](https://woocommerce.com/products/composite-products/) on your store.
2. Create at least one product with the Composite Products type, with at least one component.

### To test

1. Build and run the app.
2. Go to the Products tab.
3. Open a Composite Product.
4. Select the Components row in product details.
5. Select a component from the list and confirm it opens the Component Settings with the expected details (image, title, description, and placeholders for component options and default option).

## Screenshots

https://user-images.githubusercontent.com/8658164/227608095-ee090b80-f142-4ada-819a-586940ef9b4e.mp4

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Ecarrion — COMMENTED** [review]
The code looks good but I haven't been able to properly test this because I'm getting parsing errors on multiple stores. 

In my test one, I'm getting.

```
 - 4 : CodingKeys(stringValue: "default_option_id", intValue: nil)
      - debugDescription : "Expected to decode String but found a number instead."
```
And in yours `teststore.rachel_test_domain....` im getting

```
    - 2 : CodingKeys(stringValue: "average_rating", intValue: nil)
      - debugDescription : "Expected to decode String but found a number instead."
```      
      
    
Have you experienced that?

**Comment by rachelmcr** [comment]
> Have you experienced that?

@Ecarrion I hadn't experienced that (not even the parsing error on my test store, which is weird). Thanks for patching those errors in https://github.com/woocommerce/woocommerce-ios/pull/9298. I've merged the changes from `trunk` into this branch; could you try testing this again?

**Review by Ecarrion — APPROVED** [review]
I still can't access composite products on `dulces.mystagingwebsite.com` or on `teststore.rachel-test-domain.com`.

I could access them on `superlativecentaur.wpcomstating.com` and the navigation looks alright! 

I did notice a small UI problem that I think is not related to this PR tho.

Screenshot 2023-04-03 at 9 21 21 AM

See how the disclosure indicators are hidden by the notch, their layout should be inside the safe areas constraints.

**Comment by rachelmcr** [comment]
> See how the disclosure indicators are hidden by the notch, their layout should be inside the safe areas constraints.

Good catch, thanks! Those rows only had padding on the leading edge; I fixed that in 57c56fe with padding on both horizontal edges. I also fixed the dividers so the divider at the bottom of the section is full width. (I think you mentioned this on an earlier PR and I misunderstood/didn't see what you meant there.)

Simulator Screen Shot - iPhone 14 Pro - 2023-04-03 at 15 56 46

I've started to look into the differences in the API responses on these stores, to get the parsing sorted out for composite products.

**Pull request merged**
