### PR TITLE
Update illustrations for products tab empty state and product loader states

### PR DESCRIPTION
**Pull request by jaclync**
Part of #3786 

## Why

We're ready to update the illustrations in the app to the latest design from core! This PR focused on the orders tab, and the change of empty search results also applies to products tab empty search results.

Ref: G's post p91TBi-40j-p2

## Changes

- Added 3 new image assets (the pre-existing ones are still used in other screens): `emptyProductsTabImage`, `productDeletedImage`, and `productErrorImage`
- In `ProductLoaderViewController`, updated UI for two empty state scenarios: the product cannot be loaded, and the product has been deleted
  - Updated to use `EmptyStateViewController` instead of `OverlayMessageView`, which does not share the same style as other empty states (e.g. the CTA is secondary style in `OverlayMessageView`)
- In `ProductsViewController`, updated UI for empty state:
  - In order to support popover for Add Product bottom sheet on tablet:
    - Added support for `UIView` source view for Add Product bottom sheet in `AddProductCoordinator`, in addition to the existing `UIBarButtonItem` source view. I updated the arrow directions to `.any` so that it can be dynamic
    - Added `UIButton` parameter to `EmptyStateViewController.Config.withButton` so that we can pass the button as the source view
  - Updated to use `EmptyStateViewController` instead of `OverlayMessageView`
  - Fixed an issue where initial empty state isn't shown https://github.com/woocommerce/woocommerce-ios/commit/e320fb1beff091bf1a1e19cb689e733f9160d42f

### Products tab empty state

- For easier testing, you can update the expected site ID to a different one (e.g. 123):
https://github.com/woocommerce/woocommerce-ios/blob/eeee79ebafb171a64eeae3a9a78afa38b0403efc/Yosemite/Yosemite/Tools/Products/ResultsController+FilterProducts.swift#L9
- Launch the app, log in if needed
- Go to the products tab --> the empty state should be shown with the expected UI

### Product cannot be loaded

- For easier testing, you can update the code below to `self.state = .failure`:
https://github.com/woocommerce/woocommerce-ios/blob/eeee79ebafb171a64eeae3a9a78afa38b0403efc/WooCommerce/Classes/ViewRelated/Products/Product%20Loader/ProductLoaderViewController.swift#L118
- Launch the app, log in if needed
- Go to the orders tab
- Tap on an order
- Tap on a product in the order --> the product loading error UI should look as expected

### Product has been deleted

- For easier testing, you can update the code below to `self.state = .notFound`:
https://github.com/woocommerce/woocommerce-ios/blob/eeee79ebafb171a64eeae3a9a78afa38b0403efc/WooCommerce/Classes/ViewRelated/Products/Product%20Loader/ProductLoaderViewController.swift#L118
- Launch the app, log in if needed
- Go to the orders tab
- Tap on an order
- Tap on a product in the order --> the product deleted error UI should look as expected

## Example screenshots

Screencast for adding a product from the products tab empty state:

https://user-images.githubusercontent.com/1945542/110584347-04ce8980-81aa-11eb-9273-1ef231d4c35b.mov

Tablet screenshots for the Add Product popover:

Add product from navigation bar | Add product from empty state CTA
-- | --
Simulator Screen Shot - iPad Air (4th generation) - 2021-03-10 at 12 35 21 | Simulator Screen Shot - iPad Air (4th generation) - 2021-03-10 at 12 35 24

### Dark mode

\ | Product deleted | Product loading error | Products tab empty state
-- | -- | -- | --
before | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 10 25 10 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 10 40 44 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 10 41 30
after | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 11 10 38 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 11 12 01 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 12 30 40

### Light mode

\ | Product deleted | Product loading error | Products tab empty state
-- | -- | -- | --
before | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 10 24 30 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 10 40 35 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 10 41 56
after | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 11 10 52 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 11 11 52 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 12 30 50

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by shiki — COMMENTED** [review]
> Product has been deleted

🛑 For some reason, I could not reproduce this. Here are my steps: 

1. Submitted an order of Product A. 
2. In wp-admin, moved Product A to Trash. 
3. Opened the app and opened the product from the submitted order. The product can still be loaded. 🤷 

I'm not sure how this was supposed to work. If I permanently delete the product, I would see the [product cannot be loaded](https://user-images.githubusercontent.com/1945542/110584206-d05acd80-81a9-11eb-9eac-15ffbc2623a6.png) instead. 

I can reproduce the same behavior in RC 6.2. 

@pmusolino Do you have some background about this behavior?

**Review by shiki — CHANGES_REQUESTED** [review]
Code looks good to me. Just that behavior question I have in https://github.com/woocommerce/woocommerce-ios/pull/3811#pullrequestreview-608961745. 

@pmusolino Let me know how we can move forward with that.

**Comment by pmusolino** [comment]
@shiki I'll take care of this after the hack week 👍

**Comment by pmusolino** [comment]
@shiki I double-checked this PR, and everything works like expected. 

> I'm not sure how this was supposed to work. If I permanently delete the product, I would see the product cannot be loaded instead.

This is correct, because if you move the product into the trash, it will become no more visible to customers in the shop, but for us, it just changed the state and we are able to load it. If you permanently delete the product, we will no more able to load the product, and the empty state will be shown 👍

**Review by shiki — APPROVED** [review]
Quickly discussed in p1615912091003400-slack-C6H8C3G23. The app still loads trashed products for me. 

image

It looks like the product loading was still successful even though I trashed the product. This line is executed instead of the notFound state:

https://github.com/woocommerce/woocommerce-ios/blob/87d05204b601aec1ae20753fc69ed6f12755cb5e/WooCommerce/Classes/ViewRelated/Products/Product%20Loader/ProductLoaderViewController.swift#L122

Maybe the error changed at some point and trashed products can be loaded now. 🤷 But as I think more about this, this is probably alright. It’s better to show the product to the merchant anyway. So :shipit:

**Pull request merged**
