### PR TITLE
[Woo POS] Add new items to the top of the cart

### PR DESCRIPTION
**Pull request by staskus**
## Description

Add new items to the top of the cart:
- Use insert(item, at: 0) instead of append
- Add new test

### Adding items

1. Open POS
2. Select a new item
3. Confirm a new item appears at the top of the cart
4. Check Out
5. Confirm items appear in the same order
6. Come back
7. Check Out again
8. Confirm totals are not reloaded since items remained the same
9. Remove first, last, and middle items, and confirm they are removed as expected
10. Clean the cart
11. Confirm it continues working

### Scrolling

1. Open POS
2. Add many items, more than fits in the cart
3. Scroll to the bottom of the cart
4. Add item
5. Confirm that cart scrolls to the top

## Testing information

Added a new unit test confirming that items are added in reverse order.

Manually tested scenarios mentioned in 'Steps to reproduce' to confirm that previous Cart functionality continues to work as before

### General behavior
https://github.com/user-attachments/assets/44e45c44-c44e-4218-9285-117466b7d9fd

### Scrolling to the last added item

https://github.com/user-attachments/assets/b4b3540a-cb91-44b1-b512-e45f2ae007d1

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by joshheald** [comment]
I know you've put this back in draft, but I had a quick look anyway. Two issues I spotted:

1. It doesn't scroll to the top when you insert something after scrolling down... it probably should?
2. The insertion animation is a bit broken...

https://github.com/user-attachments/assets/86946c77-0e41-413b-8fdb-3c3f1272f2c7

**Comment by joshheald** [comment]
> It doesn't scroll to the top when you insert something after scrolling down... it probably should?

Oh wait, you just pushed that

**Comment by staskus** [comment]
> Oh wait, you just pushed that

@joshheald yes, sorry. I missed this behavior.

**Review by joshheald — APPROVED** [review]
Looks great! Sorry for the premature comments.

**Pull request merged**
