### PR TITLE
[Menu] Use tab container view controller for Hub Menu

### LINKED ISSUE #13640: [Crash] Crash on iOS 18 when tapping the Menu tab
**Describe the bug**

The app crashes on a device with the iOS 18 beta after installing/connecting Jetpack (while logged in to a store that wasn't previously connected via Jetpack) and then tapping the Menu tab.

**To Reproduce**
1. Log in to the app with a WooCommerce store without Jetpack.
2. Follow the prompt to install and connect Jetpack.
3. After Jetpack is installed, tap the Menu tab in the bottom tab bar.
4. Result: Crash.

Here's the start of the crash details (full details available in Xcode crashes or TestFlight crashes in App Store Connect - I didn't see it reported in Sentry):

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: WooCommerce [7884]

Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x18e8ad08c __exceptionPreprocess + 164 (NSException.m:249)
1   libobjc.A.dylib               	0x18bbaf2e4 objc_exception_throw + 88 (objc-exception.mm:356)
2   Foundation                    	0x18dc7e15c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 288 (NSException.m:252)
3   UIKitCore                     	0x191a6d3e0 -[UITabBarController _viewControllerForTabBarItem:] + 432 (UITabBarController.m:3964)
4   UIKitCore                     	0x191a6d48c -[UITabBarController _tabBarItemClicked:] + 32 (UITabBarController.m:3975)
```

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Closes: #13640

### What?

The app crashes in the iOS 18 beta upon navigating to the Menu tab after switching stores. 

Crash log

```
*** Assertion failure in -[WooCommerce.MainTabBarController _viewControllerForTabBarItem:], UITabBarController.m:3964
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Inconsistency in UITabBar items and view controllers detected. No view controller matches the UITabBarItem '<UITabBarItem: 0x106fc7180> title='Menu' image=<UIImage:0x302be5b90 named(main: icon-hub-menu) {21, 20} renderingMode=alwaysTemplate> selected'.'
*** First throw call stack:
(0x1921a908c 0x18f4ab2e4 0x19157a15c 0x1953693e0 0x19536948c 0x194cc8588 0x1023de3e4 0x19522bf4c 0x194cc8588 0x1023de3e4 0x194cc8460 0x194cc82b0 0x19522d3bc 0x194cc8588 0x1023de3e4 0x194cc8460 0x194cc82b0 0x195429964 0x194c10a58 0x194c104a4 0x194aa4aec 0x194aa5018 0x194aaed84 0x1949a70e8 0x1949a4e60 0x1949a4ab0 0x1949a5a24 0x19217c088 0x19217c01c 0x192179b08 0x192178d04 0x1921785b8 0x1dda511c4 0x194cd7a70 0x194d85ee0 0x108396f68 0x1b788ad34)
libc++abi: terminating due to uncaught exception of type NSException
```

### How?

We couldn't find any helpful information about the reason for the crash from the crash log. 

As per our investigation this crash happens when the Hub menu view controller is replaced after switching stores. 

Both the orders and products screens use a `TabContainerController`, and the Hub Menu uses a `WooTabNavigationController` in the `MainTabBarController`.

In this PR, we start using `TabContainerController` for the "Hub Menu" tab, just like the "Orders" and "Products" tabs.

### Why?

Thanks to Huong, our reasoning behind this change is:

`HubMenu` 's root view is a `NavigationStack`, which might have a similar behavior with Orders and Products tabs' split views. Both are unusable when embedded inside a navigation controller in tab controller, so moving hub menu to a `TabContainerController` sounds like a good solution. This leaves us with only Dashboard using `WooTabNavigationController`, which works fine for now as its root view is simply a scroll view.

We also found this thread, which talks about a similar crash log - https://developer.apple.com/forums/thread/762260

Internal - p1724124295456389-slack-C03L1NF1EA3

🗒️ I am not targeting a beta fix; I want this change to go through the full beta testing cycle. This leaves us time to find any unintended side effects. 

## Steps to reproduce

Prerequisites
- You need a device running iOS 18 beta.
- Test the below steps on both iOS beta and official versions. 

Non-Jetpack store
- Login into the app using a JN store without Jetpack.
- From the Dashboard, follow the Jetpack prompt and finish installing Jetpack.
- Navigate to `Menu` and validate that there is no crash. 
- Smoke test that navigation from inside the "Menu" tab works as before.

Jetpack
- Login into the app using a Woo Store with Jetpack using your WPCOM account
- Navigate to Menu and switch stores.
- After landing in the Dashboard navigate to Menu again and validate that there is no crash.
- Smoke test that navigation from inside the "Menu" tab works as before.

Product review push notification
- Login into the app using a Woo Store with Jetpack using your WPCOM account.
- Allow push notifications permission.
- Send the app to the background.
- From the web, leave a review for a product.
- You should receive a push notification about the new product review in the Woo App.
- Tap on it and validate that you are navigated to the Product Review detail page.

## Testing information

- Please smoke test the navigation in the Hub menu tab to works as before.

## Screenshots

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/219">20.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by selanthiraiyan** [comment]
👋 @rachelmcr Could you kindly help us test the PR on a device running iOS 18 beta? Thank you!

**Review by itsmeichigo — COMMENTED** [review]
The code changes look good to me. I don't have a physical device with iOS 18 beta, but I tested the following scenarios:

✅  Simulator with iOS 18.1 beta: the menu tab is no longer missing upon login, and the app doesn't crash when switching to the menu tab after Jetpack setup / switching stores for Jetpack sites. 



✅ Opening review details from push notification on a physical device running iOS 17.5.1.

⚠️ Smoke testing navigation: there's a minor issue with the navigation title missing on the Review list and Coupon list when navigated from the hub menu. This doesn't happen consistently, so can be reproducible by navigating back and forth with these screens. This might have something to do with the title being set in the wrapped UIViewController - I suppose setting titles on the SwiftUI component might fix it.

**Comment by rachelmcr** [comment]
@selanthiraiyan I tested on my iPhone with iOS 18.0 beta and it works great! Thanks! 👍

**Comment by selanthiraiyan** [comment]
Thanks for the review, @itsmeichigo!

I have logged a separate GH issue for the missing navigation titles issue: https://github.com/woocommerce/woocommerce-ios/issues/13676. We can address that separately, as it is is not a regression caused by the changes from this PR. 

Please approve the PR if this sounds good to you.

**Review by itsmeichigo — APPROVED** [review]
🚢

**Pull request merged**
