### PR TITLE
[Order Creation] Prevent line deletion via steppers

### LINKED ISSUE #11650: [Order Details] Show disabled `-` in favour of `x` removal button in stepper
> During a HACK week, I experimented with this and prototyped [an undo button for accidental removal via the stepper] – see this thread for our discussions: {p1701966962814919/1698242168.356949-slack-C6H8C3G23}
> 
> While it looks nice in a demo, I found that it wasn't reliable if you start being less gentle with it. It _may_ have been made a little more resilient by some other changes we've made since then, but I suspect the underlying issue is still there.
> 
> The unreliability comes from the way we sync changes to the order product rows, which results in a PUT to /orders/{id} for (almost) every change to the order, in real time. These can clash, which is normally resolvable, but if you end up removing and re-adding a product to the order, it gets a new line ID and can sometimes result in having the same product in the order twice.
> 
> [Due to this unreliability, we decided] to remove the `x` button in the stepper, which has been on my to-do list for a while.[...]

_Originally posted by @joshheald in https://github.com/woocommerce/woocommerce-ios/issues/9680#issuecomment-1882768636_

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #11650

## Description

Up to now, it’s been possible to remove a product by tapping the delete button in the product stepper. We previously made this easier to identify by changing the button to a red `x`, however it was still easy to accidentally trigger, and annoying to recover from (as the product needs to be found and added again.)

As one attempt to improve this, we tried adding an undo button in a notice after deletion, but it opened up too many issues of unreliability, e.g. sometimes adding the same product as two lines of the order.

Since there’s a dedicated `remove product from order` button, visible alongside the stepper, we’ve decided to remove this functionality from the stepper.

This PR disables the `-` button of the stepper when it’s at the minimum quantity.

## Testing instructions

1. Launch the app
2. Navigate to `Orders > +`
3. Add a product
4. Observe that the `-` button on the stepper is disabled (visually and taps do not work)
5. Tap `+`
6. Observe that the `-` button is enabled
7. Tap `-`
8. Observe that the `-` button is disabled again.

Repeat the above test while editing an order.

Note that the button no longer is an `x` and no longer deletes the line item. The `Remove item from order` button still works and is the way to remove a line item.

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/2472348/574d51db-abac-4b5b-8f26-82b8f310e49e

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by joshheald** [comment]
@iamgabrielma please could you review this?

@jaclync – no need for a full review but I wanted to get your eyes on this if you have a moment because of the product bundles stuff. I _think_ that product bundles didn't have the `x` deletion functionality on the stepper anyway, because we don't provide a remove product closure to the stepper view model... but I wanted to check and don't have any set up to test with. Some context as to how I set them up would be more than enough!

@bozidarsevo - FYI

**Comment by bozidarsevo** [comment]
> @bozidarsevo - FYI

Looks good! :)

**Review by iamgabrielma — APPROVED** [review]
LGTM and tests well! :shipit:

**Review by jaclync — APPROVED** [review]
> no need for a full review but I wanted to get your eyes on this if you have a moment because of the product bundles stuff. I _think_ that product bundles didn't have the `x` deletion functionality on the stepper anyway, because we don't provide a remove product closure to the stepper view model... but I wanted to check and don't have any set up to test with. Some context as to how I set them up would be more than enough!

Correct, the bundled product rows cannot be removed, only the top-level bundle product has editable quantity. I tested the PR and it works as expected!

Regarding how to set up product bundles:
- the store has the [Product Bundles extension](https://woocommerce.com/products/product-bundles/) installed and active (this extension is also included in a Woo Express store by default)
- the store has at least one bundle product with non-empty bundle items ([setup guide](https://woo.com/document/bundles/bundles-configuration/#getting-started)). currently, it can only be created and configured in core
- now the bundle product should be able to be added to an order in the app

**Comment by joshheald** [comment]
> I tested the PR and it works as expected!
>
> Regarding how to set up product bundles:
> 
>     * the store has the [Product Bundles extension](https://woocommerce.com/products/product-bundles/) installed and active (this extension is also included in a Woo Express store by default)
> 
>     * the store has at least one bundle product with non-empty bundle items ([setup guide](https://woo.com/document/bundles/bundles-configuration/#getting-started)). currently, it can only be created and configured in core
> 
>     * now the bundle product should be able to be added to an order in the app

Thanks for testing it @jaclync, and for the instructions! I'll add that to one of my test sites since I'm working in the Order Creation/Editing space a lot right now

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/180">16.9</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/180">16.9</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
