### PR TITLE
Feature/add release tooling

### PR DESCRIPTION
**Pull request by loremattei**
This PR adds some Fastlane lanes that help the release of the app.
In order to share the same code, all the actions in the WordPress iOS repository have been extracted and added to the release-toolkit.

# To Test
Testing is not trivial and should be done paying great attention, especially for the code_freeze lane because the test is done on the main repository.

In order to make the steps clearer, I'm referring to defined release numbers, instead of saying _this version_ or _next version_. Note that these numbers works as of today, when 1.4 is the version in beta testing. If you test this PR later, you have to change the number consequently. 

### code_freeze lane
This lanes executes the steps to code freeze a new version of the app.
Please, be super careful with this and make sure to revert all the changes that the script does.

1. Tag a fake version 1.4 in your local repository: `git checkout develop`  &&  `git tag 1.4`.  You don't need push it to origin.
2. Checkout this branch and run `bundle exec fastlane code_freeze`.
3. Verify that a new 1.5 branch has been created.
4. Verify that the version has been updated in XCConfig, Deliverfile and download_metadata.
5. Verify that the English version of Localizable.strings has been updated with the latest strings.
6. Verify that the 1.5 milestone has marked with the snowflake icon.
7. Verify that the branch protection has been set for the `release/1.5` branch.
8. Verify that the change log file has been created in your home.

Clean up
1. Remove the branch protection for the `release/1.5` branch on GitHub.
2. Delete the `release/1.5` branch on GitHub.
3. Remove the snowflake icon from the 1.5 milestone.
4. Remove the 1.5 tag from your local repository.
5. Remove the `release/1.5` branch from your local repository.

### new_beta_release lane
This lane updates the version of the app to prepare for a new beta release.
The simpler way to test this lane is to use a forked repository.
1. Fork the repository. For the rest of the steps, use the forked repo.
2. Checkout the `release/1.4` branch and merge this branch into it.
3. Run `bundle exec fastlane new_beta_release`.
4. Verify that the proposed version is right and confirm.
5. Verify that the xcconfig file has been updated correctly and that the new tag has been added.
6. Verify that all the files have been committed.

### finalize_release lane
This lane bumps the version to the final one, downloads the translations and clean the temp tags.
The simpler way to test this lane is to continue to use the forked repository from the step above.
1. Checkout the `release/1.4` branch.
2. Run `bundle exec fastlane finalize_release`.
3. Verify that the app translations and the metadata translations have been downloaded.
4. Verify that the xcconfig file has been updated correctly and that the new tag has been added.
5. Verify that all the files have been committed.
6. Verify that the temporary tags for the beta versions have been deleted.

### build_and_upload_release lane
This lane builds the current branch and uploads the binary to TestFlight and the related dSYM to Crashlytics. 
Since we can't delete test versions from TestFlight, the test can be performed rebuilding the current release/1.4 branch (the original one! not the forked one that has been configured with a new version number!) and verifying that the upload fails because a binary with that version already exists. 
It confirms that the build, signing and login into TestFlight work. The actual upload is handled by the Fastlane itself.
1. Switch to the original repository.
2. Checkout the `release/1.4` branch.
3. Run `bundle exec fastlane build_and_upload_release`.
4. Verify that the binary is built.
5. When prompted, login into TestFlight.
6. Verify that the upload is started and that it fails because of the version validation.

### CODE REVIEW

**Comment by jtreanor** [comment]
The `code_freeze` lane is failing for me. It gets as far as the `ios_localize_project` step but then I get this error:

```
[12:07:15]: ----------------------------------
[12:07:15]: --- Step: ios_localize_project ---
[12:07:15]: ----------------------------------
[12:07:15]: Updating project localisation...
[12:07:15]: $ cd ./ && ./Scripts/localize.py
[12:07:17]: ▸ 2019-03-22 12:07:17.096 genstrings[18504:69095741] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString characterAtIndex:]: Range or index out of bounds'
[12:07:17]: ▸ *** First throw call stack:
[12:07:17]: ▸ (
[12:07:17]: ▸ 0   CoreFoundation                      0x00007fff3bb64ecd __exceptionPreprocess + 256
[12:07:17]: ▸ 1   libobjc.A.dylib                     0x00007fff67c20720 objc_exception_throw + 48
[12:07:17]: ▸ 2   CoreFoundation                      0x00007fff3bb64cff +[NSException raise:format:] + 201
[12:07:17]: ▸ 3   CoreFoundation                      0x00007fff3bad9c11 -[__NSCFString characterAtIndex:] + 102
[12:07:17]: ▸ 4   genstrings                          0x00000001066eafad -[NSString(local) getArgumentsForRange:] + 297
[12:07:17]: ▸ 5   genstrings                          0x00000001066e9def processString + 810
[12:07:17]: ▸ 6   genstrings                          0x00000001066e9914 main + 1684
[12:07:17]: ▸ 7   libdyld.dylib                       0x00007fff68ceeed9 start + 1
[12:07:17]: ▸ )
[12:07:17]: ▸ libc++abi.dylib: terminating with uncaught exception of type NSException
[12:07:17]: ▸ iconv: WooCommerce/Resources/en.lproj/Localizable.strings: No such file or directory
[12:07:17]: $ git add ./WooCommerce*.lproj/Localizable.strings
[12:07:17]: $ git commit -m "Updates strings for localization"
[12:07:17]: ▸ [release/1.5 dc125142] Updates strings for localization
[12:07:17]: ▸ 1 file changed, 1196 deletions(-)
[12:07:17]: ▸ rewrite WooCommerce/Resources/en.lproj/Localizable.strings (100%)
[12:07:17]: $ git push
[12:07:21]: ▸ To github.com:woocommerce/woocommerce-ios.git
[12:07:21]: ▸ 070ca8ba..dc125142  release/1.5 -> release/1.5
[12:07:21]: Done.
```

When checking the release branch against the list in your description, everything looks good except that `en/Localizable.strings` is empty.

As well as the above error, I am seeing the following error just before `bundle exec fastlane code_freeze` finishes:

```
/Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/source/git.rb:203:in `rescue in load_spec_files': https://github.com/wordpress-mobile/release-toolkit (at 0.1.9@a7f414b) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/source/git.rb:200:in `load_spec_files'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/source/path.rb:100:in `local_specs'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/source/git.rb:167:in `specs'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/lazy_specification.rb:76:in `__materialize__'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/spec_set.rb:88:in `block in materialize'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/spec_set.rb:85:in `map!'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/spec_set.rb:85:in `materialize'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/definition.rb:170:in `specs'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/definition.rb:237:in `specs_for'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/definition.rb:226:in `requested_specs'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:108:in `block in definition_method'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:20:in `setup'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler.rb:107:in `setup'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/setup.rb:20:in `<top (required)>'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/james/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

[12:07:26]: RubyGems is not listed as your Gem source
[12:07:26]: You can run `gem sources` to see all your sources
[12:07:26]: Please run the following command to fix this:
[12:07:26]: $ gem sources --add https://rubygems.org
```

**Comment by loremattei** [comment]
Mmm... it doesn't seem a fail related to Fastlane. It looks like genstrings is failing.
I'm going to take a look.

**Comment by loremattei** [comment]
It turned out that develop was broken. I fixed it and merged the update into this branch, so it should be ready for a new run.

**Comment by jtreanor** [comment]
### code_freeze lane

- [x] Tag a fake version 1.5 in your local repository: git checkout develop && git tag 1.4. You don't need push it to origin.
- [x] Checkout this branch and run bundle exec fastlane code_freeze.
- [x] Verify that a new 1.6 branch has been created.
- [x] Verify that the version has been updated in XCConfig, Deliverfile and download_metadata.
- [x] Verify that the English version of Localizable.strings has been updated with the latest strings.
- [x] Verify that the 1.6 milestone has marked with the snowflake icon.
- [x] Verify that the branch protection has been set for the release/1.6 branch.
- [x] Verify that the change log file has been created in your home.

Clean up

- [ ] Remove the branch protection for the release/1.5 branch on GitHub.
- [ ] Delete the release/1.5 branch on GitHub.
- [ ] Remove the snowflake icon from the 1.5 milestone.
- [ ] Remove the 1.5 tag from your local repository.
- [ ] Remove the release/1.5 branch from your local repository.

### new_beta_release lane
This lane updates the version of the app to prepare for a new beta release.
The simpler way to test this lane is to use a forked repository.
- [ ] Fork the repository. For the rest of the steps, use the forked repo.
- [ ] Checkout the `release/1.4` branch and merge this branch into it.
- [ ] Run `bundle exec fastlane new_beta_release`.
- [ ] Verify that the proposed version is right and confirm.
- [ ] Verify that the xcconfig file has been updated correctly and that the new tag has been added.
- [ ] Verify that all the files have been committed.

### finalize_release lane
This lane bumps the version to the final one, downloads the translations and clean the temp tags.
The simpler way to test this lane is to continue to use the forked repository from the step above.
- [ ] Checkout the `release/1.4` branch.
- [ ] Run `bundle exec fastlane finalize_release`.
- [ ] Verify that the app translations and the metadata translations have been downloaded.
- [ ] Verify that the xcconfig file has been updated correctly and that the new tag has been added.
- [ ] Verify that all the files have been committed.
- [ ] Verify that the temporary tags for the beta versions have been deleted.

### build_and_upload_release lane
This lane builds the current branch and uploads the binary to TestFlight and the related dSYM to Crashlytics. 
Since we can't delete test versions from TestFlight, the test can be performed rebuilding the current release/1.4 branch (the original one! not the forked one that has been configured with a new version number!) and verifying that the upload fails because a binary with that version already exists. 
It confirms that the build, signing and login into TestFlight work. The actual upload is handled by the Fastlane itself.
- [ ] Switch to the original repository.
- [ ] Checkout the `release/1.4` branch.
- [ ] Run `bundle exec fastlane build_and_upload_release`.
- [ ] Verify that the binary is built.
- [ ] When prompted, login into TestFlight.
- [ ] Verify that the upload is started and that it fails because of the version validation.

**Pull request merged**
