### PR TITLE
[Design review] Products tab: divider updates

### LINKED ISSUE #12212: [Design review] Products tab: divider updates
Design ref: w3JBReW1UJesCf02sj43kR-fi-1894_11886

- [ ] Add a divider between the table view and the sort/filter bar
- [ ] Remove the divider beneath the navigation bar title (I don't seem to see this in my testing)

Image

### PR DESCRIPTION
**Pull request by bozidarsevo**
Closes: #12212

## Description

- Added function removeShadow() to remove shadow from navigation bar
- Added separator line between toolbar and tableview on products list screen

## Testing instructions

- Open products tab on both iPhone and iPad
- Check that there **IS NOT** divider below "Products" navigation title and check that there **IS** a divider between sorting toolbar and table view

## Screenshots

| Before      | After |
| ----------- | ----------- |
| Simulator Screenshot - iPhone 15 Pro - 2024-03-18 at 10 40 47      | Simulator Screenshot - iPhone 15 Pro - 2024-03-18 at 10 35 12       |

| Before      | After |
| ----------- | ----------- |
| Simulator Screenshot - iPad Pro (11-inch) (4th generation) - 2024-03-18 at 10 42 08      | Simulator Screenshot - iPad Pro (11-inch) (4th generation) - 2024-03-18 at 10 34 20       |

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by iamgabrielma** [comment]
Looking good!  The lines look as expected on loading the view for first time, however, as soon as we navigate through product creation and we go back to the Products view, the divider lines will appear again. Example:

Simulator Screen Recording - iPhone 15 - 2024-03-19 at 10 19 58

I'm not quite sure if this is the cause, but I suspect there's an issue by setting this in `viewDidLoad` (or only in viewDidLoad), and we may want to add it somewhere else in the view's lifecycle? Or perhaps the navigation bar is being override with other properties when we navigate? Since the `removeShadow()` will only be called once when the view controller is first loaded in memory, but not later.

**Comment by bozidarsevo** [comment]
> Example

Good catch! Will check it and fix it!

**Comment by bozidarsevo** [comment]
> > Example
> 
> Good catch! Will check it and fix it!

Updated:
Simulator Screen Recording - iPhone 15 Pro - 2024-03-19 at 10 59 52

**Review by iamgabrielma — APPROVED** [review]
LGTM! 🚢

**Pull request merged**
