### PR TITLE
Blaze: analytics

### PR DESCRIPTION
**Pull request by jaclync**
Part of #9866 

## Why

We're following a similar analytics plan as JP mobile, as documented in pe5sF9-1Ad-p2#metrics. This allows us to see the completion rate of the Blaze flow, and track how many campaigns are created on mobile.

## How

The most nontrivial piece of the logic is how it calculates the current step of the Blaze flow given the URL, since JP mobile did some work on the web side to make it easier for tracking the steps like `step-#`. It's a bit hard to deduct what the step index means though. In any case, I followed [the JPiOS implementation](https://github.com/wordpress-mobile/WordPress-iOS/blob/01df04e28f5eeca28d28935c2999c9a12f32f372/WordPress/Classes/ViewRelated/Blaze/Webview/BlazeWebViewModel.swift#L117) for this with a reference link.

Event | Trigger | Properties
-- | -- | --
blaze_entry_point_displayed | When the Blaze entry point is shown to the user. | source *1
blaze_entry_point_tapped | When the Blaze entry point is tapped by the user. | source *1
blaze_flow_started | When the Blaze webview is first loaded. | source *1
blaze_flow_canceled | When the Blaze webview is dismissed without completing the flow. | source *1,current_step *2
blaze_flow_completed | When the Blaze webview is dismissed after completing the flow, when the step reaches step-5 according to the JPiOS Tracks event `jpios_blaze_flow_completed`. | source *1,current_step *2
blaze_flow_error | When the Blaze webview returns an error. | source *1,current_step *2

## Testing instructions

Prerequisite 1: since the remote feature flag isn't implemented/enabled yet (will do it when we're ready to release to minimize the number of backend Diffs), please enable the remote feature locally. I'd recommend updating `FeatureFlagStore.isRemoteFeatureFlagEnabled` to return `true` in the successful completion block on L57. 

Prerequisite 2: the site is hosted on WPCOM and is public (not staging - you can publicize a store by tapping on the onboarding task). the site also has at least one product that is public and not password protected.

### Menu tab

- Log in to a store as in the prerequisites
- Go to the Menu tab --> the Blaze row should appear. if not, you can go to another tab and then come back to the Menu tab. When the Blaze row appears, an event should be logged `🔵 Tracked blaze_entry_point_displayed, properties: [AnyHashable("source"): "menu", …]`
- Tap on `Blaze` row --> an event should be logged `🔵 Tracked blaze_entry_point_tapped, properties: [AnyHashable("source"): "menu", …]`. When the webview is loaded, an event should be logged `🔵 Tracked blaze_flow_started, properties: [AnyHashable("source"): "menu”, …]`
- Navigate back to the Menu tab —> an event should be logged `🔵 Tracked blaze_flow_canceled, properties: [AnyHashable("current_step"): "products-list", AnyHashable("source"): "menu”, …]`
- Tap on `Blaze` row again, and continue to complete creating a campaign (testing tips pe5sF9-1yI-p2#testing-tips) —> an event should be logged `🔵 Tracked blaze_flow_completed, properties: [AnyHashable("source"): "menu", AnyHashable("current_step"): "step-5”, …]`

### Product menu

- [ ] @jaclync tests the same for the product more menu entry point
- [ ] @jaclync tries testing the error case like going offline to trigger the error event

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by itsmeichigo — APPROVED** [review]
LGTM 🚢

**Comment by itsmeichigo** [comment]
Potential issue for improvement later: I also saw in Xcode a warning about `asyncMap` publishing changes from a background thread when we use it in `HubMenu`. I'm not sure if we should annotate the `Task` inside `asyncMap` with `@MainActor`.

**Comment by jaclync** [comment]
> Potential issue for improvement later: I also saw in Xcode a warning about `asyncMap` publishing changes from a background thread when we use it in `HubMenu`. I'm not sure if we should annotate the `Task` inside `asyncMap` with `@MainActor`.

@itsmeichigo May I ask where you saw the error in Xcode, and the steps that triggered the warning? I tried finding the warning in the Xcode console and issue navigatior and I didn't see warnings other than the known issue https://github.com/woocommerce/woocommerce-ios/issues/8767 from the webview `[Security] This method should not be called on the main thread as it may lead to UI unresponsiveness.` 🤔 

In any case, I marked the eligibility check functions as `@MainActor` just in case https://github.com/woocommerce/woocommerce-ios/pull/9906/commits/4fbfe0cc1b22b322622da40a9b1904c8500e6e86.

**Comment by itsmeichigo** [comment]
> May I ask where you saw the error in Xcode, and the steps that triggered the warning?

I just stayed in the hub menu, and I got the warning:

Screenshot 2023-06-09 at 13 17 59

I noticed then that the Blaze row was not displayed on the menu. This issue may not happen consistently - I suppose it depends on how the device handles threads. We should test on a real device to get more realistic errors.

Your update seems to fix the issue - but if you prefer to call those checks in a background thread, we can also add `.receive(on: DispatchQueue.main)` before assigning a value to `$isSiteEligibleForBlaze` in `HubMenuViewModel`.

**Comment by jaclync** [comment]
> I just stayed in the hub menu, and I got the warning:
> 
> Screenshot 2023-06-09 at 13 17 59
> I noticed then that the Blaze row was not displayed on the menu. This issue may not happen consistently - I suppose it depends on how the device handles threads. We should test on a real device to get more realistic errors.

Thanks for sharing the repro steps @itsmeichigo, I was able to reproduce the warning on a physical device without tapping the Blaze entry point. Updated with the last 2 commits to switch back to the main thread before `asyncMap` and fixed a test case now that it can be called on the main thread after `setupMenuElements`. The full warning message is:

```
Publisher+Concurrency.swift:16 Publishing changes from background threads is not allowed; make sure to publish values from the main thread (via operators like receive(on:)) on model updates.
```

Lemme know if you have other thoughts on the last 2 commits, otherwise I'll merge it later today.

**Comment by itsmeichigo** [comment]
The new updates look good to me! 🚢

**Pull request merged**
