### PR TITLE
Update illustrations for login error screens, reviews tab empty state, and shipping label printing instructions

### PR DESCRIPTION
**Pull request by jaclync**
Part of #3786 

## Why

We're ready to update the illustrations in the app to the latest design from core! This PR focused on the login error screens, reviews tab empty state, and shipping label printing instructions.

## Changes

Updated illustrations in 6 screens:
- Log in - not a WP site
- Log in - not a WP.com account
- Log in - No Jetpack - main screen and info modal
- Reviews tab empty state
- Shipping label printing instructions

I enabled vector representation for a few image assets to support scaling PDF assets without losing image quality.

### Log in - not a WP site

- Log out if needed
- Tap "Enter Your Store Address"
- Enter a site address that is not a WP site (e.g. githug.com)
- Tap "Continue" --> the error screen illustration should look as expected

### Log in - not a WP.com account

- Log out if needed
- Tap "Continue with WordPress.com"
- Enter an email that isn't associated with a WP.com account
- Tap "Continue" --> the error screen illustration should look as expected

### Log in - No Jetpack

- Log out if needed
- Tap "Enter Your Store Address"
- Enter a site address that is not connected to Jetpack (e.g. `edgetest.mystagingwebsite.com` - it's a Pressable site with Jetpack installed but not active and not connected)
- Tap "Continue" --> the error screen should look as expected
- Tap "What is Jetpack?" --> the modal illustration should look as expected

### Reviews tab empty state

- For easier testing, you can update the expected siteID in the following line to a different value (e.g. 123):
https://github.com/woocommerce/woocommerce-ios/blob/eeee79ebafb171a64eeae3a9a78afa38b0403efc/WooCommerce/Classes/ViewRelated/Reviews/DefaultReviewsDataSource.swift#L126
- Log in if needed
- Go to the reviews tab --> the empty state illustration should look as expected

### Shipping label printing instructions

Prerequisites: the site has [WooCommerce Shipping & Tax plugin](https://docs.woocommerce.com/document/woocommerce-shipping-and-tax/) and there is an order with at least one non-refunded shipping label.

You can set up your store to use a test credit card with instructions in p91TBi-3xD-p2.

- Go to the orders tab
- Tap on an order with at least one non-refunded shipping label
- After syncing, tap "Don't know how to print from your phone?" info row in a package card --> the state illustration should look as expected on the printing instructions screen

## Example screenshots

Notes for design reviewers: for the reviews tab empty state, only the illustration is updated in this PR while the design includes changes on the CTA and message. I left a question about the CTA, and it can be updated as a separate subtask for #3786

### Dark mode

\ | Log in - not a WP site | Log in - not a WP.com account | Log in - No Jetpack | Log in - what is Jetpack | Reviews tab empty state | Shipping label printing instructions
-- | -- | -- | -- | -- | -- | --
before | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 35 58 | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 36 07 | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 36 26 | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 36 29 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 14 16 24 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 14 14 45
after | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 50 44 | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 50 58 | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 52 03 | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 52 07 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 14 59 37 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 14 59 42

### Light mode

\ | Log in - not a WP site | Log in - not a WP.com account | Log in - No Jetpack | Log in - what is Jetpack | Reviews tab empty state | Shipping label printing instructions
-- | -- | -- | -- | -- | -- | --
before | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 25 56 | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 26 46 | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 34 06 | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 34 10  | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 14 16 31 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 14 14 18
after | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 50 25 | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 51 14 | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 51 46 | Simulator Screen Shot - iPhone 8 Plus - 2021-03-10 at 14 51 49 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 14 59 08 | Simulator Screen Shot - iPhone 11 - 2021-03-10 at 14 59 25

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Awesome work @jaclync

**Review by rachelmcr — APPROVED** [review]
Looks great! 🚀  

The only thing I noticed while testing the login error screen updates is that this screen isn't slated for an update, but it's using an older illustration:



Here's how to get to it:

- Log out if needed
- Tap "Enter Your Store Address"
- Enter the site address for a WooCommerce store
- Enter an email that **is** associated with a WordPress.com account but **not** associated with this site
- Enter your password to finish logging in, and notice the error screen that appears

Should this be added to the list of screens to update as part of https://github.com/woocommerce/woocommerce-ios/issues/3786?

**Comment by rachelmcr** [comment]
I asked about the illustration above (internal ref: p91TBi-40j-p2#comment-3703) and will go ahead and merge these changes.

**Comment by Garance91540** [comment]
Hi @rachelmcr !Thanks for catching this. I tagged you on Figma on the illustrations we should be using here

**Pull request merged**
