### PR TITLE
Dark Mode: update colors for login flow

### PR DESCRIPTION
**Pull request by jaclync**
Login flow for #1638 

- [x] ⚠️Update `Podfile` after https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/173 is merged and released ⚠️ 

## Changes

- Most of the changes are in the `WordPressAuthenticator` PR: TODO after creating the PR
- Added 2 new image assets for login flow and passed these two images in `WordPressAuthenticatorDisplayImages` to initialize `WordPressAuthenticator`:
  - `loginMagicLinkImage`
  - `loginSiteAddressInfoImage`
- Updated colors for the login with site address info alert in `AppDelegate`

## Testing

- Log out of the app
- Tap "Log in with Jetpack"
- Tap "Enter the address..."
- Tap "Need help finding your site address?" --> the alert should look as expected in Light and Dark modes (note that some colors are cached when switching Light/Dark mode on the same screen during testing. Because this alert UI component is in another shared library `WordPressUI` and most of the users probably wouldn't switch Light/Dark mode on this particular screen, it might make sense to skip this edge case for now)
- Tap "OK" to dismiss the alert
- Enter a valid site address and tap "Next" --> the icon of the site address should have the expected color
- Navigate back to the home screen
- Tap "Log in with Jetpack"
- Enter a non-a8c email address and tap "Next"
- Tap "Send Link" --> the image and the "Enter your password instead." button should have the expected colors

## Example screenshots

Note for @kyleaparker: for the site address help alert Light mode, the lightest background color behind the header image I could find in our color palette is system gray6 but it still looks darker than the design. Do you know if there is a closer color?

Screen | Dark | Light
-- | -- | --
Site address help alert | Simulator Screen Shot - iPhone 11 - 2019-12-23 at 17 01 34 | Simulator Screen Shot - iPhone 11 - 2019-12-23 at 17 01 44
After entering site address | Simulator Screen Shot - iPhone 11 - 2019-12-23 at 17 01 23 | Simulator Screen Shot - iPhone 11 - 2019-12-23 at 17 01 14
Magic link | Simulator Screen Shot - iPhone 11 - 2019-12-23 at 17 00 10 | Simulator Screen Shot - iPhone 11 - 2019-12-23 at 17 00 33

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jaclync** [comment]
@kyleaparker as @mindgraffiti pointed out in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/173#pullrequestreview-337758076, the site header text in the following screenshots is a bit dark in Dark mode. Right now it's set to WP `darkGrey` (R:46 G:68 B:83) and not configurable. Do you know if there are any colors out of [these semantic/color options](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Authentication/AuthenticationManager.swift#L26-L47) configured for Woo that we can use for the site info header text? Once we have some color candidates, I'll check if it looks good on WPiOS

screen | Dark | Light
-- | -- | --
After entering site address | Simulator Screen Shot - iPhone 11 - 2019-12-23 at 17 01 23 | Simulator Screen Shot - iPhone 11 - 2019-12-23 at 17 01 14

**Comment by kyleaparker** [comment]
>Do you know if there are any colors out of these semantic/color options configured for Woo that we can use for the site info header text? Once we have some color candidates, I'll check if it looks good on WPiOS

Do any of these just use the plain text colour? Potentially primaryTitleColor but I'm not sure exactly what colour that is.

**Comment by jaclync** [comment]
@kyleaparker what do you think of these colors? the prompt is using `instructionColor` and the site address is using `subheadlineColor` (both are `secondaryLabel` color)

screen | Dark | Light
-- | -- | --
After entering site address | Simulator Screen Shot - iPhone 11 - 2020-01-08 at 16 10 29 | Simulator Screen Shot - iPhone 11 - 2020-01-08 at 16 10 15

**Comment by kyleaparker** [comment]
>@kyleaparker what do you think of these colors? the prompt is using instructionColor and the site address is using subheadlineColor (both are secondaryLabel color)

That works 👍

**Comment by jaclync** [comment]
Update: I reverted the changes to the colors for the site info after entering the site address re https://github.com/woocommerce/woocommerce-ios/pull/1655#issuecomment-571940015 (thanks for the review Kylea) because I haven't got to gather design feedback from WPiOS. Merging this PR soon after CI, so that we can still get the rest of the login color updates to release 3.4

**Pull request merged**
