### PR TITLE
UL&S: Remove mention to Jetpack and link to Jetpack's configuration instructions

### LINKED ISSUE #3128: [UL&S] Login prologue. Change order of login options, present "Ever Your Store Address" as the first option
Attempt to change the ordering of the two options in the Login Prologue:

### PR DESCRIPTION
**Pull request by ctarda**
Closes #3128 

⚠️ Please notice this PR is not against `develop`, but against the feature branch for UL&S 🙇 

# Changes

| Before | After |
| ---- | ---- |
|  |  |

* The area where Jetpack was mentioned is removed. 
* Some code that dealt with dynamic type, and that is not necessary anymore, is also removed.

The design (notice the link to Jetpack is missing):

The order of the buttons at the bottom is a separate ticket: #3128 

# Testing
* Checkout the branch, build and run.
* Log out if necessary.
* Attempt to log in again. Notice if the reference to Jetpack is gone from the login prologue
* Change font sizes. The label "Manage orders..." should change its font size.

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ctarda** [comment]
@Garance91540  As a side note, I have logged #3144 for changing the background color of the area where the bottom buttons seat.

**Review by Garance91540 — COMMENTED** [review]
Hi Cesar, Great start!

As you already mentioned:

- the bottom buttons background needs updating
- the buttons order should be switch and "Enter your store address" be primary

Regarding the Jetpack mention, we don't currently display it on Android, and I think we should try without it on iOS too. The rationale is that we know the Jetpack connexion is the biggest friction point for users when logging in. But we want the most people starting this flow, and when using the "enter your store address" pathway, they might never know they needed Jetpack to connect. If they need Jetpack, they'll be helped to connect it later on. 

Lastly, the font of the text "Manage orders, etc" should be SF Pro text 16px Semibold, color Woo Purple 60

**Review by pmusolino — COMMENTED** [review]
Thank you @ctarda for working on this!

The mention of Jetpack is now removed as expected. 💯 

I've just a question: is it expected that the background of the buttons is grey and that the background color of the other screens (like the screen where you add your email) is white?

| Login             |  Continue with WordPress.com |
:-------------------------:|:-------------------------:
Simulator Screen Shot - iPhone 11 Pro - 2020-11-12 at 15 27 29 | Simulator Screen Shot - iPhone 11 Pro - 2020-11-12 at 15 28 47

**Comment by ctarda** [comment]
Good catch @pmusolino @Garance91540  

I should have mentioned the issues with the background of the buttons in the PR description as well. Due to a limitation in WPauthenticator we are deferring that for now: #3144 

Also, the ordering of the buttons is deferred for now as well: #3128 

I'll push an update with the corrections to the font size and color of the "Manage orders" label

**Comment by ctarda** [comment]
I just pushed an update to the styling of the "Manage orders... " label:

**Review by pmusolino — APPROVED** [review]
LGTM :shipit: thanks @ctarda! :D

**Review by Garance91540 — APPROVED** [review]
👏👏👏

**Pull request merged**
