### PR TITLE
[Blaze] Storage: Entity to store brief Blaze campaign info

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Part of: #12120 

## Description

Adds a new entity to the storage layer to store brief blaze campaign list info received from v1.1. endpoint.

## Testing instructions
- Install a build from https://github.com/woocommerce/woocommerce-ios/pull/12121 and replace that with a build from this branch.
- The app should launch and work without any core data migration crashes. 

## Screenshots
NA

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/188">17.6</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by selanthiraiyan** [comment]
@hafizrahman 👋 

I am going to rename `BriefBlazeCampaignInfo` into `BlazeCampaignListItem` based on this suggestion from @itsmeichigo here. https://github.com/woocommerce/woocommerce-ios/pull/12121#issuecomment-1968314370

Please pause reviewing if you are already on it. Sorry for the inconvenience. 🙏

**Comment by selanthiraiyan** [comment]
@hafizrahman I have finished renaming in commits https://github.com/woocommerce/woocommerce-ios/pull/12124/commits/fa9a885901d861737e5a6b9d0d19d6e16ce8e6aa and https://github.com/woocommerce/woocommerce-ios/pull/12124/commits/785c851d8cf13cf46230e9fccc88a986aed60fa3. The PR is ready for review now. Thank you!

**Review by hafizrahman — APPROVED** [review]
This works as expected. The branch mentioned in the testing instruction is already deleted, so I'm testing using `trunk` first instead and then with this branch. It works correctly.

**Comment by selanthiraiyan** [comment]
> The branch mentioned in the testing instruction is already deleted, so I'm testing using trunk first instead and then with this branch. It works correctly.

Thank you! 🙇

**Pull request merged**
