### PR TITLE
Blaze: Add new budget fields for campaign list item

### PR DESCRIPTION
**Pull request by itsmeichigo**
Part of #12301 

## Description

This PR updates the `BlazeCampaignListItem` model in the Networking layer to include the new budget fields following a new API update [peeHDf-2fw-p2#comment-1934].

## Testing instructions

Just CI passing is sufficient.

## Screenshots

N/A

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by hafizrahman — COMMENTED** [review]
This looks good to me aside from unit tests that seem to need updating 👍🏼

**Comment by itsmeichigo** [comment]
Oops I updated the tests, please take another look 😅

**Review by hafizrahman — APPROVED** [review]
Good to go now 👍🏼

**Pull request merged**
