### PR TITLE
Merge release 20.2.1 into 20.3

### PR DESCRIPTION
**Pull request by pmusolino**
Merge release changes from 20.2.1 into release 20.3

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR has the <code>Releases</code> label: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by itsmeichigo — APPROVED** [review]

**Review by bozidarsevo — APPROVED** [review]

**Comment by AliSoftware** [comment]
@pmusolino 🚨  The fact that you resolved the conflict by [merging 'release/20.3' into release/20.2.1](https://github.com/woocommerce/woocommerce-ios/pull/13931/commits/37db6992b4de28367f0f70788449a9510f58daeb) here is a problem, since by doing that it means that you included commits from `release/20.3` into `20.2.1`, while there might be code from `20.3` that is not supposed to be shipped in `20.2.1`

image

To avoid this issue, we usually create an intermediate branch from `release/20.2.1` and create a PR to backmerge that intermediate branch into `release/20.3` instead (see [a past backmerge PR for inspiration and illustration with ASCII art](https://github.com/woocommerce/woocommerce-ios/pull/13869#issue-2509870033)); that way, if you need to solve conflicts, you can merge `release/20.3` into the intermediate branch to fix the conflicting files, without risking to accidentally include commits from `release/20.3` into the `release/20.2.1` branch.

Besides, the fact that you didn't create an intermediate branch had the side effect that GitHub deleted the `release/20.2.1` branch once this PR was merged, because the `release/20.2.1` branch was not protected anymore (and our GitHub settings are set to delete unprotected branches once their PR is merged)
image

This will make the rest of the release tasks fail given that the `release/20.2.1` doesn't exist anymore so it will not be able to push new commits to it to update app store metadata etc.

---

To solve this mess, the easiest way is to restore the `release/20.2.1` branch to the commit that was just BEFORE commit 37db699 (the one where you merged `release/20.3` into `release/20.2.1`)—in other words point it to commit 6728f9e6e3da4759ee4373af24a6c1a8991baa0a— and redo a new backmerge PR, but this time properly using an intermediate branch to avoid all those issues.

**Comment by pmusolino** [comment]
Ouch @AliSoftware ! That commit was generated automatically by Github (you can notice it because of the `Verified` tag) while managing the conflict [on this file](https://github.com/woocommerce/woocommerce-ios/blob/37db6992b4de28367f0f70788449a9510f58daeb/config/Version.Public.xcconfig), so it seems that instead of managing only the conflict, back merged `release/20.3` on `release/20.2.1` and I don't understand how this could have happened. 🤔 

I'll try to follow the approach you suggested, and let's see 🤞

**Comment by AliSoftware** [comment]
> That commit was generated automatically by Github (you can notice it because of the Verified tag) while managing the conflict [on this file](https://github.com/woocommerce/woocommerce-ios/blob/37db6992b4de28367f0f70788449a9510f58daeb/config/Version.Public.xcconfig), so it seems that instead of managing only the conflict, back merged release/20.3 on release/20.2.1 and I don't understand how this could have happened. 🤔

Yep, that's how GitHub handles things when you use the web UI to fix the conflict: it tries to merge the target branch of the PR into the head branch of the PR, let you solve conflicts (that arose from that up-merge) via the UI, and commit the result. And to be honest, that's also usually the same process that one would use to manually resolve a conflict even outside the GitHub web UI (e.g. via `git` terminal commands on your Mac or using a GUI app), so that makes sense that the web UI works that way.

It's just that in our case, the backmerge PRs are not meant as "final merges" (as in "I'm done with this feature branch and it's ready to be integrated, so I want to merge it to `trunk` and delete the feature branch once it's merged as I won't need it anymore")—for which it wouldn't really matter if you merged `trunk` into your feature branch to fix those conflicts because you'd delete the feature branch right away anyway—but instead those backmerge PRs are more to "keep the `release/20.2.1` and `release/20.3` branches in sync" (the idea here being similar to as if we cherry-picked all the fixes made during the hotfix from the `release/20.2.1` branch to apply the same fixes to `release/20.3`, except it's usually simpler to just merge the branches than cherry-pick each individual commit from one branch to the other one by one), but all while our work with the `release/20.2.1` branch is not done yet and we're not ready to delete the `release/20.2.1` branch yet because we might need to push more commits to it later.
_(Same applies to backmerge PRs we do during a regular sprint from `release/x.y` to `trunk` after we do a new beta for example, where the aim of those is to ensure the bugfixes added to `release/x.y` will also be applied to `trunk`, but while we still want the `release/x.y` branch to stay around during the rest of the sprint and might do more backmerge PRs in the duration of the sprint if we have more bugfixes and create more betas later in the week…)_

**Comment by AliSoftware** [comment]
@pmusolino Now that you restored the `release/20.2.1` branch to the commit before the accidental merge, I've recreated the proper backmerge PR via intermediate branch in https://github.com/woocommerce/woocommerce-ios/pull/13945.

**Comment by AliSoftware** [comment]
Just to close the loop:

We ended up just restoring the `release/20.2.1` branch and force-pushing it back to point to 6728f9e6e3da4759ee4373af24a6c1a8991baa0a—so that the commit that was used for conflict resolution (the `Merge branch 'release/20.3' into release/20.2.1` one, 37db6992b4de28367f0f70788449a9510f58daeb) would not be part of the `release/20.2.1` branch anymore (but only be part of `release/20.3`), thus solving the mess.

And after that, we didn't need to redo any other backmerge PR via intermediate branch since 37db6992b4de28367f0f70788449a9510f58daeb + the merge commit 3f8096f031f6d8a4ae4510ae5aeeb9d339a8bee7 from this current PR—that included the fix from #13945—were already part of the `release/20.3` branch[^1]

[^1]: In fact [when we tried to create a new backmerge PR via intermediate branch to merge it to `release/20.3`, GitHub errored saying there was nothing new to merge](https://github.com/woocommerce/woocommerce-ios/pull/13945#issuecomment-2346208731))

**Pull request merged**
