### PR TITLE
Fix a memory issue where `IssueRefundViewController` and `RefundConfirmationViewController` are not deallocated after the refund flow

### PR DESCRIPTION
**Pull request by jaclync**
Ref  p91TBi-8fj-p2

### Description

While fixing a similar memory issue for in-person payments/refunds flow, I noticed the `IssueRefundViewController` and `RefundConfirmationViewController` are not deallocated after the refund flow while the coordinator and other classes are gone. After some debugging, it looks like the view controllers are retained by something related to `NotificationCenter` if they are used directly in the second level of callback. I'm still looking for an explanation as in the reference p2.

Screen Shot 2022-04-18 at 3 11 55 PM
Screen Shot 2022-04-18 at 3 20 15 PM

### Testing instructions

- Go to the orders tab
- Tap on a refundable order
- Tap "Issue Refund"
- Select some items or fees to refund, and tap "Next"
- On the next confirmation screen, drag down to dismiss the refund flow and discard any changes --> in the memory debugger, there should not be any refund objects specific to the flow

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jaclync** [comment]
Ready for review now even though we don't have new insights on p91TBi-8fj-p2 🙂

**Comment by toupper** [comment]
Nice fix @jaclync! Seems like there was a retain cycle when setting the closures indeed.

#### Tested

Go to the orders tab
Tap on a refundable order
Tap "Issue Refund"
Select some items or fees to refund, and tap "Next"
On the next confirmation screen, drag down to dismiss the refund flow and discard any changes --> in the memory debugger, there should not be any refund objects specific to the flow ✅

**Review by toupper — APPROVED** [review]

**Comment by koke** [comment]
Noting here that I left a comment in the original P2. I think this solution works, but adding the currently leaked objects to the closures' capture lists as `weak`/`unowned` might be a simpler solution

**Comment by jaclync** [comment]
Thank you for the p2 suggestion @koke! I updated the PR with `weak` just in case the lifetime might not match after any potential future changes.

I tested with both in-person refunds and remote refunds, and the refund flow works as before without any lingering refund classes in memory after the refund ✅ 

The CI currently failed on the Installable Build step, it's a known issue in Platform9 p1652160006832509-slack-CC7L49W13

**Review by koke — APPROVED** [review]

**Pull request merged**
