### PR TITLE
[HACK week] Networking: Process network response in background thread

### LINKED ISSUE #11255: Networking: Mapping response in main thread
Internal - peaMlT-gA-p2

### Problem

The networking layer `Mapper`s parses a networking response into models from the main thread.

When a large network response is mapped from the main thread, the main thread gets blocked. 

A blocked main thread results in app hangs and the watchdog can terminate the app if the main thread is blocked for a significant amount of time.

### Possible fix

Do the mapping from a background thread and fire the completion handlers from the main thread.

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Closes: #11255

### What? 

The networking layer Mappers parses a networking response into models from the main thread.

### Why?

When a large network response is mapped from the main thread, the main thread gets blocked.

A blocked main thread results in app hangs and the watchdog can terminate the app if the main thread is blocked for a significant amount of time.

### How? 

Process the network response from the background thread by moving the code inside a `Task`.

## Testing instructions

Smoke test the app using both WPCOM and wporg login and ensure that it works as before.

## Screenshots
NA

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by itsmeichigo** [comment]
> Process the network response from the background thread by moving the code inside a Task.

I think there's a misunderstanding about the use of `Task` here. According to the documentation:

> When you create an instance of Task, you provide a closure that contains the work for that task to perform.

The code added to the closure isn't executed in the background thread. It continues to run on the same thread of the current context. Only when you have a suspension point (marked with `await`) does the system decide which thread to run the code.

If you want to break out of the current context, you can use `Task.detached` - but it doesn't guarantee that your code will run on a background thread. To explicitly state this, I'd suggest using the classic `DispatchQueue`:

```Swift
DispatchQueue.global().async {
    do {
        let validator = request.responseDataValidator()
        try validator.validate(data: data)
        let parsed = try mapper.map(response: data)
        DispatchQueue.main.async {
            completion(.success(parsed))
        }
    } catch {
        self.handleResponseError(error: error, for: request)
        self.handleDecodingError(error: error, for: request, entityName: "\(M.Output.self)")
        DDLogError("<> Mapping Error: \(error)")
        DispatchQueue.main.async {
            completion(.failure(error))
        }
    }
}
```

**Comment by selanthiraiyan** [comment]
Thanks for the review, @itsmeichigo!

Kindly allow me to share my understanding.

1. By moving the code inside a `Task`, we are allowing the system to decide which thread to run the code from.
2. By not specifying `@MainActor` we also make it clear that this doesn't have to run in the main thread.

This way, we stop thinking in terms of threads, and we let the concurrency system choose the appropriate thread. 

---


> The code added to the closure isn't executed in the background thread. It continues to run on the same thread of the current context. Only when you have a suspension point (marked with await) does the system decide which thread to run the code.

My understanding is that a task runs on an automatically managed background dthread. The system will automatically choose the thread and priority. We can also specify a priority using `Task(priority: .high) {` if needed. [Source](https://www.avanderlee.com/concurrency/tasks/#the-thread-used-for-execution)


I kept breakpoints in the mapper code to see the threads and verified that the mapper code is not executed in the main-thread. (Compared this branch with code from trunk)

| trunk | this branch |
|--------|--------|
| trunk- | task-branch |

--- 


I would love to know your thoughts. Thank you!

**Comment by itsmeichigo** [comment]
Thanks for the explanations, Sharma!

> This way, we stop thinking in terms of threads, and we let the concurrency system choose the appropriate thread.

I thought we wanted to run the decoding on the background thread specifically. That's why I suggested specifying the threads for this fix. Is there any chance the system chooses the main thread for the task?

**Comment by selanthiraiyan** [comment]
> Is there any chance the system chooses the main thread for the task?

Great question. I am still trying to figure out the answer to this. I think it is possible, and it could happen when other threads are busy and creating a new thread isn't efficient (to avoid thread explosion). As far as I know, we have no control over this apart from specifying a Task priority. 

> I thought we wanted to run the decoding on the background thread specifically. That's why I suggested specifying the threads for this fix.

Good point. Now when I think about it more, my intention is to move it off the main thread to prevent the mapping process from blocking the main thread.  Considering that using a `Task` achieves the desired effect we can avoid using a specific queue. What do you think?

**Review by itsmeichigo — APPROVED** [review]
From the discussion above, I suppose we want to avoid GCD entirely and use `Task` in all cases. I found an [article](https://www.avanderlee.com/concurrency/tasks/) stating this:

> By default, a task executes on an automatically managed background thread. 

Unfortunately, the documentation doesn't explicitly state this, so I'm still unsure about this use when the goal was to move the heavy computation tasks off the main thread. 

But as you pointed out, we can delegate the thread choosing to the system, so I'm approving this PR. Let's observe the mapping issue and see if this fixes it.

**Comment by selanthiraiyan** [comment]
Thanks for the review, Huong! 

> But as you pointed out, we can delegate the thread choosing to the system, so I'm approving this PR. Let's observe the mapping issue and see if this fixes it.

We can keep an eye on the app hangs in Xcode Organizer for this 16.6 version. peaMlT-gA-p2#xcode-organizeri-decided-to-look-into-xcode-organizer-to-find-more-info

If those App Hangs related to decoding stop occurring in 16.6, we can be sure that this fix works as expected.

**Pull request merged**
