### PR TITLE
Simple Payments: Release Feature

### LINKED ISSUE #5353: Simple Payments: Release Feature
### Tasks
- [x] Re-organize feature to swap prototype for the full implementation
- [x] Delete feature flag
- [x] Update release notes

### PR DESCRIPTION
**Pull request by Ecarrion**
closes #5353 

# Why

In order to release the Simple Payments feature for release 8.2(to be frozen by the end of this week) this PR:

- Removes the `.simplePaymentPrototype` feature flag: Only the full version will be available after 8.2
- Removes the Simple Payments beta feature switch: The feature is complete and no longer considered experimental.
- Updates release notes.

# Testing

- Simulate the complete Simple Payments flow.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by shiki — APPROVED** [review]
Great work, @Ecarrion! 

One thing that I think we should fix as soon as possible, preferably within the sprint is the label for the tax information. It gets cut off. 



But then, when I start another flow, it's fixed. 🤷 



Really weird!

Also that thing about the Next button becoming untappable happened 3 times during my testing. 😐 Still no clear reproduction steps. 😞

**Comment by Ecarrion** [comment]
@shiki could you share the specific device you were testing on, I haven't found a way to replicate that :-/

**Comment by shiki** [comment]
Sorry. iPhone Xs, 14.8.

**Comment by Ecarrion** [comment]
Thanks for the review @shiki

I haven't been able to reproduce either of the issues but I have added [a change](https://github.com/woocommerce/woocommerce-ios/pull/5635/commits/b107ee20d112c0bba0ee7c3a5073035e5739f604) to force that label to grow as needed.

Regarding the unresponsive button, I keep testing and looking for ways to reproduce it :-(

**Pull request merged**
