### PR TITLE
Shipping Labels: display carrier and rates information, and allow the selection

### PR DESCRIPTION
**Pull request by pmusolino**
Part of #4085 

## Description
In this PR I continue the work started [here](https://github.com/woocommerce/woocommerce-ios/pull/4229) on the UI of Carriers and Rates.
Now:
- we will display the correct information about every carrier;
- we will display the information about extra rates of every carrier (signature or adult signature, if available);
- we will allow selecting a rate, and to add the request of a signature or adult signature;

**The unit tests of the view models are part of another PR https://github.com/woocommerce/woocommerce-ios/pull/4275**

## Changes
- I updated the `insurance` property under the `ShippingLabelCarrierRate`, since it’s a `Double`.
- Implemented `ShippingLabelCarrierRowViewModel` as a separate file.
- `ShippingLabelCarrierRow` now is able to handle the selected/unselected state, and also to display the extra info about signature and adult signature.
- `ShippingLabelCarriersViewModel` now handles the selected rates and has a new method for generating the rows.

## Testing
1. Launch the app in debug mode (because of the feature flag).
2. Open an order detail that is eligible for the shipping label.
3. Press the button "Create Shipping Label".
4. Press the button "Continue" in Create Shipping Label form, under the **Ship From** cell. Confirm the address.
5. Press the button "Continue" in Create Shipping Label form, under the **Ship To** cell. Confirm the address.
6. Press the button "Continue" in Create Shipping Label form, under the **Package Details** cell.
7. You should see the screen that shows the Package Details screen and all the items that will be shipped.
8. Press the "Package selected" row. 
9. Select a package, then press "Done".
10. Add a Total package weight, press "Done".
11. The "Shipping Carrier and Rates" cell should be enabled now. Press it.
12. You should see the new screen "Carrier and Rates". It should display first the ghost cells, then the data fetched from the API.
13. Make sure the info of every carrier is shown in the correct way, and that you are able to select a carrier and a signature/adult signature. (You will not be able to confirm your final choice, it will be implemented in the next PR).

## Screenshot

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ealeksandrov — APPROVED** [review]
It works and code looks good :shipit:

One note - there are 2 autolayout warnings, on Shipping Label Form, appearing when "Rates" cell is activated. I think that's for "Continue" button with spinner inside that cell.

```
2021-05-26 20:28:50.159102+0300 WooCommerce[20426:450414] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600002e14190 h=--& v=--& UITableViewCellContentView:0x7fdf21ddfe70.height == 66   (active)>",
    "<NSLayoutConstraint:0x600002e11cc0 UILabel:0x7fdf21de1c00.height == 24   (active)>",
    "<NSLayoutConstraint:0x600002e11ea0 V:|-(0)-[UILabel:0x7fdf21de1fe0]   (active, names: '|':UIView:0x7fdf21de1e70 )>",
    "<NSLayoutConstraint:0x600002e11f40 V:[UILabel:0x7fdf21de1fe0]-(0)-|   (active, names: '|':UIView:0x7fdf21de1e70 )>",
    "<NSLayoutConstraint:0x600002e12080 V:[UILabel:0x7fdf21de1c00]-(4)-[UIStackView:0x7fdf21ddea30]   (active)>",
    "<NSLayoutConstraint:0x600002e12120 V:[UIStackView:0x7fdf21ddea30]-(0)-|   (active, names: '|':UIView:0x7fdf21de30e0 )>",
    "<NSLayoutConstraint:0x600002e12210 V:|-(0)-[UILabel:0x7fdf21de1c00]   (active, names: '|':UIView:0x7fdf21de30e0 )>",
    "<NSLayoutConstraint:0x600002e125d0 V:[UIStackView:0x7fdf21de0000]-(10)-|   (active, names: '|':UITableViewCellContentView:0x7fdf21ddfe70 )>",
    "<NSLayoutConstraint:0x600002e12620 V:|-(10)-[UIStackView:0x7fdf21de0000]   (active, names: '|':UITableViewCellContentView:0x7fdf21ddfe70 )>",
    "<NSLayoutConstraint:0x600002e13110 UILayoutGuide:0x600003478380'UIViewLayoutMarginsGuide'.top == UIButtonLabel:0x7fdf21de4c50.top   (active)>",
    "<NSLayoutConstraint:0x600002e13160 UILayoutGuide:0x600003478380'UIViewLayoutMarginsGuide'.bottom == UIButtonLabel:0x7fdf21de4c50.bottom   (active)>",
    "<NSLayoutConstraint:0x600002e13570 'UISV-canvas-connection' UIStackView:0x7fdf21ddea30.top == UIView:0x7fdf21de1e70.top   (active)>",
    "<NSLayoutConstraint:0x600002def4d0 'UISV-canvas-connection' V:[WooCommerce.ButtonActivityIndicator:0x7fdf21de2250'Continue']-(0)-|   (active, names: '|':UIStackView:0x7fdf21ddea30 )>",
    "<NSLayoutConstraint:0x600002e13980 'UISV-canvas-connection' UIStackView:0x7fdf21de0000.top == UIView:0x7fdf21de30e0.top   (active)>",
    "<NSLayoutConstraint:0x600002e139d0 'UISV-canvas-connection' V:[UIView:0x7fdf21de30e0]-(0)-|   (active, names: '|':UIStackView:0x7fdf21de0000 )>",
    "<NSLayoutConstraint:0x600002defb10 'UISV-spacing' V:[UIView:0x7fdf21de1e70]-(8)-[WooCommerce.ButtonActivityIndicator:0x7fdf21de2250'Continue']   (active)>",
    "<NSLayoutConstraint:0x600002e12d50 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x600003478380'UIViewLayoutMarginsGuide']-(8)-|   (active, names: '|':WooCommerce.ButtonActivityIndicator:0x7fdf21de2250'Continue' )>",
    "<NSLayoutConstraint:0x600002e12cb0 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x600003478380'UIViewLayoutMarginsGuide']   (active, names: '|':WooCommerce.ButtonActivityIndicator:0x7fdf21de2250'Continue' )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002e13160 UILayoutGuide:0x600003478380'UIViewLayoutMarginsGuide'.bottom == UIButtonLabel:0x7fdf21de4c50.bottom   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-05-26 20:28:50.164729+0300 WooCommerce[20426:450414] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600002e14190 h=--& v=--& UITableViewCellContentView:0x7fdf21ddfe70.height == 66   (active)>",
    "<NSLayoutConstraint:0x600002e11cc0 UILabel:0x7fdf21de1c00.height == 24   (active)>",
    "<NSLayoutConstraint:0x600002e11ea0 V:|-(0)-[UILabel:0x7fdf21de1fe0]   (active, names: '|':UIView:0x7fdf21de1e70 )>",
    "<NSLayoutConstraint:0x600002e11f40 V:[UILabel:0x7fdf21de1fe0]-(0)-|   (active, names: '|':UIView:0x7fdf21de1e70 )>",
    "<NSLayoutConstraint:0x600002e12080 V:[UILabel:0x7fdf21de1c00]-(4)-[UIStackView:0x7fdf21ddea30]   (active)>",
    "<NSLayoutConstraint:0x600002e12120 V:[UIStackView:0x7fdf21ddea30]-(0)-|   (active, names: '|':UIView:0x7fdf21de30e0 )>",
    "<NSLayoutConstraint:0x600002e12210 V:|-(0)-[UILabel:0x7fdf21de1c00]   (active, names: '|':UIView:0x7fdf21de30e0 )>",
    "<NSLayoutConstraint:0x600002e125d0 V:[UIStackView:0x7fdf21de0000]-(10)-|   (active, names: '|':UITableViewCellContentView:0x7fdf21ddfe70 )>",
    "<NSLayoutConstraint:0x600002e12620 V:|-(10)-[UIStackView:0x7fdf21de0000]   (active, names: '|':UITableViewCellContentView:0x7fdf21ddfe70 )>",
    "<NSLayoutConstraint:0x600002e13110 UILayoutGuide:0x600003478380'UIViewLayoutMarginsGuide'.top == UIButtonLabel:0x7fdf21de4c50.top   (active)>",
    "<NSLayoutConstraint:0x600002e13390 UIButtonLabel:0x7fdf21de4c50.centerY == WooCommerce.ButtonActivityIndicator:0x7fdf21de2250'Continue'.centerY   (active)>",
    "<NSLayoutConstraint:0x600002e13570 'UISV-canvas-connection' UIStackView:0x7fdf21ddea30.top == UIView:0x7fdf21de1e70.top   (active)>",
    "<NSLayoutConstraint:0x600002def4d0 'UISV-canvas-connection' V:[WooCommerce.ButtonActivityIndicator:0x7fdf21de2250'Continue']-(0)-|   (active, names: '|':UIStackView:0x7fdf21ddea30 )>",
    "<NSLayoutConstraint:0x600002e13980 'UISV-canvas-connection' UIStackView:0x7fdf21de0000.top == UIView:0x7fdf21de30e0.top   (active)>",
    "<NSLayoutConstraint:0x600002e139d0 'UISV-canvas-connection' V:[UIView:0x7fdf21de30e0]-(0)-|   (active, names: '|':UIStackView:0x7fdf21de0000 )>",
    "<NSLayoutConstraint:0x600002defb10 'UISV-spacing' V:[UIView:0x7fdf21de1e70]-(8)-[WooCommerce.ButtonActivityIndicator:0x7fdf21de2250'Continue']   (active)>",
    "<NSLayoutConstraint:0x600002e12cb0 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x600003478380'UIViewLayoutMarginsGuide']   (active, names: '|':WooCommerce.ButtonActivityIndicator:0x7fdf21de2250'Continue' )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002e13390 UIButtonLabel:0x7fdf21de4c50.centerY == WooCommerce.ButtonActivityIndicator:0x7fdf21de2250'Continue'.centerY   (active)>
```

**Comment by pmusolino** [comment]
Thank you for the review @ealeksandrov!
I'm not able to replicate those 2 warnings. Are you sure they are shown in Shipping Label Form?
On which device did you test it?

**Comment by ealeksandrov** [comment]
Interesting! I test on iPhone 12 simulator and I also saw same warnings on #4291:

https://user-images.githubusercontent.com/3132438/119815766-92419000-bef4-11eb-9f01-a9183f393601.mp4

**Comment by pmusolino** [comment]
Interesting, It doesn't happen on iPhone 12 Pro. I'll check it out and I opened an issue for it https://github.com/woocommerce/woocommerce-ios/issues/4306. 👍

**Pull request merged**
