### PR TITLE
[Payments Menu] New Payments Menu deeplinks, shortcuts, and searchability

### LINKED ISSUE #11100: [Payments Menu] Deeplink support

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #11100

## Description

We have various deeplinks, shortcuts, and Spotlight search support which go to the payments menu.

This PR updates the deeplink handling to:
1. Be used in all these cases
2. Open the correct version of the payments menu based on the toggle
3. Add support for the deeplink destinations to the new payments menu

### Deeplinks

1. Launch the app from Xcode
2. Turn on the `New Payments Menu` experimental toggle
3. Add the following URLs to a note in the Notes app
4. Tap each, and make sure they load to the expected screen
5. Repeat with the `New Payments Menu` toggled off.

#### URLs
`https://woo.com/mobile/payments`
`https://woo.com/mobile/payments/collect-payment`
`https://woo.com/mobile/payments/tap-to-pay`
`https://woocommerce.com/mobile/payments`
`https://woocommerce.com/mobile/payments/collect-payment`
`https://woocommerce.com/mobile/payments/tap-to-pay`

### Shortcut

1. Launch the app from Xcode
2. Turn on the `New Payments Menu` experimental toggle
3. Add a new shortcut in the Shortcuts app, using the Woo Collect Payment action
4. Run the shortcut
5. Observe that the collect payment screen opens

### Spotlight search

1. Launch the app from Xcode
2. Turn on the `New Payments Menu` experimental toggle
3. Do a Spotlight search for "Payments"
4. Tap the Woo result
5. Observe that the payments menu opens

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/2472348/dec716a0-d2f5-44dd-86af-06ddd984b8e2

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by toupper** [comment]
Good work Josh! I have a question for the code, and a few test findings.

Question: I see that there's a refactor for the navigation, i.e. change in the CollectPaymentAppIntent, the new destination classes ... Out of curiosity, what's the purpose of that refactor?

And test results:

- The issues come mostly when there's already a view presented in the payments menu:

https://github.com/woocommerce/woocommerce-ios/assets/1864060/df36fac3-9bf8-4274-bebf-d4f4a2752853

1. Present the Simple Payment Screen
2. Try to open tap to pay deeplink from Notes
3. It doesn't present the tap to pay screen. Instead, it pushes again the Payments menu. Some buttons do not react after tapping on them, e.g. Simple Payments

- When Tap to Pay is presented, and we try to open collect payment, it opens again Tap to Pay flow:

https://github.com/woocommerce/woocommerce-ios/assets/1864060/ff4cd987-4809-4be1-8f81-bf73d6f1e12a

Apart from that, when another screen is presented modally, e.g custom amounts in order creation, and we tap to follow a link, it sometimes reaches the Payments menu without opening the target screen, and stays there. My guess is that we need to synchronize the push transition with the new screen modally presentation, otherwise they clash.

- Spotlight

When tapping Payments in Spotlight, nothing related with Woo popped up. In order for that to show, we have to register the user activity, and [that](https://github.com/woocommerce/woocommerce-ios/blob/a6c526d7db9bb23525fafb3bf6343fd8e809064e/WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person%20Payments/LegacyInPersonPaymentsMenuViewController.swift#L89) happens in the `LegacyInPersonPaymentsMenuViewController` My guess is that, since we don't use that class now, it's never registered. My second guess is that since you were testing both flows -old and new- you were able to register it, but I went directly to enable the new flow in settings without opening -and registering- the Payments screen.

Let me know if you need more help and we can debug it together.

**Comment by joshheald** [comment]
> Good work Josh! I have a question for the code, and a few test findings.

@toupper Thanks for the review and testing!
 
> Question: I see that there's a refactor for the navigation, i.e. change in the CollectPaymentAppIntent, the new destination classes ... Out of curiosity, what's the purpose of that refactor?

Prompted by neccesity, and then tidied up when I realised the existing system didn't make so much sense any more. 

I found that with the SwiftUI presentation of views from the payments menu, you really need to get hold of the instance of the viewModel. Static navigation function don't make much sense in this case. It _is_ possible, but clunkier, so the refactor was prompted by moving to instance-based navigation.

Once I'd done that, it became clear that `DeeplinkForwarder` was just navigating one step of a deeplink. So that's renamed and has new methods, as well as defining destinations outside the screens they relate to. We could make this a much fuller system, but I didn't want to go that far yet, so it's still pretty simple

> And test results:
> 
>     * The issues come mostly when there's already a view presented in the payments menu:
> ...
>     3. It doesn't present the tap to pay screen. Instead, it pushes again the Payments menu. Some buttons do not react after tapping on them, e.g. Simple Payments

Thanks, and sorry for missing this. It should be relatively easy to fix with the new code, since we can check whether payments is already shown or not before pushing it.

>     * When Tap to Pay is presented, and we try to open collect payment, it opens again Tap to Pay flow:

That's interesting... I suppose it needs something to dismiss any presented views of the view model before presenting a new one.

> Apart from that, when another screen is presented modally, e.g custom amounts in order creation, and we tap to follow a link, it sometimes reaches the Payments menu without opening the target screen, and stays there. My guess is that we need to synchronize the push transition with the new screen modally presentation, otherwise they clash.

That's a shame because it's noticably quicker with the new links, IMO. I'll see about adding a wait for the push. Did you find this was more common with any particular links?

> When tapping Payments in Spotlight, nothing related with Woo popped up. In order for that to show, we have to register the user activity, and [that](https://github.com/woocommerce/woocommerce-ios/blob/a6c526d7db9bb23525fafb3bf6343fd8e809064e/WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person%20Payments/LegacyInPersonPaymentsMenuViewController.swift#L89) happens in the `LegacyInPersonPaymentsMenuViewController` My guess is that, since we don't use that class now, it's never registered. My second guess is that since you were testing both flows -old and new- you were able to register it, but I went directly to enable the new flow in settings without opening -and registering- the Payments screen.

Yeah, you're right about the registration clash, I realised that in a later PR: #11169 . It's actually pretty annoying with SwiftUI, because the `.userActivity` modifier only gets called if you use a SwiftUI `App` container and SwiftUI App Lifecycle. Obviously I'm not adopting that in this work!

**Comment by joshheald** [comment]
@toupper I've fixed the issues with navigation: 147fe71

As discussed separately, you can see the hacky fix for Spotlight search here – see the `InPersonPaymentsMenuViewModel` change in this PR: https://github.com/woocommerce/woocommerce-ios/pull/11169/files. I've seen this working today :badpokerface:

Could you take another look at the navigation issues and approve if you agree please?

**Review by toupper — APPROVED** [review]
Thanks for the explanation and the fixes @joshheald! Now the navigation works fine 👍 
I found a couple of UI glitches mostly related to the navigation bars, but I guess that's out of the scope of this PR. I add here a video and screenshot for the record. (Xcode 15 + iOS 17 device)



https://github.com/woocommerce/woocommerce-ios/assets/1864060/e2076a57-b755-4963-94c7-07654c8d084b

**Pull request merged**
