### PR TITLE
[Orders] Enable Order tab Split View in dev builds

### PR DESCRIPTION
**Pull request by joshheald**
## Description

Since Project Lily Pad M2 is nearing completion, we want to open it up to wider view within the dev team.

This PR changes the default setting for dev builds (including App Center) to show the split view interface in the Orders tab.

If testing goes to plan, this will later be turned on for release builds in 17.1

### Dev builds
1. Launch the app using the debug scheme on an iPad or large iPhone in landscape
2. Tap `Orders`
3. Observe that the split view interface is shown.

### Release builds
1. Select the `Release` build configuration for the run action in Xcode
2. Build and run the app on an iPad or large iPhone simulator (devices will not work here)
3. Tap `Orders`
4. Observe that only the Order List is shown.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/181">17.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by iamgabrielma** [comment]
We might need to add an `isUITesting` flag for the time being and loop QE for the failing UI tests:
```
test_add_note_to_existing_order() in OrdersTests (2 times)
test_cancel_order_creation() in OrdersTests (2 times)
test_create_new_order() in OrdersTests (2 times)
test_load_existing_order() in OrdersTests (2 times)
test_load_orders_screen() in OrdersTests (2 times)
test_load_orders_screen() in OrdersTests (2 times)
```

I tried running them locally to confirm CI, but I seem unable to start the UI testing suite since I upgraded to Xcode 15 🤔

**Comment by joshheald** [comment]
> We might need to add an `isUITesting` flag for the time being and loop QE for the failing UI tests:
> 
> ```
> test_add_note_to_existing_order() in OrdersTests (2 times)
> test_cancel_order_creation() in OrdersTests (2 times)
> test_create_new_order() in OrdersTests (2 times)
> test_load_existing_order() in OrdersTests (2 times)
> test_load_orders_screen() in OrdersTests (2 times)
> test_load_orders_screen() in OrdersTests (2 times)
> ```
> 
> I tried running them locally to confirm CI, but I seem unable to start the UI testing suite since I upgraded to Xcode 15 🤔

Oops, I didn't check back and notice those. I'll see if I can run them locally, I still have Xcode 14.3 if that's needed.

**Comment by bozidarsevo** [comment]
Tested and looks good!
I will do another look once CI is green 👍

**Comment by joshheald** [comment]
UI tests are failing because _for some reason_ the Orders tab opens to the secondary column (i.e. empty state, or Order Detail) when running in UITests.

The failing tests all expect to see the Order List, which is what happens when you use the app for realsies.

I'm looking for a way to make it work the same in UI tests as it does in normal use, ideally without hacking some fix in to the tests.

**Comment by joshheald** [comment]
After a pretty frustrating few hours of trying to find a workaround, I've found that #11710 fixes the UI tests here, as well as several other things. 

~I'm going to disable the Orders UI tests for this PR, and then re-enable them in #11710.~

I'm going to merge #11710 first, then they should pass here.

However, I'll do this next week when I can be sure of the interplay with #11729 

@woocommerce/penguin-team FYI

**Comment by joshheald** [comment]
I've pushed up a fix merging the above mentioned branches.

This still fails one OrderTest for me: `test_create_new_order` fails when it's trying `addCustomAmount` with the error
```
Failed to failed to scroll to visible (by AX action) Key, {{129.0, 852.0}, {135.0, 54.0}}, label: '2', error: Error kAXErrorCannotComplete performing AXAction kAXScrollToVisibleAction on element AX element pid: 37051, elementOrHash.elementID: 105553156493728.1140. (Underlying Error: Error kAXErrorCannotComplete performing AXAction kAXScrollToVisibleAction on element AX element pid: 37051, elementOrHash.elementID: 105553156493728.1140)
```

However, that happens on trunk too so I think it's something with my machine/simulator. Pushed to see if it passes in CI

**Comment by joshheald** [comment]
The change in ee0ea03 fixed the tests on iPad, but on CI the run took a really long time:

```
[09:54:51]: ▸     ✔ test_load_orders_screen on 'Clone 2 of iPad Air (5th generation) - WooCommerceUITests-Runner (2378)' (1116.766 seconds)
```

I'm running again to check... but I'm pretty sure it doesn't normally take 18m for one test.

No such problem running that test locally, on either size of device.

_Edit: looking at some of the other recent jobs, this already happens fairly frequently, no particular concern related to this change._

_This PR is ready for review now, and will need @woocommerce/mobile-ui-testing-squad to approve as well 💜_

_The second run saw iPad tests finish in a sensible time._

**Review by iamgabrielma — APPROVED** [review]
Works nicely! 🚢

**Review by jostnes — APPROVED** [review]
Thanks for updating the tests to work on both screen types @joshheald! The changes look good - I ran the tests on iPad Air and iPhone 15 simulators and the tests work as expected on both.

I checked the build with the questionable test run time of 18mins and it's most likely due to CI slowness (which I've seen happen from time to time). Based on the test logs (can be downloaded from the step artifacts), 14+ out of the 18 mins happened during setup, so shouldn't be related to the changes in this PR:

image

**Comment by joshheald** [comment]
Thanks for the review @jostnes 

> I checked the build with the questionable test run time of 18mins and it's most likely due to CI slowness (which I've seen happen from time to time). Based on the test logs (can be downloaded from the step artifacts), 14+ out of the 18 mins happened during setup, so shouldn't be related to the changes in this PR.

That's good to know; from the console output, it looked like the test itself was taking the time. The test logs were still processing when I tried to check them, but it's helpful to see that now 😊

**Pull request merged**
