### PR TITLE
Added tracking events for Downloadable Files

### LINKED ISSUE #3381: Add Tracking for Downloadable Files and Enable it for All
### Detail Page

- [ ] When the Downloadable files button is tapped, trigger the event `product_detail_view_downloadable_files_tapped`.

### Settings

- [ ] When tapping Done, trigger the event `product_downloadable_files_settings_changed`. 

### Downloadable File Item

- [ ]  When modifying downloadable files, trigger these events:

Event Name | Trigger | Custom Properties
--------|-------|----
`products_downloadable_file`        |  When tapping Add in the Add downloadable file screen.      |  `action="added"`
`products_downloadable_file`        |  When tapping Update for an existing downloadable file.      |  `action="updated"`
`products_downloadable_file`        |  After confirming the deletion of a downloadable file.      |  `action="deleted"`

## Enable for All

- [ ]  The Downloadable Files feature should no longer be hidden under the M5 feature flag.

---

Android: https://github.com/woocommerce/woocommerce-android/issues/3353

### PR DESCRIPTION
**Pull request by pmusolino**
Closes #3381

## Description
Added the events for downloadable files.
@shiki while I was working on this issue, I discovered that we didn't add any event when the Downloadable Files are updated. Do we want to add any events there?
The feature will be enabled for everyone at the end of milestone 5. #3400

## Testing 
1. Open a product with some downloadable files.
2. Tap the cell of the Downloadable files: the event `product_detail_view_downloadable_files_tapped` should be triggered.
3. Open the downloadable files settings, and edit them: when tapping Done, the event `product_downloadable_files_settings_changed` should be triggered.
4. When you modify downloadable files (add/update/delete), the event `products_downloadable_file` should be triggered.

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Ecarrion — APPROVED** [review]

**Comment by pmusolino** [comment]
@shiki while I was working on this issue, I discovered that we didn't add any event when the Downloadable Files are updated. Do we want to add any events there?

**Comment by shiki** [comment]
@pmusolino Would you mind giving me more information about “when the Downloadable Files are updated”? It's not this one, right? 



I see you already implemented this so I'm not sure what you're referring to. Sorry. 😬

**Comment by pmusolino** [comment]
Exactly. The events that you mentioned are referred to these screens:
Schermata 2021-01-04 alle 17 15 39


But after Updating/Deleting/Adding a Downloadable File, the user should tap the "Done" button in the Downloadable Files list, because they can still discard the changes.

Look at these screens below:

| Done button (apply the changes to the product)            |  If the user press back, they can discard the changes |
:-------------------------:|:-------------------------:
Simulator Screen Shot - iPhone 12 Pro - 2021-01-04 at 17 16 52 | Simulator Screen Shot - iPhone 12 Pro - 2021-01-04 at 17 16 47

**Comment by shiki** [comment]
@pmusolino Thanks for the details. 

I don't think we need an event for those. Even though they're not _committed_, the `added`, `updated`, and `deleted` events are sufficient signals to determine how our merchants use this feature or whether they're using it at all. 

I could be wrong. Can you think of any questions that we might not be able to answer if we don't have the “commit” or “discard” events?

We can also add them later if we found out that we're wrong.

**Comment by pmusolino** [comment]
Yes probably you are right, these events are enough to know if the users are using or not this feature.

> We can also add them later if we found out that we're wrong.

Sound good!

**Comment by shiki** [comment]
I just noticed that we could have used the [Custom Properties pattern](https://github.com/woocommerce/woocommerce-ios/blob/develop/docs/tracking-events.md#custom-properties) for the `products_downloadable_file` event. 🙂

**Pull request merged**
