### PR TITLE
Merge release/20.2.1 into release/20.3

### PR DESCRIPTION
**Pull request by AliSoftware**
Merging `release/20.2.1` into `release/20.3`.

Via intermediate branch `merge/release-20.2.1-into-release-20.3`, to help fix conflicts if any:
```
                          release/20.2.1  ----o-- - - -
                                               \
    merge/release-20.2-into-release-20.3        `---.
                                                     \
                            release/20.3  ------------x- - -
```

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/222">20.3 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AliSoftware** [comment]
@pmusolino Given this PR uses an intermediate branch, there won't be a problem when you'll use "Resolve conflicts", as GitHub will merge `release/20.3` into `merge/release-20.2.1-into-release-20.3` this time to commit the conflict resolution, so this won't risk accidentally merging `release/20.3` into `release/20.2.1` anymore.

The proper way to fix those conflicts is to pick whatever is currently in the `release/20.3` target branch. Because we want to keep the content/values of `RELEASE-NOTES.txt` and `config/Version.Public.xcconfig` that are meant for version `20.3` in the `release/20.3` branch even after this PR is merged.

**Comment by AliSoftware** [comment]
🚨  Error on my part, I made this PR target `trunk` while it was meant to target `release/20.3`. Please hold.

**Comment by AliSoftware** [comment]
So… given we already merged `release/20.2.1` into `release/20.3` and thus the bug fix from https://github.com/woocommerce/woocommerce-ios/pull/13926 already made its way to `release/20.3` branch after all, there's nothing more to integrate into the `release/20.3` branch after all.

In fact, if I were to try asking GitHub to update this PR to merge the head `merge/release-20.2.1-into-release-20.3` branch into `release/20.3` (instead of `trunk` that I selected erroneously when I created the PR), GitHub is telling me:
> There are no new commits between base branch ‘release/20.3’ and head branch ‘merge/release-20.2.1-into-release-20.3’

Which makes sense since we indeed already included everything there.

So the only thing that was needed to fix our mistake from https://github.com/woocommerce/woocommerce-ios/pull/13931#issuecomment-2346004443 was to restore the `release/20.2.1` branch to point to the commit before the accidental `Merge release/20.3 into release/20.2.1`, i.e. force-push `release/20.2.1` to point back to 6728f9e6e3da4759ee4373af24a6c1a8991baa0a. Which we already did earlier.

All that means that this PR can be closed after all, and the resolution of the accidental up-merge was resolved by a simple force-push instead.

**Pull request closed without merging**
