### PR TITLE
Reviews UI mark III. Mark reviews as read

### LINKED ISSUE #1252: Reviews tab: mark reviews as read
Add logic to mark reviews as read, following Android.
Parent issue: #1160

- Fetch notifications and match them up to reviews by `comment_id`
- If a review does not have a matching notification, then we would consider it as read
- If it has a matching notification, then we'd set the read status to whatever the read status is on the review

### PR DESCRIPTION
**Pull request by ctarda**
Fixes #1252. 

Third step in the implementation the Reviews tab: mark reviews as read.

The logic is as described in p99K0U-1Fk-p2. In a nutshell, we would mark as read the notification matching the review (where the review id is the notification's comment id)

Reviews should we be marked as read by navigating to the review details screen. Also, all reviews can be marked as read by tapping the top right button (check mark) in the reviews screen.

## Changes
- Add logic to mark a single review as read when entering the ReviewDetailsViewController
- Add logic to mark all reviews as read in ReviewsViewModel
- Add logic to fetch notifications and observe them in ReviewsViewModel

## Testing
As with other PRs in this series...
- Checkout the branch, run the tests
- Undo the feature flag. Because the NotificationsViewController is instantiated in a Storyboard, it will be necessary to touch `FeatureFlag.swift` to:
```
        case .reviews:
            return BuildConfiguration.current == .localDeveloper
```
and it will also be necessary to change the class of the first view controller in the Notifications.storyboard from NotificationsViewController to ReviewsViewController
- As an alternative, revert locally the commit dc49cdf1e3b57d3b926923268393d73c32a64319
- Navigate to the reviews tab > select a review. The review should be marked as read
- Navigate to the reviews tab. Tap the "mark all as read" button. All reviews should be marked as read

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ctarda** [comment]
Thanks @jaclync !

I just pushed an update that I think fixes the issue. Apparently there was a combination of a race condition when fetching notifications plus an error in the results controller when a new review is aded to the list that prevented the brand new review's cell from refreshing properly. 🤷‍♂ 

Anyway, I think this is ready for another round

**Comment by ctarda** [comment]
Would you mind giving another run to the same dataset? All reviews should be marked as read now.

However, there is still something that is not quite right:

1. Run the app
2. Add a new review to the WooCommerce store
3. Pull to refresh the review list
4. Notice how the new review is initialised as read, and then, after the notifications is loaded, updated to unread.

I am not sure how to solve that. The reviews endpoint is way faster than the notifications one. If we wait until the notifications have been fetched, we will create another issue, as it wouldn't be possible to reload the list when a single notification is marked as read. 

Thoughts @mindgraffiti @jaclync ?

**Comment by mindgraffiti** [comment]
> Let's talk about this notification syncing issue more separately and not let this block this PR (marking reviews as read)

Agreed. @ctarda I would merge this one and open a bug ticket or Spike for the remaining problem. Notifications are not an easy thing to fix nor easy to find workarounds.

**Comment by ctarda** [comment]
Thanks folks. I'll merge as soon as I merge the Xcode 11 tooling into this branch, and the PR passes CI.

The issue to research what to do with the notifications is #1316

**Pull request merged**
