### PR TITLE
Continuous Improvements: Tags loading indicator

### LINKED ISSUE #4294: Product Details: make categories and tags screens use a consistent loading indicator
Steps to reproduce:

1. Switch to a store that has many categories.
1. Open any product for editing.
1. Tap the Categories option and check for a loading indicator.
1. Repeat the same steps for Tags.

**Result:** the categories screen doesn't display a proper loading indicator. (<a href="https://user-images.githubusercontent.com/1119271/119735882-374b6280-be3a-11eb-99f8-180ddaaa09fe.mp4">53s</a>) 

Categories loading|Tags loading
---|---
image|image

<sup>Tested with WCiOS 6.7.0.0 TestFlight beta on iPhone 6S iOS 14.6.</sup>

<sup>(internal reference: p5T066-2iC-p2#comment-8430 /ht @elibud)</sup>

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #4294 

### Description
The PR replaces the loading state based on showing the "Loading" cell with the usage of Ghost animation (check the video)

### How to test
* Open a product with tags
* Click tags
* Notice a new loading animation

### Screenshots

https://user-images.githubusercontent.com/4923871/142406347-e14331a0-edce-444b-96bc-5d20277f9ae7.mp4

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ctarda** [comment]
@Ecarrion  would you mind taking a look at this PR? You know this part of the system better than me 😊

**Comment by Ecarrion** [comment]
> @Ecarrion would you mind taking a look at this PR? You know this part of the system better than me 😊

@ctarda Sure, I'll take a look in a bit!

**Review by Ecarrion — APPROVED** [review]
Code and tests are great! 🚀 

A small thing to improve could be that in landscape the ghost cell does not seem to go all the way to the edge of the screen. 

That normally happens because the table view was pinned to the view safe area and not to the view edges.

https://user-images.githubusercontent.com/562080/142554496-1c3a61ec-a868-41b7-8ad6-d7e0991681db.mov

**Comment by kidinov** [comment]
@Ecarrion thank you for the review!

Indeed the issue was in the wrong constraint used. Fixed here 2a997bba770146c33c8cf40f8d0bac93e043968d

**Pull request merged**
