### PR TITLE
[Dynamic Dashboard] Dashboard store performance empty view

### LINKED ISSUE #12557: Empty state for performance card
image

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Closes: #12557 

## Description

Updates the empty state design of Store performance card. 

## Testing instructions

- Lanch and login into the app.
- Enable the "Performance" card in the dashboard if needed.
- Tap the calendar icon from the "Performance" card and switch to a date range that doesn't have any revenue.
- You should see the new empty view with the magnifying glass.
- Switch to a range with revenue and validate that the view looks as before.

## Screenshots

| No revenue | Store has revenue |
|--------|--------|
| Simulator Screenshot - iPhone 13 Pro - 2024-04-25 at 22 18 38 | Simulator Screenshot - iPhone 13 Pro - 2024-04-25 at 22 18 32 | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/200">18.4</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by itsmeichigo** [comment]
Thanks, Sharma for working on this! The rule mark in the middle of the chart looks a bit thick and distracting to me, so I did some experiments and found that this view can be improved by adding a few more tweaks:
- Set the rule mark foreground color to `listForegroundColor` to blend in with the card view.
- Remove the image from the rule mark's annotation.
- Add a layover to the `StoreStatsChart` if there is no revenue:

```Swift
// Simulate an empty chart
VStack {
    Divider()
    Spacer()
    Divider()
    Spacer()
    Divider()
    Spacer()
}
.overlay {
    Image(.magnifyingGlassNotFound)
        .opacity(0.5)
        .padding(.bottom, 32)
}
.renderedIf(!viewModel.chartViewModel.hasRevenue)
```

The view would look like this:



WDYT?

**Comment by selanthiraiyan** [comment]
Thanks for the great suggestion, @itsmeichigo! 🙇 

I added your suggestion in https://github.com/woocommerce/woocommerce-ios/pull/12570/commits/e8333f2a903ddf5cf59cefcbde0e6ed0c4d9b1f6

| No revenue | Store has revenue |
|--------|--------|
| Simulator Screenshot - iPhone 13 Pro - 2024-04-26 at 09 54 54 | Simulator Screenshot - iPhone 13 Pro - 2024-04-26 at 09 55 02 | 

The PR is ready for another look.

**Review by itsmeichigo — APPROVED** [review]
:shipit:

**Comment by itsmeichigo** [comment]
One minor nit though: should we hide the granularity text for the empty state of custom range too?

**Comment by selanthiraiyan** [comment]
> One minor nit though: should we hide the granularity text for the empty state of custom range too?

Added it in 0fb27f660b9bd00a3487680d6dc14ff781270dcb. 
I tried adding this in the view model, but I couldn't figure out how to unit-test it (and update existing tests) by mocking revenue. I ended up moving it to the view instead to include this change in this release. Kindly let me know if you think this needs to be moved to the view model after mocking revenue. 

| Before | After |
|--------|--------|
| Simulator Screenshot - iPhone 13 Pro - 2024-04-26 at 11 36 42 | Simulator Screenshot - iPhone 13 Pro - 2024-04-26 at 11 37 23 |

**Comment by itsmeichigo** [comment]
Keeping this on the view is fine to me - thanks!

**Pull request merged**
