### PR TITLE
[Woo Express Sign Up] Remove option to create WPCOM account from invalid email screen

### LINKED ISSUE #12375: Remove "Create An Account" on the incorrect email address screen
Remove the "Create An Account" button

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Closes: #12375 

## Testing instructions
1. Launch app logout if needed
2. Tap "Log In"
3. Enter a valid JP connected Woo store URL and continue
4. Enter an invalid email (which is not a WPCOM account email) to login
5. In the error screen validate that you don't see the "Create An Account" to create a new WPCOM account

## Screenshots

| Before | After |
|--------|--------|
| Simulator Screenshot - iPhone 13 Pro - 2024-03-28 at 11 22 47 | Simulator Screenshot - iPhone 13 Pro - 2024-03-28 at 17 45 42 | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by itsmeichigo — APPROVED** [review]
Just FYI, I added a feature flag for Woo Express signup removal - but since this change is small I suppose we can ship it right away.

**Comment by selanthiraiyan** [comment]
Thanks for the review, @itsmeichigo!

> Just FYI, I added a feature flag for Woo Express signup removal - but since this change is small I suppose we can ship it right away.

@hafizrahman and I discussed about the feature flag here https://github.com/woocommerce/woocommerce-ios/pull/12376#pullrequestreview-1966081608.

We thought the feature flag was added for the purpose of the Authenticator library.

**Comment by itsmeichigo** [comment]
Yeah the feature flag was there because we couldn't deliver the whole feature when I created the PR. Since we plan to deliver everything this week, I suppose we don't need the flag for this week's PRs then.

**Pull request merged**
