### PR TITLE
Update pods to recommended Xcode settings

### PR DESCRIPTION
**Pull request by mindgraffiti**
Save the settings for scheme updates so that Xcode stops warning that the pod settings need updated in the project.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pmusolino** [comment]
I retested this, and I realized I had done the test with the recommended settings already updated.
It seems that `Update to recommended settings` updates other information but they are part of the git ignore, for this reason, it is not possible to remove the warning. After every pod install the warning will reappear.

**Comment by mindgraffiti** [comment]
@pmusolino did you update your local .gitignore file? I don't see `.xcscheme` files in the repo's [.gitignore](https://github.com/woocommerce/woocommerce-ios/blob/develop/.gitignore)

**Comment by pmusolino** [comment]
Sorry @mindgraffiti, I explained myself wrong. I meant to say that maybe updating to the recommended settings did not just update what was included in this Pull Request, but also other files that have been excluded (and which maybe are in git ignore). I say this because also with the right `LastUpgradeVersion`, I'm able to see the warning.

And if I try to fix it manually, when I try to do a simple `pod install` the warning re-appear

**Comment by mindgraffiti** [comment]
Ohhh. Well darn. Thanks Paolo, closing this.

**Pull request closed without merging**
