### PR TITLE
[Subscriptions in Order Creation 3] Update order details row with subscription details

### LINKED ISSUE #12441: [SiOC 3] Order details: Update product rows to display subscription details
Suggested design vs current implementation:

20240424 subs section design vs app

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #12441 

## Description
This PR updates the Subscription details row within Order Details when an order has a subscription product, following the figma designs at Q9tkFMtymZz0yhfLLbKhig-fi-2176_61285 (under `i1 - 06 - Order Details`):

Screenshot 2024-04-24 at 16 02 09

| Before | After |
|--------|--------|
| 20240424 order details subscription section - before | Simulator Screenshot - iPhone 15 - 2024-04-24 at 15 57 07 | 

## Changes
- Reordered order details rows, now `subscriptions` section appears before `payment` section.
- Updated existing `OrderSubscriptionTableViewCell` for the new design. Mostly redo the .xib file and add a new label and a separator.
- Updated cell strings to be formatted via `localizedStringWithFormat`
- Cleanup: Moved `OrderSubscriptionTableViewCellViewModel` to a separate file
- Cleanup: Updated the `subscriptionTitle` to not appear as a decimal number
- Cleanup: Updated affected `NSLocalizedStrings` to use `value:`

## Testing instructions
- On a store using WooCommerce Subscriptions, process an order with subscription products through the web (not the app, since is not yet supported. Orders processed through the app won't display this section). You can use the testing site https://indiemelon.mystagingwebsite.com/ if you prefer, that already has processed orders.
- In the app, go to `Orders` > Tap in the order you just processed (or look for orders `2478` or `2572` in https://indiemelon.mystagingwebsite.com/ )
- When loaded, scroll down and observe the Subscriptions section renders correctly.

PD: I'm not a big fan of the amount of separator lines when there's multiple subscriptions (see order `2572`). I'll followup with design and iterate further if needed:

Screenshot 2024-04-24 at 16 15 41

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/200">18.4</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by joshheald** [comment]
> PD: I'm not a big fan of the amount of separator lines when there's multiple subscriptions (see order 2572). I'll followup with design and iterate further if needed:

I agree.

As implemented, the separator between the frequency row and the subscription doesn't match designs, as it doesn't reach all the way to the trailing edge of the cell. If it _did_ match, I think the information heirarchy would be even harder to follow.

Given the pressures on Joe, let's try and iterate on this ourselves – what about starting by removing the separator, and _perhaps_ changing to a grey colour?

Additionally, the number in "Every 1 day" (/week/month/year) is pretty clunky. It would be better if this could just be "Every day, every week, every month", and only use the number when it's greater than 1.

**Review by joshheald — APPROVED** [review]
Works as expected... I agree on the design though, so let's maybe make some more tweaks to the look. See previous comment.

**Comment by iamgabrielma** [comment]
> Let's try and iterate on this ourselves – what about starting by removing the separator, and perhaps changing to a grey colour?

Definitely, on https://github.com/woocommerce/woocommerce-ios/pull/12549/commits/c422b9f2231ea3b0de983e885d43e238fa2a8663 I've removed the separator, adjusted the vertical space between components to half of what it was, and updated the interval part of the text to use a secondary style:

| Before | After |
|--------|--------|
| Screenshot 2024-04-24 at 16 15 41 | Screenshot 2024-04-25 at 10 15 07 | 

> Additionally, the number in "Every 1 day" (/week/month/year) is pretty clunky. It would be better if this could just be "Every day, every week, every month", and only use the number when it's greater than 1.

Agree with this one. I've [raised this before](p1712741053001459/1712711323.553239-slack-C025A8VV728) and ended keeping this approach because it's how is displayed in core, but every time I see it I want to change it 😂 Since the same happens across several components (product selector, product rows, product collapsible cards, and here in order details) I'll tackle this separately and update the tests as well. Logged: https://github.com/woocommerce/woocommerce-ios/issues/12555

**Pull request merged**
