### PR TITLE
[Mobile Payments] Adjust modal dimensions for iPads

### LINKED ISSUE #4557: iPad modals - UI update
Hi there, 

I realized there were no tablet designs for the CPP projects. I added them in Figma for reference. Similarly to the mobile modals, is it possible to update the modal sizes so they are consistent across the flow?

Screen Shot 2021-07-06 at 2 37 40 PM

### PR DESCRIPTION
**Pull request by koke**
Fixes #4557 

This implements the changes requested in #4557 to make the modals a bit bigger on iPads. Looking at the screens in Figma, I wasn't able to see a consistent layout (the horizontal margin of the buttons was 96, 103, or 114.25 depending on the screen), so here's how I interpreted the rules:

- The modal size is 454x490
- The vertical padding is 42px
- Instead of setting a horizontal padding, I tried to keep the content at the same size it was on the iPhone modals (280-2x16 = 248px) and make sure it's centered. This would be equivalent to a 103px horizontal padding, but it made a bit more sense to define it that way
- All these new rules apply when both the horizontal and vertical [size class](https://useyourloaf.com/blog/size-classes/) are "regular"

## To test

1. Find an order that's eligible for payments
2. Tap Collect Payment
3. Connect to a reader and go through the payment flow

The modal view controller is generic to all the payment modals, so the changes should be the same for all screens, but feel free to test as many cases as you want.

You can also check that the modals haven't changed when running on an iPhone.

Screen Shot 2021-09-06 at 14 07 16|Screen Shot 2021-09-06 at 14 08 09|Screen Shot 2021-09-06 at 14 07 24
-|-|-
Screen Shot 2021-09-06 at 14 07 27|Screen Shot 2021-09-06 at 14 07 33|Screen Shot 2021-09-06 at 14 07 40

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ghost** [comment]
These are looking good to me so far thanks @koke before I approve, @Garance91540 do you have any thoughts on the alignment of the modals that don't have a button, etc at the bottom? Should we just align vertically?

**Review by ctarda — APPROVED** [review]
Looks good to me, and tests well.

Some screenshots:






:shipit:

**Review by Garance91540 — COMMENTED** [review]
> @Garance91540 do you have any thoughts on the alignment of the modals that don't have a button, etc at the bottom? Should we just align vertically?

Yes, I think we should keep the text top aligned and try centering the image in the modal for those ones. If not the white space in the bottom half part of the modal is a bit too prominent

**Comment by koke** [comment]
> we should keep the text top aligned and try centering the image in the modal for those ones

To clarify this, I've been following this idea from #4550 that "all the other modal elements are vertically distributed between the modal titles and the buttons". In the case where there are no buttons, applying that behavior effectively distributes the content between the titles and the bottom of the modal, which I don't think it's what we want.

Screen Shot 2021-09-07 at 17 21 49

The latest thing I was trying (unsuccessfully so far, we'll see about that tomorrow) was to add a fixed size spacer with the height equivalent to the case when there are two buttons (95px), so that the content is distributed between the titles and the empty buttons view. It would look like this:

Screen Shot 2021-09-07 at 18 16 12

@Garance91540 does that look good to you?

**Comment by Garance91540** [comment]
> @Garance91540 does that look good to you?

yes!

**Comment by koke** [comment]
Added the missing centering on fa7e694. It took me a while to figure it out, and the final solution is a bit hacky but it seems to work fine. Instead of trying to adjust the spacer and all the content hugging priorities, I skip the spacer, and adjust the bottom padding to include all the extra space that the buttons would take.
Screen Shot 2021-09-08 at 16 25 40

I tested multiple sizes on iPad and iPhone:

Screen Shot 2021-09-08 at 16 17 26|Screen Shot 2021-09-08 at 16 17 01
-|-
Screen Shot 2021-09-08 at 16 17 04|Screen Shot 2021-09-08 at 16 26 53
Screen Shot 2021-09-08 at 16 19 15|Screen Shot 2021-09-08 at 16 19 19

@ctarda do you mind reviewing the code change in fa7e694?

**Review by ctarda — APPROVED** [review]
The new updates look good to me @koke Im sorry I missed the request for review. :shipit:

**Review by Garance91540 — APPROVED** [review]
👏

**Pull request merged**
