### PR TITLE
[Woo POS - payments onboarding] Update WooPayments setup URL from Payments Overview to Payments Connect

### PR DESCRIPTION
**Pull request by jaclync**
Part of #14296 

## Why

As recommended by the WooPayments web team in pdfdoF-5Bo-p2#comment-6655:

> If the intent is to point merchants to a webview from where they can start/continue their WooPayments onboarding specifically (with WooPayments installed and activated), you can continue using admin.php?page=wc-admin&path=%2Fpayments%2Foverview, or, better yet, you can use admin.php?page=wc-admin&path=%2Fpayments%2Fconnect. WooPayments will take care of redirecting between the two.

This PR aims to change the payments setup URL from Payments Overview to Payments Connect.

After testing on a few sites (Pressable, WPCOM, JN), the Payments Overview (when tapping on the Payments menu on the left sidebar in wp-admin) and Payments Connect are the same right now. Conceptually, the Connect page makes more sense to set up / connect the payments account while the Overview page might contain other information that could distract the merchant away from connecting the account.

## How

This PR only changes the URL from Payments Overview to Payments Connect.
The addition of a `from` parameter will be in a separate PR as it involves more code changes that I'm less sure about.

There are two use cases of the payments setup URL:

- `InPersonPaymentsPluginNotSetup`
- `InPersonPaymentsStripeAccountOverdue`

## Steps to reproduce

Since this change affects the existing onboarding flow for all entry points (POS, IPP, Payments menu), I think focusing on testing the most critical flow, IPP, is the best use of time.

### Stripe overdue

Prerequisite: store payment gateway is active and set up but account has `account.wcpayStatus == .restricted && account.hasOverdueRequirements`. Alternatively, you can hard code the state by returning `.stripeAccountOverdueRequirement(plugin: .wcPay)` at the beginning of `CardPresentPaymentsOnboardingUseCase.checkOnboardingState`.

- Log in to the store with site credentials
- Go to the orders tab
- Create an order
- Enter a custom amount or add some products then recalculate
- Collect payment
- Tap `Card Reader` --> an onboarding modal should be shown. after the loading state, the Stripe overdue UI should be shown
- Tap `Resolve Now` --> a webview should be shown. log in to wp-admin if needed for WPCOM login. the webview should show how to connect to the payment account, and should be the same as when tapping on the Payments tab on the left sidebar

### Payments plugin not set up

Prerequisite: store payment gateway is active but isn't set up completely. Alternatively, you can hard code the state by returning `.pluginSetupNotCompleted(plugin: .wcPay)` at the beginning of `CardPresentPaymentsOnboardingUseCase.checkOnboardingState`.

- Log in to the store with site credentials
- Go to the orders tab
- Create an order with a custom amount or product, or tap on an order ready for payment collection
- Collect payment
- Tap `Card Reader` --> an onboarding modal should be shown. after the loading state, the plugin not set up UI should be shown
- Tap `Finish Setup in Store Admin` --> a webview should be shown. log in to wp-admin if needed for WPCOM login. the webview should show how to connect to the payment account, and should be the same as when tapping on the Payments tab on the left sidebar

## Testing information

I couldn't reproduce the actual scenario of "Stripe overdue" onboarding state, so I tested by manually returning the state in code.

## Screenshots

Example for the "plugin not set up" error:

https://github.com/user-attachments/assets/5f7e03ec-7538-4a8a-ad6a-a0813c4a06fc

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by staskus — APPROVED** [review]
✅  I tested payment onboarding scenarios from scratch and the link worked well  I didn't find cases where it didn't open the account overview. (I integrated [this change](https://github.com/woocommerce/woocommerce-ios/pull/14310) since otherwise Stripe connection would fail) 

I also tested the hardcoded scenarios and they worked as described as well.

I remember @joshheald had thoughts on this URL change, is there anything else we should check to raise our confidence that the URL change doesn't break onboarding?

**Comment by joshheald** [comment]
> I remember @joshheald had thoughts on this URL change, is there anything else we should check to raise our confidence that the URL change doesn't break onboarding?

Nope, no concerns from me about this. I think you might be thinking of when we start using `payments_enabled`, which the web team also suggested.

@staskus did you check actually completing the information from the new link? Or just that it opened? I don't think it should be a problem but I'm on alert about that after finding it in the beta the other day. That was an authentication change though, so this _should_ be fine

**Comment by staskus** [comment]
> did you check actually completing the information from the new link?

@joshheald Yes, I tested the whole flow as well.

**Comment by jaclync** [comment]
I also tested again and was able to complete the onboarding with a site in dev mode. Merging the PR shortly.

**Pull request merged**
